- usecase/webapi-usecase-tests/samples/DownloadAndroid/README.md
- usecase/webapi-usecase-tests/samples/DownloadAndroid/css/style.css
- usecase/webapi-usecase-tests/samples/DownloadAndroid/index.html
- usecase/webapi-usecase-tests/samples/DownloadAndroid/js/jqueryprogressbar.js
- usecase/webapi-usecase-tests/samples/DownloadAndroid/js/main.js
Impacted tests(designed): new 1, update 0, delete 0
> [usecase-webapi][XWALK-1736] Add usecase for download usecase

- usecase/usecase-webapi-xwalk-tests/samples/Vehicle/README.md
- usecase/usecase-webapi-xwalk-tests/samples/Vehicle/index.html
- usecase/usecase-webapi-xwalk-tests/samples/Vehicle/js/main.js
Unit test result summmary: pass 1, fail 0, block 0
> [usecase][XWALK-2620] Update usecase for Vehicle info API

- stability/stability-longlasting-android-tests/tests.full.xml
- stability/stability-longlasting-android-tests/tests.xml
- Update the order for run tests
> [stability] Update tests.xml and tests.full.xml for stability-longlasting-android-tests

- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests/LocalStorage/index.html
> [usecase][xwalk-3286] Update one test steps for localstorage

- usecase/wrt-usecase-android-tests/suite.json
- usecase/wrt-usecase-android-tests/tests/LocalStorage/index.html
> [Crosswalk-10][usecase-wrt][xwalk-3286] Update one test steps for localstorage

- wrt/wrt-packertool2-android-tests/README
- wrt/wrt-packertool2-android-tests/mode.txt
- wrt/wrt-packertool2-android-tests/packertool2/absolutePathtest.py
- wrt/wrt-packertool2-android-tests/packertool2/anyLocationtest.py
- wrt/wrt-packertool2-android-tests/packertool2/appPathtest.py
- wrt/wrt-packertool2-android-tests/packertool2/comm.py
- wrt/wrt-packertool2-android-tests/packertool2/compressortest.py
- wrt/wrt-packertool2-android-tests/packertool2/descriptiontest.py
- wrt/wrt-packertool2-android-tests/packertool2/indextest.py
- wrt/wrt-packertool2-android-tests/packertool2/manifesttest.py
- wrt/wrt-packertool2-android-tests/packertool2/othertest.py
- wrt/wrt-packertool2-android-tests/packertool2/permissiontest.py
- wrt/wrt-packertool2-android-tests/packertool2/projectdirtest.py
- wrt/wrt-packertool2-android-tests/packertool2/projectonlytest.py
- wrt/wrt-packertool2-android-tests/tests.full.xml
- wrt/wrt-packertool2-android-tests/tests.xml
Impacted TCs num(approved): New 2, Update 2, Delete 0
Android test result summary: Pass 4, Fail 0, Block 0
- Add license to all scripts
> [wrt] Add 2 TCs to wrt-packertool2-android-tests

- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_Xwalk_Backend_PkgInstallFromDirectory_Apps.sh
- wrt/wrt-packagemgt-tizen-tests/tests.full.xml
- wrt/wrt-packagemgt-tizen-tests/tests.xml
> [wrt][XWALK-2971] Add 1 new test case for Package Management

- embeddingapi/embedding-api-android-tests/embeddingapi/AndroidManifest.xml
- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/ExtensionEcho_broadcast.java
- embeddingapi/embedding-api-android-tests/tests_v1.xml
- embeddingapi/embedding-api-android-tests/tests_v2.xml
- embeddingapi/embedding-api-android-tests/tests_v3.xml
- embeddingapi/embedding-api-android-tests/tests_v4.xml
- tools/build/pack.py
- usecase/usecase-embedding-android-tests/inst.apk.py
- Improve pack.py for embeddingapi
- Add ExtensionEcho_broadcast.java
- Correct the package path of embeddingapi/embedding-api-android-tests/tests_*.xml
- Correct the package path of usecase-embedding-android-tests/inst.apk.py
Unit test result summary: pass 159, fail 19, block 0
> [embedding] Improve pack.py for embeddingapi

- usecase/usecase-wrt-tizen-tests/tests.full.xml
- usecase/usecase-wrt-tizen-tests/tests.tizen.xml
- usecase/usecase-wrt-tizen-tests/tests.xml
Impacted TCs num(approved):New 0,Update 0,Delete 1
Test Result: no UT
> [wrt][XWALK-3115] Update usecase remove xwalk -c test case

- webapi/tct-webdatabase-w3c-tests/tests.full.xml
- webapi/tct-webdatabase-w3c-tests/tests.xml
Impacted tests(approved): new 13, update 0, delete 0
Unit test result summary: pass 0, fail 0, block 13
Block Reason: not support openDatabaseSync() method
> [webapi][XWALK-2768] Change designed test to approved for WebDatabase

- webapi/tct-flexiblebox-css3-tests/flexiblebox/CSS3FlexBox_initial_value.html
- Update align-self initial value to auto following spec defined
Unit test platform: [IVI] crosswalk-10.39.233, t-e-c 0.120
> [Crosswalk-10][webapi][XWALK-3056] Update align-self initial value

- webapi/tct-csp-w3c-tests/csp/reference/csp_referrer_always-ref.html
- webapi/tct-csp-w3c-tests/csp/reference/csp_referrer_never-ref.html
- webapi/tct-csp-w3c-tests/csp/reference/csp_referrer_origin-ref.html
Because some words missing in these 3 reference files.
Unit test result summary:pass 0,fail 4,block 0
> [webapi][XWALK-2976] Update 3 reference files in Crosswalk-10

- misc/web-abat-xwalk-tests/inst.wgt.py
- misc/web-abat-xwalk-tests/inst.xpk.py
- misc/web-mbat-xwalk-tests/inst.wgt.py
- misc/web-mbat-xwalk-tests/inst.xpk.py
- misc/webapi-uiautomation-xwalk-tests/inst.wgt.py
- misc/webapi-uiautomation-xwalk-tests/inst.xpk.py
- misc/wrt-documentation-verification-tests/inst.wgt.py
- misc/wrt-documentation-verification-tests/inst.xpk.py
- misc/wrt-sampleapp-android-tests/inst.wgt.py
- misc/wrt-sampleapp-android-tests/inst.xpk.py
- misc/wrt-sampleapp-tizen-tests/inst.wgt.py
- misc/wrt-sampleapp-tizen-tests/inst.xpk.py
- misc/xwalk-system-tests/inst.wgt.py
- misc/xwalk-system-tests/inst.xpk.py
- Removing trailing space from inst.wgt.py files
> [misc] Update inst.wgt.py to reflect pkgcmd -l change

- behavior/inst.wgt.py
- behavior/inst.xpk.py
- Removing trailing space from inst.wgt.py files
> [behavior] Update inst.wgt.py to reflect pkgcmd -l change

- wrt/wrt-securitymanu-android-tests/testapp/security_url_certificate_tests/index.html
> [wrt][xwalk-3320] Update one test for wrt-securitymanu-android-tests

- usecase/usecase-wrt-android-tests/tests.full.xml
- usecase/usecase-wrt-android-tests/tests/MiniLZMACompressionUI/README.md
- usecase/usecase-wrt-android-tests/tests/MiniLZMACompressionUI/index.html
Impacted tests(designed): new 1, update 0, delete 0
Unit test result summary: pass 0, fail 0, block 1
Block reason:feature unresolved
https://crosswalk-project.org/jira/browse/XWALK-3338
> [usecase][xwalk-3338] Add 1 new test case

- webapi/tct-webstorage-w3c-tests/tests.full.xml
- webapi/tct-webstorage-w3c-tests/tests.xml
- webapi/tct-webstorage-w3c-tests/webstorage/localStorage_iframe.html
- webapi/tct-webstorage-w3c-tests/webstorage/sessionStorage_iframe.html
- webapi/tct-webstorage-w3c-tests/webstorage/window_localStorage_iframe_item.html
- webapi/tct-webstorage-w3c-tests/webstorage/window_sessionStorage_iframe_item.html
> Update 2 manual cases to auto cases for webstorage

- usecase/usecase-wrt-tizen-tests/tests.full.xml
- usecase/usecase-wrt-tizen-tests/tests/ApplicationShowHide/README.md
- usecase/usecase-wrt-tizen-tests/tests/ApplicationShowHide/index.html
Impacted tests(designed): new 1, update 0, delete 0
Unit test platform: [tizen]
Unit test result summary: pass 0, fail 0, block 1
Block reason:feature triaged
https://crosswalk-project.org/jira/browse/XWALK-3341
> [usecase][xwalk-3355] Add show and hide test for WRT

- usecase/usecase-cordova-android-tests/tests.full.xml
- usecase/usecase-cordova-android-tests/tests.xml
- usecase/usecase-cordova-android-tests/tests/BridgeReload/REAMDE.md
- usecase/usecase-cordova-android-tests/tests/BridgeReload/index.html
- usecase/usecase-cordova-android-tests/tests/BridgeReload/page1.html
- usecase/usecase-cordova-android-tests/tests/BridgeReload/page2.html
- usecase/usecase-cordova-android-tests/tests/BridgeReload/test.js
-Sort the tests.*xml by case id at the same time
Impacted test(approved): new 1, update 0, delete 0
Unit test platform: [android]
> [usecase-cordova][xwalk-3097]Add one usecase for bridge reloading 

- usecase/usecase-wrt-tizen-tests/tests.full.xml
- usecase/usecase-wrt-tizen-tests/tests.xml
Update case status with following rules:
- Crosswalk feature in "RESOLVED" status: APPROVED
- Crosswalk feature in "ACCEPTED" status: DESIGNED
- Crosswalk test case tasks from bugs: APPROVED with bug ID in UT result
> [wrt][XWALK-3355] Update case status with right rules

- wrt/wrt-packagemgtmanu-tizen-tests/packagemgtmanu/Crosswalk_App_Icon.html
- wrt/wrt-packagemgtmanu-tizen-tests/tests.full.xml
- wrt/wrt-packagemgtmanu-tizen-tests/tests.xml
Task: xwalk-2324 Bug: xwalk-2216
> [wrt][xwalk-2324] Update check app icon test for package management

- webapi/webapi-simd-nonw3c-tests/tests.full.xml
- Case number isn't consistent in tests.xml and tests.full.xml, so update.
> [webapi][XWALK-3337] Update subcase num for SIMD

- webapi/tct-3dtransforms-css3-tests/suite.json
- webapi/tct-audio-html5-tests/suite.json
- webapi/tct-backgrounds-css3-tests/suite.json
- webapi/tct-colors-css3-tests/suite.json
- webapi/tct-flexiblebox-css3-tests/suite.json
- webapi/tct-multicolumn-css3-tests/suite.json
- webapi/tct-svg-html5-tests/suite.json
- Testkit-lite tool can not connect to android device if lack this param.
> [webapi] Add apk-common-opts param to suite.json file

- wrt/wrt-packertool2-android-tests/packertool2/comm.py
- wrt/wrt-packertool2-android-tests/packertool2/versionCodetest.py
- wrt/wrt-packertool2-android-tests/tests.full.xml
- wrt/wrt-packertool2-android-tests/tests.xml
- Fail bug: xwalk-3329
Impacted TCs num(approved): New 3, Update 0, Delete 0
Android test result summary: Pass 2, Fail 1, Block 0
> [wrt][xwalk-3331] Add tests for manifest options versionCode

- usecase/usecase-wrt-android-tests/tests/SecurityUrlCertificate/index.html
- wrt/wrt-securitymanu-android-tests/testapp/security_url_certificate_tests/index.html
- Fail reason: xwalk-2498
Android test result summary: Pass 0, Fail 2, Block 0
> [Crosswalk-11][wrt][xwalk-3320] Update case url for test certificate

- usecase/usecase-wrt-android-tests/tests/SecurityUrlCertificate/index.html
> [usecase][xwalk-3320] Update test url for test certificate

- webapi/webapi-simd-nonw3c-tests/simd/float32x4.html
- webapi/webapi-simd-nonw3c-tests/tests.full.xml
- webapi/webapi-simd-nonw3c-tests/tests.xml
- Add test case to check SMI in bounds check of SIMD load and store API
> [webapi][XWALK-3372] Add tests for SIMD

- embeddingapi/embedding-api-android-tests/tests.full.xml
- embeddingapi/embedding-api-android-tests/tests_v1.xml
- embeddingapi/embedding-api-android-tests/tests_v2.xml
- embeddingapi/embedding-api-android-tests/tests_v3.xml
- embeddingapi/embedding-api-android-tests/tests_v4.xml
- Mod id attribute of tests_v*.xml to avoid the duplicate case ids
- correct the subcase attribute of tests.full.xml
> [embeddingapi][XWALK-3297] Mod id attribute of tests_v*.xml

- wrt/tct-sp02-wrt-tests/scripts/wrt_sp02_localstorage_check.sh
- Change file existence judge by file number compare
- Avoid test failed when packaging use signature
> [wrt][xwalk-3385] Update script code for file existence judge

- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Negative_NullValueDescription.html
Android test result summary: Pass 1, Fail 0, Block
> [Crosswalk-11][wrt][xwalk-2715] Update one test about project-dir option for rtcoremanu

- wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Manifest_Permission_FieldDuplicate.html
- wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Manifest_Permission_FieldLowercase.html
- wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Manifest_Permission_FieldMore2.html
- wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Manifest_Permission_FieldUppercase.html
- wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Packer_Tool_Description.html
- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Negative_NullValueDescription.html
Android test result summary: Pass 6, Fail 0, Block
> [Crosswalk-10][wrt][xwalk-2715] Update some tcs for packertoolmanu and rtcoremanu

- wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Manifest_Permission_FieldDuplicate.html
- wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Manifest_Permission_FieldLowercase.html
- wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Manifest_Permission_FieldMore2.html
- wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Manifest_Permission_FieldUppercase.html
- wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Packer_Tool_Description.html
- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Negative_NullValueDescription.html
Android test result summary: Pass 6, Fail 0, Block
> [Crosswalk-9][wrt][xwalk-2715] Update some tcs for packertoolmanu and rtcoremanu

- behavior/subtestresult.xml
- behavior/tests.full.xml
- behavior/tests.tizen.xml
- behavior/tests/ConfigurationExtension/index.html
- behavior/tests/WRTSupport/index.html
- behavior/tests/WRTUI/index.html
- Update tests.full.xml、tests.tizen.xml、subtestresult.xml subcase number
- Remove no use tests configuration in ConfigurationExtension/index.html
- Remove no use tests configuration in WRTSupport/index.html
- Remove no use tests configuration in WRTUI/index.html
> [behavior][xwalk-3373] Update no use tests profile

- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- usecase/usecase-wrt-android-tests/tests/InputDate/README.md
- usecase/usecase-wrt-android-tests/tests/InputDate/index.html
- Fail bug ID: xwalk-3330
Android test result summary: Pass 0, Fail 1, Block
> [usecase-wrt][xwalk-3333] Add test for Input date

- misc/sampleapp-android-tests/sampleapp/M39_Beacon.html
- misc/sampleapp-android-tests/sampleapp/M39_Generators.html
- misc/sampleapp-android-tests/sampleapp/M39_WebAnimationsJavascriptAPI.html
- misc/sampleapp-android-tests/sampleapp/M39_WebApplicationManifest.html
- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
> [misc] Integrate M39 Samples for Sampleapp-android

- misc/sampleapp-tizen-tests/sampleapp/M39_Beacon.html
- misc/sampleapp-tizen-tests/sampleapp/M39_Generators.html
- misc/sampleapp-tizen-tests/sampleapp/M39_WebAnimationsJavascriptAPI.html
- misc/sampleapp-tizen-tests/tests.full.xml
- misc/sampleapp-tizen-tests/tests.xml
Unit test platform: [ivi]
Unit test result summary: pass 0, fail 0, block 3
Block reason: xwalk-launcher cannot open a url
> [misc] Integrate M39 Samples for Sampleapp-tizen

- webapi/tct-csp-w3c-tests/tests.full.xml
- Auto case number isn't consistent in tests.xml and tests.full.xml, so update tests.full.xml
> [webapi][XWALK-3415] Update CSP tests execution type in tests.full.xml

- usecase/usecase-wrt-android-tests/suite.json
Android test result summary: Pass 1, Fail 0, Block
> [usecase][xwalk-2870] Update suite.json for test schemencontent

- usecase/usecase-miniwrt-android-tests/tests.android.xml
- usecase/usecase-miniwrt-android-tests/tests.full.xml
- usecase/usecase-miniwrt-android-tests/tests/MiniLZMACompressionUI/README.md
- usecase/usecase-miniwrt-android-tests/tests/MiniLZMACompressionUI/index.html
Impacted tests(designed): new 0, update 1, delete 0
> [usecase][xwalk-3338] Update LZMA compression support

- usecase/wrt-usecase-android-tests/suite.json
Android test result summary: Pass 1, Fail 0, Block
> [Crosswalk-10][usecase][xwalk-2870] Update test for schemecontent

- usecase/usecase-wrt-android-tests/suite.json
Android test result summary: Pass 1, Fail 0, Block
> [Crosswalk-11][usecase][xwalk-2870] Update suite.json for test SchemeContent

- misc/sampleapp-android-tests/sampleapp/M38_CollectionsIterators.html
- misc/sampleapp-android-tests/sampleapp/M38_FileConstructor.html
- misc/sampleapp-android-tests/sampleapp/M38_PictureElement.html
- misc/sampleapp-android-tests/sampleapp/M38_ScreenOrientation.html
- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
> [misc] Integrate M38 Samples for Sampleapp-android

- tools/resources/bddrunner
- usecase/usecase-webapi-xwalk-tests/suite.json
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/testscripts/TypedArray.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/environment.py
- usecase/usecase-webapi-xwalk-tests/testscripts/steps/steps.py
- Mantain automation framework to testsscript
- Automate TypedArray usecase
> [usecase] Add automation framework to usecase

- misc/sampleapp-tizen-tests/sampleapp/M38_CollectionsIterators.html
- misc/sampleapp-tizen-tests/sampleapp/M38_FileConstructor.html
- misc/sampleapp-tizen-tests/sampleapp/M38_PictureElement.html
- misc/sampleapp-tizen-tests/sampleapp/M38_ScreenOrientation.html
- misc/sampleapp-tizen-tests/tests.full.xml
- misc/sampleapp-tizen-tests/tests.xml
Unit test platform: [ivi]
Unit test result summary: pass 0, fail 0, block 4
Block reason: xwalk-launcher cannot open a url
> [misc] Integrate M38 Samples for Sampleapp-tizen

- misc/sampleapp-android-tests/sampleapp/SIMD_AppFunction.html
- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
> [misc][xwalk-2647] Add test for sample app SIMD

- webapi/tct-flexiblebox-css3-tests/flexiblebox/csswg/align-content-004.htm
- webapi/tct-flexiblebox-css3-tests/flexiblebox/csswg/align-items-004.htm
- webapi/tct-flexiblebox-css3-tests/tests.full.xml
- webapi/tct-flexiblebox-css3-tests/tests.xml
Impacted tests(approved):new 0,update 2,delete 0
Unit test result summary:pass 0,fail 2,block 0
> [webapi] Add reference file to align-{content,items}-004

- misc/sampleapp-android-tests/sampleapp/M40_ReportValidity.html
- misc/sampleapp-android-tests/sampleapp/M40_ServiceWorker.html
- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
> [misc] Integrate M40 Samples for Sampleapp-android

- misc/sampleapp-tizen-tests/sampleapp/M40_ReportValidity.html
- misc/sampleapp-tizen-tests/sampleapp/M40_ServiceWorker.html
- misc/sampleapp-tizen-tests/tests.full.xml
- misc/sampleapp-tizen-tests/tests.xml
Unit test platform: [ivi]
Unit test result summary: pass 0, fail 0, block 2
Block reason: xwalk-launcher cannot open a url
> [misc] Integrate M40 Samples for Sampleapp-tizen

- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
- The position of testcase SIMD is wrong in pr https://github.com/crosswalk-project/crosswalk-test-suite/pull/1715, so need to update it
> [misc] Update tests.full.xml and tests.xml

- tools/atip/atip/web/web.py
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/testscripts/Forms.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/HTMLTemplate.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/Jsenhance.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/SIMD.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/ShadowDom.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/steps/steps.py
Impacted TCs num(approved): New 0, Update 5, Delete 0
Unit test result summary: Pass 5, Fail 0, Blocked 0
> [usecase-webapi] Automate 5 usecases and add some functions in web.py

- usecase/wrt-usecase-android-tests/tests/SecurityUrlCertificate/index.html
- wrt/wrt-securitymanu-android-tests/testapp/security_url_certificate_tests/index.html
- Fail reason: xwalk-2498
Android test result summary: Pass 0, Fail 2, Block 0
> [Crosswalk-10][usecase-wrt] Update url for test secrity

- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/testscripts/RawSockets.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/WebSocket.feature
- Fail Reason: websocket connect failed.
Unit test result summary: Pass 1, Fail 1, Blocked 0
> [usecase] Automate 2 usecases

- webapi/tct-csp-w3c-tests/csp/support/frame-ancestor-none.html
- webapi/tct-csp-w3c-tests/csp/support/frame-ancestors-asterisk.html
- The support file lost, so add.
> [webapi][XWALK-3088] Add support file for CSP

- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- The case can't test on device ASUS Memo pad 8.
> [Crosswalk-11][usecase-wrt] Update the ART Mode usecase status

- usecase/wrt-usecase-android-tests/tests.android.xml
- usecase/wrt-usecase-android-tests/tests.full.xml
- The case can't test on device ASUS Memo pad 8.
> [Crosswalk-10][usecase-wrt] Update the ART Mode usecase status

- webapi/tct-colors-css3-tests/colors/csswg/reference/t422-rgba-clip-outside-device-gamut-b-ref.html
- webapi/tct-colors-css3-tests/colors/csswg/reference/t422-rgba-onscreen-b-ref.html
- webapi/tct-colors-css3-tests/colors/csswg/reference/t424-hsl-clip-outside-gamut-b-ref.html
- webapi/tct-colors-css3-tests/colors/csswg/reference/t424-hsl-values-b-ref.html
- webapi/tct-colors-css3-tests/colors/csswg/reference/t425-hsla-clip-outside-device-gamut-b-ref.html
- webapi/tct-colors-css3-tests/colors/csswg/reference/t425-hsla-values-b-ref.html
- webapi/tct-colors-css3-tests/colors/csswg/t422-rgba-clip-outside-device-gamut-b.htm
- webapi/tct-colors-css3-tests/colors/csswg/t422-rgba-onscreen-b.htm
- webapi/tct-colors-css3-tests/colors/csswg/t424-hsl-clip-outside-gamut-b.htm
- webapi/tct-colors-css3-tests/colors/csswg/t424-hsl-values-b.htm
- webapi/tct-colors-css3-tests/colors/csswg/t425-hsla-clip-outside-device-gamut-b.htm
- webapi/tct-colors-css3-tests/colors/csswg/t425-hsla-values-b.htm
- webapi/tct-colors-css3-tests/tests.full.xml
- webapi/tct-colors-css3-tests/tests.xml
Impacted tests(approved):new 0,update 6,delete 0
Unit test result summary:pass 1,fail 5,block 0
> [webapi] Add reference file for css color tests

- usecase/usecase-webapi-xwalk-tests/samples/WebSocket/index.html
- usecase/usecase-webapi-xwalk-tests/samples/WebSocket/js/main.js
> [usecase-webapi][XWALK-3500] Modify the way to get the value of textbox for WebSocket

- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- usecase/usecase-wrt-android-tests/tests/UpgradeCompatibility/README.md
- usecase/usecase-wrt-android-tests/tests/UpgradeCompatibility/index.html
> [xwalk-3287][usecase-wrt] Add test for UpgradeCompatibility

- stability/stability-longlasting-tizen-tests/longlasting/MemoryFreeLongTime.sh
- stability/stability-longlasting-tizen-tests/tests.full.xml
- stability/stability-longlasting-tizen-tests/tests.xml
Task: xwalk-3502 Bug:xwalk-3454
> [stability][xwalk-3502] Add case for memory leak in crosswalk wrt

- webapi/tct-csp-w3c-tests/csp/csp_referrer_always.html
- webapi/tct-csp-w3c-tests/csp/csp_referrer_default.html
- webapi/tct-csp-w3c-tests/csp/reference/csp_referrer_always-ref.html
- Update referrer to the correct path
Unit test Platform: Tizen-IVI
> [webapi][XWALK-3490] Update referrer tests for CSP

- behavior/index.html
- behavior/js/main.js
- behavior/js/tests.js
- Store the data in the localStorage
- Add the export result function
- Add the reset localStorage function
> [behavior][XWALK-3196] Add the export result function for behavior

- wrt/tct-ext02-wrt-tests/tests.full.xml
- Update test.full.xml file format error in tct-ext02-wrt-tests
> [wrt] Update test.full.xml file format error

- webapi/webapi-mediaserver-tizen-tests/mediaserver/MediaServer_find_basic.html
- Failure analysis: https://crosswalk-project.org/jira/browse/XWALK-2563
> [webapi][XWALK-3504] Lack of quotations to complete the test for mediaserver

- behavior/index.html
- behavior/js/main.js
- behavior/js/tests.js
- Store the data in the localStorage
- Add the export result function
- Add the reset localStorage function
> [Crosswalk-11][behavior][XWALK-3196] Add the export result function for behavior

- behavior/index.html
- behavior/js/main.js
- behavior/js/tests.js
- Store the data in the localStorage
- Add the export result function
- Add the reset localStorage function
> [Crosswalk-10][behavior][XWALK-3196] Add the export result function for behavior

- webapi/tct-colors-css3-tests/colors/csswg/reference/t422-rgba-clamping-a1.0-b-ref.html
- webapi/tct-colors-css3-tests/colors/csswg/reference/t424-hsl-basic-a-ref.html
- webapi/tct-colors-css3-tests/colors/csswg/reference/t424-hsl-parsing-f-ref.html
- webapi/tct-colors-css3-tests/colors/csswg/t422-rgba-clamping-a1.0-b.htm
- webapi/tct-colors-css3-tests/colors/csswg/t424-hsl-basic-a.htm
- webapi/tct-colors-css3-tests/colors/csswg/t424-hsl-parsing-f.htm
- webapi/tct-colors-css3-tests/colors/csswg/t425-hsla-parsing-f.htm
- webapi/tct-colors-css3-tests/tests.full.xml
- webapi/tct-colors-css3-tests/tests.xml
Unit test result summary:pass 1,fail 3,block 0
> [webapi] Sync reference files for CSS Color tests to latest W3C

- misc/sampleapp-android-tests/sampleapp/M41_LexicalDeclarations.html
- misc/sampleapp-android-tests/sampleapp/M41_MediaQueries.html
- misc/sampleapp-android-tests/sampleapp/M41_PixelatedImage.html
- misc/sampleapp-android-tests/sampleapp/M41_TemplateLiterals.html
- misc/sampleapp-android-tests/sampleapp/M41_WebAudioSuspendResume.html
- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
> [misc] Integrate M41 Samples for Sampleapp-android

- misc/sampleapp-tizen-tests/sampleapp/M41_LexicalDeclarations.html
- misc/sampleapp-tizen-tests/sampleapp/M41_MediaQueries.html
- misc/sampleapp-tizen-tests/sampleapp/M41_PixelatedImage.html
- misc/sampleapp-tizen-tests/sampleapp/M41_TemplateLiterals.html
- misc/sampleapp-tizen-tests/sampleapp/M41_WebAudioSuspendResume.html
- misc/sampleapp-tizen-tests/tests.full.xml
- misc/sampleapp-tizen-tests/tests.xml
Unit test platform: [ivi]
Unit test result summary: pass 0, fail 0, block 5
Block reason: xwalk-launcher cannot open a url
> [misc] Integrate M41 Samples for Sampleapp-tizen

- wrt/wrt-packagemgt-tizen-tests/packagemgt/Common
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_Tizen_MultipleWebApp_Install_test.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_Tizen_WebApp_Install_test.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_Tizen_WebApp_Launch_Command_test.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_Tizen_WebApp_Uninstall_test.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_WebApp_Install_Resource.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_WebApp_Launch.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_WebApp_Launcher_Cache.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_WebApp_Uninstall.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_CheckDB.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_MultiVersionHigher.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_MultiVersionLower.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_OneVersionHigher.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_OneVersionLower.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_SameVersionAndDifferID.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_SameVersionAndID.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_VersionMultiToOneHigher.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_VersionMultiToOneLower.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_VersionOneToMultiHigher.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_XPK_Update_VersionOneToMultiLower.sh
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_Xwalk_Backend_PkgInstallFromDirectory_Apps.sh
Impacted tests(approved): new 0, update 20, delete 0
Unit test result summary: pass 20, fail 0, block 0
Bug:xwalk-3045
> [wrt][xwalk-3045] Update cases in package management

- webapi/webapi-nfc-w3c-tests/nfc/support/nfc_common.js
- webapi/webapi-nfc-w3c-tests/nfc/support/unitcommon.js
- Add checking for testharness to avoid outer script duplicate
Impacted tests(approved): new 0, update 58, delete 0
Unit test result summary: pass 58, fail 0, block 0
> [webapi][XWALK-3459] Update common script for NFC API

- behavior/tests/ConfigurationExtension/res/setting-encrypt-disable.html
- behavior/tests/ConfigurationExtension/res/setting-encrypt-enable.html
- behavior/tests/PackageManagement/res/Sample-widget3.html
- behavior/tests/Stability/res/test-half-memory.html
- behavior/tests/WRTSupport/res/protection-encryption-check.html
- misc/xwalk-system-tests/tests/applicationswitching/js/main.js
- usecase/usecase-webapi-xwalk-tests/samples/ApplicationSwitching/js/main.js
- usecase/usecase-webapi-xwalk-tests/samples/Package/js/main.js
- webapi/tct-testconfig/tests.full.xml
- webapi/tct-testconfig/tests.xml
- webapi/webapi-mediarenderer-tizen-tests/README
- webapi/webapi-mediaserver-tizen-tests/README
- wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_WebApp_Launcher_Cache.sh
- wrt/wrt-packagemgtmanu-tizen-tests/packagemgtmanu/Crosswalk_WebApp_Uninstall_Resource.html
- Update app storage path from ".config" to "apps_rw"
in behavior/misc/usecase/webapi/wrt folder
> Update app storage path from ".config" to "apps_rw"

- misc/sampleapp-android-tests/sampleapp/SIMD_Close.html
- misc/sampleapp-android-tests/sampleapp/SIMD_Icon.html
- misc/sampleapp-android-tests/sampleapp/SIMD_Install.html
- misc/sampleapp-android-tests/sampleapp/SIMD_Launch.html
- misc/sampleapp-android-tests/sampleapp/SIMD_Orientation.html
- misc/sampleapp-android-tests/sampleapp/SIMD_Switch.html
- misc/sampleapp-android-tests/sampleapp/SIMD_Uninstall.html
- misc/sampleapp-android-tests/sampleapp/SIMD_Uninstall_WithAppRunning.html
- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
Impacted TCs num(approved): New 8, Update 0, Delete 0
Android test result summary: Pass 8, Fail 0, Block 0
> [misc][xwalk-2637] Add tests for sampleapp SIMD

- tools/bootstrap-fw/css/main.css
- usecase/usecase-cordova-android-tests/tests.full.xml
- usecase/usecase-cordova-android-tests/tests.xml
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/tests.tizen.xml
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- usecase/usecase-wrt-tizen-tests/tests.full.xml
- usecase/usecase-wrt-tizen-tests/tests.tizen.xml
- Update the icon and background of set for usecase-cordova-android
- Update the suitename for usecase-cordova-android, usecase-webapi-xwalk, usecase-wrt-android and usecase-wrt-tizen
> [usecase-cordova] Update the suitename and the icon of set for usecase-cordova-android

- behavior/tests/Viewport/index.html
- misc/web-mbat-xwalk-tests/mbat/Crosswalk_WebApp_Install.html
- usecase/usecase-wrt-tizen-tests/samples/MultiUser/index.html
- wrt/wrt-commandlinemanu-tizen-tests/commandlinemanu/Crosswalk_Run_As_Service_Launch.html
- Update manual tests for normal user desc in behavior/misc/wrt/usecase
- The doc/Web_BAT_Test_Suite_User_Guide.md will update by others
(Doc/readme/guide)
Task: xwalk-3538
> [xwalk-3538] Update manual tests for normal user desc

- behavior/inst.wgt.py
- behavior/inst.xpk.py
- Get user dynamically by using option 'inst.py -a <user>'
- PASS to install/uninstall wgt in Tizen Common using './inst.py [-u]' (default user: app)
- PASS to install/uninstall wgt in Tizen Common using './inst.py -a guest [-u]'
> [behavior][xwalk-3535] Multi user support in inst.*.py

- webapi/tct-sessionhistory-html5-tests/sessionhistory-py/w3c/location_port.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory/w3c/location_port.html
- Keep location port test same with w3c.
> [webapi][XWALK-3022] Update location port test from w3c

- misc/sampleapp-android-tests/sampleapp/RTC_datachannel.html
- misc/sampleapp-android-tests/sampleapp/support/datachannel.html
- misc/sampleapp-android-tests/sampleapp/support/main.js
- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
Fail reason: the first channel cannot be fired.
> [misc] Integrate webrtc for Sampleapp-android

- misc/sampleapp-tizen-tests/sampleapp/RTC_datachannel.html
- misc/sampleapp-tizen-tests/sampleapp/support/datachannel.html
- misc/sampleapp-tizen-tests/sampleapp/support/main.js
- misc/sampleapp-tizen-tests/tests.full.xml
- misc/sampleapp-tizen-tests/tests.xml
Fail reason: the first channel cannot be fired
> [misc] Integrate webrtc for Sampleapp-tizen

- wrt/wrt-manifest-tizen-tests/README
- wrt/wrt-manifest-tizen-tests/run_test.py
- wrt/wrt-packertool-tizen-tests/README
- wrt/wrt-packertool-tizen-tests/packertool/Crosswalk_Tizen_Packaging_Tool_Install_test.sh
- wrt/wrt-packertool-tizen-tests/packertool/Crosswalk_Tizen_Packaging_Tool_Uninstall_test.sh
Impacted tests(approved): new 0, update 266, delete 0
Unit test result summary: pass 266, fail 0, block 0
Task: xwalk-3536
> [wrt][xwalk-3536] Update get user dynamically for packtool/manifest

- misc/webapi-uiautomation-xwalk-tests/html5-extra-app/testscripts/environment.py
- misc/webapi-uiautomation-xwalk-tests/w3c-webstorage-app/testscripts/environment.py
- tools/atip/atip/tizen/tizen.py
- tools/atip/atip/web/web.py
- tools/atip/tests/environment.py
- usecase/usecase-webapi-xwalk-tests/testscripts/environment.py
- webapi/tct-extra-html5-tests/html5-extra-app/testscripts/environment.py
- webapi/tct-webstorage-w3c-tests/w3c-webstorage-app/testscripts/environment.py
- Tizen user can be given by param of lite dynamically.
- The default tizen user is app.
> [atip][XWALK-3539] Update tizen.py to get user id dynamically

- webapi/tct-sessionhistory-html5-tests/sessionhistory-py/w3c/location_port.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory/w3c/location_port.html
Keep location port test same with w3c.
> [Crosswalk-11][webapi][XWALK-3022] Sync location W3C test to latest

- webapi/tct-sessionhistory-html5-tests/sessionhistory-py/w3c/location_hash.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory-py/w3c/location_host.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory-py/w3c/location_hostname.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory-py/w3c/location_href.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory-py/w3c/location_pathname.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory-py/w3c/location_protocol.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory-py/w3c/location_search.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory/w3c/location_hash.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory/w3c/location_host.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory/w3c/location_hostname.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory/w3c/location_href.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory/w3c/location_pathname.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory/w3c/location_protocol.html
- webapi/tct-sessionhistory-html5-tests/sessionhistory/w3c/location_search.html
> [webapi] Sync location W3C tests to latest

- doc/Behavior_Test_Tool_User_Guide.md
- doc/WebAPI_Test_Suite_User_Guide.md
- doc/Web_BAT_Test_Suite_User_Guide.md
- doc/Web_Runtime_Test_Suite_User_Guide.md
Change the app and developer usernames to normaluser.
The documents shall be revised in unity style.
> [XWALK-3542] Update docs for multiuser support

- usecase/usecase-wrt-android-tests/samples/SharedModeGooglePlay/README.md
- usecase/usecase-wrt-android-tests/samples/SharedModeGooglePlay/index.html
- usecase/usecase-wrt-android-tests/samples/SharedModeGooglePlay/res/manifest.json
- usecase/usecase-wrt-android-tests/steps/SharedModeGooglePlay/step.js
- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
> [usecase][xwalk-2948] Add test for sharedmodegoogleplay

- webapi/tct-audio-html5-tests/tests.full.xml
- webapi/tct-audio-html5-tests/tests.xml
> [webapi][XWALK-3505] Add onload delay time

- wrt/wrt-upgrademanu-android-tests/tests.full.xml
- wrt/wrt-upgrademanu-android-tests/tests.xml
- wrt/wrt-upgrademanu-android-tests/upgrademanu/Crosswalk_Shared_Embedded_Version_cookie.html
- wrt/wrt-upgrademanu-android-tests/upgrademanu/Crosswalk_Shared_Embedded_Version_other.html
- wrt/wrt-upgrademanu-android-tests/upgrademanu/Crosswalk_Shared_Shared_Binary_Lib_cookie.html
- wrt/wrt-upgrademanu-android-tests/upgrademanu/Crosswalk_Shared_Shared_Binary_Lib_other.html
- wrt/wrt-upgrademanu-android-tests/upgrademanu/Crosswalk_Shared_Shared_Version_cookie.html
- wrt/wrt-upgrademanu-android-tests/upgrademanu/Crosswalk_Shared_Shared_Version_other.html
Impacted TCs num(approved): New 0, Update 8, Delete 0
Android test result summary: Pass 0, Fail 0, Block 8
- Block reason: xwalk-3473
> [wrt] Update test description for upgrademanu

- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/testscripts/AppURI.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/ContactsManager.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/DeviceCapabilities.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/Forms.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/WebRTC.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/steps/steps.py
> [usecae-webapi] Automate 4 usecases

- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/testscripts/IndexedDB.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/NavigationTiming.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/SessionHistory.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/WebStorage.feature
> [usecase] Automate 4 usecases

- usecase/usecase-cordova-android-tests/samples/PageVisibility/index.html
- usecase/usecase-cordova-android-tests/samples/TargetBlank/index.html
> [usecase-cordova][XWALK-3576] Import main.js file to index.html for PageVisibility and TargetBlank

- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- The case can't test on device ASUS Memo Pad 8
Impacted TCs num(designed): New 0, Update 1, Delete 0
> [usecase] Update test ARTMode status

- tools/build/pack.py
- usecase/usecase-wrt-android-tests/suite.json
- wrt/wrt-manifest-android-tests/ge_package.py
- The test suites can be built successfully
> [wrt-usecase][xwalk-3473] Update scripts due to spec changed

- usecase/usecase-cordova-android-tests/samples/CordovaPackage/index.html
> [usecase-cordova][XWALK-3580] Update the location of test.py for CordovaPackage

- wrt/tct-ext02-wrt-tests/tests.xml
- The test.xml file missing one '</description>' node
> [wrt] Update test.xml format error in tct-ex02-wrt-tests

- wrt/wrt-packertool2-android-tests/packertool2/apksizetest.py
- wrt/wrt-packertool2-android-tests/testapp/contactextension/contactextension/contactextension.js
> [wrt][xwalk-3584] Update test for apksize to packertool2

- tools/atip/atip/web/web.py
> [atip][xwalk-3579] Fix typo in web.py

- webapi/tct-canvas-html5-tests/tests.full.xml
- webapi/tct-canvas-html5-tests/tests.xml
- webapi/tct-csp-w3c-tests/tests.full.xml
- webapi/tct-csp-w3c-tests/tests.xml
- webapi/tct-flexiblebox-css3-tests/tests.full.xml
- webapi/tct-flexiblebox-css3-tests/tests.xml
- Due to testkit-lite has been updated to support both stub and webdriver mode to run all tests,
so update xml files to suite.
Unit test result summary: These three apk can run well on android.
> [webapi][OTCIS-4450] Update xml for canvas csp and flexiblebox

- webapi/tct-fonts-css3-tests/tests.full.xml
- webapi/tct-fonts-css3-tests/tests.xml
- Due to testkit-lite has been updated to support both stub and webdriver mode to run all tests, so update xml files to suite.
Unit test result summary: the suite can run well on android.
> [webapi][OTCIS-4450] Update xml for Fonts

- webapi/tct-3dtransforms-css3-tests/tests.full.xml
- webapi/tct-3dtransforms-css3-tests/tests.xml
- webapi/tct-audio-html5-tests/tests.full.xml
- webapi/tct-audio-html5-tests/tests.xml
- webapi/tct-backgrounds-css3-tests/tests.full.xml
- webapi/tct-backgrounds-css3-tests/tests.xml
- webapi/tct-colors-css3-tests/tests.full.xml
- webapi/tct-colors-css3-tests/tests.xml
- Update xml for 3dtransforms, audio, backgrounds and colors
- Due to testkit-lite has been updated to support both stub and webdriver
mode to run all tests, so update xml files to suite
Unit test result summary: suites can run well on android
> [webapi][OTCIS-4450] Update xml for 4 suites

- usecase/usecase-webapi-xwalk-tests/manifest.json
- Add permission for Geolocation, Contacts, Vibration tests
- Use new manifest format
- The related tests:
Vibration get PASS
LocationGPS still get Fail[XWALK-3259]
> [usecase][xwalk-3440] Update manifest.json to latest

- wrt/wrt-manifest-tizen-tests/const.py
Impacted tests(approved): new 0, update 264, delete 0
Unit test result summary: pass 264, fail 0, block 0
> [wrt] Update pyunit TIZEN_USER for default value

- usecase/usecase-webapi-xwalk-tests/manifest.json
- Add permission for Geolocation, Contacts, Vibration tests
- Use new manifest format
- The related tests:
Vibration get PASS
LocationGPS still get Fail[XWALK-3259]
> [Crosswalk-11][usecase][xwalk-3440] Update manifest.json to latest

- webapi/tct-multicolumn-css3-tests/tests.full.xml
- webapi/tct-multicolumn-css3-tests/tests.xml
- webapi/tct-svg-html5-tests/tests.full.xml
- webapi/tct-svg-html5-tests/tests.xml
- webapi/tct-text-css3-tests/tests.full.xml
- webapi/tct-text-css3-tests/tests.xml
- Update xml for svg, text and multicolumn
- Due to testkit-lite has been updated to support both and webdriver mode to run all tests, so update xml files to suit
> [webapi][OTCIS-4450] Update xml for 3 suites

- wrt/tct-pm-wrt-tests/scripts/wrt_pm_dataStored_Update.sh
- wrt/tct-pm-wrt-tests/scripts/wrt_pm_uninstallation_application_erased.sh
- wrt/tct-sp02-wrt-tests/scripts/wrt_sp02_localstorage_check.sh
- Update the installed app path from 'xwalk-service' to 'xwalk'
> [wrt][xwalk-3590] Update script codes' installed app path

- webapi/tct-audio-html5-tests/tests.full.xml
- webapi/tct-audio-html5-tests/tests.xml
> [crosswalk-11][webapi][XWALK-3505] Add onload delay time

- misc/sampleapp-android-tests/testscripts/environment.py
- misc/webapi-uiautomation-xwalk-tests/html5-extra-app/testscripts/environment.py
- misc/webapi-uiautomation-xwalk-tests/w3c-webstorage-app/testscripts/environment.py
- tools/atip/atip/common/steps.py
- tools/atip/atip/web/web.py
- tools/atip/tests/environment.py
- tools/atip/tools/set_env.sh
- tools/atip/tools/webdriver.xw_android_cordova.json
- tools/atip/tools/webdriver.xw_android_xwalk.json
- usecase/usecase-webapi-xwalk-tests/testscripts/environment.py
- webapi/tct-extra-html5-tests/html5-extra-app/testscripts/document_oninput_event.feature
- webapi/tct-extra-html5-tests/html5-extra-app/testscripts/environment.py
- webapi/tct-webstorage-w3c-tests/w3c-webstorage-app/testscripts/Storage_example_insurance_on_trip.feature
- webapi/tct-webstorage-w3c-tests/w3c-webstorage-app/testscripts/environment.py
-add CordovaLauncher/XWalkLauncher support
-add other app launcher support with pkg and activity name
-add TIZEN_USER support for local debug in set_env.sh
UT Result: BDD suites run well
> [ATIP] Add CordovaLauncher/XWalkLauncher support

- usecase/usecase-webapi-xwalk-tests/suite.json
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.auto.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/tests.tizen.xml
- Merge xml file in usecase and demoexpress
- Due to testkit-lite has been updated to support both and webdriver mode to run all tests, so update xml files to suit
- BDD case result:
-  Impacted TCs num(approved): New 0, Update 20, Delete 0
-  Unit test Platform: Andriod
-  Unit test result summary: Pass 14, Fail 6, Blocked 0
> [usecase][OTCIS-4450] Update xml for usecase

- usecase/usecase-webapi-xwalk-tests/samples/CSP/res/csp-asterisk/index.html
- usecase/usecase-webapi-xwalk-tests/samples/CSP/res/csp-cross-origin/index.html
- usecase/usecase-webapi-xwalk-tests/samples/CSP/res/csp-none/index.html
- usecase/usecase-webapi-xwalk-tests/samples/CSP/res/csp-self/index.html
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.auto.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/tests.tizen.xml
- usecase/usecase-webapi-xwalk-tests/testscripts/CSP.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/Selectors.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/WebDatabase.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/WebMessaging.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/steps/steps.py
> [usecase] Add 4 new bdd tests

- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
- Due to testkit-lite has been updated to support both and webdriver mode to run all tests, so update xml files to suit
> [misc][OTCIS-4450] Update xml for sampleapp

- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.auto.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/tests.tizen.xml
- webapi/tct-extra-html5-tests/tests.full.xml
- webapi/tct-extra-html5-tests/tests.xml
- webapi/tct-webstorage-w3c-tests/tests.full.xml
- webapi/tct-webstorage-w3c-tests/tests.xml
- Add "/opt/\<suite-name\>/" to \<bdd_test_script_entry\>
- Format tests xml using "xmllint --format"
- Add back the missed <capability/> in usecase tests.xml
> Update bdd_test_script_entry for BDD tests

- usecase/usecase-webapi-xwalk-tests/tests.auto.xml
- usecase/usecase-webapi-xwalk-tests/testscripts/ContactsManager.feature
- Add a 3 seconds sleep steps to ContactsManager.
- Update the subcase of CSP from 9 to 8, otherwise there will be a case blocked.
> [usecase] Update ContactsManager.feature

- usecase/usecase-wrt-android-tests/samples/SharedModeGooglePlay/index.html
- usecase/usecase-wrt-android-tests/samples/SharedModeGooglePlay/res/manifest.json
- usecase/usecase-wrt-android-tests/steps/SharedModeGooglePlay/step.js
- usecase/usecase-wrt-android-tests/suite.json
> [usecase-wrt] Update test description for SharedModeGooglePlay

- behavior/js/main.js
- behavior/js/tests.js
- behavior/subtestresult.xml
- behavior/suite.json
- behavior/tests/ConfigurationExtension/index.html
- behavior/tests/ConfigurationExtension/res/application-content.html
- behavior/tests/Gamepad/index.html
- behavior/tests/Gamepad/res/GamePadButton_basic-manual.html
- behavior/tests/Gamepad/res/GamePad_basic-manual.html
- behavior/tests/Gamepad/res/GamePad_connected-manual.html
- behavior/tests/Gamepad/res/GamepadEvent_gamepadconnected-manual.html
- behavior/tests/Gamepad/res/GamepadEvent_gamepaddisconnected-manual.html
- behavior/tests/VKB/index.html
- behavior/tests/Viewport/index.html
- behavior/tests/WRTSupport/index.html
- behavior/tests/WRTSupport/res/other-uri-schemes.html
- behavior/tests/WRTSupport/res/url-access-multi.html
- Add function to save the result of subcase
> [Crosswalk-11][behavior][XWALK-3570] Add function to save the result of subcase for behavior

- webapi/tct-webstorage-w3c-tests/webstorage/StorageEvent_constructor_key_undefined.html
- webapi/tct-webstorage-w3c-tests/webstorage/StorageEvent_constructor_oldValue_undefined.html
- webapi/tct-webstorage-w3c-tests/webstorage/StorageEvent_constructor_url_undefined.html
> [webapi][XWALK-3524] Update tests for WebStorage

- usecase/usecase-webapi-xwalk-tests/samples/SpeechSynthesis/js/main.js
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- The SpeechSynthesis feature(XWALK-1140) is not ready on Android.
SpeechSynthesis.speak() exist, but the functional does not work
- Test PASS on Chrome 41.0.2272.74
Unit test platform: [Android][Crosswalk 13.41.309.0]
> [usecase][xwalk-1140] Enable SpeechSynthesis on Android

- webapi/tct-forms-html5-tests/forms/w3c/COPYING
- webapi/tct-forms-html5-tests/forms/w3c/form-elements-nameditem-02.html
Unit test platform: [android] crosswalk-12.40.281
> [webapi][XWALK-1134] Sync form W3C test to latest

- webapi/tct-forms-html5-tests/forms/w3c/COPYING
- webapi/tct-forms-html5-tests/forms/w3c/form-elements-nameditem-02.html
Unit test platform: [android] crosswalk-12.40.281
> [crosswalk-11][webapi][XWALK-1134] Sync form W3C test to latest

- webapi/tct-widget02-w3c-tests/scripts/w3c_widget_installfail.sh
- webapi/tct-widget02-w3c-tests/scripts/w3c_widget_launch.sh
- webapi/tct-widget02-w3c-tests/scripts/xwalk_common.sh
> [webapi][xwalk-3520] Update shell script to align test result

- wrt/wrt-rtcoremanu-android-tests/testapp/manifest_negative_nullvalue_csp/manifest.json
> [wrt][xwalk-3638] Update the value of version in the manifest file

- tools/atip/atip/web/web.py
- usecase/usecase-webapi-xwalk-tests/testscripts/IndexedDB.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/WebDatabase.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/WebMessaging.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/WebStorage.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/steps/steps.py
- Add new steps to find element by given attribute
- Modify the related feature files
> [atip] Add new steps for searching element by specified attribute

- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.auto.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/tests.tizen.xml
- usecase/usecase-webapi-xwalk-tests/testscripts/Sandbox.feature
> [usecase] Automate sandbox usecase

- embeddingapi/embedding-api-android-tests/suite.json
- embeddingapi/embedding-api-android-tests/tests.full.xml
- embeddingapi/embedding-api-android-tests/tests_v1.xml
- Update suite json file to copy tests.full.xml to release pkg
- Update tests.full.xml to correct the case num, id and path
- Correct the case num of tests_v1.xml
> [embedding] update tests and suite file

- tools/bootstrap-fw/index.html
- tools/bootstrap-fw/js/main.js
- tools/bootstrap-fw/js/report.js
- Add function to merge the testcase into the same set
- Add function to differentiate the testcase by execution_type
> [usecase] Add function to merge the testcase into the same set for usecase

- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
- misc/sampleapp-android-tests/testscripts/gallery_appFunction.feature
- misc/sampleapp-android-tests/testscripts/simd_appFunction.feature
- misc/sampleapp-android-tests/testscripts/sysapps_appFunction.feature
- tools/atip/README.md
> update sample app and atip readme

- webapi/webapi-speechapi-tizen-tests/speechapi/Speech_vocalizeString_setCBListener-manual.html
> [webapi][xwalk-3199] Update test steps for Speech API manual testing

- tools/build/README.md
- tools/build/pack_cordova_sample.py
-support both cordova 3.6 and cordova 4.0 build
-totally 4 apps, mobilespec, helloworld, gallery, remotedebugging
-mobilespec build on cordova 4.0 not in scope currently
> [tools-build] Add Cordova sample apps auto build

- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/ExtensionEcho_broadcast.java
> [embedding][XWalk-3318] update case for testBroadcastMessage_function

- wrt/wrt-apptools-android-tests/apptools/comm.py
- wrt/wrt-apptools-android-tests/apptools/create_no_sdk.py
Android test result summary: Pass 3, Fail 0, Block 0
> [wrt-apptools] Update tests for apptools

- tools/build/pack.py
- usecase/usecase-wrt-android-tests/samples/ImmersiveFullscreen/README.md
- usecase/usecase-wrt-android-tests/samples/ImmersiveFullscreen/index.html
- usecase/usecase-wrt-android-tests/samples/ImmersiveFullscreen/res/manifest.json
- usecase/usecase-wrt-android-tests/steps/ImmersiveFullscreen/step.js
- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
> [usecase-wrt][xwalk-3662] Add test for immersive fullscreen

- wrt/wrt-manifest2-android-tests/manifest2/name_null_value.py
- wrt/wrt-manifest2-android-tests/testapp/manifest_name_nullvalue/index.html
- wrt/wrt-manifest2-android-tests/testapp/manifest_name_nullvalue/manifest.json
- wrt/wrt-manifest2-android-tests/tests.full.xml
- wrt/wrt-manifest2-android-tests/tests.xml
> [wrt][xwalk-3648] Improve one manual test to auto

- tools/build/README.md
- tools/build/pack_cordova_sample.py
-Add one precondition in README.md
-Update pack script to adapt different env
> [tools-build] Improve cordova sample app pack

- behavior/js/main.js
- behavior/js/tests.js
- behavior/subtestresult.xml
- behavior/suite.json
- behavior/tests/ConfigurationExtension/index.html
- behavior/tests/ConfigurationExtension/res/application-content.html
- behavior/tests/Gamepad/index.html
- behavior/tests/Gamepad/res/GamePadButton_basic-manual.html
- behavior/tests/Gamepad/res/GamePad_basic-manual.html
- behavior/tests/Gamepad/res/GamePad_connected-manual.html
- behavior/tests/Gamepad/res/GamepadEvent_gamepadconnected-manual.html
- behavior/tests/Gamepad/res/GamepadEvent_gamepaddisconnected-manual.html
- behavior/tests/VKB/index.html
- behavior/tests/Viewport/index.html
- behavior/tests/WRTSupport/index.html
- behavior/tests/WRTSupport/res/other-uri-schemes.html
- behavior/tests/WRTSupport/res/url-access-multi.html
- Add function to save the result of subcase
> [behavior][XWALK-3570] Add function to save the result of subcase for behavior

- behavior/js/main.js
- behavior/js/tests.js
- behavior/subtestresult.xml
- behavior/suite.json
- behavior/tests/ConfigurationExtension/index.html
- behavior/tests/ConfigurationExtension/res/application-content.html
- behavior/tests/Gamepad/index.html
- behavior/tests/Gamepad/res/GamePadButton_basic-manual.html
- behavior/tests/Gamepad/res/GamePad_basic-manual.html
- behavior/tests/Gamepad/res/GamePad_connected-manual.html
- behavior/tests/Gamepad/res/GamepadEvent_gamepadconnected-manual.html
- behavior/tests/Gamepad/res/GamepadEvent_gamepaddisconnected-manual.html
- behavior/tests/VKB/index.html
- behavior/tests/Viewport/index.html
- behavior/tests/WRTSupport/index.html
- behavior/tests/WRTSupport/res/other-uri-schemes.html
- behavior/tests/WRTSupport/res/url-access-multi.html
- Add function to save the result of subcase
> [Crosswalk-12][behavior][XWALK-3570] Add function to save the result of subcase for behavior

- webapi/tct-extra-html5-tests/suite.json
- webapi/tct-webstorage-w3c-tests/suite.json
Add copylist sub section to apk-aio otherwise all-in-one package will lose the related html files for sub app.
> [webapi] Update suite.json file in extra and webstorage suite

- webapi/tct-extra-html5-tests/suite.json
- webapi/tct-webstorage-w3c-tests/suite.json
Add copylist sub section to apk-aio otherwise all-in-one package will lose the related html files for sub app.
> [webapi]Update suite.json file in extra and webstorage suite

- misc/sampleapp-tizen-tests/sampleapp/M37_NavigatorLanguage.html
- misc/sampleapp-tizen-tests/sampleapp/support/blink/navigator_language.html
- misc/sampleapp-tizen-tests/sampleapp/support/w3c/language.html
- misc/sampleapp-tizen-tests/tests.full.xml
- misc/sampleapp-tizen-tests/tests.xml
> [misc] Integrate M37 Sample for Sampleapp-tizen

- tools/xmlsimplifier/README
- tools/xmlsimplifier/config
- tools/xmlsimplifier/xmlsimlifier.py
- This tools is for simplify the complex tests.xml.
- This tool can identify platfrom and execution type.
> [tool] Add xmlsimlifier.py

- usecase/usecase-wrt-android-tests/samples/ChromeProtocol/README.md
- usecase/usecase-wrt-android-tests/samples/ChromeProtocol/index.html
- usecase/usecase-wrt-android-tests/samples/ChromeProtocol/res/index.html
- usecase/usecase-wrt-android-tests/samples/ChromeProtocol/res/manifest.json
- usecase/usecase-wrt-android-tests/steps/ChromeProtocol/step.js
- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
> [usecase-wrt][xwalk-3595] Add test for ChromeProtocol

- usecase/usecase-wrt-android-tests/samples/ChromeProtocol/README.md
- usecase/usecase-wrt-android-tests/samples/ChromeProtocol/index.html
- usecase/usecase-wrt-android-tests/samples/ChromeProtocol/res/index.html
- usecase/usecase-wrt-android-tests/samples/ChromeProtocol/res/manifest.json
- usecase/usecase-wrt-android-tests/steps/ChromeProtocol/step.js
- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
> [Crosswalk-12][usecase-wrt][xwalk-3595] Add test for ChromeProtocol

- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- usecase/usecase-wrt-android-tests/tests/ChromeProtocol/README.md
- usecase/usecase-wrt-android-tests/tests/ChromeProtocol/index.html
- usecase/usecase-wrt-android-tests/tests/ChromeProtocol/res/index.html
- usecase/usecase-wrt-android-tests/tests/ChromeProtocol/res/manifest.json
> [Crosswalk-11][usecase-wrt][xwalk-3595]Add test for ChromeProtocol

- apptools/wrt-apptools-android-tests/README
- apptools/wrt-apptools-android-tests/apptools/create_no_sdk.py
- Update the README file due to we just need run tests on master now.
> [apptools] Update test for create_no_sdk

- tools/build/pack_cordova_sample.py
> [tools-build] Fix env export issue

- usecase/usecase-webapi-xwalk-tests/samples/FileSystem/index.html
- usecase/usecase-webapi-xwalk-tests/samples/FileSystem/js/main.js
- usecase/usecase-webapi-xwalk-tests/steps/FileSystem/step.js
-Update the test step info
-Update the savefile function
-Remove jquery attribute which is not support on android platform
> [usecase][xwalk-3627] Fix the write file issue of filesystem

- tools/bootstrap-fw/js/main.js
- Update 'sid' of the duplicate set
> [usecase][XWALK-3749] Update 'sid' of the duplicate set for usecase

- tools/atip/atip/common/common.py
- tools/atip/atip/web/web.py
- usecase/usecase-webapi-xwalk-tests/testscripts/steps/steps.py
- Add new steps to save the specified div on page as pictures, and check if these divs are the same as others or not by picture similarity.
> [atip]Add new steps to check if many divs are the same

- tools/build/pack_cordova_sample.py
-Mobilespec can be built successfully
> [Crosswalk-12][tools-build] Fix env export issue in pack_cordova_sample.py

- usecase/usecase-webapi-xwalk-tests/samples/CSP/res/default-src_self/index.html
- usecase/usecase-webapi-xwalk-tests/tests.auto.xml
- usecase/usecase-webapi-xwalk-tests/testscripts/CSP.feature
This PR is dependent on PR#1960
> [usecase] Automate 1 usecase

- tools/apkanalyser/README.md
After running the tool on OSX, I thought that it will good to update some info for users on the same platform.
> Added OSX info and updated link to apktool.

- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkResourceClientTest.java
- embeddingapi/embedding-api-android-tests/tests_v1.xml
Impacted tests(approved): new 4, update 3, delete 1
> [embeddingapi][XWALK-3725] Update XWalkResourceClientTest

- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
Impacted TCs num(approved): New 52, Update 0, Delete 0
Android test result summary: Pass 48, Fail 1, Block 3
- The fail BugId: xwalk-3798
- The three tests blocked due to the failed test
> [apptools] Add nodeunit TCs to test*.xml

- tools/build/pack_deb.py
> [tools]Add pack_deb.py file for linux

- misc/webappmanu-linux-tests/tests.full.xml
- misc/webappmanu-linux-tests/tests.xml
- Update 'status' property from 'designed' to 'approved' in tests.full.xml
- Add new cases list in tests.xml
- Update 'test_script_entry' property value
> [misc] Update tests.full/tests.xml file in webappmanu-linux-tests

- misc/sampleapp-ios-tests/README
- misc/sampleapp-ios-tests/sampleapp/HexGL_Build.html
- misc/sampleapp-ios-tests/sampleapp/HexGL_Function.html
- misc/sampleapp-ios-tests/sampleapp/SampleApp_Build.html
- misc/sampleapp-ios-tests/sampleapp/SampleApp_Function.html
Impacted TCs num(approved): New 4, Update 0, Delete 0
Android test result summary: Pass 4, Fail 0, Block 0
> [misc-ios] Add tests for sampleapp on ios

- cordova/cordova-feature-ios-tests/README
- cordova/cordova-feature-ios-tests/feature/Cordova_Plugin_Device_Demo_Build.html
- cordova/cordova-feature-ios-tests/feature/Cordova_Plugin_Device_Demo_Cordova_Build.html
- cordova/cordova-feature-ios-tests/feature/Cordova_Plugin_Device_Demo_Function.html
- cordova/cordova-feature-ios-tests/feature/Cordova_Plugin_Device_Demo_XwalkView_Build.html
- cordova/cordova-feature-ios-tests/feature/Cordova_Plugin_File_Demo_Build.html
- cordova/cordova-feature-ios-tests/feature/Cordova_Plugin_File_Demo_Cordova_Build.html
- cordova/cordova-feature-ios-tests/feature/Cordova_Plugin_File_Demo_Function.html
- cordova/cordova-feature-ios-tests/feature/Cordova_Plugin_File_Demo_XwalkView_Build.html
Impacted TCs num(approved): New 8, Update 0, Delete 0
Android test result summary: Pass 2, Fail 6, Block 0
- The Failed BugId: xwalk-3840
> [cordova-ios] Add tests for cordova feature

- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkUIClientTest.java
- embeddingapi/embedding-api-android-tests/tests.full.xml
- embeddingapi/embedding-api-android-tests/tests_v1.xml
Impacted tests(approved): new 0, update 0, delete 2
Unit test result summary: pass 0, fail 0, block 0
> [embeddingapi][XWALK-3250] Remove 2 unavailable XWalkUIClientTest subcases

- webapi/tct-colors-css3-tests/css3-color-app/testscripts/t31-color-currentColor-b.feature
> [webapi]keep the result picture

- tools/atip/atip/web/steps.py
- tools/atip/atip/web/web.py
- Save the page as baseline picture, and then check them by manual.Remove those error ones.
- Save the current test page, and then diff it with baseline picture. If same,then the case pass.
> [atip] Add new steps to save baseline picture

- misc/sampleapp-ios-tests/sampleapp/SampleApp_Build.html
- misc/sampleapp-ios-tests/sampleapp/SampleApp_XWalkView_Build.html
Impacted TCs num(approved): New 1, Update 2, Delete 0
Unit test Platform: IOS
IOS test result summary: Pass 2, Fail 1, Block 0
- Fail BugId: xwalk-3845
> [misc-ios] Update tests for sampleapp

- misc/webappmanu-linux-tests/inst.deb.py
- usecase/usecase-wrt-linux-tests/inst.deb.py
- Update code to native mode in order that run in deepin platform
- Remove some unwanted function
- Test successfully
> [misc|usecase] Update inst.deb.py script file

- tools/atip/atip/web/web.py
- If there is no data.conf file, the test tool will work OK.
- Save the result pictures together with the baseline
> [atip] Update atip to adapt if there is no data.conf

- tools/atip/atip/web/web.py
> [atip] save baseline pictures by device

- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkUIClientTest.java
- embeddingapi/embedding-api-android-tests/tests.full.xml
- embeddingapi/embedding-api-android-tests/tests_v1.xml
Impacted tests(approved): new 0, update 0, delete 2
Unit test result summary: pass 0, fail 0, block 0
> [Crosswalk-12][embeddingapi][XWALK-3250] Remove 2 unavailable XWalkUIClientTest subcases

- webapi/tct-colors-css3-tests/css3-color-app/testscripts/t31-color-currentColor-b.feature
> [webapi] Use the html file name as picture name

- usecase/usecase-cordova-android-tests/samples/AppContainer/COPYING
- usecase/usecase-cordova-android-tests/samples/AppContainer/REAMDE.md
- usecase/usecase-cordova-android-tests/samples/AppContainer/index.html
- usecase/usecase-cordova-android-tests/samples/AppContainer/js/index.js
- usecase/usecase-cordova-android-tests/steps/AppContainer/step.js
- usecase/usecase-cordova-android-tests/tests.full.xml
- usecase/usecase-cordova-android-tests/tests.xml
Unit test platform: [Nexus 5][Crosswalk 13.41.309.0]
> [cordova][xwalk-2934] Add test for access iframe with different origin

- stability/stability-iterative-android-tests/iterative/Launch_Exit_Repeatedly.py
> [stability][xwalk-3822] Update TC for iterative

- stability/stability-iterative-android-tests/iterative/Install_Uninstall_Repeatedly.py
- stability/stability-iterative-android-tests/iterative/Launch_Exit_Repeatedly.py
- stability/stability-iterative-android-tests/suite.json
Android test result summary: Pass 2, Fail 0, Block 0
- Add README file to copyist
> [stability][xwalk-3814] Update TCs and suite.json

- tools/build/pack.py
- tools/build/pack_cordova_sample.py
-Successfully pack all cordova suites for 5 times
> [tools][xwalk-3753] Add ANDROID_HOME env before cordova build

- misc/sampleapp-android-tests/sampleapp/M39_WebAnimations_AnimateMethod.html
- misc/sampleapp-android-tests/sampleapp/M39_WebAnimations_PlaybackControl.html
- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
Unit test platform: [Android][Crosswalk 13.42.319.0]
> [misc] Integrate animation sample for WebAnimations

- usecase/usecase-webapi-xwalk-tests/samples/WebCL/README.md
- usecase/usecase-webapi-xwalk-tests/samples/WebCL/index.html
- usecase/usecase-webapi-xwalk-tests/samples/WebCL/res/COPYING
- usecase/usecase-webapi-xwalk-tests/samples/WebCL/res/index.html
- usecase/usecase-webapi-xwalk-tests/steps/WebCL/step.js
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- the WebCL is not supported now, so labeled as designed
> [usecase] Add WebCL usecase

- apptools/apptools-linux-tests/suite.json
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
- apptools/apptools-linux-tests/tools/README
Impacted tests(approved): new 27, update 0, delete 0
Unit test result summary: pass 27, fail 0, block 0
> [apptools] Add nodeunit test for linux apptools

- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Disk_Cache_Size.html
- wrt/wrt-rtcoremanu-android-tests/suite.json
- wrt/wrt-rtcoremanu-android-tests/tests.full.xml
- wrt/wrt-rtcoremanu-android-tests/tests.xml
> [wrt][xwalk-3824] Add test for disk-cache-size option

- apptools/apptools-ios-tests/suite.json
- cordova/cordova-feature-ios-tests/suite.json
- misc/sampleapp-ios-tests/suite.json
- tools/build/pack_ios.py
- The three suites can build successfully.
> [tools-ios] Add pack_ios.py for ios tests

- apptools/apptools-android-tests/README
- apptools/apptools-android-tests/inst.apk.py
- apptools/apptools-android-tests/suite.json
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
- The results won't change after remove the subcase when the value is one
- Add inst.apk.py for manual tests
- The subcase value of application.js should be 7
- Update the command about testkit-lite
> [apptools] Remove subcase when the value is one

- webapi/tct-sandbox-html5-tests/tests.full.xml
- webapi/tct-sandbox-html5-tests/tests.xml
- Change the bdd case execution type from auto to manual
> [webapi][XWALK-3920] Change bdd case execution type for Sandbox

- webapi/tct-backgrounds-css3-tests/suite.json
- webapi/tct-fonts-css3-tests/suite.json
Impacted TCs num(approved): New 0, Update 78, Delete 0
Unit test result summary: Pass 78, Fail 0, Blocked 0
> [webapi][XWALK-3930] Update suit.json to ensure manual case run normally

- tools/build/README.md
- tools/build/pack.py
- tools/build/pack_cordova_sample.py
- Check pack.py in usecase-cordova-android-tests, cordova-sampleapp-android-tests successfully
> [cordova][XWALK-2941] Update pack.py and pack_cordova_sample.py to support shared mode

- webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest/w3c/resources/cgi/inspect-headers.cgi
Unit test platform: [Android][Crosswalk 14.42.331.0]
> [webapi][xwalk-2081] Update inspect-headers.cgi

- webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest/w3c/resources/cgi/inspect-headers.cgi
Unit test platform: [Android][Crosswalk 14.42.331.0]
> [Crosswalk-13][webapi][xwalk-2081]Update inspect-headers.cgi

- webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest/w3c/resources/cgi/inspect-headers.cgi
Unit test platform: [Android][Crosswalk 14.42.331.0]
> [Crosswalk-12][webapi][xwalk-2081] Update inspect-headers.cgi

- behavior/tests/FullScreen/js/main.js
> [behavior][XWALK-3904] Success to cancel css fullscreen mode for fullsrceen

- usecase/usecase-wrt-linux-tests/README.md
Describe the purpose of the test suite and add new test developer.
> [usecase] Update README for the WRT test suite for Linux

- usecase/usecase-wrt-android-tests/samples/LZMACompressionUI/README.md
- usecase/usecase-wrt-android-tests/samples/LZMACompressionUI/index.html
- usecase/usecase-wrt-android-tests/steps/LZMACompressionUI/step.js
- usecase/usecase-wrt-android-tests/tests.full.xml
- Move this test from usecase/usecase-litewrt-android-tests
> [usecase][xwalk-3810] Add test for LZMACompressionUI

- tools/build/README.md
- tools/build/pack.py
- tools/build/pack_cordova_sample.py
- Check pack.py in usecase-cordova-android-tests, cordova-sampleapp-android-tests successfully
> [cordova][Crosswalk-13] Update pack.py and pack_cordova_sample.py to support archs

- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
> [apptools-android][XWALK-3937] Update the set name for apptools android

- usecase/usecase-wrt-android-tests/samples/SharedModeGooglePlay/index.html
- The test can open the third party app store with Crosswalk canary
> [usecase] Update test description

- cordova/cordova-feature-android-tests/README
- cordova/cordova-feature-android-tests/feature/CrossWalk_Cordova_Mobile_Spec_Icon.html
- cordova/cordova-feature-android-tests/feature/CrossWalk_Cordova_Remote_Debug_Breakpoints.html
- cordova/cordova-feature-android-tests/feature/CrossWalk_Cordova_Remote_Debug_CheckInfo.html
- cordova/cordova-feature-android-tests/feature/CrossWalk_Cordova_Remote_Debug_Connection.html
- cordova/cordova-feature-android-tests/feature/CrossWalk_Cordova_Remote_Debug_Modification.html
- cordova/cordova-feature-android-tests/feature/comm.py
- cordova/cordova-feature-android-tests/feature/remotedebugging_pack.py
- cordova/cordova-feature-android-tests/mode.txt
- cordova/cordova-feature-android-tests/suite.json
- cordova/cordova-feature-android-tests/tests.full.xml
- cordova/cordova-feature-android-tests/tests.xml
- cordova/cordova-sampleapp-android-tests/README
- cordova/cordova-sampleapp-android-tests/mode.txt
- cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
- cordova/cordova-sampleapp-android-tests/sampleapp/gallery_build.py
- cordova/cordova-sampleapp-android-tests/suite.json
- cordova/cordova-webapp-android-tests/README
- cordova/cordova-webapp-android-tests/mode.txt
- cordova/cordova-webapp-android-tests/suite.json
- cordova/cordova-webapp-android-tests/webapp/Crosswalk_Cordova_ADT_Project_Import.html
- cordova/cordova-webapp-android-tests/webapp/comm.py
- cordova/cordova-webapp-android-tests/webapp/webapp_build.py
- cordova/cordova-webapp-android-tests/webapp/webapp_create.py
- cordova/cordova-webapp-android-tests/webapp/webapp_run.py
- Update auto cases to support shared mode scene
- Update description for some manual cases
- Failure analysis:XWALK-3956
Impacted tests(approved): new 0, update 11, delete 0
Unit test result summary: pass 8, fail 3, block 0
> [cordova][XWALK-2941] update cases to support shared mode scene

- usecase/usecase-embedding-android-tests/embeddingapi/assets/openedWindow.html
- usecase/usecase-embedding-android-tests/embeddingapi/assets/window_create_open.html
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/OnCreateWindowRequestedActivity.java
> [usecase-embeddingapi][XWALK-2754] Adjust one usecase to suit the bug 2754

- apptools/apptools-android-tests/README
- apptools/apptools-android-tests/apptools/allpairs.py
- apptools/apptools-android-tests/apptools/comm.py
- apptools/apptools-android-tests/apptools/create_remote.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
Failure analysis: https://crosswalk-project.org/jira/browse/XWALK-3960
Impacted tests(approved):new 4,update 6,delete 0
Unit test result summary:pass 7,fail 3,block 0
> [apptools-android] Add nodeunit test for android apptools

- usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
- usecase/usecase-embedding-android-tests/embeddingapi/res/layout/xwview_transparent_layout.xml
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithTransparent.java
- usecase/usecase-embedding-android-tests/tests.android.xml
- usecase/usecase-embedding-android-tests/tests.full.xml
> [embeddingapi][XWALK-3754][XWALK-3778] add use case to check XWalkView's transparent feature

- apptools/apptools-android-tests/apptools/comm.py
> [apptools-android] Add judgment condition to build result for apptools android

- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/AnimatableXWalkViewActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ExtensionActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/FullScreenActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/LoadAppFromManifestLayoutActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/MultiSurfaceViewsActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/MultiTextureViewsActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/MultiXWalkViewActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/OnCreateWindowRequestedActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/OnHideOnShowActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/OnIconAvailableOnReceivedIconActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/PauseTimersActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ResourceAndUIClientsActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ShouldOverrideUrlLoadingActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkNavigationActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkPreferencesActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkVersionAndAPIVersion.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithLayoutActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithTransparent.java
Impacted tests(approved): new 0, update 18, delete 0
Unit test result summary: pass 16, fail 2, block 0
> [usecase-embeddingapi][XWALK-2948] Enable usecase tests to support shared mode

- embeddingapi/embedding-api-android-tests/embeddingapi/AndroidManifest.xml
- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java
Impacted tests(designed|approved): new 0, update 0, delete 0
Unit test result summary: pass 184, fail 16, block 0
> [embeddingapi][XWALK-2948] Enable tests to support shared mode

- apptools/apptools-android-tests/apptools/allpairs.py
- apptools/apptools-ios-tests/apptools/allpairs.py
- apptools/apptools-ios-tests/apptools/pkgName.py
- apptools/apptools-ios-tests/report/cmd.txt
-Update name of generated file
-Fail reson: XWALK-3968
Impacted tests: new 0, update 4, delete 0
Unit test summary: pass 0, fail 4, block 0
> [apptools] Move negtivate name to right place

- apptools/apptools-android-tests/apptools/create_remote.py
> [apptools-android] Remove prj before create apptools android

- webapi/webapi-contactsmanager-w3c-tests/contactsmanager/Navigator_contacts_attribute.html
> [webapi][XWALK-2452]Pass Navigator.contacts by reference

- tools/apkanalyser/main.py
- tools/apkanalyser/result/apk-analyser-result.xsl
- tools/apkanalyser/xml.py
> [tools][apk analyser] Add XWalk Webview Plugin detection

- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.auto.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- usecase/usecase-wrt-android-tests/testscripts/PermissionApiContacts.feature
- usecase/usecase-wrt-android-tests/testscripts/WebappXwalkHost.feature
- usecase/usecase-wrt-android-tests/testscripts/environment.py
- usecase/usecase-wrt-android-tests/testscripts/steps/steps.py
- Add automation feature files
- Format tests xml
toos/xmlsimplifier/xmlsimlifier.py -f tests.full.xml -o tests.android.xml -p android
toos/xmlsimplifier/xmlsimlifier.py -f tests.full.xml -o tests.auto.xml -e auto
Unit test platform: [Android][Crosswalk 14.42.331.0]
> [usecase-wrt] Automation PermissionApiContacts and WebappXwalkHost

- cordova/cordova-feature-android-tests/README
- cordova/cordova-feature-android-tests/suite.json
- cordova/cordova-sampleapp-android-tests/README
- cordova/cordova-sampleapp-android-tests/suite.json
- cordova/cordova-webapp-android-tests/README
- cordova/cordova-webapp-android-tests/suite.json
- Check the step with helloworld, remotedebugging and gallery successfully
- Check the step with cordova-feature-android-tests successfully
> [cordova][XWALK-3984] Update README to support Cordova 4.0 App build with Crosswalk Canary

- apptools/apptools-android-tests/apptools/AppTools_Help.html
- apptools/apptools-android-tests/apptools/Update_CurrentVersion.html
- apptools/apptools-android-tests/apptools/Update_Download.html
- apptools/apptools-android-tests/apptools/allpairs.py
- apptools/apptools-android-tests/apptools/build.py
- apptools/apptools-android-tests/apptools/comm.py
- apptools/apptools-android-tests/apptools/pkgName.py
- apptools/apptools-android-tests/apptools/update.py
- apptools/apptools-android-tests/apptools/version.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
- Failure analysis: https://crosswalk-project.org/jira/browse/XWALK-3779
Impacted tests(approved):new 14,update 2,delete 0
Unit test result summary:pass 15,fail 1,block 0
> [apptools-android] Add tests to test update command for apptools android

- apptools/apptools-android-tests/apptools/AppTools_Download.html
- apptools/apptools-android-tests/apptools/AppTools_Help.html
- apptools/apptools-android-tests/apptools/Update_CurrentVersion.html
- apptools/apptools-android-tests/apptools/Update_Download.html
- apptools/apptools-android-tests/apptools/comm.py
- Failure analysis: https://crosswalk-project.org/jira/browse/XWALK-3779
Unit test result summary:pass 52,fail 3,block 0
> [apptools-android][XWALK-3990] Update the path of main crosswalk-app

- apptools/apptools-linux-tests/apptools/AppTools_Help.html
- apptools/apptools-linux-tests/apptools/version.py
- apptools/apptools-linux-tests/inst.deb.py
- apptools/apptools-linux-tests/suite.json
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
- Failure analysis: https://crosswalk-project.org/jira/browse/XWALK-4022
Impacted tests(approved):new 2,update 0,delete 0
Unit test result summary:pass 1,fail 1,block 0
> [apptools-depin] Add tests to test help and version command for apptools linux

- apptools/apptools-ios-tests/apptools/AppTools_Help.html
- apptools/apptools-ios-tests/apptools/version.py
- apptools/apptools-ios-tests/tests.full.xml
- apptools/apptools-ios-tests/tests.xml
- Failure analysis: https://crosswalk-project.org/jira/browse/XWALK-3781
Impacted tests(approved):new 2,update 0,delete 0
Unit test result summary:pass 1,fail 1,block 0
> [apptools-ios] Add tests to test help and version command for apptools ios

- usecase/usecase-webapi-xwalk-tests/samples/FileSystem/index.html
- usecase/usecase-webapi-xwalk-tests/samples/FileSystem/js/main.js
- usecase/usecase-webapi-xwalk-tests/steps/FileSystem/step.js
-Update the test step info
-Update the savefile function
-Remove jquery attribute which is not support on android platform
> [Crosswalk-12][usecase][xwalk-3627] Fix the write file issue of filesystem

- wrt/tct-appwgt-wrt-tests/blackdirs
- wrt/tct-ext02-wrt-tests/blackdirs
- wrt/tct-pm-wrt-tests/blackdirs
- wrt/tct-sp02-wrt-tests/blackdirs
- wrt/tct-stab-wrt-tests/blackdirs
This is a finding from Cici when talk to Samsung engineer.
> [wrt] Remove unreferenced blackdirs

- embeddingapi/embedding-api-android-tests/embeddingapi/assets/redirect_url.html
- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/LoadTest.java
-Modify the test case 'testGetOriginalUrl' in embeddingAPI
-Add the redirect_url.html about redirection
> [embeddingapi][XWALK-2352]modify 'testGetOriginalUrl'

- apptools/apptools-ios-tests/apptools/crosswalk_app_basic_default.html
- apptools/apptools-ios-tests/apptools/crosswalk_app_basic_release.html
- apptools/apptools-ios-tests/apptools/crosswalk_build_nosdk.html
- apptools/apptools-ios-tests/tests.full.xml
- apptools/apptools-ios-tests/tests.xml
Unit test result summary: pass 1, fail 2, block 0
Fail Reason: XWALK-4048
> [apptools][ios] Add 3 tests

- usecase/usecase-webapi-xwalk-tests/steps/PageVisibility/step.js
- usecase/usecase-webapi-xwalk-tests/tests.wts.xml
> [usecase-webapi][XWALK-4049] Deploy the test to Web Testing Service

- tools/atip/atip/web/steps.py
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.auto.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- usecase/usecase-wrt-android-tests/testscripts/SecurityUrlCertificate.feature
- Fail Reason: https://crosswalk-project.org/jira/browse/XWALK-3806
Unit test platform: [Android][Crosswalk 14.42.335.0]
> [usecase-wrt] Antomatic SecurityUrlCertificate

- embeddingapi/embedding-api-ios-tests/README
- embeddingapi/embedding-api-ios-tests/embeddingapi/xwalkview.py
- embeddingapi/embedding-api-ios-tests/suite.json
- embeddingapi/embedding-api-ios-tests/tests.full.xml
- embeddingapi/embedding-api-ios-tests/tests.xml
- tools/build/setup_ios.py
Impacted TCs num(approved): New 30, Update 0, Delete 0
Unit test Platform: iOS
iOS test result summary: Pass 0, Fail 30, Block 0
The fail bugId: XWALK-4071
> [embeddingapi-ios] Add XWalkViewTest for embeddingapi

- webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/ecmascript_simd_tests.js
- webapi/webapi-simd-nonw3c-tests/simd/float64x2.html
- webapi/webapi-simd-nonw3c-tests/simd/int32x4.html
Unit test platform: [Android][Crosswalk 14.43.342.0]
> [webapi][XWALK-3457] Update SIMD tests by latest spec

- stability/stability-embeddingapi-android-tests/inst.apk.py
- stability/stability-embeddingapi-android-tests/suite.json
- tools/build/pack.py
[XWALK-4096]pack support build test app in java build & build test suite app in js build for stability testcase
> pack support for stability testcase

- embeddingapi/embedding-api-android-tests/embeddingapi/assets/index.xhtml
-Modify index.xhtml in the test case 'testLoad_xhtml_url' in embeddingAPI
> [embeddingapi][XWALK-4059]modify index.xhtml

- tools/bootstrap-fw/index.wts.html
- Due to usecase run on the wts do not need to choose execution type. so add a new index.html.
> [usecase] Add index.html to suit wts environment

- tools/xmlsimplifier/config
- webapi/tct-colors-css3-tests/tests.full.xml
- webapi/tct-colors-css3-tests/tests.xml
- Format tests.full.xml:
`xmllint --format tests.full.xml > tests.full.xml`
- Add new conf item in tools/xmlsimplifier/conf for bdd manual tests
- Smiply tests.xml from tests.full.xml:
`tools/xmlsimplifier/xmlsimlifier.py -f tests.full.xml -o tests.xml`
BUG=https://crosswalk-project.org/jira/browse/XWALK-4120
> [webapi] Update tests.xml to align with tests.full.xml for CSS3 Colors

- usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithLoadImage.java
- usecase/usecase-embedding-android-tests/tests.android.xml
- usecase/usecase-embedding-android-tests/tests.full.xml
-Verifies XWalkView can load image.
> [embeddingapi][XWalk-3738]Add a usecase for load/display image

- embeddingapi/embedding-api-android-tests/embeddingapi/assets/redirect_url.html
- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/LoadTest.java
-Modify the test case 'testGetOriginalUrl' in embeddingAPI
-Add the redirect_url.html about redirection
> [crosswalk13][embeddingapi][XWALK-2352]modify testGetOriginalUrl

- wrt/wrt-rt-linux-tests/tests.full.xml
- wrt/wrt-rt-linux-tests/tests.xml
Update component to "Crosswalk WRT/CSP"
> [webapi] Update component for wrt-rt-linux-tests

- wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_arm_shared.html
- wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_arm_x86_shared.html
- wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_arm_embeded.html
- wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_arm_shared_x86_crosswalk.html
- wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_x86_shared_arm_crosswalk.html
- wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_x86_shared.html
- wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_shared_download_break.html
- wrt/wrt-sharedmodemanu-android-tests/tests.full.xml
- wrt/wrt-sharedmodemanu-android-tests/tests.xml
- Add 2 TCs, update 4 TCs for suite wrt-sharedmodemanu-android-tests
> [wrt]Update the cases for sharedmode

- wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_arm_shared_x86_2.html
- wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_x86_shared_arm_2.html
- wrt/wrt-sharedmodemanu-android-tests/tests.full.xml
- wrt/wrt-sharedmodemanu-android-tests/tests.xml
-Add 2 TCs for suite wrt-sharedmodemanu-android-tests
> [wrt]Add cases for sharedmode

- embeddingapi/embedding-api-android-tests/embeddingapi/assets/index.xhtml
-Modify index.xhtml in the test case 'testLoad_xhtml_url' in embeddingAPI
> [Crosswalk13][embeddingapi][XWALK-4059]modify index.xhtml

- stability/stability-embeddingapi-android-tests/auto/Launch_Create1_Exit_Repeat1000.py
- stability/stability-embeddingapi-android-tests/manual/Multi_Tab Xwalkview_Website.html
- stability/stability-embeddingapi-android-tests/testapp/AndroidManifest.xml
- stability/stability-embeddingapi-android-tests/testapp/res/layout/view_tab_scroll.xml
- stability/stability-embeddingapi-android-tests/testapp/src/org/xwalkview/maximum/app/TabSurfaceViewsActivity.java
- stability/stability-embeddingapi-android-tests/testapp/src/org/xwalkview/maximum/app/TabTextureViewsActivity.java
- stability/stability-embeddingapi-android-tests/testapp/src/org/xwalkview/maximum/app/TabWebViewsActivity.java
- stability/stability-embeddingapi-android-tests/testapp/src/org/xwalkview/maximum/app/XWalkBaseTabActivity.java
- stability/stability-embeddingapi-android-tests/tests.full.xml
- stability/stability-embeddingapi-android-tests/tests.xml
> [stability-embeddingapi][XWALK-3783]Add multi tab case for stability

- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Disk_Cache_Size.html
- wrt/wrt-rtcoremanu-android-tests/suite.json
- wrt/wrt-rtcoremanu-android-tests/testapp/disk-cache-size-tests/manifest.json
> [wrt][xwalk-3821] Update the TCs for --disable-cache-size

- stability/stability-manual-android-tests/manual/Overload_LoadLargeImageList.html
- stability/stability-manual-android-tests/manual/Standard_ScrollLargeHightPage.html
- stability/stability-manual-android-tests/suite.json
- stability/stability-manual-android-tests/testapp/README
- stability/stability-manual-android-tests/tests.full.xml
- stability/stability-manual-android-tests/tests.xml
- Add two stability tests for XWALK-4050/4094, XWALK-3941
- Update test purpose in test xml
- Format tests.full.xml:
`xmllint --format tests.full.xml`
- convert tests.xml from tests.full.xml:
`tools/xmlsimplifier/xmlsimlifier.py -f tests.full.xml -o tests.xml`
Unit test platform: [Android][Crosswalk 14.43.342.0]
BUG=https://crosswalk-project.org/jira/browse/XWALK-4050
BUG=https://crosswalk-project.org/jira/browse/XWALK-4094
BUG=https://crosswalk-project.org/jira/browse/XWALK-3941
> [stability] Add LoadImageList and ScrollLargeHightPage test

- misc/webapi-noneservice-tests/pack.sh
- misc/webapi-service-tests/pack.sh
- tools/build/pack.py
- tools/build/pack_cordova_sample.py
- Check pack.py in usecase-cordova-android-tests, cordova-sampleapp-android-tests successfully
- Check pack.sh in webapi-noneservice-tests and webapi-service-tests successfully
BUG=https://crosswalk-project.org/jira/browse/XWALK-4055
> [cordova][XWALK-4055] pack cordova 4.0 using cli way

- cordova/cordova-feature-android-tests/README
- cordova/cordova-feature-android-tests/feature/comm.py
- cordova/cordova-feature-android-tests/feature/mobilespec_close.py
- cordova/cordova-feature-android-tests/feature/mobilespec_launch.py
- cordova/cordova-feature-android-tests/feature/remotedebugging_pack.py
- cordova/cordova-feature-android-tests/suite.json
- cordova/cordova-sampleapp-android-tests/README
- cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
- cordova/cordova-sampleapp-android-tests/sampleapp/gallery_build.py
- cordova/cordova-sampleapp-android-tests/sampleapp/gallery_close.py
- cordova/cordova-sampleapp-android-tests/sampleapp/gallery_launch.py
- cordova/cordova-sampleapp-android-tests/sampleapp/gallery_uninstall_withAppRunning.py
- cordova/cordova-sampleapp-android-tests/suite.json
- cordova/cordova-webapp-android-tests/README
- cordova/cordova-webapp-android-tests/suite.json
- cordova/cordova-webapp-android-tests/webapp/comm.py
- cordova/cordova-webapp-android-tests/webapp/webapp_build.py
- cordova/cordova-webapp-android-tests/webapp/webapp_close.py
- cordova/cordova-webapp-android-tests/webapp/webapp_create.py
- cordova/cordova-webapp-android-tests/webapp/webapp_launch.py
- cordova/cordova-webapp-android-tests/webapp/webapp_run.py
- doc/Cordova_Test_Suite_User_Guide.md
Impacted tests(approved): new 0, update 12, delete 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4139
> [cordova][XWALK-4139] Update cases for cordova cli integration

- webapi/webapi-webrtc-w3c-tests/webrtc/blink/RTCPeerConnection-AddRemoveStream.html
Unit test Platform: Crosswalk Project for Android 14.42.355.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-3974
> [webapi] Fix WebRTC test issue on MEMO Pad

- usecase/usecase-cordova-android-tests/samples/CordovaXwalkHost/README.md
- usecase/usecase-cordova-android-tests/samples/CordovaXwalkHost/index.html
- usecase/usecase-cordova-android-tests/samples/CordovaXwalkHost/res/index.html
- usecase/usecase-cordova-android-tests/steps/CordovaXwalkHost/step.js
- usecase/usecase-cordova-android-tests/suite.json
- usecase/usecase-cordova-android-tests/tests.full.xml
Impacted tests(desgined): new 1, update 0, delete 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-3882
> [usecase-cordova][XWALK-3882] Add usecase for cordova xwalk host

- webapi/tct-webmessaging-w3c-tests/webmessaging/webmessaging_MessagePort_postMessage_no_args.html
Unit test Platform: Crosswalk Project for Android 14.43.342.0
https://crosswalk-project.org/jira/browse/XWALK-4039
> [Crosswalk-14] Update the case for WebMessaging

- apptools/apptools-linux-tests/apptools/allpairs.py
- apptools/apptools-linux-tests/apptools/create.py
- apptools/apptools-linux-tests/apptools/pkgName.py
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
- Failure analysis: https://crosswalk-project.org/jira/browse/XWALK-4013
Impacted tests(approved):new 1,update 17,delete 0
Unit test result summary:pass 17,fail 1,block 0
> [apptools-depin] Update project name for apptools depin

- usecase/usecase-wrt-android-tests/samples/MisarchEmbeddedArm/README.md
- usecase/usecase-wrt-android-tests/samples/MisarchEmbeddedArm/index.beta.html
- usecase/usecase-wrt-android-tests/samples/MisarchEmbeddedArm/index.html
- usecase/usecase-wrt-android-tests/samples/MisarchEmbeddedArm/res/manifest.json
- usecase/usecase-wrt-android-tests/samples/MisarchEmbeddedIA/README.md
- usecase/usecase-wrt-android-tests/samples/MisarchEmbeddedIA/index.beta.html
- usecase/usecase-wrt-android-tests/samples/MisarchEmbeddedIA/index.html
- usecase/usecase-wrt-android-tests/samples/MisarchEmbeddedIA/res/manifest.json
- usecase/usecase-wrt-android-tests/steps/MisarchEmbeddedArm/step.js
- usecase/usecase-wrt-android-tests/steps/MisarchEmbeddedIA/step.js
- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
> [usecase] Add misarch tests for sharedmode

- webapi/tct-webmessaging-w3c-tests/webmessaging/webmessaging_MessagePort_postMessage_no_args.html
Unit test Platform: Crosswalk Project for Android 14.43.342.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4039
> [webapi] Update the case for WebMessaging

- usecase/usecase-wrt-android-tests/suite.json
- Add the MisarchEmbeddedIA and MisarchEmbeddedArm beta html to suite.json
> [usecase] Update suite.json for pack beta test suite

- webapi/webapi-simd-nonw3c-tests/simd/float64x2.html
- webapi/webapi-simd-nonw3c-tests/simd/int32x4.html
- webapi/webapi-simd-nonw3c-tests/tests.full.xml
- webapi/webapi-simd-nonw3c-tests/tests.xml
Fail analysis: See more info at https://crosswalk-project.org/jira/browse/XWALK-4222.
Impacted TCs num(approved): New 32, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 15.43.347
Unit test result summary: Pass 16, Fail 16, Blocked 0
https://crosswalk-project.org/jira/browse/XWALK-3780
> [webapi] Enable 32 tests for SIMD

- apptools/apptools-android-tests/apptools/check_target_version.py
- apptools/apptools-android-tests/tests.full.xml
The status of test case is designed.
https://crosswalk-project.org/jira/browse/XWALK-3833
> [apptools-android] Check for required minimum API target version on apptools android

- usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
- usecase/usecase-embedding-android-tests/embeddingapi/res/layout/clearcache_layout.xml
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithClearCache.java
- usecase/usecase-embedding-android-tests/tests.android.xml
- usecase/usecase-embedding-android-tests/tests.full.xml
-Add usecase to clear the cache and disk cache
BUG=https://crosswalk-project.org/jira/browse/XWALK-4052
> [embeddingapi][XWALK-4052]add usecase to clear the cache

- apptools/apptools-ios-tests/apptools/crosswalk_app_basic_default.html
- apptools/apptools-ios-tests/apptools/crosswalk_app_basic_release.html
- apptools/apptools-ios-tests/apptools/crosswalk_build_nosdk.html
> [apptools-ios] Fix typo

- tools/build/pack.py
@jennycao Sorry for this bug, it lead to failure in some other suites build packing. fix it now.
> [tools]Update pack.py for new ways to pack usecase-wrt beta suite

- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
Impacted tests(approved):new 0,update 6,delete 0
Unit test result summary:pass 6,fail 0,block 0
> [apptools-android] Set timeout for apptools android

- tools/build/pack.py
- The test suite can build successfully after update the script
> [usecase] Update beta to googleplayer in script pack.py

- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- Remove some testcase due to the cases have been updated
- The test suite can build successfully
> [usecase] Update tests*.xml for sharedmode

- tools/build/README.md
- tools/build/pack.py
- tools/build/pack_cordova_sample.py
- Automate Cordova API 4.0 build in pack_cordova_sample.py
- Improve pack.py, pack_cordova_sample.py to check exist before copy generated apk
> [XWALK-4239][Crosswalk-14] Automate Cordova API 4.0 build in pack_cordova_sample.py

- apptools/apptools-android-tests/apptools/Update_Download.html
- apptools/apptools-android-tests/apptools/check_log.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
- apptools/apptools-ios-tests/apptools/check_log.py
- apptools/apptools-ios-tests/tests.full.xml
- apptools/apptools-ios-tests/tests.xml
- apptools/apptools-linux-tests/apptools/check_log.py
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4199
https://crosswalk-project.org/jira/browse/XWALK-4272
Impacted tests(approved):new 3,update 4,delete 0
Unit test result summary:pass 5,fail 2,block 0
> [apptools] Add tests to check logs for apptools

- usecase/usecase-embedding-android-tests/embeddingapi/assets/openedWindow.html
- usecase/usecase-embedding-android-tests/embeddingapi/assets/window_create_open.html
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/OnCreateWindowRequestedActivity.java
BUG=https://crosswalk-project.org/jira/browse/XWALK-3918
> [usecase-embeddingapi][xwalk-3918][Crosswalk-13] Adjust one usecase to suit the bug 2754

- doc/Coding_Style_Guide_CheatSheet.md
And format this doc's code snippets.
> [doc] Add a practice of python code auto formatting

- tools/build/pack.py
- usecase/usecase-cordova-android-tests/README.md
- usecase/usecase-cordova-android-tests/suite.json
Unit test platform: Crosswalk Project for Android 15.43.347.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4246
> [usecase-cordova][Crosswalk-14] Add screenshot plugin when building package

- usecase/usecase-cordova-android-tests/README.md
- usecase/usecase-cordova-android-tests/suite.json
Unit test platform: Crosswalk Project for Android 15.43.347.0
https://crosswalk-project.org/jira/browse/XWALK-4246
> [usecase-cordova] Add screenshot plugin when building cordova usecase package

- misc/webappmanu-linux-tests/tests.full.xml
- misc/webappmanu-linux-tests/tests.xml
Unit test platform: Crosswalk Project for Linux 15.43.347.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4285
> [misc] Update test entry for Webapp Manu Linux

- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.shared.xml
- Move the test UpgradeLib from tests.android.xml to tests.shared.xml
> [usecase] Move UpgradeLib to shared.xml

- apptools/apptools-ios-tests/apptools/crosswalk_app_basic_default.html
- apptools/apptools-ios-tests/apptools/crosswalk_app_basic_release.html
- apptools/apptools-ios-tests/apptools/crosswalk_build_nosdk.html
Impacted tests(approved):new 0, update 3, delete 0
Unit test platform:[iOS]
Unit test result summary:pass 3, fail 0, block 0
> [apptools-ios] Improve test steps

- webapi/tct-webstorage-w3c-tests/tests.full.xml
- webapi/tct-webstorage-w3c-tests/tests.xml
Unit test platform: Crosswalk for Android 15.43.354.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-3807
> [webapi] Update xml for WebStorage

- usecase/usecase-wrt-android-tests/samples/LZMACompressionUI/index.html
- usecase/usecase-wrt-android-tests/samples/LZMACompressionUI/res/manifest.json
- usecase/usecase-wrt-android-tests/steps/LZMACompressionUI/step.js
- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
https://crosswalk-project.org/jira/browse/XWALK-4326
https://crosswalk-project.org/jira/browse/XWALK-3810
> [usecase] Update the description for LZMACompressionUI

- usecase/usecase-embedding-android-tests/testresult.xsl
BUG=https://crosswalk-project.org/jira/browse/XWALK-4297
> [usecase-embeddingapi] Add testresult.xsl for usecase-embedding-android-tests

- usecase/usecase-embedding-android-tests/suite.json
- usecase/usecase-embedding-android-tests/tests.android.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-3931
> [Crosswalk-13][usecase-embeddingapi]Consist tests.android.xml with tests.full.xml

- usecase/usecase-wrt-android-tests/suite.json
- The suite can work well after update the suite.json
> [Crosswalk-14][usecase] Update suite.json for tests.shared.xml

- tools/build/README.md
- tools/build/pack_cordova_sample.py
- It's successful to build CIRC apk
BUG=https://crosswalk-project.org/jira/browse/XWALK-4329
> [Cordova] Auto the CIRC build

- usecase/usecase-wrt-android-tests/samples/LZMACompressionUI/index.html
- usecase/usecase-wrt-android-tests/steps/DownloadUsage/res/downloadsimul/step.js
- usecase/usecase-wrt-android-tests/steps/LZMACompressionUI/step.js
- Update downloadsimul description
- Update the format for LZMACompressionUI
https://crosswalk-project.org/jira/browse/XWALK-4326
Android test result summary: Pass 1, Fail 1, Block 0
> [usecase] Update the description for downloadsimul

- tools/build/pack.py
- usecase/usecase-cordova-android-tests/suite.json
https://crosswalk-project.org/jira/browse/XWALK-4246
> [Crosswalk-14][usecase-cordova] Update thirdparty plugin path

- apptools/apptools-sampleapp-tests/sampleapp-android/Crosswalk_Apptools_SampleApp_Gallery_Build_Arm.html
- apptools/apptools-sampleapp-tests/sampleapp-android/Crosswalk_Apptools_SampleApp_Gallery_Build_X86.html
- apptools/apptools-sampleapp-tests/sampleapp-deb/Crosswalk_Apptools_SampleApp_Gallery_Build_Deb.html
- apptools/apptools-sampleapp-tests/sampleapp-ios/Crosswalk_Apptools_SampleApp_Gallery_Build_iOS.html
- apptools/apptools-sampleapp-tests/tests.android.xml
- apptools/apptools-sampleapp-tests/tests.deb.xml
- apptools/apptools-sampleapp-tests/tests.full.xml
- apptools/apptools-sampleapp-tests/tests.ios.xml
> [apptools] Add checkpoints for apptools sampleapps

- usecase/usecase-apptools-tests/samples-android/AppTools_arm/index.html
- usecase/usecase-apptools-tests/samples-android/AppTools_x86/index.html
- usecase/usecase-apptools-tests/samples-deb/AppTools_deb/index.html
- usecase/usecase-apptools-tests/samples-ios/AppTools_iOS/index.html
- usecase/usecase-apptools-tests/tests.android.xml
- usecase/usecase-apptools-tests/tests.deb.xml
- usecase/usecase-apptools-tests/tests.full.xml
- usecase/usecase-apptools-tests/tests.ios.xml
> [usecase-apptools] Add checkpoints for usecase apptools

- tools/atip/atip/web/steps.py
- usecase/usecase-webapi-xwalk-tests/testscripts/WebStorage.feature
Unit test platform: Crosswalk Project for Android 15.43.355.0
> [usecase-webapi] Update WebStorage.feature

- tools/build/pack_cordova_sample.py
-Add com.telerik.plugins.nativepagetransitions@0.4.0 plugin and cordova-plugin-thirdparty-tests in mobilespec build
-Improve mobilespec build for cordova 4.0
-It's successfull to build mobilespec apk using this script
BUG=https://crosswalk-project.org/jira/browse/XWALK-4347
> [cordova] Google NativepageTransition plugin interation

- usecase/usecase-wrt-android-tests/samples/ApplicationlocalStorage/README.md
- usecase/usecase-wrt-android-tests/samples/ApplicationlocalStorage/index.html
- usecase/usecase-wrt-android-tests/samples/ApplicationlocalStorage/res/rebootsystem/index.html
- usecase/usecase-wrt-android-tests/samples/ApplicationlocalStorage/res/res/index.html
- usecase/usecase-wrt-android-tests/samples/ApplicationlocalStorage/res/res/js/main.js
- usecase/usecase-wrt-android-tests/samples/ApplicationlocalStorage/res/res/manifest.json
- usecase/usecase-wrt-android-tests/samples/ApplicationlocalStorage/res/restartapp/index.html
- usecase/usecase-wrt-android-tests/samples/ApplicationlocalStorage/res/upgradeapp/index.html
- usecase/usecase-wrt-android-tests/samples/ApplicationlocalStorage/subcase.json
- usecase/usecase-wrt-android-tests/steps/ApplicationlocalStorage/res/rebootsystem/step.js
- usecase/usecase-wrt-android-tests/steps/ApplicationlocalStorage/res/restartapp/step.js
- usecase/usecase-wrt-android-tests/steps/ApplicationlocalStorage/res/upgradeapp/step.js
- usecase/usecase-wrt-android-tests/steps/ApplicationlocalStorage/step.js
- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- Fail BugID: XWALK-4260
Impacted TCs num(approved): New 3, Update 0, Delete 0
Android test result summary: Pass 0, Fail 3, Block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4271
> [usecase] Add test for localStorage

- apptools/apptools-android-tests/apptools/mainactivity.py
- apptools/apptools-android-tests/tests.full.xml
Add 3 test cases to test MainActivity.java changed. The status of these test cases are designed.
https://crosswalk-project.org/jira/browse/XWALK-4114
> [apptools-android] Check if MainActivity.java changed for apptools android

- webapi/tct-extra-html5-tests/tests.full.xml
- webapi/tct-extra-html5-tests/tests.xml
- webapi/tct-extra-html5-tests/w3c/semantics/forms/the-textarea-element/textarea-placeholder-manual.html
Unit test platform: Crosswalk Project for Android 15.43.353.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-3335
> [webapi] Add test to check placeholder in textarea element

- usecase/usecase-wrt-auto-tests/samples/PackertoolHelpVersion/helpversion.py
- usecase/usecase-wrt-auto-tests/tests.full.xml
- usecase/usecase-wrt-auto-tests/tests.xml
- The test suite can run normally
Impacted TCs num(approved): New 0, Update 0, Delete 1
> [usecase] Remove the duplicate TC from usecase auto

- wrt/wrt-packertool2-android-tests/testapp/packer_tool_minify_tests/index.html
- wrt/wrt-packertool2-android-tests/testapp/packer_tool_minify_tests/manifest.json
- wrt/wrt-packertool2-android-tests/testapp/packer_tool_minify_tests/resource/script.js
- wrt/wrt-packertool2-android-tests/testapp/packer_tool_minify_tests/resource/style.css
Android test result summary: Pass 2, Fail 0, Block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4041
> [wrt] Add sub testapp folder for packertool2

- usecase/usecase-wrt-android-tests/samples/UpgradeLib/README.md
- usecase/usecase-wrt-android-tests/samples/UpgradeLib/index.html
- usecase/usecase-wrt-android-tests/steps/DownloadUsage/res/downloadsimul/step.js
- usecase/usecase-wrt-android-tests/steps/UpgradeLib/step.js
- usecase/usecase-wrt-android-tests/tests.full.xml
- Add upgrade test
- Update test description for DownloadUsage/res/downloadsimul
> [Crosswalk-14][usecase] Add test for upgradelib

- usecase/usecase-wrt-linux-tests/tests.full.xml
- usecase/usecase-wrt-linux-tests/tests.xml
Feature https://crosswalk-project.org/jira/browse/
XWALK-3823 has been resolved, change test status from
"designed" to "approved"
Unit test platform: Crosswalk Project for Linux 15.35.43.360
> [usecase-linux] Update test status for SystemIMEs

- wrt/wrt-packertool2-android-tests/packertool2/versionCodetest.py
BUG=https://crosswalk-project.org/jira/browse/XWALK-3909
> [wrt] Update test description for versionCode

- misc/webapi-service-tests/pack.sh
BUG=https://crosswalk-project.org/jira/browse/XWALK-4381
> Modify the packing path

- tools/atip/atip/web/steps.py
- usecase/usecase-webapi-xwalk-tests/testscripts/WebStorage.feature
Unit test platform: Crosswalk Project for Android 15.43.355.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4379
> [Crosswalk-14][usecase-webapi] Update WebStorage.feature

- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
- usecase/usecase-embedding-android-tests/tests.android.xml
- usecase/usecase-embedding-android-tests/tests.full.xml
-update usecase-embedding-android-tests tests.xml file
-complete usecase-embedding-android-tests README
Unit test result summary: pass 0, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4392
> [embeddingapi] Update usecase android test xml

- cordova/cordova-feature-android-tests/README
- cordova/cordova-sampleapp-android-tests/README
- cordova/cordova-webapp-android-tests/README
- tools/build/README.md
- tools/build/pack.py
- tools/build/pack_cordova_sample.py
- usecase/usecase-cordova-android-tests/samples/StatusBar4.0/index.html
-It's successful to build cordova 4.0 pkg
BUG=https://crosswalk-project.org/jira/browse/XWALK-4398
> [cordova] Upgrade Cordova CLI to higher version

- usecase/usecase-apptools-tests/manifest.json
Add manifest.json for packing deepin package successful
BUG=https://crosswalk-project.org/jira/browse/XWALK-4409
> [usecase-apptools] Add manifest.json for usecase apptools

- apptools/apptools-linux-tests/apptools/check_log.py
https://crosswalk-project.org/jira/browse/XWALK-4199
Unit test platform:[Deepin]
Unit test result summary:pass 0,fail 1,block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4408
> [apptools-deepin] Update the path of file for apptools deepin

- tools/build/README.md
- usecase/usecase-cordova-android-tests/samples/CordovaPackage4.0/index.html
- usecase/usecase-cordova-android-tests/samples/StatusBar3.6/index.html
-Build cordova pkg successfully
BUG=https://crosswalk-project.org/jira/browse/XWALK-4413
> [cordova] Update the plugman version

- wrt/wrt-packertool2-android-tests/testapp/packer_tool_minify_tests/index.html
- wrt/wrt-packertool2-android-tests/testapp/packer_tool_minify_tests/manifest.json
- wrt/wrt-packertool2-android-tests/testapp/packer_tool_minify_tests/resource/script.js
- wrt/wrt-packertool2-android-tests/testapp/packer_tool_minify_tests/resource/style.css
Android test result summary: Pass 2, Fail 0, Block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4041
> [Crosswalk-14][wrt] Add sub testapp folder for packertool2

- wrt/wrt-packertool2-android-tests/packertool2/versionCodetest.py
BUG=https://crosswalk-project.org/jira/browse/XWALK-3909
> [Crosswalk-14][wrt] Update test description for versionCode

- cordova/cordova-api-ios-tests/README
- cordova/cordova-api-ios-tests/cordovaapi/mobilespec.js
- cordova/cordova-api-ios-tests/cordovaapi/mobilespec_test.py
- cordova/cordova-api-ios-tests/suite.json
- cordova/cordova-api-ios-tests/tests.full.xml
- cordova/cordova-api-ios-tests/tests.xml
- tools/build/setup_ios.py
- The test suite can run normally.
- Update tools/build/setup_ios.py
> [cordova] Add uiautomation script for mobilespec

- tools/build/pack_cordova_sample.py
-Pack mobilespec apk successfully
BUG=https://crosswalk-project.org/jira/browse/XWALK-4414
> [cordova] Upgrade NativePageTransitions to 0.4.1

- wrt/wrt-rtcoremanu-android-tests/suite.json
BUG=https://crosswalk-project.org/jira/browse/XWALK-4362
> [wrt] Update test for disk-cache-size

- wrt/wrt-rtcoremanu-android-tests/suite.json
> [Crosswalk-14][wrt] Update test for disk-cache-size

- embeddingapi/embedding-api-ios-tests/README
- embeddingapi/embedding-api-ios-tests/embeddingapi/xwalkview.py
- The test suite can run normally
> [embedding] Format the python script for xwalkview test

- embeddingapi/embedding-api-ios-tests/README
- embeddingapi/embedding-api-ios-tests/embeddingapi/xwalkview.py
- The test suite can run normally with testkit-lite
- Update README file
> [Crosswalk-14][wrt] Format python script for xwalkview

- tools/atip/atip/web/steps.py
- usecase/usecase-webapi-xwalk-tests/testscripts/WebStorage.feature
Unit test platform: Crosswalk Project for Android 15.43.355.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4379
> [Crosswalk-13][usecase-webapi] Update WebStorage.feature

- usecase/usecase-webapi-xwalk-tests/steps/Geolocation/step.js
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/tests.wts.xml
Unit test platform: Crosswalk Project for Android 15.44.364.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4113
> [usecase] Rename Geolocation from LocationGPS

- cordova/cordova-feature-android-tests/feature/CrossWalk_Cordova_Remote_Debug_ReplaceState.html
- cordova/cordova-feature-android-tests/tests.full.xml
- cordova/cordova-feature-android-tests/tests.xml
Unit test platform: Crosswalk Project for Android 15.44.365.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-3362
> [cordova] Add case for replaceState

- cordova/cordova-sampleapp-android-tests/tests.full.xml
- cordova/cordova-sampleapp-android-tests/tests.xml
- cordova/cordova-webapp-android-tests/tests.full.xml
- cordova/cordova-webapp-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-3996
> [Crosswalk-14][cordova] make the component name coincident for cordova features

- webapi/webapi-presentation-xwalk-tests/presentation/presentation_test/steps03-manual.html
Unit test platform: Crosswalk for Android 15.43.354.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4419
> [webapi] Update test for WebAPI presentation

- usecase/usecase-webapi-xwalk-tests/steps/Geolocation/step.js
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
Unit test platform: Crosswalk Project for Android 15.44.364.0
https://crosswalk-project.org/jira/browse/XWALK-4113
> [Crosswalk-13][usecase] Rename Geolocation from LocationGPS

- usecase/usecase-webapi-xwalk-tests/steps/Geolocation/step.js
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/tests.wts.xml
Unit test platform: Crosswalk Project for Android 15.44.364.0
https://crosswalk-project.org/jira/browse/XWALK-4113
> [Crosswalk-14][usecase] Rename Geolocation from LocationGPS

- webapi/tct-touchevent-w3c-tests/tests.full.xml
- webapi/tct-touchevent-w3c-tests/tests.xml
Unit test platform: Crosswalk Project for Android 15.44.364.0
> [webapi] Fix dupldate test entry in Touch Event

- misc/sampleapp-ios-tests/sampleapp/HexGL_Build.html
- misc/sampleapp-ios-tests/sampleapp/HexGL_Function.html
- misc/sampleapp-ios-tests/sampleapp/Presentation_Function.html
- misc/sampleapp-ios-tests/sampleapp/SampleApp_Build.html
- misc/sampleapp-ios-tests/sampleapp/SampleApp_Function.html
- misc/sampleapp-ios-tests/tests.full.xml
- misc/sampleapp-ios-tests/tests.xml
- Fail BugID: XWALK-4473
Impacted TCs num(approved): New 1, Update 5, Delete 0
Unit test Platform: iOS
iOS test result summary: Pass 5, Fail 1, Block 0
> [misc] Add test for Presentation

- cordova/cordova-api-ios-tests/tests.full.xml
- cordova/cordova-api-ios-tests/tests.xml
- Remove the subcase from tests*.xml
> [cordova] Update tests*.xml for cordovaapi

- usecase/usecase-cordova-android-tests/samples/StatusBar3.6/index.html
- usecase/usecase-cordova-android-tests/samples/StatusBar4.0/index.html
- usecase/usecase-cordova-android-tests/suite.json
- Use the latest version of statusbar for StatusBar4.0
- Use statusbar 0.1.9 for StatusBar3.6
Unit test platform: Crosswalk Project for Android 15.44.365.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4351
> [cordova] Add test resources for usecase-cordova 4.0

- cordova/cordova-sampleapp-android-tests/sampleapp/Crosswalk_Cordova_SampleApp_CIRC_Channel.html
Unit test platform: Crosswalk Project for Android 15.44.365.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4418
> [cordova] update one step of Crosswalk_Cordova_SampleApp_CIRC_Channel

- usecase/usecase-wrt-android-tests/samples/NormalizingDialogs/README.md
- usecase/usecase-wrt-android-tests/samples/NormalizingDialogs/index.html
- usecase/usecase-wrt-android-tests/samples/NormalizingDialogs/res/appstore/index.html
- usecase/usecase-wrt-android-tests/samples/NormalizingDialogs/res/newer/index.html
- usecase/usecase-wrt-android-tests/samples/NormalizingDialogs/res/older/index.html
- usecase/usecase-wrt-android-tests/samples/NormalizingDialogs/subcase.json
- usecase/usecase-wrt-android-tests/steps/NormalizingDialogs/res/appstore/step.js
- usecase/usecase-wrt-android-tests/steps/NormalizingDialogs/res/newer/step.js
- usecase/usecase-wrt-android-tests/steps/NormalizingDialogs/res/older/step.js
- usecase/usecase-wrt-android-tests/steps/NormalizingDialogs/step.js
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- Fail BugID: XWALK-4480
Impacted TCs num(approved): New 3, Update 0, Delete 0
Android test result summary: Pass 1, Fail 2, Block 0
> [usecase] Add tests for NormallizingDialogs

- embeddingapi/embedding-api-android-tests/embeddingapi/assets/pause_timers.html
- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkViewTest.java
- embeddingapi/embedding-asyncapi-android-tests/embeddingapi/assets/pause_timers.html
- embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkViewTest.java
-Modify testResumeTimers_function & testPauseTimers_function cases
BUG=https://crosswalk-project.org/jira/browse/XWALK-4444
> [Embeddingapi] Modify pause & resume time autocase

- usecase/usecase-wrt-linux-tests/res/testapp/org.display.standalone/index.html
BUG=https://crosswalk-project.org/jira/browse/XWALK-4460
> [Linux] Update title desc for Standalone usecase

- misc/webappmanu-linux-tests/webapp/Youdao_Note_Feature.html
- misc/webappmanu-linux-tests/webapp/Youdao_Note_Link.html
- misc/webappmanu-linux-tests/webapp/Youdao_Note_Name.html
- misc/webappmanu-linux-tests/webapp/Youdao_Note_UI.html
Unit test platform: Crosswalk for Linux 15.43.360.0
https://crosswalk-project.org/jira/browse/XWALK-4461
> [misc-linux] Update test steps for Youdao note

- webapi/tct-fileapi-w3c-tests/tests.full.xml
- webapi/tct-fileapi-w3c-tests/tests.xml
Unit test Platform: Crosswalk Project for Android 15.44.364
> [webapi] Update the reduplicated case for FileAPI

- tools/resources/testharness/README.md
- tools/resources/testharness/testharness.js
Try run test suites, test run normally including:
webapi-devicecapabilities-w3c-tests
webapi-promises-nonw3c-tests
> [tools] Sync testharness.js related scripts to latest

- embeddingapi/embedding-api-android-tests/README
- embeddingapi/embedding-api-android-tests/embeddingapi/build.gradle
- embeddingapi/embedding-api-android-tests/embeddingapi/pom.xml
- tools/build/pack.py
- usecase/usecase-embedding-android-tests/README.md
- usecase/usecase-embedding-android-tests/embeddingapi/build.gradle
- usecase/usecase-embedding-android-tests/embeddingapi/pom.xml
- It's successful to build embeddingapi pkg using maven build and gradle build
https://crosswalk-project.org/jira/browse/XWALK-3784
> [Crosswalk-14][embeddingapi] Improve maven build and gradle build for embeddingapi

- usecase/usecase-wrt-android-tests/steps/ManifestCSP/step.js
- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
> [usecase-wrt] Add test for CSP to usecase

- usecase/usecase-apptools-tests/samples-android/AppTools_install_crosswalk_app_arm/index.html
- usecase/usecase-apptools-tests/samples-android/AppTools_install_crosswalk_app_x86/index.html
- usecase/usecase-apptools-tests/tests.android.xml
- usecase/usecase-apptools-tests/tests.full.xml
Impacted tests(approved):new 2,update 0,delete 0
Unit test result summary:pass 2,fail 0,block 0
> [usecase-apptools] Add tests to test installing crosswalk-app-tools for apptools android

- embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/AnimatableXWalkViewActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/ContactExtensionActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/EchoExtensionActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/FullScreenActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/LoadAppFromManifestLayoutActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/MultiSurfaceViewsActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/MultiTextureViewsActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/MultiXWalkViewActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/OnCreateWindowRequestedActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/OnHideOnShowActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/OnIconAvailableOnReceivedIconActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/PauseTimersActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/ResourceAndUIClientsActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/ShouldOverrideUrlLoadingActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkBlockAndErrorRedirection.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkNavigationActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkPreferencesActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkVersionAndAPIVersion.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithClearCache.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithDispatchKeyEvent.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithDownloadListenerActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithLayoutActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithLoadImage.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithRedirection.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithTransparent.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkWithInputConnection.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkWithSaveState.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/ZoomInAndOutXWalkViewActivity.java
-Change XWalkInitializer aysnchronization way due to its interface
-cover embeddingapi usecase & autocase two projects
Impacted tests(approved): new 0, update 29, delete 0
Unit test result summary: pass 29, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4527
> [Embeddingapi] Modify XWalkInitializer asynchronization interface

- embeddingapi/embedding-api-android-tests/embeddingapi/assets/pause_timers.html
- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkViewTest.java
-Modify testResumeTimers_function & testPauseTimers_function cases
https://crosswalk-project.org/jira/browse/XWALK-4444
> [Crosswalk14][Embeddingapi] Modify pause & resume time autocase

- embeddingapi/embedding-api-android-tests/README
- embeddingapi/embedding-api-android-tests/embeddingapi/build.gradle
- embeddingapi/embedding-api-android-tests/embeddingapi/pom.xml
- embeddingapi/embedding-asyncapi-android-tests/README
- embeddingapi/embedding-asyncapi-android-tests/embeddingapi/build.gradle
- embeddingapi/embedding-asyncapi-android-tests/embeddingapi/pom.xml
- tools/build/pack.py
- usecase/usecase-embedding-android-tests/README.md
- usecase/usecase-embedding-android-tests/embeddingapi-async/build.gradle
- usecase/usecase-embedding-android-tests/embeddingapi-async/pom.xml
- usecase/usecase-embedding-android-tests/embeddingapi/build.gradle
- usecase/usecase-embedding-android-tests/embeddingapi/pom.xml
- It's successful to build embeddingapi pkg using maven build and gradle build
https://crosswalk-project.org/jira/browse/XWALK-3784
> [embeddingapi] Improve maven build and gradle build for embeddingapi pack

- usecase/usecase-webapi-xwalk-tests/testscripts/DeviceCapabilities.feature
BUG=https://crosswalk-project.org/jira/browse/XWALK-4483
> [usecase-webapi] Increase timeout for DeviceCapabilities on Nexus4

- usecase/usecase-webapi-xwalk-tests/testscripts/DeviceCapabilities.feature
https://crosswalk-project.org/jira/browse/XWALK-4483
> [Crosswalk-14][usecase-webapi] Increase timeout for DeviceCapabilities on Nexus4

- stability/stability-manual-android-tests/manual/Download_File_LongTime.html
- stability/stability-manual-android-tests/suite.json
- stability/stability-manual-android-tests/tests.full.xml
- stability/stability-manual-android-tests/tests.xml
Fail to download zip file in web app, it's only support text and image.
> [stability] Add DownloadFileLongTime tests

- misc/sampleapp-android-tests/sampleapp/simd_icon.html
- misc/sampleapp-android-tests/sampleapp/simd_orientation.html
- misc/sampleapp-android-tests/sampleapp/simd_switch.html
- misc/sampleapp-android-tests/sampleapp/webgl_appFunction.html
- misc/sampleapp-android-tests/sampleapp/webgl_icon.html
- misc/sampleapp-android-tests/sampleapp/webgl_install.py
- misc/sampleapp-android-tests/sampleapp/webgl_launch.py
- misc/sampleapp-android-tests/sampleapp/webgl_orientation.html
- misc/sampleapp-android-tests/sampleapp/webgl_pack.py
- misc/sampleapp-android-tests/sampleapp/webgl_stop.py
- misc/sampleapp-android-tests/sampleapp/webgl_switch.html
- misc/sampleapp-android-tests/sampleapp/webgl_uninstall.py
- misc/sampleapp-android-tests/sampleapp/webgl_uninstall_withAppRunning.py
- misc/sampleapp-android-tests/sampleapp/webrtc_appFunction.html
- misc/sampleapp-android-tests/sampleapp/webrtc_pack.py
- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
- misc/sampleapp-android-tests/testscripts/simd_appFunction.feature
- Add 10 tests for WebGL
- Update tests for WebRTC and Simd
Impacted tests(approved):new 11,update 6,delete 3
Unit test result summary:pass 17,fail 0,block 0
> [sampleapp-android] Add tests to test webgl for sampleapp android

- webapi/tct-3dtransforms-css3-tests/tests.full.xml
- webapi/tct-3dtransforms-css3-tests/tests.xml
The id named by file name, so update.
> [webapi] Update the invalid id for 3dtransforms

- webapi/tct-sse-w3c-tests/sse-py/w3c/resources/reconnect-fail.py
- webapi/tct-sse-w3c-tests/sse-py/w3c/resources/status-reconnect.py
- webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest-py/w3c/resources/delay.py
Add Data Type, Length checking
> [webapi] Fix IAP security issue

- tools/build/README.md
- tools/build/pack_cordova_sample.py
- support to pack mobilespec apk without crosswalk
- support to update the tools/mobilespec_4.0 directory automatically
- It's successfull to build mobilespec 3.6 and mobilespec 4.0 package
BUG=https://crosswalk-project.org/jira/browse/XWALK-4553
> [cordova] Improve the mobilespec pack

- apptools/apptools-android-tests/apptools/backends.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
- apptools/apptools-ios-tests/apptools/backends.py
- apptools/apptools-ios-tests/tests.full.xml
- apptools/apptools-ios-tests/tests.xml
- apptools/apptools-linux-tests/apptools/backends.py
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
Impacted tests(approved):new 3,update 0,delete 0
Unit test result summary:pass 3,fail 0,block 0
https://crosswalk-project.org/jira/browse/XWALK-4565
> [apptools] Add tests to verify backends command for apptools

- tools/build/README.md
- tools/build/pack_cordova_sample.py
- support to pack mobilespec apk without crosswalk
- support to update the tools/mobilespec_4.0 directory automatically
- It's successfull to build mobilespec 3.6 and mobilespec 4.0 package
BUG=https://crosswalk-project.org/jira/browse/XWALK-4564
> [Crosswalk-14][cordova] Improve mobilespec build

- tools/build/pack_wts.sh
1. Add common and resources folders in package.
2. Add version.json file in package.
BUG=XWALK-4557
> [wts-pack] Update webTestService packaging script and rename to pack_wts.sh

- misc/sampleapp-android-tests/testscripts/environment.py
- misc/webapi-uiautomation-xwalk-tests/html5-extra-app/testscripts/environment.py
- misc/webapi-uiautomation-xwalk-tests/w3c-webstorage-app/testscripts/environment.py
- tools/atip/atip/web/web.py
- tools/atip/tests/environment.py
- usecase/usecase-webapi-xwalk-tests/testscripts/environment.py
- usecase/usecase-wrt-android-tests/testscripts/environment.py
- webapi/tct-backgrounds-css3-tests/css3-backgrounds-app/testscripts/environment.py
- webapi/tct-colors-css3-tests/css3-color-app/testscripts/environment.py
- webapi/tct-extra-html5-tests/html5-extra-app/testscripts/environment.py
- webapi/tct-fonts-css3-tests/css3-fonts-app/testscripts/environment.py
- webapi/tct-sandbox-html5-tests/html5-sandbox-app/testscripts/environment.py
- webapi/tct-svg-html5-tests/html5-svg-app/testscripts/environment.py
- webapi/tct-text-css3-tests/css3-text-app/testscripts/environment.py
- webapi/tct-webstorage-w3c-tests/w3c-webstorage-app/testscripts/environment.py
Add test url in webdriver env to redirect baseline path
BUG=WEBQA-248
> [ATIP] Fix improper path of baseline

- webapi/tct-notification-w3c-tests/tests.full.xml
- webapi/tct-notification-w3c-tests/tests.xml
Add tests for notification.permission
Unit test platform: Crosswalk for Android 15.44.374.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4505
> [webapi] Add tests for Web Notifications

- misc/webapi-noneservice-tests/pack.sh
- misc/webapi-service-tests/pack.sh
- webapi/tct-backgrounds-css3-tests/suite.json
- webapi/tct-colors-css3-tests/suite.json
- webapi/tct-extra-html5-tests/suite.json
- webapi/tct-fonts-css3-tests/suite.json
- webapi/tct-sandbox-html5-tests/suite.json
- webapi/tct-svg-html5-tests/suite.json
- webapi/tct-text-css3-tests/suite.json
- webapi/tct-webstorage-w3c-tests/suite.json
tct-backgrounds-css3-tests
Unit test result summary: pass 564, fail 46, block 0
tct-colors-css3-tests
Unit test result summary: pass 88, fail 25, block 0
tct-extra-html5-tests
Unit test result summary: pass 630, fail 9, block 0
tct-fonts-css3-tests
Unit test result summary: pass 129, fail 7, block 0
tct-sandbox-html5-tests
Impacted …
> [webapi] Add sub tests config for all-in-one package

- webapi/tct-csp-w3c-tests/csp-py/csp_ro_connect-src_asterisk.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_connect-src_cross-origin.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_connect-src_cross-origin_multi.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_connect-src_none.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_connect-src_self.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_media-src_corss-origin_audio_blocked_ext.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_media-src_corss-origin_audio_blocked_int.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_media-src_corss-origin_video_blocked_ext.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_media-src_corss-origin_video_blocked_int.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_media-src_none_audio_blocked_ext.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_media-src_none_audio_blocked_int.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_media-src_none_video_blocked_ext.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_media-src_none_video_blocked_int.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_style-src_asterisk.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_style-src_cross-origin.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_style-src_cross-origin_multi.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_style-src_none.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_style-src_self.py
- webapi/tct-csp-w3c-tests/csp-py/csp_ro_style-src_unsafe-inline.py
Impacted tests(approved): new 0, update 35, delete 0
Unit test platform: WTS
Unit test result summary: pass 17, fail 18, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4504
> [wts] Rewrite cgi to py for CSP

- misc/sampleapp-android-tests/testscripts/environment.py
- misc/webapi-uiautomation-xwalk-tests/html5-extra-app/testscripts/environment.py
- misc/webapi-uiautomation-xwalk-tests/w3c-webstorage-app/testscripts/environment.py
- tools/atip/atip/web/web.py
- tools/atip/tests/environment.py
- usecase/usecase-webapi-xwalk-tests/testscripts/environment.py
- usecase/usecase-wrt-android-tests/testscripts/environment.py
- webapi/tct-backgrounds-css3-tests/css3-backgrounds-app/testscripts/environment.py
- webapi/tct-colors-css3-tests/css3-color-app/testscripts/environment.py
- webapi/tct-extra-html5-tests/html5-extra-app/testscripts/environment.py
- webapi/tct-fonts-css3-tests/css3-fonts-app/testscripts/environment.py
- webapi/tct-sandbox-html5-tests/html5-sandbox-app/testscripts/environment.py
- webapi/tct-svg-html5-tests/html5-svg-app/testscripts/environment.py
- webapi/tct-text-css3-tests/css3-text-app/testscripts/environment.py
- webapi/tct-webstorage-w3c-tests/w3c-webstorage-app/testscripts/environment.py
Add test url in webdriver env to redirect baseline path
BUG=WEBQA-248
> [Crosswalk 14][ATIP] Fix improper path of baseline

- webapi/webapi-nacl-xwalk-tests/nacl/spec.json
- webapi/webapi-nacl-xwalk-tests/tests.full.xml
- webapi/webapi-nacl-xwalk-tests/tests.xml
- webapi/webapi-nfc-w3c-tests/nfc/spec.json
https://crosswalk-project.org/jira/browse/XWALK-4536
> [webapi] Fix spec category issue of NFC and NaCL suites

- webapi/tct-webstorage-w3c-tests/webstorage/w3c/storage_local_setitem_quotaexceedederr.html
- webapi/tct-webstorage-w3c-tests/webstorage/w3c/storage_session_setitem_quotaexceedederr.html
Unit test Platform: Crosswalk Project for Android 15.44.361.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-3807
> [webapi][Crosswalk-14] Update tests for WebStorage

- doc/Web_Test_Suite_Developer_Guide.md
- webapi/tct-audio-html5-tests/README
- webapi/tct-audio-html5-tests/audio/spec.json
- webapi/tct-browserstate-html5-tests/README
- webapi/tct-browserstate-html5-tests/browserstate/spec.json
- webapi/tct-fileapi-w3c-tests/README
- webapi/tct-fileapi-w3c-tests/fileapi/spec.json
- webapi/tct-filesystemapi-w3c-tests/README
- webapi/tct-filesystemapi-w3c-tests/filesystemapi/spec.json
- webapi/tct-filewriterapi-w3c-tests/README
- webapi/tct-filewriterapi-w3c-tests/filewriterapi/spec.json
- webapi/tct-geoallow-w3c-tests/README
- webapi/tct-geoallow-w3c-tests/geoallow/spec.json
- webapi/tct-geodeny-w3c-tests/README
- webapi/tct-geodeny-w3c-tests/geodeny/spec.json
- webapi/tct-gumallow-w3c-tests/README
- webapi/tct-gumallow-w3c-tests/gumallow/spec.json
- webapi/tct-sandbox-html5-tests/README
- webapi/tct-sandbox-html5-tests/sandbox/spec.json
- webapi/tct-sessionhistory-html5-tests/README
- webapi/tct-sessionhistory-html5-tests/sessionhistory-py/spec.json
- webapi/tct-sessionhistory-html5-tests/sessionhistory/spec.json
- webapi/tct-touchevent-w3c-tests/README
- webapi/tct-touchevent-w3c-tests/touchevent/spec.json
- webapi/tct-video-html5-tests/README
- webapi/tct-video-html5-tests/video/spec.json
- webapi/webapi-input-html5-tests/README
- webapi/webapi-input-html5-tests/input/spec.json
Web Testing Service uses the description to show specifications.
> [webapi] Unify specification description

- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
- apptools/apptools-ios-tests/tests.full.xml
- apptools/apptools-ios-tests/tests.xml
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
Impacted tests(approved): new 24, update 0, delete 0
Unit test result summary: pass 24, fail 0, block 0
> [apptools] Add nodeunit tests for apptools

- apptools/apptools-android-tests/apptools/target_platforms.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
- apptools/apptools-ios-tests/apptools/target_platforms.py
- apptools/apptools-ios-tests/tests.full.xml
- apptools/apptools-ios-tests/tests.xml
- apptools/apptools-linux-tests/apptools/target_platforms.py
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4565
> [apptools] Rename 'backends' command to 'platforms' for apptools

- usecase/usecase-wrt-android-tests/samples/ThemeColor/README.md
- usecase/usecase-wrt-android-tests/samples/ThemeColor/index.html
- usecase/usecase-wrt-android-tests/steps/ThemeColor/step.js
- usecase/usecase-wrt-android-tests/tests.android.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
https://crosswalk-project.org/jira/browse/XWALK-4305
> [usecase] Add test for theme-color

- misc/sampleapp-android-tests/testscripts/steps/steps.py
- tools/atip/README.md
- tools/atip/atip/common/steps.py
- tools/atip/atip/web/steps.py
- tools/atip/atip/web/web.py
- tools/atip/tests/environment.py
To make the instance name more unified
BUG=https://crosswalk-project.org/jira/browse/XWALK-4631
> [ATIP] Rename context.app as context.web

- tools/build/pack_wts.sh
Update pack_wts.sh to add usecase test suite and enhance script.
Add -a option to specify the commit ID (default is the latest commit ID)
Move the error message to /tmp directory.
> [WTS-pack] Update pack_wts.sh to add usecase test

- stability/stability-lowresource-android-tests/README
- stability/stability-lowresource-android-tests/tests.full.xml
- stability/stability-lowresource-android-tests/tests.xml
> [stability] Update Low Memory tests to approved

- tools/atip/atip/common/steps.py
- tools/atip/atip/web/steps.py
- tools/atip/atip/web/web.py
- tools/atip/tests/environment.py
And rename context dict from context.webs to context.apps to
compatible with uiautomator
BUG=https://crosswalk-project.org/jira/browse/XWALK-4650
> [ATIP] Move webdriver specfic steps from common to web

- misc/sampleapp-windows-tests/tests.full.xml
- misc/sampleapp-windows-tests/tests.xml
Impacted tests(designed): new 0, update 1, delete 0
Unit test platform: Crosswalk Project for Android 14.43.343.0
> [windows] Unify the  Ttpod_Launch case name in tests.xml and tests.full.xml

- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Negative_NullValueVersion.html
- wrt/wrt-rtcoremanu-android-tests/tests.full.xml
- wrt/wrt-rtcoremanu-android-tests/tests.xml
Android test result summary: Pass 0, Fail 0, Block 0
> [wrt] Update tests for rtcoremanu

- apptools/apptools-android-tests/apptools/comm.py
- apptools/apptools-android-tests/apptools/versionCode.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
Impacted tests(approved): new 5, update 40, delete 0
Unit test result summary: pass 40, fail 5, block 0
https://crosswalk-project.org/jira/browse/XWALK-3830
> [apptools-android] Add tests to test implement verion code adjustmentfor ABI on apptools android

- usecase/usecase-webapi-xwalk-tests/testscripts/Forms.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/Sandbox.feature
Unit test platform: Crosswalk Project for Android 15.44.365.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4445
> [usecase] Add more waiting time for feature steps

- apptools/apptools-android-tests/apptools/create_with_target_platform.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
- apptools/apptools-ios-tests/apptools/create_with_target_platform.py
- apptools/apptools-ios-tests/tests.full.xml
- apptools/apptools-ios-tests/tests.xml
- apptools/apptools-linux-tests/apptools/create_with_target_platform.py
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4662
https://crosswalk-project.org/jira/browse/XWALK-4661
Impacted tests(approved):new 15,update 0,delete 0
Unit test result summary:pass 13,fail 2,block 0
https://crosswalk-project.org/jira/browse/XWALK-4622
> [apptools] Add tests for creating project with target platform on apptools

- tools/atip/atip/web/steps.py
- tools/atip/atip/web/web.py
BUG=https://crosswalk-project.org/jira/browse/XWALK-4640
> [ATIP] Add new step in ATIP

- webapi/webapi-download-android-tests/tests.full.xml
- Update test status from designed to approved
- Add test entery in tests.full.xml for tests which has existted in tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4508
> [webapi] Update xml for webapi-download-android-tests

- webapi/tct-backgrounds-css3-tests/css3-backgrounds-app/bdd.config.xml
- webapi/tct-colors-css3-tests/css3-color-app/bdd.config.xml
- webapi/tct-extra-html5-tests/html5-extra-app/bdd.config.xml
- webapi/tct-fonts-css3-tests/css3-fonts-app/bdd.config.xml
- webapi/tct-sandbox-html5-tests/html5-sandbox-app/bdd.config.xml
- webapi/tct-svg-html5-tests/html5-svg-app/bdd.config.xml
- webapi/tct-text-css3-tests/css3-text-app/bdd.config.xml
- webapi/tct-webstorage-w3c-tests/w3c-webstorage-app/bdd.config.xml
Due to Tizen platform has been removed, so remove the related config file for bdd tests.
> [webapi] Remove bdd.config.xml for bdd tests

- webapi/tct-extra-html5-tests/html5-extra-app/testscripts/area_noref.feature
Unit test platform: Crosswalk Project for Android 15.44.376.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4442
> [webapi] Add more waiting time for bdd steps in HTML5 Extra

- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Negative_NullValueVersion.html
- wrt/wrt-rtcoremanu-android-tests/tests.full.xml
- wrt/wrt-rtcoremanu-android-tests/tests.xml
> [Crosswalk-14][wrt] Update test for rtcoremanu

- misc/sampleapp-android-tests/README
- misc/sampleapp-android-tests/sampleapp/comm.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_appFunction.html
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_install.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_launch.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_orientation.html
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_pack.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_stop.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_uninstall.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_uninstall_withAppRunning.py
- misc/sampleapp-android-tests/sampleapp/hexgl_presentation_function.html
- misc/sampleapp-android-tests/tests.full.xml
- misc/sampleapp-android-tests/tests.xml
- Add function test for extensionsandroid
- Update tests for extensionsandroid
- Add presentation api test for hexgl
- The fail BugID: XWALK-4620/XWALK-4598
Impacted TCs num(approved): New 2, Update 8, Delete 0
Android test result summary: Pass 0, Fail 10, Block 0
> [misc] Update tests for extensionandroid

- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Negative_NullValueVersion.html
- wrt/wrt-rtcoremanu-android-tests/tests.full.xml
- wrt/wrt-rtcoremanu-android-tests/tests.xml
> [Crosswalk-12][wrt] Update test for rtcore

- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Negative_NullValueVersion.html
> [wrt] Update test description for rtcoremanu

- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Negative_NullValueVersion.html
> [Crosswalk-14][wrt] Update test desciption for rtcoremanu

- wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Negative_NullValueVersion.html
- wrt/wrt-rtcoremanu-android-tests/tests.full.xml
- wrt/wrt-rtcoremanu-android-tests/tests.xml
> [Crosswalk-13][wrt] Update test for rtcoremanu

- cordova/cordova-api-ios-tests/cordovaapi/mobilespec_test.py
- cordova/cordova-api-ios-tests/tests.xml
- embeddingapi/embedding-api-ios-tests/embeddingapi/xwalkview.py
- embeddingapi/embedding-api-ios-tests/tests.full.xml
- embeddingapi/embedding-api-ios-tests/tests.xml
- tools/build/setup_ios.py
- The test suite can run normally
Impacted TCs num(approved): New 0, Update 30, Delete 0
Unit test Platform: iOS
iOS test result summary: Pass 30, Fail 0, Block 0
> [ios] Update test scripts for all auto ios tests

- tools/format/json_formatter
@zqzhang , could you help to check? thanks
> Support json minimize in formater tool.

- tools/atip/atip/web/web.py
- usecase/usecase-webapi-xwalk-tests/samples/WebCrypto/index.html
- usecase/usecase-webapi-xwalk-tests/tests.android.xml
- usecase/usecase-webapi-xwalk-tests/tests.auto.xml
- usecase/usecase-webapi-xwalk-tests/tests.full.xml
- usecase/usecase-webapi-xwalk-tests/tests.wts.xml
- usecase/usecase-webapi-xwalk-tests/testscripts/Geolocation.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/HrtimeAndroid.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/WebCL.feature
- usecase/usecase-webapi-xwalk-tests/testscripts/WebCrypto.feature
Unit test Platform: Crosswalk Project for Android 15.44.374
> [usecase] Automation 4 tests for usecase

- webapi/webapi-webrtc-w3c-tests/tests.full.xml
- webapi/webapi-webrtc-w3c-tests/tests.xml
Impacted tests(approved): new 2, update 11, delete 0
Unit test platform: Crosswalk Project for Android 15.44.376.0
Unit test result summary: pass 13, fail 0, block 0
> [webapi] Add unreferenced tests to tests.xml for WebRTC

- webapi/tct-notification-w3c-tests/notification/w3c/COPYING
- webapi/tct-notification-w3c-tests/notification/w3c/body-basic-manual.html
- webapi/tct-notification-w3c-tests/notification/w3c/body-empty-manual.html
- webapi/tct-notification-w3c-tests/notification/w3c/common.js
- webapi/tct-notification-w3c-tests/notification/w3c/constructor-basic.html
- webapi/tct-notification-w3c-tests/notification/w3c/constructor-invalid.html
- webapi/tct-notification-w3c-tests/notification/w3c/event-onclick-manual.html
- webapi/tct-notification-w3c-tests/notification/w3c/event-onclose.html
- webapi/tct-notification-w3c-tests/notification/w3c/event-onshow.html
- webapi/tct-notification-w3c-tests/notification/w3c/icon-basic-manual.html
- webapi/tct-notification-w3c-tests/notification/w3c/icon-empty-manual.html
- webapi/tct-notification-w3c-tests/notification/w3c/instance.html
- webapi/tct-notification-w3c-tests/notification/w3c/lang.html
- webapi/tct-notification-w3c-tests/notification/w3c/permission.html
- webapi/tct-notification-w3c-tests/notification/w3c/requestPermission-granted-manual.html
- webapi/tct-notification-w3c-tests/notification/w3c/tag-different-manual.html
- webapi/tct-notification-w3c-tests/notification/w3c/tag-same-manual.html
- webapi/tct-notification-w3c-tests/tests.full.xml
- webapi/tct-notification-w3c-tests/tests.xml
Impacted TCs num(approved): New 64, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 15.44.374.0
Unit test result summary: Pass 62, Fail 22, Blocked 0
> [webapi] Integrate w3c tests for notification

- webapi/tct-forms-html5-tests/tests.full.xml
- webapi/tct-forms-html5-tests/tests.xml
- webapi/tct-indexeddb-w3c-tests/tests.full.xml
- webapi/tct-indexeddb-w3c-tests/tests.xml
- webapi/webapi-webcl-nonw3c-tests/tests.full.xml
- webapi/webapi-webcl-nonw3c-tests/tests.xml
- webapi/webapi-webrtc-w3c-tests/tests.full.xml
- webapi/webapi-webrtc-w3c-tests/tests.xml
Unit test platform: Crosswalk for Android 15.43.354
Unit result summary: pass 2, fail 0, block 0
> [webapi] Update test entry for Forms, IndexedDB, WebCL and WebRTC

- tools/atip/README.md
BUG=https://crosswalk-project.org/jira/browse/XWALK-4682
> [ATIP] Update README.md

- apptools/apptools-android-tests/apptools/Check_VersionName.html
- apptools/apptools-android-tests/apptools/versionName.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4627
> [apptools-android] Add tests to test versionName from manifest version code

- usecase/usecase-cordova-android-tests/samples/Language3.6/REAMDE.md
- usecase/usecase-cordova-android-tests/samples/Language3.6/index.html
- usecase/usecase-cordova-android-tests/samples/Language3.6/res/test.py
- usecase/usecase-cordova-android-tests/samples/Language4.0/README.md
- usecase/usecase-cordova-android-tests/samples/Language4.0/index.html
- usecase/usecase-cordova-android-tests/samples/Language4.0/res/test.py
- usecase/usecase-cordova-android-tests/steps/Language/step.js
- usecase/usecase-cordova-android-tests/suite.json
- usecase/usecase-cordova-android-tests/tests.full.xml
- usecase/usecase-cordova-android-tests/tests.xml
Fail analyse: XWALK-4679
Unit test platform: Crosswalk Project for Android 14.43.343.18
BUG=https://crosswalk-project.org/jira/browse/XWALK-4500
> [usecase-cordova]Add case for window.navigator.language

- wrt/wrt-packertoolmanu-android-tests/suite.json
BUG=https://crosswalk-project.org/jira/browse/XWALK-4671
> [wrt] Update suite.json for packertoolmanu

- misc/sampleapp-android-tests/testscripts/simd_appFunction.feature
Unit test Platform: Crosswalk for Android 14.13.343.20
BUG=https://crosswalk-project.org/jira/browse/XWALK-4685
> [webapi][Crosswalk-14] Update SIMD feature for sampleapp

- misc/sampleapp-ios-tests/sampleapp/Presentation_Function.html
Unit test Platform: iOS
iOS test result summary: Pass 1, Fail 0, Block 0
> [misc-ios] Update test description for hexgl

- misc/sampleapp-android-tests/sampleapp/comm.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_install.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_launch.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_pack.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_stop.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_uninstall.py
- misc/sampleapp-android-tests/sampleapp/extensionsandroid_uninstall_withAppRunning.py
Android test result summary: Pass 6, Fail 0, Block 0
> [misc] Update tests script for extensions_android

- tools/atip/atip/android/android.py
- tools/atip/atip/android/steps.py
- tools/atip/atip/common/common.py
- tools/atip/atip/common/steps.py
- tools/atip/atip/web/steps.py
- tools/atip/atip/web/web.py
- tools/atip/setup.py
- tools/atip/tests/environment.py
- tools/atip/tests/steps/steps.py
- Add uiautomator libraries and steps
- Initial uiautomator class
BUG=https://crosswalk-project.org/jira/browse/XWALK-4652
> [ATIP] Initial uiautomator as backend in ATIP

- apptools/apptools-android-tests/apptools/Keeping_Screen_On.html
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4033
> [apptools-android] Add tests to test keeping_screen_on for apptools android

- apptools/apptools-android-tests/apptools/Check_Fullscreen.html
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4680
> [apptools-android] Add tests to test fullscreen apps for apptools android

- tools/atip/atip/android/android.py
- tools/atip/atip/android/steps.py
- tools/atip/atip/common/steps.py
- Add atip android system wifi operation steps
BUG=https://crosswalk-project.org/jira/browse/XWALK-4727
> [atip-android] Add atip android system wifi operation steps

- tools/atip/atip/android/android.py
- tools/atip/atip/common/steps.py
-Modify atip android system wifi operation steps
https://crosswalk-project.org/jira/browse/XWALK-4727
> [atip-android] Modify atip android system wifi operation steps

- webapi/tct-canvas-html5-tests/tests.xml
Unit test platform: Crosswalk for Android 15.43.354
Unit result summary: pass 1, fail 0, block 0
> [webapi] Fix test entery issue for Canvas

- tools/atip/README.md
- tools/atip/atip/android/android.py
- tools/atip/atip/common/steps.py
-Add two steps for enable/disable airplane mode
-Modify README.md
BUG=https://crosswalk-project.org/jira/browse/XWALK-4728
> [atip-android] Add two steps for enable/disable airplane mode

- apptools/apptools-android-tests/apptools/Remote_Debugging.html
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4027
> [apptools-android] Add tests to test remote debugging for apptools android

- misc/sampleapp-android-tests/README
- The test suite can run normally with testkit-lite follow the README comment
> [misc] Update file README for sampleapp

- tools/atip/tests/environment.android.py
-Modify atip entry env variables acquire
-increase program compatibility
> [ATIP] Modify atip entry env variables acquire

- apptools/apptools-android-tests/apptools/build_path.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
- apptools/apptools-ios-tests/apptools/build_path.py
- apptools/apptools-ios-tests/tests.full.xml
- apptools/apptools-ios-tests/tests.xml
- apptools/apptools-linux-tests/apptools/build_path.py
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4700
> [apptools] Add tests to test build project with webapp path for apptools

- tools/build/pack_cordova_sample.py
- usecase/usecase-cordova-android-tests/samples/RenamePkg/REAMDE.md
- usecase/usecase-cordova-android-tests/samples/RenamePkg/index.html
- usecase/usecase-cordova-android-tests/steps/RenamePkg/step.js
- usecase/usecase-cordova-android-tests/tests.full.xml
- usecase/usecase-cordova-android-tests/tests.xml
Unit test platform: Crosswalk Project for Android 15.44.382.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4184
> [usecase-cordova] Add case for rename pkg

- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.auto.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- usecase/usecase-wrt-android-tests/testscripts/ChromeProtocol.feature
- usecase/usecase-wrt-android-tests/testscripts/steps/steps.py
> [usecase-wrt] Improve manual test to auto using webdriver

- tools/build/README.md
- tools/build/pack_cordova_sample.py
Unit test platform: Crosswalk Project for Android 15.44.382.0
https://crosswalk-project.org/jira/browse/XWALK-4184
> [usecase-cordova] Improve renamePkg case

- tools/atip/atip/web/steps.py
- tools/atip/atip/web/web.py
Unit test Platform: Crosswalk Project for Android 15.44.374
BUG=https://crosswalk-project.org/jira/browse/XWALK-4757
> [atip] Add new step for atip

- apptools/apptools-android-tests/apptools/package_id.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
- apptools/apptools-ios-tests/apptools/package_id.py
- apptools/apptools-ios-tests/tests.full.xml
- apptools/apptools-ios-tests/tests.xml
- apptools/apptools-linux-tests/apptools/package_id.py
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4707
https://crosswalk-project.org/jira/browse/XWALK-4772
https://crosswalk-project.org/jira/browse/XWALK-4785
Impacted tests(approved): new 6, update 0, delete 0
Unit test result summary: pass 3, fail 3, block 0
https://crosswalk-project.org/jira/browse/XWALK-4710
> [apptools] Add tests to test package ID for apptools

- wrt/wrt-securitymanu-android-tests/inst.apk.py
- Update the inst.apk.py for that can install all apk in this folder
> [wrt] Update the inst script for securitymanu

- tools/atip/README.md
- tools/atip/atip/android/android.py
- tools/atip/atip/android/steps.py
- tools/atip/atip/web/web.py
-Reconstruct aitp android uiautomator model core
BUG=https://crosswalk-project.org/jira/browse/XWALK-4781
> [ATIP] Reconstruct aitp android uiautomator model core

- apptools/apptools-android-tests/apptools/apk_name.py
- apptools/apptools-android-tests/apptools/comm.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4630
> [apptools-android] Add tests to test apk name contains versionCode for apptools android

- webapi/tct-3dtransforms-css3-tests/tests.full.xml
- webapi/tct-3dtransforms-css3-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-4592
> [webapi] Update css-transforms-3d-on-anonymous-block-001-manual.html to reference test

- usecase/usecase-wrt-android-tests/tests.auto.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- usecase/usecase-wrt-android-tests/testscripts/WebAppTaskManager.feature
> [usecase-wrt] Improve manual test to auto for WebAppTaskManager

- usecase/usecase-wrt-android-tests/testscripts/ChromeProtocol.feature
> [usecase-wrt] Update bdd tests to sync with lastest atip steps for ChromeProtocol

- apptools/apptools-android-tests/apptools/update_path.py
- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4713
> [apptools-android] Add tests to test update project with webapp path for apptools android

- tools/atip/README.md
- tools/atip/atip/common/steps.py
-Add atip android execute command step
-Verified locally
> [atip-android] Add atip android execute command step

- misc/webapi-service-docroot-tests/webrunner/testrunner.js
- tools/resources/webrunner/testrunner.js
https://github.com/testkit/webrunner/commit/5ae225043ee9ed0b3e7be908a3ebf3a1494e4ba6
> [tools] Sync web runner to latest to support W3C sub-tests

- webapi/tct-fileapi-w3c-tests/tests.full.xml
- webapi/tct-fileapi-w3c-tests/tests.xml
Impacted tests(approved): new 209, update 0, delete 0
Unit result summary: pass 304, fail 27, block 0
> [webapi] Update xml to support subcase mode for FileAPI

- webapi/tct-forms-html5-tests/tests.full.xml
- webapi/tct-forms-html5-tests/tests.xml
Impacted tests(approved): new 239, update 0, delete 0
Unit result summary: pass 358, fail 28, block 0
> [webapi] Update xml to support subcase mode for Forms

- webapi/tct-indexeddb-w3c-tests/tests.full.xml
- webapi/tct-indexeddb-w3c-tests/tests.xml
Impacted tests(approved): new 18, update 0, delete 0
Unit result summary: pass 402, fail 1, block 0
> [webapi] Update xml to support subcase mode for IndexdDB

- webapi/webapi-input-html5-tests/tests.full.xml
- webapi/webapi-input-html5-tests/tests.xml
Unit result summary: pass 32, fail 1, block 0
> [webapi] Update xml to support subcase mode for Input

- webapi/tct-pagevisibility-w3c-tests/tests.full.xml
- webapi/tct-pagevisibility-w3c-tests/tests.xml
Impacted tests(approved): new 11, update 0, delete 0
Unit result summary: pass 31, fail 0, block 0
> [webapi] Update xml to support subcase mode for Pagevisibility

- webapi/tct-selectorslevel2-w3c-tests/tests.full.xml
- webapi/tct-selectorslevel2-w3c-tests/tests.xml
Impacted tests(approved): new 2526, update 0, delete 0
Unit result summary: pass 1737, fail 874, block 0
> [webapi] Update xml to support subcase mode for Selectors Level2

- webapi/tct-sessionhistory-html5-tests/tests.full.xml
- webapi/tct-sessionhistory-html5-tests/tests.xml
Impacted tests(approved): new 26, update 0, delete 0
Unit result summary: pass 175, fail 5, block 0
> [webapi] Update xml to support subcase mode for Session History

- webapi/tct-typedarrays-nonw3c-tests/tests.full.xml
- webapi/tct-typedarrays-nonw3c-tests/tests.xml
Impacted tests(approved): new 158, update 0, delete 0
Unit result summary: pass 546, fail 58, block 0
> [webapi] Update xml to support subcase mode for Typedarrays

- webapi/tct-video-html5-tests/tests.full.xml
- webapi/tct-video-html5-tests/tests.xml
Impacted tests(approved): new 45, update 0, delete 0
Unit result summary: pass 333, fail 73, block 25
> [webapi] Update xml to support subcase mode for Video

- webapi/tct-webstorage-w3c-tests/tests.full.xml
- webapi/tct-webstorage-w3c-tests/tests.xml
Unit result summary: pass 141, fail 4, block 2
> Update xml to support subcase mode for Web Storage

- webapi/tct-workers-w3c-tests/tests.full.xml
- webapi/tct-workers-w3c-tests/tests.xml
Impacted tests(approved): new 9, update 0, delete 0
Unit result summary: pass 57, fail 3, block 35
> [webapi] Update xml to support subcase mode for Workers

- webapi/tct-navigationtiming-w3c-tests/tests.full.xml
- webapi/tct-navigationtiming-w3c-tests/tests.xml
Impacted tests(approved): new 190, update 0, delete 0
Unit result summary: pass 226, fail 0, block 9
> [webapi] Update xml to support subcase mode for Navigation Timing

- webapi/tct-sse-w3c-tests/tests.full.xml
- webapi/tct-sse-w3c-tests/tests.xml
Unit result summary: pass 66, fail 11, block 2
> [webapi] Update xml to support subcase mode for sse

- webapi/tct-webmessaging-w3c-tests/tests.full.xml
- webapi/tct-webmessaging-w3c-tests/tests.xml
Impacted tests(approved): new 6, update 0, delete 0
Unit test platform: Crosswalk for Android 15.44.384.0
Unit result summary: pass 114, fail 6, block 0
> [webapi] Update xml to support subcase mode for Web Messaging

- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
- embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/CookieManagerTest.java
- embeddingapi/embedding-api-android-tests/tests.full.xml
- embeddingapi/embedding-api-android-tests/tests_v5.xml
- embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
- embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/CookieManagerTest.java
- embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
- embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml
-Add autocase for XWalkCookieManager apis
https://crosswalk-project.org/jira/browse/XWALK-3528
> [Embeddingapi] Add autocase for XWalkCookieManager apis

- usecase/usecase-embedding-android-tests/suite.json
- usecase/usecase-embedding-android-tests/tests.android.xml
- usecase/usecase-embedding-android-tests/testscripts/PauseJsTimers.feature
- usecase/usecase-embedding-android-tests/testscripts/PauseJsTimers_async.feature
- usecase/usecase-embedding-android-tests/testscripts/steps/steps.py
-Modify usecase project xml to implement atip uiautomator
BUG=https://crosswalk-project.org/jira/browse/XWALK-4759
> [Embeddingapi] Modify usecase project xml to implement atip uiautomator

- webapi/tct-webgl-nonw3c-tests/suite.json
This is the test result on Nexus3.
Unit test result summary: Pass 1569, Fail 23, Blocked 3
BUG=https://crosswalk-project.org/jira/browse/XWALK-4672
> [webapi] Update suite.json for webgl

- tools/atip/README.md
- tools/atip/atip/android/android.py
- tools/atip/atip/android/steps.py
- tools/atip/atip/common/steps.py
- Modify wait object show steps
> [ATIP-android] Modify wait object show steps

- doc/Web_Test_Suite_Developer_Guide.md
BUG=https://crosswalk-project.org/jira/browse/XWALK-4782
> [doc] Remove "partial" support on Web_Test_Suite_Developer_Guide.md

- tools/atip/README.md
Add specific environment.py for uiautomator only tests to eliminate dependency from WebDriver
> [ATIP] Update environment.py support in README.md

- wrt/wrt-uxmanu-android-tests/tests.full.xml
- wrt/wrt-uxmanu-android-tests/tests.xml
- wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature
> [wrt] Improve manual test to auto test using atip for uxmanu

- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
> [apptools-android] Add nodeunit cases for apptools android

- tools/xml/csv2xml.py
- tools/xml/xml2csv.py
- Add subcase support
- Rewrite csv2xml.py by object-oriented programming
> [tools] Add subcase support for csv2xml and xml2csv 

- apptools/apptools-sampleapp-tests/README
- apptools/apptools-sampleapp-tests/sampleapp-android/Crosswalk_Apptools_SampleApp_Gallery_Build_Arm.html
- apptools/apptools-sampleapp-tests/sampleapp-android/Crosswalk_Apptools_SampleApp_Gallery_Build_X86.html
- apptools/apptools-sampleapp-tests/tests.android.xml
- apptools/apptools-sampleapp-tests/tests.full.xml
- usecase/usecase-apptools-tests/README
- usecase/usecase-apptools-tests/samples-android/AppTools_arm/index.html
- usecase/usecase-apptools-tests/samples-android/AppTools_install_crosswalk_app_arm/index.html
- usecase/usecase-apptools-tests/samples-android/AppTools_install_crosswalk_app_x86/index.html
- usecase/usecase-apptools-tests/samples-android/AppTools_x86/index.html
- usecase/usecase-apptools-tests/tests.android.xml
- usecase/usecase-apptools-tests/tests.full.xml
> [apptools] Update test steps for apptools on windows

- usecase/usecase-apptools-tests/samples-ios/AppTools_install_using_npm/index.html
- usecase/usecase-apptools-tests/tests.full.xml
- usecase/usecase-apptools-tests/tests.ios.xml
https://crosswalk-project.org/jira/browse/XWALK-4808
https://crosswalk-project.org/jira/browse/XWALK-4497
> [usecase-apptools] Add tests to test install Crosswalk for iOS app-tools backend using npm

- usecase/usecase-wrt-android-tests/suite.json
- usecase/usecase-wrt-android-tests/tests.auto.xml
- usecase/usecase-wrt-android-tests/tests.full.xml
- usecase/usecase-wrt-android-tests/testscripts/ApplicationlocalStorage.feature
> [usecase] Improve manual tests to auto using ATIP

- usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
- usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/cookiemanager_layout.xml
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/CookieManagerTestActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
- usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
- usecase/usecase-embedding-android-tests/embeddingapi/res/layout/cookiemanager_layout.xml
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/CookieManagerTestActivity.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
- usecase/usecase-embedding-android-tests/tests.android.xml
- usecase/usecase-embedding-android-tests/tests.full.xml
-Add autocase for XWalkCookieManager apis
https://crosswalk-project.org/jira/browse/XWALK-3528
> [Embeddingapi] Add usecase for XWalkCookieManager apis

- wrt/wrt-manifest-android-tests/gen_apks.py
- wrt/wrt-packertool-android-tests/gen_apks.py
Modified gen_apk.py in wrt-packertool-android-tests and wrt-manifest-android-tests
BUG=XWALK-4750
> [build-script] Update gen_apks.py to enhance multi-process building.

- tools/atip/atip/android/android.py
- tools/atip/atip/android/steps.py
-Add atip android uiautomator steps comments
-verified locally
> [ATIP-android] Add atip android uiautomator steps comments

- misc/webapi-noneservice-tests/pack.sh
- misc/webapi-service-tests/pack.sh
- update all in one script  for cordova 4.x support
- update all in one script  for crosswalk version config of cordova 4.x
- update all in one script  for shared mode support of cordova 4.x
- build all in one pkgs successfully
> [cordova] update all in one script for cordova 4.x

- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithDispatchDrawAsync.java
Unit test platform: Crosswalk Project for Android 16.44.391.0
> [usecase-embedding]Update the tip for async usecase of dispatchDraw

- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithDispatchDrawAsync.java
Unit test platform: Crosswalk Project for Android 16.44.391.0
> [crosswalk-15][usecase-embedding]Update the tip for async usecase of dispatchDraw

- usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
- usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
- usecase/usecase-embedding-android-tests/tests.android.xml
- usecase/usecase-embedding-android-tests/tests.full.xml
-Modify embedding usecase xml id name
> [Embeddingapi] Modify embedding usecase xml id name

- cordova/cordova-feature-android-tests/feature/comm.py
- cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
- cordova/cordova-webapp-android-tests/webapp/comm.py
- misc/webapi-noneservice-tests/pack.sh
- misc/webapi-service-tests/pack.sh
- tools/build/pack.py
- tools/build/pack_cordova_sample.py
- usecase/usecase-cordova-android-tests/samples/CordovaPackage4.x/res/test.py
- usecase/usecase-cordova-android-tests/samples/SharedModeLibraryDownload4.x/res/test.py
- usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/REAMDE.md
- pack cordova 4.x pkg successfully
BUG=https://crosswalk-project.org/jira/browse/XWALK-4853
> [cordova] Update the cordova-plugin-crosswalk-webview install  command

- cordova/cordova-feature-android-tests/feature/comm.py
- cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
- cordova/cordova-webapp-android-tests/webapp/comm.py
- misc/webapi-noneservice-tests/pack.sh
- misc/webapi-service-tests/pack.sh
- tools/build/pack.py
- tools/build/pack_cordova_sample.py
- usecase/usecase-cordova-android-tests/samples/CordovaPackage4.x/res/test.py
- usecase/usecase-cordova-android-tests/samples/SharedModeLibraryDownload4.x/res/test.py
- usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/REAMDE.md
- pack cordova 4.x pkg successfully
BUG=https://crosswalk-project.org/jira/browse/XWALK-4853
> [Cordova][Crosswalk-15] Update the cordova-plugin-crosswalk-webview install command

- webapi/tct-flexiblebox-css3-tests/tests.full.xml
- webapi/tct-flexiblebox-css3-tests/tests.xml
- webapi/tct-fonts-css3-tests/tests.full.xml
- webapi/tct-fonts-css3-tests/tests.xml
- webapi/tct-mediacapture-w3c-tests/tests.full.xml
- webapi/tct-mediacapture-w3c-tests/tests.xml
- webapi/tct-text-css3-tests/tests.full.xml
- webapi/tct-text-css3-tests/tests.xml
- [webapi] Add subcase support in Flexiblebox,Fonts,Mediacapture,Text
- Format tests.full.xml by: xmllint --format tests.full.xml > tests.full.new.xml
Impacted tests(approved): new 0, update 24, delete 0
Unit test platform: Crosswalk for Android 16.44.392.0
Unit result summary: pass 24, fail 0, block 0
> [webapi] Add subcase support in Flexiblebox,Fonts,Mediacapture,Text

- webapi/tct-extra-html5-tests/xhtml5/w3c/test-body.xhtml
Unit test Platform: Crosswalk Project for Android 16.44.389.0
https://crosswalk-project.org/jira/browse/XWALK-4840
> [webapi] Fix link file lost for body_link-manual.xhtml

- apptools/apptools-android-tests/tests.full.xml
- apptools/apptools-android-tests/tests.xml
- apptools/apptools-ios-tests/tests.full.xml
- apptools/apptools-ios-tests/tests.xml
- apptools/apptools-linux-tests/tests.full.xml
- apptools/apptools-linux-tests/tests.xml
Due to windows tests only work on windows, so delete them
Impacted tests(approved): new 6, update 0, delete 2
> [apptools] Add nodeunit cases for apptools

- webapi/tct-extra-html5-tests/xhtml5/w3c/test-body.xhtml
https://crosswalk-project.org/jira/browse/XWALK-4840
> [Crosswalk-15][webapi] Fix link file lost for body_link-manual.xhtml

- cordova/cordova-sampleapp-android-tests/tests.3.6.xml
- cordova/cordova-sampleapp-android-tests/tests.4.x.xml
- cordova/cordova-sampleapp-android-tests/tests.full.xml
- cordova/cordova-webapp-android-tests/tests.full.xml
- cordova/cordova-webapp-android-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-4887
> [cordova] Update component name and category

- cordova/cordova-sampleapp-android-tests/tests.3.6.xml
- cordova/cordova-sampleapp-android-tests/tests.4.x.xml
- cordova/cordova-sampleapp-android-tests/tests.full.xml
- cordova/cordova-webapp-android-tests/tests.full.xml
- cordova/cordova-webapp-android-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-4887
> [cordova][Crosswalk-15] Update component name and category

- usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
- usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_on_touch_event_async.xml
- usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/MyXWalkView.java
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
- usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithOnTouchEventAsync.java
- usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
- usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_on_touch_event.xml
- usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/MyXWalkView.java
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
- usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithOnTouchEvent.java
- usecase/usecase-embedding-android-tests/tests.android.xml
- usecase/usecase-embedding-android-tests/tests.full.xml
Bug is reported
https://crosswalk-project.org/jira/browse/XWALK-4879
> [usecase-embedding] Add a usecase for validating onTouchEvent

- tools/atip/README.md
- tools/atip/atip/android/android.py
- tools/atip/atip/android/steps.py
-add new step to launch test app by click app icon
BUG=https://crosswalk-project.org/jira/browse/XWALK-4878
> [ATIP-android] add new step to launch test app

- tools/atip/README.md
- tools/atip/atip/android/android.py
- tools/atip/atip/common/steps.py
-add new step to enable or disable location service
BUG=https://crosswalk-project.org/jira/browse/XWALK-4890
> [ATIP-android] add new step to enable or disable location service
