crosswalk-project/crosswalk-test-suite

behavior/js/main.js

- On IVI app exit working must use tizen API, so improve exit method to support both IVI and android platform
Unit test on platforms IVI and android, the app can exit successfully.

[behavior][XWALK-3251] Fix app exit button can not work on IVI

---

behavior/js/main.js

- On IVI app exit working must use tizen API, so improve exit method to support both IVI and android platform
Unit test on platforms IVI and android, the app can exit successfully.

[crosswalk-10][behavior][XWALK-3251] Fix app exit button disabled

---

webapi/tct-colors-css3-tests/colors/csswg/t422-rgba-func-int-a.htm

Remove the invalid charcter '\' from test code.

[webapi][XWALK-3118] Delete the excess character '\'

---

usecase/usecase-cordova-android-tests/inst.wgt.py
usecase/usecase-cordova-android-tests/inst.xpk.py
usecase/usecase-webapi-xwalk-tests/inst.wgt.py
usecase/usecase-webapi-xwalk-tests/inst.xpk.py
usecase/usecase-wrt-android-tests/inst.wgt.py
usecase/usecase-wrt-android-tests/inst.xpk.py
usecase/usecase-wrt-tizen-tests/inst.wgt.py
usecase/usecase-wrt-tizen-tests/inst.xpk.py

- Remove trailing space from inst.wgt.py files

[usecase] Update inst.wgt.py to reflect pkgcmd -l change 

---

wrt/wrt-packertool2-android-tests/packertool2/othertest.py
wrt/wrt-packertool2-android-tests/tests.full.xml
wrt/wrt-packertool2-android-tests/tests.xml

- Update script othertest.py to fix bug
- Update the xml files due to the current order affect the test results
Android test result summary: Pass 4, Fail 0, Block 0

[wrt][xwalk-3327] Update 4 TCs for wrt-packertool2-android-tests

---

webapi/tct-widget02-w3c-tests/scripts/xwalk_common.sh

[webapi] Update xwalk_common script to reflect pkgcmd -l change

---

webapi/tct-package-tizen-tests/package/support/unitcommon.js

This patch fixes improper values in conversion table
which are used to validate conversion.

[webapi][XWALK-3323] Fix improper tct-package-tizen-tests input values

---

webapi/tct-websocket-w3c-tests/tests.full.xml
webapi/tct-websocket-w3c-tests/tests.xml

- Change 'execution_type' from 'manual' to 'auto'
- Failure analysis: https://crosswalk-project.org/jira/browse/XWALK-1791
Impacted tests(approved): new 0, update 39, delete 0
Unit test result summary: pass 37, fail 1, block 1

[webapi] Update tests from manual to auto for websocket

---

webapi/tct-audio-html5-tests/audio/w3c/audio_loop_base.html

- The testharness.js have updated to the latest, and the function setup changed.
- Function setup accept "explicit_timeout:true", case run no time limit in these way.
- The default timeout time is 10s, if case run time more than 10s, it will lead to block.
- Unfortunately setup can't set timeout value by itself again, there are only 10s or no time limit.
Unit test platform: [android] crosswalk-10.38.222

[webapi][XWALK-3201] Update the function setup parameter

---

cordova/cordova-mobilespec-android-tests/inst.wgt.py
cordova/cordova-mobilespec-android-tests/inst.xpk.py
cordova/cordova-sampleapp-android-tests/inst.wgt.py
cordova/cordova-sampleapp-android-tests/inst.xpk.py
cordova/cordova-webapp-android-tests/inst.wgt.py
cordova/cordova-webapp-android-tests/inst.xpk.py

- Removing trailing space from inst.wgt.py files

[cordova] Update inst.wgt.py to reflect pkgcmd -l change

---

webapi/tct-testconfig/tests.full.xml
webapi/tct-testconfig/tests.xml

- Remove useless pre-condition(WRT Autodevice)
- Remove the pre-condition not suitable for IVI (Time, Power)
- Remove empty &lt;pre_condition&gt; and &lt;post_condition&gt;
- Format the files using 'xmllint --format'

[webapi] Remove back-light pre-condition from IVI testing

---

webapi/tct-power-tizen-tests/README
webapi/tct-power-tizen-tests/tests.full.xml
webapi/tct-power-tizen-tests/tests.xml

- Remove 4 tests for Tizen Power because IVI cannot change back-light

[webapi][xwalk-2225] Remove back-light related tests for Tizen Power

---

webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/ecmascript_simd_tests.js
webapi/webapi-simd-nonw3c-tests/tests.full.xml
webapi/webapi-simd-nonw3c-tests/tests.xml

- SIMD.js API spec adds "ByScalar" to shift operations, add tests to test the new feature.
- Fail Reasion: the new feature is not supported now.
Impacted TCs num: New 48, Update 0, Delete 0
Unit test result summary: Pass 0, Fail 48, Blocked 0

[webapi][XWALK-3117] Add tests to SIMD

---

webapi/tct-backgrounds-css3-tests/backgrounds/csswg/background-size-030.html

- Change the word squares to square in this test so that it can share a same reftest with other tests. 
Impacted tests(approved): new 0, update 1, delete 0 
Unit test platform: [TizenIVI] 

[webapi][XWALK-2955] Update background-size-30.html test

---

webapi/tct-mediaqueries-css3-tests/tests.full.xml
webapi/tct-mediaqueries-css3-tests/tests.xml

- CSS MediaQueries does not need depend on 'accelerometer' capability, remove it from tests xml
Unit test platform:[Tizen]
Unit test result summary: pass 52, fail 0, block 0

[webapi] Remove accelerometer capability in CSS MediaQueries

---

tools/bootstrap-fw/js/list.js

- When first time launch usecase, enter 'Security' set then back, result of 'Security' appears. But when enter 'CSP' then back, result disappears. Fix this bug.

[usecase] Fix bug result appears exception for usecase

---

tools/atip/atip/web/steps.py

The previous step lacks the prefix of page url

[tools][XWALK-3358] update the step to get current page url

---

embeddingapi/embedding-api-android-tests/embeddingapi/AndroidManifest.xml
embeddingapi/embedding-api-android-tests/embeddingapi/assets/echo.html
embeddingapi/embedding-api-android-tests/embeddingapi/assets/external.js
embeddingapi/embedding-api-android-tests/embeddingapi/assets/externalJs.html
embeddingapi/embedding-api-android-tests/embeddingapi/assets/framesEcho.html
embeddingapi/embedding-api-android-tests/embeddingapi/assets/innerJs.html
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestXWalkResourceClientBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestXWalkUIClientBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/LoadTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkUIClientTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkViewTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v2/XWalkExtensionTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v4/XWalkResourceClientTest.java

- Failure analysis: When the html file useing the write js method to make page content, the onPageLoadStopped of XWalkUIClient can't be triggered
Impacted tests(approved): new 3, update 5, delete 0
Unit test result summary: pass 7, fail 1, block 0

[embeddingapi][XWalk-3318] Improve embeddingapi cases

---

webapi/webapi-rawsockets-w3c-tests/rawsockets/TCPServerSocket_method_close.html

- The close method can not fire TCPSocket.close event, so update

[webapi][XWALK-3446] Update test logic for Rawsockets

---

webapi/tct-webstorage-w3c-tests/webstorage/w3c/storage_local_setitem_quotaexceedederr.html
webapi/tct-webstorage-w3c-tests/webstorage/w3c/storage_session_setitem_quotaexceedederr.html

- These tests need more time to waitting for result of storage_local_setitem_quotaexceedederr
Unit test platform: [android]

[webapi][XWALK-3390] Improve tests for Storage quotaexceedederr

---

embeddingapi/embedding-api-android-tests/embeddingapi/assets/console_message.html
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnConsoleMessageHelper.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestXWalkUIClientBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkUIClientTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java
embeddingapi/embedding-api-android-tests/tests_v1.xml
embeddingapi/embedding-api-android-tests/tests_v5.xml

- Add cases for XWalkUIClient.onConsoleMessage and XWalkView.setUserAgentString

[embedding][XWALK-3349] Add cases for 2 features of embeddingapi

---

webapi/webapi-mediaserver-tizen-tests/mediaserver/MediaServerIdEvent_id_exist.html

[webapi][XWALK-3503] Change event object to event.id for mediaserver

---

webapi/webapi-mediaserver-tizen-tests/mediaserver/MediaContainer_upload_basic.html

[webapi][XWALK-3501] Lack of ')' to complete the test code for mediaserver

---

webapi/webapi-rawsockets-w3c-tests/tests.full.xml
webapi/webapi-rawsockets-w3c-tests/tests.xml

- The onhalfclose and onmessage events haved been removed by new spec, so remove related tests
- SPEC url：http://www.w3.org/TR/raw-sockets/#interface-tcpsocket
Impacted TCs num(approved): New 0, Update 0, Delete 2
Unit test result summary: Pass 0, Fail 0, Blocked 0

[webapi][XWALK-2435] Remove tests for RawSockets

---

webapi/webapi-rawsockets-w3c-tests/rawsockets/UDPSocket_interface_basic.html

- Because joinMulticastGroup and leaveMulticastGroup methods have been changed to joinMulticast and leaveMulticast by the new spec, so update tests.
- SPEC url:http://www.w3.org/TR/raw-sockets/#interface-udpsocket

[webapi][XWALK-2436] Update tests for rawsockets

---

webapi/tct-video-html5-tests/video/w3c/video_loop_base.html

- Function setup can't set timeout value by itself again in the latest testharness.js
- Add 'meta name=timeout content=long', then test run time will be 60s.
Unit test platform: [android] crosswalk-12.40.281

[webapi] Add long timeout for video

---

behavior/tests/ConfigurationExtension/res/setting-encrypt-disable.html
behavior/tests/ConfigurationExtension/res/setting-encrypt-enable.html
behavior/tests/PackageManagement/res/Sample-widget3.html
behavior/tests/Security/index.html
behavior/tests/Stability/res/test-half-memory.html
behavior/tests/WRTSupport/res/protection-encryption-check.html
doc/Web_Runtime_Crosswalk_Test_Suite_User_Guide.md
tools/atip/tools/set_env.sh
tools/atip/tools/webdriver.xw_tizen.json
usecase/usecase-wrt-tizen-tests/samples/ApplicationProtection/index.html
webapi/tct-application-tizen-tests/README
webapi/tct-notification-tizen-tests/notification/StatusNotification_appControl_attribute.html
webapi/tct-privilege-tizen-tests/privilege/ContentManager_scanFile.html
webapi/webapi-mediarenderer-tizen-tests/README
webapi/webapi-mediaserver-tizen-tests/README
wrt/wrt-packertool-tizen-tests/inst.wgt.py

- TESTER-HOME_DIR is used to replace static source code
/home/app during test suite packaging.
- TIZEN_USER is used for dynamic replacement by testkit.
It can also be used for manually cases which don't
need update.
- SRC_DIR is a variable used by installation scripts.

Deprecate /home/app for multiuser support

---

wrt/tct-appwgt-wrt-tests/scripts/wrt_appwgt_install.sh
wrt/tct-appwgt-wrt-tests/scripts/wrt_appwgt_install_no_signature.sh
wrt/tct-appwgt-wrt-tests/scripts/wrt_appwgt_install_only_author_signature.sh
wrt/tct-appwgt-wrt-tests/scripts/wrt_appwgt_install_valid_signature.sh
wrt/tct-appwgt-wrt-tests/scripts/wrt_appwgt_uninstall.sh
wrt/tct-appwgt-wrt-tests/scripts/xwalk_common.sh
wrt/tct-ext02-wrt-tests/scripts/Common
wrt/tct-pm-wrt-tests/scripts/Common
wrt/tct-pm-wrt-tests/scripts/wrt_pm_Install_EXE.sh
wrt/tct-pm-wrt-tests/scripts/wrt_pm_dataStored_Update.sh
wrt/tct-pm-wrt-tests/scripts/wrt_pm_uninstallation_application_erased.sh
wrt/tct-sp02-wrt-tests/scripts/wrt_sp02_localstorage_check.sh
wrt/tct-sp02-wrt-tests/scripts/xwalk_common.sh
wrt/wrt-digitalsign-tizen-tests/digitalsign/Common
wrt/wrt-digitalsign-tizen-tests/digitalsign/Crosswalk_Digital_Signature_Error.sh
wrt/wrt-digitalsign-tizen-tests/digitalsign/Crosswalk_Digital_Signature_Package.sh
wrt/wrt-manifest-tizen-tests/script/Common
wrt/wrt-manifest-tizen-tests/script/checkdb.sh
wrt/wrt-manifest-tizen-tests/script/checkdb_new.sh
wrt/wrt-manifest-tizen-tests/script/checktct_folder.sh
wrt/wrt-packagemgt-tizen-tests/packagemgt/Common
wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_WebApp_Install_Resource.sh
wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_WebApp_Launcher_Cache.sh
wrt/wrt-rtbin-tizen-tests/rtbinauto/Common
wrt/wrt-rtbin-tizen-tests/rtbinauto/Crosswalk_Run_As_Service_CheckDB.sh
wrt/wrt-rtbin-tizen-tests/rtbinauto/Crosswalk_Run_As_Service_Install.sh
wrt/wrt-rtbin-tizen-tests/rtbinauto/Crosswalk_Run_As_Service_Uninstall.sh

- Because of can not get the value of 'TIZEN_USER' when
execute shell script on ivi device, update the script
by new way in batch at here
- Talk with the testkit-lite developer, set the 'TIZEN_USER'
environment variable value on ivi device will not be achieved

[xwalk-3558] Update /home/app code by multi-user in wrt scripts

---

stability/stability-longlasting-tizen-tests/longlasting/MemoryFreeLongTime.sh

- Use testkit test this case, when testkit timeout, the
return result is block
- The reason is the cycle number error, update from 10 to 30

[stability] Update memoryfreelongtime test bug

---

webapi/webapi-simd-nonw3c-tests/tests.full.xml
webapi/webapi-simd-nonw3c-tests/tests.xml

- SIMD.float32x4.shuffleMix API has been replaced by SIMD.float32x4.swizzle, so delete related case
Impacted TCs num(approved): New 0, Update 0, Delete 1
Unit test result summary: Pass 0, Fail 0, Blocked 0

[webapi][XWALK-3518] Delete simd tests

---

wrt/wrt-packertool2-android-tests/packertool2/comm.py
wrt/wrt-packertool2-android-tests/packertool2/versionCodetest.py
wrt/wrt-packertool2-android-tests/tests.full.xml
wrt/wrt-packertool2-android-tests/tests.xml

- Add test for version when the length of version in manifest file is greater than or equal to 4
Impacted TCs num(approved): New 1, Update 3, Delete 0
Android test result summary: Pass 4, Fail 0, Block 0

[wrt][xwalk-3492] Update tests for packertool2

---

tools/atip/atip/web/steps.py

Just change the method get_page_url() to get page url by test platform name.

[atip] Update the method to get page url

---

wrt/wrt-manifest-tizen-tests/run_test.py

- Add the code for ssh connection when test device
type is ssh
Impacted tests(approved): new 0, update 264, delete 0
Unit test result summary: pass 264, fail 0, block 0
Bug: xwalk-3599

[wrt][xwalk-3599] Update ssh connection code in run_test.py

---

behavior/tests/ConfigurationExtension/res/setting-encrypt-disable.html
behavior/tests/ConfigurationExtension/res/setting-encrypt-enable.html
behavior/tests/PackageManagement/res/Sample-widget3.html
behavior/tests/Stability/res/test-half-memory.html
behavior/tests/WRTSupport/res/protection-encryption-check.html
tools/atip/tools/set_env.sh
tools/atip/tools/webdriver.xw_tizen.json
usecase/usecase-webapi-xwalk-tests/samples/ApplicationSwitching/js/main.js
usecase/usecase-webapi-xwalk-tests/samples/Package/js/main.js
usecase/usecase-wrt-tizen-tests/samples/ApplicationProtection/index.html
wrt/tct-appwgt-wrt-tests/scripts/wrt_appwgt_install.sh
wrt/tct-appwgt-wrt-tests/scripts/wrt_appwgt_install_no_signature.sh
wrt/tct-appwgt-wrt-tests/scripts/wrt_appwgt_install_only_author_signature.sh
wrt/tct-appwgt-wrt-tests/scripts/wrt_appwgt_install_valid_signature.sh
wrt/tct-appwgt-wrt-tests/scripts/wrt_appwgt_uninstall.sh
wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_WebApp_Install_Resource.sh
wrt/wrt-packagemgt-tizen-tests/packagemgt/Crosswalk_WebApp_Launcher_Cache.sh
wrt/wrt-packagemgtmanu-tizen-tests/packagemgtmanu/Crosswalk_WebApp_Uninstall_Resource.html

- Update the installed app path from 'xwalk-server' to 'xwalk'
- About manual cases, i just tested one of the most typical case
Bug: xwalk-3590

[wrt][xwalk-3590] Update the install path for tizen

---

embeddingapi/embedding-api-android-tests/inst.apk.py
embeddingapi/embedding-api-android-tests/suite.json
tools/build/pack.py

- Improve the pack.py to pack multi apks to one pkg
- Update inst.apk.py to inst or uninst multi apks
- Remove the test.xml of copylist in suite.json
Unit test result summary: pass 152, fail 19, block 22

[embeddingapi] Support to pack multi apks to one pkg

---

webapi/webapi-rawsockets-w3c-tests/rawsockets/TCPServerSocket_attribute.html

- The TCPServerSocket Constructor has been changed to one Parameter in new spec, so update test
- SPEC url:http://www.w3.org/TR/raw-sockets/#interface-tcpserversocket

[webapi][XWALK-2414] Update test for rawsockets

---

embeddingapi/embedding-api-android-tests/embeddingapi/assets/writeContent.html
embeddingapi/embedding-api-android-tests/embeddingapi/assets/writeIfrme.html
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/FullScreenTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v2/XWalkExtensionTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v2/XWalkUIClientTest.java
embeddingapi/embedding-api-android-tests/tests_v2.xml

- Add cases to check if OnReceivedTitle can be triggered when load js write page
- Add cases to check if OnPageLoadStarted can be triggered when load js write page
- Improve "testOnSyncMessage_MultiFrames" case
- Failure analysis: XWALK-3564
Impacted tests(approved): new 6, update 3, delete 0
Unit test result summary: pass 8, fail 1, block 0

[embedding][XWALK-3631] Add cases for load js write page

---

tools/atip/atip/web/web.py

- Update the method check_text_color to get the text color which is defined in <style> label. 
For example: <style> div { color: green; } </style>
Impacted cases details:
usecase-webapi-xwalk-tests/Contactsmanager.feature
usecase-webapi-xwalk-tests/Forms.feature
usecase-webapi-xwalk-tests/Jsenhance.feature
usecase-webapi-xwalk-tests/Sandbox.feature

[atip] Update method to get the text color defined in <style> label

---

webapi/webapi-simd-nonw3c-tests/tests.full.xml
webapi/webapi-simd-nonw3c-tests/tests.xml

- SIMD.float32x4.shuffleMix API has been replaced by SIMD.float32x4.swizzle, so delete related case
Impacted TCs num(approved): New 0, Update 0, Delete 1
Unit test result summary: Pass 0, Fail 0, Blocked 0

[webapi][XWALK-3518] Delete 1 SIMD test

---

usecase/usecase-webapi-xwalk-tests/samples/Es6NumericLiterals/index.html
usecase/usecase-webapi-xwalk-tests/samples/FileApiPersistent/index.html
usecase/usecase-webapi-xwalk-tests/samples/FileApiPersistent/res/index.html
usecase/usecase-webapi-xwalk-tests/tests.android.xml
usecase/usecase-webapi-xwalk-tests/tests.auto.xml
usecase/usecase-webapi-xwalk-tests/tests.full.xml
usecase/usecase-webapi-xwalk-tests/tests.tizen.xml
usecase/usecase-webapi-xwalk-tests/testscripts/Es6NumericLiterals.feature
usecase/usecase-webapi-xwalk-tests/testscripts/FileApiPersistent.feature

- Fail Reason: the Es6NumericLiterals is not supported.
Unit test result summary: Pass 1, Fail 1, Blocked 0

[usecase] Automate 2 usecases

---

webapi/webapi-nacl-xwalk-tests/README

- Nacl_api_Var_Dictionary.html has one bug:
[XWALK-1893] "Function Delete returned undefined" error occurred when deleting key value in the Nacl module's dictionary,
the issue has tracked by  https://code.google.com/p/nativeclient/issues/detail?id=3919

[webapi][xwalk-1893] Add note message for nacl

---

webapi/webapi-resourcetiming-w3c-tests/resourcetiming-py/w3c/submission/COPYING
webapi/webapi-resourcetiming-w3c-tests/resourcetiming-py/w3c/submission/test_resource_timing.html
webapi/webapi-resourcetiming-w3c-tests/resourcetiming/w3c/submission/COPYING
webapi/webapi-resourcetiming-w3c-tests/resourcetiming/w3c/submission/test_resource_timing.html

- Sometimes the TEST_ALLOWED_TIMING_DELTA is too short
when the testing device in poor performance
Unit test platform: [Android][Crosswalk 13.41.309.0]

[webapi][xwalk-3765] Increase allowed timing delta

---

apptools/wrt-apptools-android-tests/apptools/build.py
apptools/wrt-apptools-android-tests/apptools/comm.py
apptools/wrt-apptools-android-tests/tests.full.xml
apptools/wrt-apptools-android-tests/tests.xml

Impacted TCs num(approved): New 1, Update 2, Delete 0
Android test result summary: Pass 1, Fail 2, Block 0
- Update the tests status from designed to approved
- Fail BugId: xwalk-3779/3782

[apptools] Add test for build commands

---

apptools/apptools-linux-tests/COPYING
apptools/apptools-linux-tests/README
apptools/apptools-linux-tests/apptools/allpairs.py
apptools/apptools-linux-tests/apptools/build.py
apptools/apptools-linux-tests/apptools/comm.py
apptools/apptools-linux-tests/apptools/create.py
apptools/apptools-linux-tests/apptools/pkgName.py
apptools/apptools-linux-tests/suite.json
apptools/apptools-linux-tests/tests.full.xml
apptools/apptools-linux-tests/tests.xml

Impacted tests(approved): new 18, update 0, delete 0
Unit test result summary: pass 16, fail 2, block 0
Fail reason:
- Create pkgname like "org.example.1234test/org.example.1234" successfully, but expect failed
Bug id: xwalk-3818

[apptools]Add apptools test suite for linux

---

webapi/webapi-input-html5-tests/tests.full.xml
webapi/webapi-input-html5-tests/tests.xml

- It looks like the white space in url value was only stripped in Chromium M41, while all other releases before and after that one this is not done. Remove the tests from Crosswalk 13.
See https://code.google.com/p/chromium/issues/detail?id=446108 for more context.

[webapi][xwalk-3797] Remove unsupported url tests in HTML5 input element

---

apptools/apptools-linux-tests/apptools/build.py
apptools/apptools-linux-tests/apptools/comm.py
apptools/apptools-linux-tests/tests.full.xml
apptools/apptools-linux-tests/tests.xml

Unit test result summary: pass 17, fail 2, block 0
Update:
* update the run method, and tests xml file.  add new method to prevent process is engaged
* update the build method, add the delete temporary files
Fail reason:
* Create pkgname like "org.example.1234test/org.example.1234" successfully, but expect failed
Buid id: xwalk-3818

[apptools]Update apptools test suite for linux

---

tools/atip/atip/web/steps.py

This steps is used to save the screenshot as base64 data,encrypt it with md5.

[atip] Update the steps name to make it more clear

---

misc/webappmanu-linux-tests/webapp/resources/org.webapps.baiduhi/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.baidumap/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.baidumusic/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.baiduonlinestorage/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.cargobridge/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.chainrxn/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.dbankonlinestorage/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.doitim/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.douban/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.fetion/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.kingsoftfastdocs/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.kingsoftonlinestorage/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.kugoumusic/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.kuwomusic/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.microsoftskydrive/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.paulrouget/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.pirateslovedaisies/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.sinaweibo/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.test12306/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.towerim/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.ttpod/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.xiamimusic/manifest.json
misc/webappmanu-linux-tests/webapp/resources/org.webapps.youdaonote/manifest.json
usecase/usecase-wrt-linux-tests/res/testapp/org.packagemanage.cookies/manifest.json
usecase/usecase-wrt-linux-tests/res/testapp/org.packagemanage.cookiesupgrade/manifest.json

The start_url is an official member of manifest for a web application
specified at http://w3c.github.io/manifest/#start_url-member
It should be supported by Crosswalk Project since there are two features
requirement at
https://crosswalk-project.org/jira/browse/XWALK-890
https://crosswalk-project.org/jira/browse/XWALK-3696
However it is reported that an error appears when use, at
https://crosswalk-project.org/jira/browse/XWALK-3656
... and that is why the app->launch->web_url workaround is used.

[XWALK-3656] Use official start_url member in manifest

---

webapi/tct-backgrounds-css3-tests/suite.json
webapi/tct-fonts-css3-tests/suite.json

- When crete all in one packages, part of bdd tests would lost support file, so add support file copy command in suite.json to ensure test run normally.
Impacted TCs num(approved): New 0, Update 78, Delete 0
Unit test result summary: Pass 78, Fail 0, Blocked 0

[webapi][XWALK-3930] Update suite.json for backgrounds and fonts

---

webapi/tct-backgrounds-css3-tests/suite.json
webapi/tct-fonts-css3-tests/suite.json

- When crete all in one packages, part of bdd tests would lost support file, so add support file copy command in suite.json to ensure test run normally.
Impacted TCs num(approved): New 0, Update 78, Delete 0
Unit test result summary: Pass 78, Fail 0, Blocked 0

[webpai][XWALK-3930] Update suite.json for backgrounds and fonts

---

embeddingapi/embedding-api-android-tests/embeddingapi/assets/window_create_open.html
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v4/XWalkUIClientTest.java

- According to the embeddingapi implement, onCreateWindowRequested only support '_blank', not support '_self', '_parent', '_top', so remove the undesired cases.
Impacted tests(approved): new 2, update 0, delete 6

[embeddingapi][XWALK-2754][hotfix] Adjust cases according to the change of onCreateWindowRequested feature

---

webapi/webapi-contactsmanager-w3c-tests/contactsmanager/Contact.html
webapi/webapi-contactsmanager-w3c-tests/contactsmanager/Contact_attributes.html
webapi/webapi-contactsmanager-w3c-tests/contactsmanager/ContactsManager_save_Contact_fullset.html
webapi/webapi-contactsmanager-w3c-tests/contactsmanager/ContactsManager_save_emails_fullset.html
webapi/webapi-contactsmanager-w3c-tests/contactsmanager/ContactsManager_save_emails_multiple.html
webapi/webapi-contactsmanager-w3c-tests/contactsmanager/ContactsManager_save_emails_partset.html
webapi/webapi-contactsmanager-w3c-tests/contactsmanager/ContactsManager_save_impp_fullset.html
webapi/webapi-contactsmanager-w3c-tests/contactsmanager/ContactsManager_save_impp_multiple.html
webapi/webapi-contactsmanager-w3c-tests/contactsmanager/ContactsManager_save_impp_partset.html
webapi/webapi-contactsmanager-w3c-tests/contactsmanager/ContactsManager_save_urls_multiple.html

Impacted tests(approved): new 0, update 11, delete 0
Unit test platform: [android][crosswalk 14.43.342.0]
Unit test result summary: pass 10, fail 1, block 0
Comments:
Type of Contact.birthday should be Date object, but after
saving, type was changed to "string" in the success callback
of ContactsManager.save(). Issue tracked by XWALK-4108

[webapi] Improve 11 tests for ContactsManager

---

webapi/tct-notification-w3c-tests/tests.full.xml
webapi/tct-notification-w3c-tests/tests.xml

- Due to before run onshow_using test need clear all notification, so move this case to other set.

[XWALK-3972] Update xml for notification

---

tools/build/pack_deb.py
webapi/tct-audio-html5-tests/inst.deb.py
webapi/tct-audio-html5-tests/suite.json
webapi/tct-notification-w3c-tests/inst.deb.py
webapi/tct-notification-w3c-tests/suite.json
webapi/tct-video-html5-tests/inst.deb.py
webapi/tct-video-html5-tests/suite.json

Enable webapi test suites (Audio/Web Notifications/Video)
on Crosswalk Project for Linux
Audio:
Unit test result summary: pass 246, fail 50, block 45
Video:
Unit test result summary: pass 285, fail 51, block 43
Web Notifications:
Unit test result summary: pass 13, fail 0, block 2

[webapi] Enable Test Suites for Crosswalk Linux

---

usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml

-App crash when enter Embedding Usecase in shared mode
-Change android application for usecase embeddinapi apk of shared mode
BUG=https://crosswalk-project.org/jira/browse/XWALK-4149
BUG=https://crosswalk-project.org/jira/browse/XWALK-4172

modify android application for usecase embeddinapi apk of shared mode

---

usecase/usecase-webapi-xwalk-tests/testscripts/ResourceTiming.feature

When the device performance or network in poor, there is no enough
time for loading resource, this make the test result unstable.
Add waiting time for 5 second.
Unit test platform: Crosswalk Project for Android 14.43.342.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4095

[usecase-webapi] Resolve unstable issue in ResourceTiming.feature

---

apptools/apptools-android-tests/apptools/build.py
apptools/apptools-android-tests/apptools/create_remote.py
apptools/apptools-android-tests/apptools/setup_crash_dir.py
apptools/apptools-android-tests/apptools/update.py

https://crosswalk-project.org/jira/browse/XWALK-4056
Impacted tests(approved):new 0,update 13,delete 0
Unit test result summary:pass 12,fail 1,block 0

[apptools-android] remove useless code for apptools android

---

webapi/webapi-gamepad-w3c-tests/tests.full.xml
webapi/webapi-gamepad-w3c-tests/tests.xml

Definitely the gamepad spec is published by W3C Web Applications Working
Group, not by System Application WG.
https://crosswalk-project.org/jira/browse/XWALK-892

[webapi] Wait for gamepad's component to be determined

---

webapi/tct-appcache-html5-tests/tests.full.xml
webapi/tct-appcache-html5-tests/tests.xml

Historically the components are from the Tizen API reference
hierarchical structure. The appcache shall be categorized in Storage,
see
https://developer.tizen.org/dev-guide/2.3.0/org.tizen.web.apireference/html/w3c_api/w3c_api_m.html#storage
https://crosswalk-project.org/jira/browse/XWALK-1355

[webapi] Correct component of HTML5 Application caches

---

webapi/webapi-appuri-w3c-tests/tests.full.xml
webapi/webapi-appuri-w3c-tests/tests.xml

As Kenneth pointed out, App URI is still being used by us and Firefox
OS, so that should stay around.
Though the App URI spec was published by W3C System Application WG, we
leverage Crosswalk Web API category as testing component. See
https://crosswalk-project.org/documentation/apis/web_apis.html
https://crosswalk-project.org/jira/browse/XWALK-388

[webapi] Leverage Crosswalk Web API category

---

tools/build/README.md
tools/build/pack.py
tools/build/pack_cordova_sample.py

- Automate Cordova API 4.0 build in pack_cordova_sample.py
- Improve pack.py, pack_cordova_sample.py to check exist before copy generated apk
BUG=https://crosswalk-project.org/jira/browse/XWALK-4239
BUG=https://crosswalk-project.org/jira/browse/XWALK-4240

[XWALK-4239] Automate Cordova API 4.0 build in pack_cordova_sample.py

---

apptools/apptools-android-tests/apptools/comm.py
apptools/apptools-android-tests/apptools/setup_cache_dir.py
apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml

[apptools-android] Instead 'crash' with 'cache' for apptools android

---

misc/webappmanu-linux-tests/webapp/Xiami_Music_Feature.html
misc/webappmanu-linux-tests/webapp/Xiami_Music_Link.html
misc/webappmanu-linux-tests/webapp/Xiami_Music_Name.html
misc/webappmanu-linux-tests/webapp/Xiami_Music_UI.html
misc/webappmanu-linux-tests/webapp/resources/org.webapps.xiamimusic/manifest.json

Test page issue (http://www.xiami.com/app/webmusic/index)
existed in both crosswalk and chrome, so replace it with
new page (http://www.xiami.com/radio)
Unit test platform: Crosswalk Project for Linux 15.43.347.0
BUG=http://crosswalk-project.org/jira/browse/XWALK-4196

[misc-linux] Update test page link for Xiami Muisc

---

tools/build/pack_deb.py
webapi/tct-notification-w3c-tests/notification/notification_permission.html
webapi/tct-notification-w3c-tests/suite.json
webapi/tct-notification-w3c-tests/tests.linux.xml

According to the comments in https://crosswalk-project.org
/jira/browse/XWALK-4061, only constructor, permission,
requestPermission and onclose are supported, update tests
following these comments
Unit test platform: Crosswalk Project for Linux 15.43.347.0

[webapi] Add tests for Notification.permission

---

usecase/usecase-wrt-linux-tests/res/testapp/org.runtime.externalurl/index.html
usecase/usecase-wrt-linux-tests/res/testapp/org.runtime.externalurl/manifest.json
usecase/usecase-wrt-linux-tests/res/testapp/org.runtime.externalurl/res/index.html
usecase/usecase-wrt-linux-tests/samples/ExternalURL/index.html

Cross-origin URL in scope is not valid as feature
description. Update scope section of manifest
following it.
Unit test platform: Crosswalk Project for Linux 15.43.347.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4151

[usecase-linux] Update usecase for externalurl

---

apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml
apptools/apptools-ios-tests/apptools/create.py
apptools/apptools-ios-tests/tests.full.xml
apptools/apptools-ios-tests/tests.xml
apptools/apptools-linux-tests/apptools/create.py
apptools/apptools-linux-tests/tests.full.xml
apptools/apptools-linux-tests/tests.xml

Due to the test case test_normal is duplicate with test_pkgName_positive1 and the testsuit of crosswalk-app-tools is updated, so delete them
Impacted tests(approved):new 19,update 19,delete 6
Unit test result summary:pass 38,fail 0,block 0

[apptools] Add nodeunit cases for apptools

---

apptools/apptools-android-tests/apptools/comm.py

Unit test result summary:pass 100,fail 5,block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4324

[apptools-android] Change dir to parent dir before removing the project for apptools android

---

misc/webappmanu-linux-tests/webapp/Cargo_Bridge_Feature.html
misc/webappmanu-linux-tests/webapp/Cargo_Bridge_Link.html
misc/webappmanu-linux-tests/webapp/Cargo_Bridge_Name.html
misc/webappmanu-linux-tests/webapp/Cargo_Bridge_UI.html

Add new option "--ppapi-flash-path=xx" for launching
test app. But display nothing after launching it with
this change, issue tracked by https://crosswalk-project.org/
jira/browse/XWALK-3670
Unit test platform: Crosswalk Project for Linux 15.43.350.0
Unit test result summary: pass 1, fail 3, block 0

[misc] Update test steps for Cargo Bridge

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/assets/zoom.html
usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/zoom_layout.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/ZoomInAndOutXWalkViewActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/assets/zoom.html
usecase/usecase-embedding-android-tests/embeddingapi/res/layout/zoom_layout.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ZoomInAndOutXWalkViewActivity.java

https://crosswalk-project.org/jira/browse/XWALK-4169
https://crosswalk-project.org/jira/browse/XWALK-4170
https://crosswalk-project.org/jira/browse/XWALK-4171
-add embeddingapi usecase for XWalkView zoomIn, zoomOut, zoomBy features

[embeddingapi] Add embeddingapi zoom feature usecase sample

---

embeddingapi/embedding-api-android-tests/embeddingapi/assets/zoom.html
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java
embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v5.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/assets/zoom.html
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml

https://crosswalk-project.org/jira/browse/XWALK-4169
https://crosswalk-project.org/jira/browse/XWALK-4170
https://crosswalk-project.org/jira/browse/XWALK-4171
-add embeddingapi autocase for XWalkView zoomIn, zoomOut, zoomBy features

[Embeddingapi] Add embeddingapi zoom feature autocase

---

webapi/tct-webgl-nonw3c-tests/webgl/khronos/COPYING
webapi/tct-webgl-nonw3c-tests/webgl/khronos/resources/js-test-pre.js
webapi/tct-webgl-nonw3c-tests/webgl/khronos/resources/unit.js
webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/COPYING
webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/external/qunit.js
webapi/webapi-webcl-nonw3c-tests/webcl/khronos/COPYING
webapi/webapi-webcl-nonw3c-tests/webcl/khronos/resources/js-test-post.js
webapi/webapi-webcl-nonw3c-tests/webcl/khronos/resources/js-test-pre.js

Support running those webapi cases of tct-webgl-nonw3c-tests,
webapi-simd-nonw3c-tests, and webapi-webcl-nonw3c-tests automatically
on Web Testing Service.

[webapi] Update qunit, khronos harnesses.

---

webapi/webapi-webspeech-w3c-tests/README

According to XWALK-4232, test device should make sure
that google voice search service is installed.
Add this to README.
BUG=https://crosswalk-project.org/jira/browse/XWALK-4338

[webapi] Add pre-condition in README for webspeech

---

usecase/usecase-embedding-android-tests/embeddingapi-async/assets/navigate.html
usecase/usecase-embedding-android-tests/embeddingapi/assets/navigate.html

-remove loading the external link with '_blank' target test part
-load link with '_blank' target won't trigger shouldOverrideUrlLoading method
https://crosswalk-project.org/jira/browse/XWALK-3897

[embeddingapi] Modify ShouldOverrideUrlLoading test case

---

usecase/usecase-embedding-android-tests/embeddingapi/assets/navigate.html

-remove loading the external link with '_blank' target test part
-load link with '_blank' target won't trigger shouldOverrideUrlLoading method
https://crosswalk-project.org/jira/browse/XWALK-3897

[Crosswalk14][embeddingapi] Modify ShouldOverrideUrlLoading test case

---

usecase/usecase-embedding-android-tests/embeddingapi/assets/navigate.html

-remove loading the external link with '_blank' target test part
-load link with '_blank' target won't trigger shouldOverrideUrlLoading method
https://crosswalk-project.org/jira/browse/XWALK-3897

[Crosswalk13][embeddingapi] Modify ShouldOverrideUrlLoading test case

---

tools/build/pack_cordova_sample.py

-When not use "--notclean", it can pack successfully now
BUG=https://crosswalk-project.org/jira/browse/XWALK-4429

[cordova] Improve pack_cordova_sample.py 

---

apptools/apptools-android-tests/apptools/cleanup_downloadfile.py
apptools/apptools-android-tests/tests.full.xml

Add 2 cases to test incomplete file is cleaned up when downing fails or be aborted. The status of these test cases are designed.
https://crosswalk-project.org/jira/browse/XWALK-3828

[apptools-android] Add case to test incomplete file is cleaned up for apptools android

---

apptools/apptools-linux-tests/apptools/comm.py

Unit test platform:[Deepin]
Unit test result summary:pass 50,fail 2,block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4452

[apptools-deepin] Change dir to parent dir before removing the project for apptools deepin

---

usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/MultiSurfaceViewsActivity.java
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithTransparent.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/MultiSurfaceViewsActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithTransparent.java

-Modify usecase MultiSurfaceViewsActivity & XWalkViewWithTransparent which set ANIMATABLE_XWALK_VIEW false value
-Drop this setting to check if the default value work or not
https://crosswalk-project.org/jira/browse/XWALK-4366

[Embeddingapi] Modify usecase about surfaceview

---

apptools/apptools-ios-tests/tests.full.xml
apptools/apptools-ios-tests/tests.xml

Change execution_type from 'manual' to 'auto', since ios has already supported testkit-lite

[apptools-ios] Change execution_type from 'manual' to 'auto' for apptools ios

---

tools/resources/testharness/testharness.css
tools/resources/testharness/testharness.js
tools/resources/testharness/testharnessreport.js

- Add new Assertions:
assert_between_exclusive
assert_between_inclusive
- Add promise_rejects to test Promises that need to reject
- Add EventWatcher to allows DOM events to be handled using Promises,
make it easier to test a very specific series of events
- Update WindowTestEnvironment prototype to support a test inside an
iframe with a same origin document
Try run test suites , tests run normally, including:
webapi-devicecapabilities-w3c-tests
webapi-contactsmanager-w3c-tests
https://crosswalk-project.org/jira/browse/XWALK-4464

[tools] Sync testharness.js scripts to latest

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithDispatchKeyEvent.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithDispatchKeyEvent.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase to check dispatchKeyEvent  method in XWalkView
https://crosswalk-project.org/jira/browse/XWALK-4459

[EmbeddingApi] Add usecase to disable back button in XWalkView

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java
embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v5.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml

-Add autocase to check XWalkView.setAcceptLanguages api
https://crosswalk-project.org/jira/browse/XWALK-4350

[Embeddingapi] Add autocase about selecting xwalkview language

---

wrt/wrt-internetstdmanu-android-tests/internetstdmanu/Crosswalk_WebSocket_userAgent.html
wrt/wrt-internetstdmanu-android-tests/tests.full.xml
wrt/wrt-internetstdmanu-android-tests/tests.xml

This test check if User-Agent is not empty when connecting via websocket
Create WebSocket same as https://github.com/crosswalk-project/crosswalk-test-suite/blob/master/webapi/tct-websocket-w3c-tests/websocket/support/websocket.js
Unit test Platform: Crosswalk Project for Android 15.43.347
BUG=https://crosswalk-project.org/jira/browse/XWALK-3076

[wrt] Add test for WebSocket

---

tools/atip/atip/web/steps.py
tools/atip/atip/web/web.py
usecase/usecase-webapi-xwalk-tests/testscripts/SIMD.feature

When SIMD button is disable, the FPS value without SIMD will get two times. Due to two FPS values have a very samll differnence and the second value always greater than the first value very little. We will get pass result.
This update is to avoid this problem.
Unit test Platform: Crosswalk Project for Android 15.44.364
Unit test result summary: Pass 0, Fail 1, Blocked 0
Fail analysis: SIMD does not work after rebase to M44. More details in https://crosswalk-project.org/jira/browse/XWALK-4207

[usecase] Update feature for SIMD

---

misc/webappmanu-linux-tests/webapp/12306_Feature.html
misc/webappmanu-linux-tests/webapp/12306_Link.html
misc/webappmanu-linux-tests/webapp/12306_Name.html
misc/webappmanu-linux-tests/webapp/12306_UI.html
misc/webappmanu-linux-tests/webapp/IM_Baidu_Feature.html
misc/webappmanu-linux-tests/webapp/IM_Baidu_Link.html
misc/webappmanu-linux-tests/webapp/IM_Baidu_Name.html
misc/webappmanu-linux-tests/webapp/IM_Baidu_UI.html

Update the way to launch test app for test12306 and baiduhi
Impacted tests(approved): new 0, update 8, delete 0
Unit test platform: Crosswalk for Linux 15.44.370.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4535

[misc-linux] Update the way to launch test app

---

usecase/usecase-wrt-linux-tests/samples/Flash/index.html
usecase/usecase-wrt-linux-tests/samples/MediaCodec/res/audioplay/index.html
usecase/usecase-wrt-linux-tests/samples/MediaCodec/res/videoplay/index.html

Update the way to launch test app for MediaCodec and Flash refer to https://crosswalk-project.org/jira/
browse/XWALK-4537
Unit test platform: Crosswalk for Linux 15.44.370.0

[usecase-linux] Update the way to launch test app

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java

-creation of XWalkView should be put in onCreate()
-Cover embeddingapi sync & async autocase
Unit test result summary: pass 44, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4451

[Embeddingapi] Modify xwalkview creation on embedding cases

---

misc/sampleapp-android-tests/sampleApp_pack.sh
misc/sampleapp-android-tests/suite.json

Add sampleApp_pack.sh to crosswalk-test-suite/misc/sampleapp-android-tests
for better maintenance. It's intended to release all the sample apps apk files
while it should not be packed into the test packages. That's why it's in the
blacklist in suite.json file.
https://crosswalk-project.org/jira/browse/XWALK-4555

[TC release]Add sampleApp_pack.sh for better maintenance

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithSetLanguage.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithSetLanguage.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase to check XWalkView.setAcceptLanguages api

[Embeddingapi] Add usecase about selecting xwalkview language

---

wrt/wrt-manifest-android-tests/gen_apks.py
wrt/wrt-manifest-android-tests/run_app.py
wrt/wrt-packertool-android-tests/run_app.py
wrt/wrt-packertool-android-tests/tests.py

- Update the naming rule for manifest script
- Update the tests.py for packertool
- The test suites can pack and run normally

[wrt] Update test script for packertool and manifest

---

webapi/tct-extra-html5-tests/tests.full.xml
webapi/tct-extra-html5-tests/tests.xml
webapi/tct-extra-html5-tests/w3c/system-state-and-capabilities/the-navigator-object/get-navigatorlanguage-manual.html
webapi/tct-extra-html5-tests/w3c/system-state-and-capabilities/the-navigator-object/navigatorlanguage.html

Change get-navigatorlanguage-manual.html precondition refer to 
https://crosswalk-project.org/jira/browse/XWALK-2132
Unit test platform: Crosswalk Project for Android 15.44.371.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-2242

[webapi] Integrate w3c tests for NavigatorLanguage

---

tools/build/test_suites.list

Web Testing Service (WTS) shall run all the test cases on Crosswalk
platforms and browsers. So it should not include any test suites
specific for Tizen platform.

[tools] Remove Tizen related test suites from WTS

---

webapi/tct-webstorage-w3c-tests/suite.json

XWALK-4397 [REG][webdriver] Click element failed in webdriver after crosswalk rebased M44
BUG=https://crosswalk-project.org/jira/browse/XWALK-4579

[webapi] Update test path of w3c-webstorage-app

---

tools/build/pack.py
tools/build/pack_cordova_sample.py

Before the pack scripts required the cordova version exactly 5.0.0.
If it's not 5.0.0, packing will fail. Now cordova version has already
upgrade to 5.1.1. But the scripts do not update to accommodate to this change.
On master branch this modification was done before but it's not synchronized to
Crosswalk-14 branch. So merge this change to Crosswalk-14 branch.
https://crosswalk-project.org/jira/browse/XWALK-4670

[tools] Apply pack scripts to cordova with higher version than 5.0.0

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java

-Add isXWalkReady function on extending XWalkActivity
-On case setUp func, wait isXWalkReady be true
Impacted tests(approved): new 0, update 60, delete 0
Unit test result summary: pass 60, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4647

[Embeddingapi] Add checking xwalkview ready module

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkViewTest.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkViewTest.java

-Modify testResumeTimers_function & testPauseTimers_function cases
BUG=https://crosswalk-project.org/jira/browse/XWALK-4444

[Embeddingapi] Change pause & resume time autocase asserting ways

---

tools/template/reftest_reference_ref.html
tools/template/reftest_test_case.html
tools/template/script_test_case.html

Historically test developer's name was put into file comments
immediately after license info. At the very beginning, this template is
OK for internal using.
As projects moving forward, these tests are expected to contribute to
upstream, e.g. W3C. It is important to put the author info into metadata
rather than into comment, because this comment including license and
author info must be removed before submission.
Sometimes, the authorship informations in metadata are used to
respect the authors, for example CSS WG nightly unstable lists all
authors in its acknowledgements section at
http://test.csswg.org/suites/css-transforms-1_dev/nightly-unstable/
Therefore both Intel and co-author Jieqiong Cui are acknowledged.
Sometimes, people can use this author metadata to talk test issues,
which is …

[tools] Put test author into metadata

---

misc/sampleapp-android-tests/sampleApp_pack.sh

Currently, the server IP and port in the code of sample app webrtc
is invalid for the test team. So update them to a valid value for the
test team before packing the test suite.
https://crosswalk-project.org/jira/browse/XWALK-4663

[sample app] Update server IP and port for webrtc sample app

---

tools/build/README.md
tools/build/pack.py
tools/build/pack_cordova_sample.py

- Support shared mode according cordova-plugin-crosswalk-webview
- Use crosswalk-test-suite/VERSION to configure the crosswalk version for cordova 4.0 pack
- It's successfull to pack embedded mode pkg
- For cordova 4.0 shared mode: feature currently not completely support
https://crosswalk-project.org/jira/browse/XWALK-4458

[cordova] Adjust the crosswalk version config

---

tools/build/README.md
tools/build/pack.py
tools/build/pack_cordova_sample.py

- Support shared mode according cordova-plugin-crosswalk-webview
- Use crosswalk-test-suite/VERSION to configure the crosswalk version for cordova 4.0 pack
- It's successfull to pack embedded mode pkg
- For cordova 4.0 shared mode: feature currently not completely support
https://crosswalk-project.org/jira/browse/XWALK-4458

[Crosswalk-14][Cordova] Adjust the pack for crosswalk version config change

---

tools/build/pack.py

- Successful to pack cordova 4.0 pkg with Crosswalk-14 code

[Crosswalk-14][hotfix][Cordova] Define CROSSWALK_VERSION variable in pack.py

---

cordova/cordova-feature-android-tests/feature/comm.py
cordova/cordova-feature-android-tests/suite.json
cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
cordova/cordova-sampleapp-android-tests/suite.json
cordova/cordova-webapp-android-tests/suite.json
cordova/cordova-webapp-android-tests/webapp/comm.py

- Support shared mode according cordova-plugin-crosswalk-webview
- Use crosswalk-test-suite/VERSION to configure the crosswalk version for cordova 4.0 build
- For cordova 4.0 shared mode: feature currently not completely support
Impacted tests(approved): new 0, update 28, delete 0
Unit test platform: Crosswalk Project for Android 14.43.343.21
Unit test result summary: pass 28, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-4458

[Crosswalk-14][Cordova] Adjust the crosswalk version config

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkUIClientTest.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkUIClientTest.java
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithDownloadListenerActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithDownloadListenerActivity.java

-Add setUserAgentString test when XWalk downloading
-Cover the XWalkViewActivity and XWalkInitializer two ways
BUG=https://crosswalk-project.org/jira/browse/XWALK-4694

[Embeddingapi] Add setUserAgentString test when XWalk downloading

---

usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ContactExtensionActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/EchoExtensionActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/FullScreenActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/LoadAppFromManifestLayoutActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/MultiXWalkViewActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/OnCreateWindowRequestedActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/OnHideOnShowActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/OnIconAvailableOnReceivedIconActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/PauseTimersActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ResourceAndUIClientsActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ShouldOverrideUrlLoadingActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkBlockAndErrorRedirection.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkNavigationActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkPreferencesActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkVersionAndAPIVersion.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithClearCache.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithDispatchKeyEvent.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithDownloadListenerActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithLayoutActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithLoadImage.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithRedirection.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithSetLanguage.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithTransparent.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkWithInputConnection.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkWithSaveState.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ZoomInAndOutXWalkViewActivity.java

-The creation of XWalkView should be put on the onCreate()
-Modify all the embedding usecase which extends XWalkActivity
Impacted tests(approved): new 0, update 26, delete 0
Unit test result summary: pass 26, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4686

[EmbeddingApi] Move the creation of XWalkView to onCreate() method

---

apptools/apptools-android-tests/README
apptools/apptools-android-tests/apptools/Check_VersionName.html
apptools/apptools-android-tests/apptools/Keeping_Screen_On.html
apptools/apptools-android-tests/apptools/versionCode.py
apptools/apptools-android-tests/apptools/versionName.py

Impacted tests(approved): new 0, update 8, delete 0
https://crosswalk-project.org/jira/browse/XWALK-4736

[apptools-android] Update tests to test 'xwalk' prefix in the manifest for apptools android

---

cordova/cordova-feature-android-tests/feature/comm.py
cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
cordova/cordova-webapp-android-tests/webapp/comm.py

- When build cordova 4.0 app, no need to read VERSION file for crosswalk version, and VERSION file not exist in the release package, so Improve comm.py to ignore the VERSION file
Impacted tests(approved): new 0, update 28, delete 0
Unit test platform: Crosswalk Project for Android 14.43.343.21
Unit test result summary: pass 28, fail 0, block 0

[cordova][hotfix] Improve comm.py for cordova feature cases

---

tools/build/README.md
tools/build/pack_cordova_sample.py
usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/REAMDE.md
usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/index.html
usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/res/index.html
usecase/usecase-cordova-android-tests/steps/XwalkCommandLine/step.js
usecase/usecase-cordova-android-tests/tests.full.xml
usecase/usecase-cordova-android-tests/tests.xml

- Check --disable-pull-to-refresh-effect --disable-webrtc and --disable-webgl for XwalkCommandLine
- Failure Analyse: XWALK-4415
Unit test platform: Crosswalk Project for Android 15.44.382.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4792

[usecase-cordova] Add XwalkCommandLine usecase

---

webapi/tct-transitions-css3-tests/tests.full.xml
webapi/tct-transitions-css3-tests/tests.xml
webapi/tct-websocket-w3c-tests/tests.full.xml
webapi/tct-websocket-w3c-tests/tests.xml
webapi/webapi-resourcetiming-w3c-tests/tests.full.xml
webapi/webapi-resourcetiming-w3c-tests/tests.xml
webapi/webapi-usertiming-w3c-tests/tests.full.xml
webapi/webapi-usertiming-w3c-tests/tests.xml

- Add subcase support for Transitions,Resourcetiming,Websocket,Usertiming
- Format tests.full.xml by:
xmllint --format tests.full.xml > tests.full.new.xml
- Remove 'Partial' for CSS Transitions
tct-transitions-css3-tests:
Impacted tests(approved): new 108, update 0, delete 0
Unit test platform: Crosswalk for Android 15.44.384.0
Unit result summary: pass 132, fail 21, block 0
webapi-resourcetiming-w3c-tests:
Impacted tests(approved): new 26, update 0, delete 0
Unit test platform: Crosswalk for Android 15.44.384.0
Unit result summary: pass 73, fail 2, block 19
tct-websocket-w3c-tests:
Impacted tests(approved): new 237, update 0, delete 0
Unit test platform: Crosswalk for Android 15.44.384.0
Unit result summary: pass 497, fail 7, block 3
webapi-usertiming-w3c-tests:
Impacted tests(approved): …

[webapi] Add subcase support for Transitions,Resourcetiming,Websocket,Usertiming

---

usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkPreferencesActivity.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkPreferencesActivity.java

-Add use case to check PROFILE_NAME in XWalkPreferences
BUG=https://crosswalk-project.org/jira/browse/XWALK-2375

[Embeddingapi] Add use case to check PROFILE_NAME in XWalkPreferences

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkResourceClientTest.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkResourceClientTest.java

-Modify testcase name to avoid effect
BUG=https://crosswalk-project.org/jira/browse/XWALK-4758

[Embeddingapi] Modify testcase name to avoid effect

---

apptools/apptools-ios-tests/apptools/allpairs.py
apptools/apptools-ios-tests/apptools/pkgName.py
apptools/apptools-ios-tests/report/cmd.txt
apptools/apptools-ios-tests/tests.full.xml
apptools/apptools-ios-tests/tests.xml

Do not allow user to name the project as "www"
https://crosswalk-project.org/jira/browse/XWALK-4813

[apptools-iOS] Do not allow user to name the project as 'www' for apptools iOS

---

webapi/tct-flexiblebox-css3-tests/tests.full.xml
webapi/tct-flexiblebox-css3-tests/tests.xml
webapi/tct-fonts-css3-tests/tests.full.xml
webapi/tct-fonts-css3-tests/tests.xml
webapi/tct-mediacapture-w3c-tests/tests.full.xml
webapi/tct-mediacapture-w3c-tests/tests.xml
webapi/tct-text-css3-tests/tests.full.xml
webapi/tct-text-css3-tests/tests.xml

- Add subcase support in Flexiblebox,Fonts,Mediacapture,Text
- Format tests.full.xml by: xmllint --format tests.full.xml > tests.full.new.xml
Impacted tests(approved): new 0, update 24, delete 0
Unit test platform: Crosswalk for Android 16.44.392.0
Unit test result summary: pass 24, fail 0, block 0

[Crosswalk-15][webapi] Add subcase support in Flexiblebox,Fonts,Mediaediacapture,Text

---

apptools/apptools-android-tests/apptools/apk_name.py
apptools/apptools-android-tests/apptools/versionCode.py
apptools/apptools-android-tests/apptools/versionName.py

Unit result summary: pass 5, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-4870
https://crosswalk-project.org/jira/browse/XWALK-4852

[apptools-android] Default version for app should be 0.1 on apptools android

---

usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/testscripts/ContactExtension.feature
usecase/usecase-embedding-android-tests/testscripts/ContactExtensionAsync.feature
usecase/usecase-embedding-android-tests/testscripts/Extension.feature
usecase/usecase-embedding-android-tests/testscripts/ExtensionAsync.feature
usecase/usecase-embedding-android-tests/testscripts/LoadAppFromManifest.feature
usecase/usecase-embedding-android-tests/testscripts/LoadAppFromManifestAsync.feature
usecase/usecase-embedding-android-tests/testscripts/OnCreateWindowRequested.feature
usecase/usecase-embedding-android-tests/testscripts/OnCreateWindowRequestedAsync.feature
usecase/usecase-embedding-android-tests/testscripts/PauseJsTimersAsync.feature
usecase/usecase-embedding-android-tests/testscripts/Versions.feature
usecase/usecase-embedding-android-tests/testscripts/VersionsAsync.feature
usecase/usecase-embedding-android-tests/testscripts/onIconAvailableOnReceivedIcon.feature
usecase/usecase-embedding-android-tests/testscripts/onIconAvailableOnReceivedIconAsync.feature

-Add embedding usecase automation cases
-Cover sync and async ways cases
Impacted tests(approved): new 14, update 0, delete 0
Unit test result summary: pass 14, fail 0, block 0

[Embeddingapi] add embedding usecase automation cases

---

tools/build/pack.py

For embeddingapi test suites, using maven/gradle/ant build ways to build 3
packages for each test suite separatedly.
To name the packages with such build way information, this commit is required.
Signed-off-by: Zhong Qiu <zhongx.qiu@intel.com>

[tools]Apply maven/gradle/ant build way to embeddingapi

---

apptools/apptools-ios-tests/tests.full.xml
apptools/apptools-ios-tests/tests.xml
apptools/apptools-linux-tests/tests.full.xml
apptools/apptools-linux-tests/tests.xml

Due to windows tests only work on windows, so delete them

[apptools] Remove nodeunit cases for apptools

---

usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/ResourceAndUIClientsActivityAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ResourceAndUIClientsActivity.java

-Add usecase for xwalk onReceivedLoadError toast api
https://crosswalk-project.org/jira/browse/XWALK-4804

[Embeddingapi] Add usecase for xwalk onReceivedLoadError toast api

---

webapi/tct-notification-w3c-tests/notification/w3c/tag-same-manual.html

As per http://www.w3.org/TR/notifications/#showing-a-notification,
a notification in the list of pending notifications or the list of active notifications
whose tag equals notification's tag and whose origin equals notification's origin,
in the same position, close old and show new.
A example introduced http://www.w3.org/TR/notifications/#tags-example
Unit test Platform: Crosswalk Project for Android 16.44.396.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4841

[webapi] Sync notification tag same test to latest W3C

---

webapi/tct-geoallow-w3c-tests/suite.json
webapi/tct-geodeny-w3c-tests/suite.json
webapi/tct-notification-w3c-tests/suite.json

Update suite.json to support bdd for aio package in tct-geoallow-w3c-tests,
tct-geodeny-w3c-tests, tct-notification-w3c-tests
tct-geoallow-w3c-tests
Unit test platform: Crosswalk for Android 16.44.395.0
tct-geodeny-w3c-tests
Unit test platform: Crosswalk for Android 16.44.395.0
tct-notification-w3c-tests
Unit test platform: Crosswalk for Android 16.44.395.0

[webapi] Update suite.json to support bdd for aio package

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/assets/datalist.html
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkWithClearFormDataAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/assets/datalist.html
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkWithClearFormData.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase for xwalkview clearFormData API
https://crosswalk-project.org/jira/browse/XWALK-4243

[EmbeddingAPI] Add usecase for xwalkview clearFormData API

---

apptools/apptools-windows-tests/apptools/Check_VersionName.html
apptools/apptools-windows-tests/apptools/apk_name.py

https://crosswalk-project.org/jira/browse/XWALK-4915

[apptools-windows] MSI name should contain version number for apptools windows

---

apptools/apptools-android-tests/apptools/create_with_target_platform.py
apptools/apptools-android-tests/apptools/target_platforms.py
apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml
apptools/apptools-ios-tests/apptools/create_with_target_platform.py
apptools/apptools-ios-tests/apptools/target_platforms.py
apptools/apptools-ios-tests/tests.full.xml
apptools/apptools-ios-tests/tests.xml
apptools/apptools-linux-tests/apptools/create_with_target_platform.py
apptools/apptools-linux-tests/apptools/target_platforms.py
apptools/apptools-linux-tests/tests.full.xml
apptools/apptools-linux-tests/tests.xml

https://crosswalk-project.org/jira/browse/XWALK-5005
https://crosswalk-project.org/jira/browse/XWALK-5006
Due to windows platforms is only support on Microsoft Windows, so delete these cases
Impacted tests(approved): new 0, update 8, delete 3
Unit test result summary: pass 6, fail 2, block 0
https://crosswalk-project.org/jira/browse/XWALK-4665

[apptools] Windows platforms is only support on Microsoft Windows

---

usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/ResourceAndUIClientsActivityAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ResourceAndUIClientsActivity.java

-Modify test case to check onPageLoadStarted and onPageLoadStopped
BUG=https://crosswalk-project.org/jira/browse/XWALK-5017

[EmbeddingApi] Add usecase for API onPageLoadStarted & onPageLoadStopped

---

embeddingapi/embedding-api-android-tests/embeddingapi/assets/navigator.online.html
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/SetNetworkAvailableTest.java
embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v5.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/assets/navigator.online.html
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/SetNetworkAvailableTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml

-Add autocase for API setNetworkAvailable

[Embeddingapi] Add autocase for API setNetworkAvailable

---

tools/atip/README.md
tools/atip/atip/web/steps.py
tools/atip/atip/web/web.py

I should see text in "{key}" area startswith "{text}"
I should see text in "{key}" area endswith "{text}"
Unit test platform: Crosswalk Project for Android 15.44.402.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4877

[ATIP] Add new step to check startswith and endswith of test content

---

apptools/apptools-windows-tests/apptools/file_name.py
apptools/apptools-windows-tests/tests.full.xml
apptools/apptools-windows-tests/tests.xml

https://crosswalk-project.org/jira/browse/XWALK-4835
https://crosswalk-project.org/jira/browse/XWALK-4854

[apptools-windows] Files starting with '.' should not be packaged for apptools windows

---

webapi/tct-2dtransforms-css3-tests/tests.full.xml
webapi/tct-appcache-html5-tests/common/domtestcase.js
webapi/tct-appcache-html5-tests/common/media.js
webapi/tct-audio-html5-tests/common/domtestcase.js
webapi/tct-audio-html5-tests/common/media.js
webapi/tct-browserstate-html5-tests/common/domtestcase.js
webapi/tct-browserstate-html5-tests/common/media.js
webapi/tct-canvas-html5-tests/common/domtestcase.js
webapi/tct-canvas-html5-tests/common/media.js
webapi/tct-dnd-html5-tests/common/domtestcase.js
webapi/tct-dnd-html5-tests/common/media.js
webapi/tct-extra-html5-tests/common/domtestcase.js
webapi/tct-extra-html5-tests/common/media.js
webapi/tct-forms-html5-tests/common/domtestcase.js
webapi/tct-forms-html5-tests/common/media.js
webapi/tct-jsenhance-html5-tests/common/domtestcase.js
webapi/tct-jsenhance-html5-tests/common/media.js
webapi/tct-sessionhistory-html5-tests/common/domtestcase.js
webapi/tct-sessionhistory-html5-tests/common/media.js
webapi/tct-svg-html5-tests/common/domtestcase.js
webapi/tct-svg-html5-tests/common/media.js
webapi/tct-text-css3-tests/text/reference/pre-wrap-line-test-ref.html
webapi/tct-video-html5-tests/common/domtestcase.js
webapi/tct-video-html5-tests/common/media.js
webapi/webapi-nativefilesystem-xwalk-tests/nativefilesystem/NativeFileSystem_getRealPath.html
webapi/webapi-nativefilesystem-xwalk-tests/nativefilesystem/NativeFileSystem_root_base.html

Clean tail space in js with following cmd:
find ./ -type f -name "*.js"|xargs -I% grep -l ' $' % |grep -v -E 'tizen|w3c|csswg|webkit' |xargs -I% sed -i 's/ *$//g' %

[webapi] Clean tail space in js, xml and html

---

apptools/apptools-android-tests/apptools/Using_Better_Fitting_Size_Icon.html
apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml

The better fitting size icon is used as app icon
https://crosswalk-project.org/jira/browse/XWALK-5079
https://crosswalk-project.org/jira/browse/XWALK-5082

[apptools-android] Add case to test the app icon for apptools android

---

cordova/cordova-feature-android-tests/feature/comm.py
cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
cordova/cordova-webapp-android-tests/webapp/comm.py
tools/build/pack.py
tools/build/pack_cordova_sample.py
usecase/usecase-cordova-android-tests/res/comm.py
usecase/usecase-cordova-android-tests/samples/CordovaPackage4.x/res/test.py
usecase/usecase-cordova-android-tests/samples/CrosswalkVersion/res/test.py
usecase/usecase-cordova-android-tests/samples/SharedModeLibraryDownload4.x/res/test.py

- Add npm support for usecase SharedModeLibraryDownload
- Improve the pack.py, pack_cordova_sample.py script for cordova 4.x build
- Improve all the auto cordova feature cases
- Improve cordova usecase SharedModeLibraryDownload CrosswalkVersion CordovaPackage
- It's successfully to package all cordova apps
Impacted tests(approved): new 0, update 31, delete 0
Unit test platform: Crosswalk Project for Android 15.44.384.8
Unit test result summary: pass 31, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5090
BUG=https://crosswalk-project.org/jira/browse/XWALK-5003

[Cordova] Improve the python script

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java
embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v5.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml

-Add autocase to implement XWalkView.getUserAgentString
BUG=https://crosswalk-project.org/jira/browse/XWALK-4825

[EmbeddingApi] Add autocase to implement XWalkView.getUserAgentString

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithSetZOrderOnTopAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithSetZOrderOnTop.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase for transparent xwalkview test
-rename original XWalkViewWithTransparent to XWalkViewWithSetZOrderOnTop
BUG=https://crosswalk-project.org/jira/browse/XWALK-5025

[EmeddingAPI] Add usecase for transparent xwalkview test

---

tools/atip/atip/web/web.py

For textarea element, innerText will be empty string when set its content,
it's better to use innerHTML for most elements.
Unit test platform: Crosswalk Project for Android 16.45.410.0
https://crosswalk-project.org/jira/browse/XWALK-4877

[atip] Update startswith and endswith to use innerHTML

---

webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/ecmascript_simd.js
webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/ecmascript_simd_tests.js
webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/float32x4array.js
webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/int32x4array.js
webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/load_stroe_test.html
webapi/webapi-simd-nonw3c-tests/simd/float32x4.html
webapi/webapi-simd-nonw3c-tests/simd/float64x2.html
webapi/webapi-simd-nonw3c-tests/simd/int32x4.html
webapi/webapi-simd-nonw3c-tests/tests.full.xml
webapi/webapi-simd-nonw3c-tests/tests.xml

- Change type name from all lower case to first Character upper case<br>
SIMD.float32x4 -> SIMD.Float32x4<br>
SIMD.int32x4 -> SIMD.Int32x4<br>
SIMD.float64x2 -> SIMD.Float64x2<br>
- Failure Analysis:<br>
https://crosswalk-project.org/jira/browse/XWALK-4147<br>
https://crosswalk-project.org/jira/browse/XWALK-4148<br>
https://crosswalk-project.org/jira/browse/XWALK-4222<br>
Impacted tests(approved): new 0, update 1503, delete 0
Unit test result summary: pass 1459, fail 44, block 0
https://crosswalk-project.org/jira/browse/XWALK-5151

[webapi] Capitalize first letter of type name in SIMD

---

misc/webapi-noneservice-tests/pack.sh

For XWALK-4898, now use the while list for the test suites.
In the pack.sh script, we need the complete the path for the test
suites by adding the webapi parent directory.
Related to: https://crosswalk-project.org/jira/browse/XWALK-4898
Signed-off-by: Zhong Qiu <zhongx.qiu@intel.com>

Complete the webapi test suite path in pack.sh

---

stability/stability-manual-android-tests/suite.json

http://nontroppo.org/timer cannot access now,
use http://worlds-highest-website.com instead.
https://crosswalk-project.org/jira/browse/XWALK-5123

[Crosswalk-15][stability] Instead unavailable website for ScrollLargeHightPage

---

stability/stability-manual-android-tests/suite.json

http://nontroppo.org/timer cannot access now,
use http://worlds-highest-website.com instead.
BUG=https://crosswalk-project.org/jira/browse/XWALK-5123

[stability] Instead unavailable website for ScrollLargeHightPage

---

stability/stability-iterative-android-tests/README
stability/stability-iterative-android-tests/iterative/Launch_Exit_Repeatedly.py

Use sample apps instead to test launch/exit repeatly, so only get
test apps from crosswalk sampleapp binary.
BUG=https://crosswalk-project.org/jira/browse/XWALK-5125

[stability]Revise to use sample apps instead for launch/exit

---

misc/sampleapp-android-tests/sampleapp/extensionsandroid_pack.py

extensions-android/build.sh has been updated to support
package mode and arch, need to add the arguments in test case.
BUG=https://crosswalk-project.org/jira/browse/XWALK-5200

[misc] Update extension pack test to support mode and arch

---

misc/sampleapp-android-tests/sampleapp/extensionsandroid_pack.py

extensions-android/build.sh has been updated to support
package mode and arch, need to add the arguments in test case.
https://crosswalk-project.org/jira/browse/XWALK-5200

[Crosswalk-15][misc]Update extension pack test to support mode and arch

---

webapi/tct-vibration-w3c-tests/vibration/w3c/COPYING
webapi/tct-vibration-w3c-tests/vibration/w3c/cancel-when-hidden-manual.html

Remove window.open/close, default multiple windows is not
supported in Crosswalk, change test to hidden by manual.
Unit test platform: Crosswalk Project for Android 15.44.383.0
https://crosswalk-project.org/jira/browse/XWALK-4307

[Crosswalk-15][webapi]Hidden test by manual in cancel-when-hidden-manual

---

webapi/tct-vibration-w3c-tests/vibration/w3c/COPYING
webapi/tct-vibration-w3c-tests/vibration/w3c/cancel-when-hidden-manual.html

Remove window.open/close, default multiple windows is not
supported in Crosswalk, change test to hidden by manual.
Unit test platform: Crosswalk Project for Android 14.43.342.0
https://crosswalk-project.org/jira/browse/XWALK-4307

[Crosswalk-14][webapi]Hidden test by manual in cancel-when-hidden-manual

---

webapi/tct-vibration-w3c-tests/vibration/w3c/COPYING
webapi/tct-vibration-w3c-tests/vibration/w3c/cancel-when-hidden-manual.html

Remove window.open/close, default multiple windows is not
supported in Crosswalk, change test to hidden by manual.
Unit test platform: Crosswalk Project for Android 16.45.410.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4307

[webapi] Hidden test by manual in cancel-when-hidden-manual

---

webapi/tct-webaudio-w3c-tests/tests.full.xml
webapi/tct-webaudio-w3c-tests/tests.xml
webapi/tct-webaudio-w3c-tests/webaudio/analysernode_default_value.html
webapi/tct-webaudio-w3c-tests/webaudio/audiocontext_createAnalyser_return_value.html

The value of channelCount get 2 not  except 1 on Crosswalk and Chrome browser desktop,
but it gets 1 on Firefox browser desktop.
Impacted TCs num(approved): New 2, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 16.45.410.0
Unit test result summary: Pass 1, Fail 1, Blocked 0

[webapi] Add webaudio.createAnalyser return value test

---

apptools/apptools-android-tests/apptools/build.py
apptools/apptools-android-tests/apptools/build_path.py
apptools/apptools-android-tests/apptools/comm.py
apptools/apptools-android-tests/apptools/create_offline.py
apptools/apptools-android-tests/apptools/create_package.py
apptools/apptools-android-tests/apptools/create_with_target_platform.py
apptools/apptools-android-tests/apptools/manifest_apk_name.py
apptools/apptools-android-tests/apptools/manifest_build_webp.py
apptools/apptools-android-tests/apptools/manifest_display.py
apptools/apptools-android-tests/apptools/manifest_multiple_icons.py
apptools/apptools-android-tests/apptools/manifest_versionCode.py
apptools/apptools-android-tests/apptools/manifest_versionName.py

Impacted tests(approved): new 0, update 39, delete 0
Unit test result summary: pass 39, fail 0, block 0

[apptools-android] Kill adb server before clearing project for testing on Windows host

---

misc/sampleapp-android-tests/sampleapp/hangonman_pack.py
misc/sampleapp-android-tests/sampleapp/helloworld_pack.py
misc/sampleapp-android-tests/sampleapp/hexgl_pack.py
misc/sampleapp-android-tests/sampleapp/memorygame_pack.py
misc/sampleapp-android-tests/sampleapp/simd_pack.py
misc/sampleapp-android-tests/sampleapp/webgl_pack.py
misc/sampleapp-android-tests/sampleapp/webrtc_pack.py

app_root = comm.sample_src_pref + sample_src
sample_src_pref in comm.py end with '/'
sample_src don't need to start with '/'
Unit test platform: Crosswalk Project for Android 16.45.421.0

[misc] Update sample src in pack testing

---

webapi/tct-webgl-nonw3c-tests/webgl-py/khronos/COPYING
webapi/tct-webgl-nonw3c-tests/webgl-py/khronos/resources/js-test-pre.js
webapi/tct-webgl-nonw3c-tests/webgl-py/khronos/resources/unit.css
webapi/tct-webgl-nonw3c-tests/webgl-py/khronos/resources/unit.js
webapi/tct-webgl-nonw3c-tests/webgl/khronos/COPYING
webapi/tct-webgl-nonw3c-tests/webgl/khronos/resources/js-test-pre.js
webapi/tct-webgl-nonw3c-tests/webgl/khronos/resources/unit.css
webapi/tct-webgl-nonw3c-tests/webgl/khronos/resources/unit.js

Support run khronos harness of tct-webgl-nonow3c-tests automatically
on testkit-lite and web testing service
XWALK-3062, XWALK-5086
testkit-lite:
Unit test platform: Crosswalk Project for Android 16.45.421.0
Unit test result summary: pass 1591, fail 2, block 0
wts:
Unit test platform: Chrome 47
Unit test result summary: pass 14450, fail 5, block 3

[webapi] Update khronos harness for testkit and wts

---

misc/sampleapp-android-tests/sampleapp/TestApp.py
stability/stability-iterative-android-tests/iterative/TestApp.py
stability/stability-lowresource-android-tests/lowresource/TestApp.py

Update isInstalled and isRunning method to search package name exactly,
this will avoid the effect of similar package name.
Unit test platform: Crosswalk Project for Android 16.45.421.0

[misc/stability] Fix isInstalled and isRunning method

---

misc/sampleapp-android-tests/sampleapp/TestApp.py
stability/stability-iterative-android-tests/iterative/TestApp.py
stability/stability-lowresource-android-tests/lowresource/TestApp.py

Update isInstalled and isRunning method to search package name exactly,
this will avoid the effect of similar package name.
Unit test platform: Crosswalk Project for Android 15.44.383.0

[Crosswalk-15][misc/stability]Fix isInstalled and isRunning method

---

apptools/apptools-android-tests/apptools/create_package.py
apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml
apptools/apptools-windows-tests/apptools/create_package.py
apptools/apptools-windows-tests/tests.full.xml
apptools/apptools-windows-tests/tests.xml

At the moment we only have a windows release in canary.
BUG=https://crosswalk-project.org/jira/browse/XWALK-5555

[apptools] Add tests to test build project without channel for apptools

---

apptools/apptools-android-tests/apptools/init_manifest.py
apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml
apptools/apptools-windows-tests/apptools/init_manifest.py
apptools/apptools-windows-tests/tests.full.xml
apptools/apptools-windows-tests/tests.xml

https://crosswalk-project.org/jira/browse/XWALK-5562

[apptools] Add tests to test init manifest with platforms for apptools

---

apptools/apptools-android-tests/apptools/init_manifest.py
apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml
apptools/apptools-windows-tests/apptools/init_manifest.py
apptools/apptools-windows-tests/tests.full.xml
apptools/apptools-windows-tests/tests.xml

BUG=https://crosswalk-project.org/jira/browse/XWALK-5442

[apptools] Add tests to test init manifest with package-id for apptools

---

webapi/webapi-webspeech-w3c-tests/webspeech/SpeechRecognitionEvent_emma-manual.html

https://github.com/crosswalk-project/blink-crosswalk/blob/master/LayoutTests/fast/speech/scripted/speechrecognition-basics.html
test SpeechRecognitionEvent.emma attribute return null,
but spec(https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html#speechreco-event) defines
"all implementations must expose a valid XML document complete with EMMA namespace" for emma attribute.
Unit test Platform: Crosswalk Project for Android 14.43.347.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5162

[Crosswalk-14][webapi] Update SpeechRecognitionEvent emma test

---

apptools/apptools-android-tests/apptools/build.py

https://crosswalk-project.org/jira/browse/XWALK-3779

[apptools-android] Update tests to remove directory armeabi-v7a/ for apptools android

---

webapi/tct-flexiblebox-css3-tests/flexiblebox/CSS3FlexBox_align-self.html
webapi/tct-flexiblebox-css3-tests/flexiblebox/CSS3FlexBox_initial_value.html
webapi/tct-flexiblebox-css3-tests/tests.full.xml
webapi/tct-flexiblebox-css3-tests/tests.xml

- justify-content property got pass result
- align-self got fail  when then flex item has no parent
Impacted TCs num(approved): New 2, Update 1, Delete 0
Unit test Platform: Crosswalk Project for Android 17.45.429.0
Unit test result summary: Pass 1, Fail 2, Blocked 0
https://crosswalk-project.org/jira/browse/XWALK-3227

[webapi] Update flexiblebox tests

---

tools/build/README.md
tools/build/build_cordova.py
tools/build/pack_cordova_sample.py
usecase/usecase-cordova-android-tests/samples/SetBackgroundColor/REAMDE.md
usecase/usecase-cordova-android-tests/samples/SetBackgroundColor/index.html
usecase/usecase-cordova-android-tests/steps/SetBackgroundColor/step.js
usecase/usecase-cordova-android-tests/tests.full.xml
usecase/usecase-cordova-android-tests/tests.xml

- Although the case is pass, the usecase-cordova-android-tests can't be packed with Crosswalk-16.45.421.1 or can't be launched with Crosswalk-17.45.432.0 because of XWALK-5092 and XWALK-5700
Unit test platform: Crosswalk Project for Android 16.45.421.1
https://crosswalk-project.org/jira/browse/XWALK-5112

[Cordova] Add setBackgroundColor usecase

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/assets/window_close_js.html
usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_on_javascript_close_window_async.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/client/XWalkViewWithOnJavascriptCloseWindowAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/assets/window_close_js.html
usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_on_javascript_close_window.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/client/XWalkViewWithOnJavascriptCloseWindow.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase for XWalkUIClient onJavascriptCloseWindow API
BUG=https://crosswalk-project.org/jira/browse/XWALK-5102

[EmbeddingAPI] Add usecase for XWalkUIClient onJavascriptCloseWindow API

---

usecase/usecase-embedding-android-tests/webviewtest/AndroidManifest.xml
usecase/usecase-embedding-android-tests/webviewtest/assets/fullscreen_enter_exit.html
usecase/usecase-embedding-android-tests/webviewtest/assets/navigate.html
usecase/usecase-embedding-android-tests/webviewtest/assets/open_file.html
usecase/usecase-embedding-android-tests/webviewtest/assets/openedWindow.html
usecase/usecase-embedding-android-tests/webviewtest/assets/window_create_open.html
usecase/usecase-embedding-android-tests/webviewtest/assets/window_icon.html
usecase/usecase-embedding-android-tests/webviewtest/res/layout/activity_with_webview_clear_cache.xml
usecase/usecase-embedding-android-tests/webviewtest/res/layout/activity_with_webview_on_received_icon.xml
usecase/usecase-embedding-android-tests/webviewtest/res/layout/activity_with_webview_onshow_file_chooser.xml
usecase/usecase-embedding-android-tests/webviewtest/res/values/strings.xml
usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/README.md
usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/basic/WebViewWithClearCache.java
usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/basic/WebViewWithFullScreenActivity.java
usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/basic/WebViewWithTransparent.java
usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/client/WebViewWithOnCreateWindow.java
usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/client/WebViewWithOnReceivedIcon.java
usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/client/WebViewWithOnShowFileChooser.java
usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/client/WebViewWithShouldOverrideUrlLoading.java

-add webview usecase WebViewWithOnReceivedIcon
-add webview usecase WebViewWithOnCreateWindow
-add webview usecase WebViewWithFullScreenActivity
-add webview usecase WebViewWithShouldOverrideUrlLoading
-add webview usecase WebViewWithTransparent
-add webview usecase WebViewWithClearCache
-add webview usecase WebViewWithOnShowFileChooser
Impacted tests(approved): new 7, update 0, delete 0
https://crosswalk-project.org/jira/browse/XWALK-5057

[EmbeddingAPI] Add usecase of WebView for xwalkview reference

---

webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/ecmascript_simd_tests.js
webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/load_stroe_test.html
webapi/webapi-simd-nonw3c-tests/simd/float32x4.html
webapi/webapi-simd-nonw3c-tests/simd/float64x2.html
webapi/webapi-simd-nonw3c-tests/simd/int32x4.html

Crosswalk have added extractLane and replaceLane for SIMD.Float32x4, SIMD.Int32x4
(https://github.com/crosswalk-project/v8-crosswalk/pull/118), so there are some changes
for SIMD.
-  m.x/y/z/w are changed to SIMD.XXXX.extractLane(m, 0/1/2/3)
-  m.withX/Y/Z/W are changed to SIMD.XXXX.replaceLane(m, 0/1/2/3, value)
Impacted TCs num(approved): New 0, Update 1069, Delete 0
Unit test Platform: Crosswalk Project for Android 17.45.437.0
Unit test result summary: Pass 1459, Fail 44, Blocked 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5731

[webapi] Update SIMD tests

---

tools/build/utils.py

When packing cordova test suites, the .git direcotry of a cordova plugin
is offen included to the zip package. This may take a lot of disk space.
Remove the .git directory to reduce the size of cordova packages.
Related to: XWALK-5767

Remove the .git directory to reduce the size

---

apptools/apptools-android-tests/apptools/Manifest_Background_Color.html
apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml

BUG=https://crosswalk-project.org/jira/browse/XWALK-5793

[apptools-android] Add tests to test manifest field background_color for apptools android

---

apptools/apptools-android-tests/apptools/Custom_Icon_Splash_Screen.html
apptools/apptools-android-tests/apptools/Default_Splash_Screen.html
apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml

BUG=https://crosswalk-project.org/jira/browse/XWALK-5558

[apptools-android] Add tests to test default splash screen for apptools android

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkSettingTest.java
embeddingapi/embedding-api-android-tests/suite.json
embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v5.xml
embeddingapi/embedding-api-android-tests/tests_v6.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkSettingTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/suite.json
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v6.xml

-Create new v6 test & modify related xml files
Impacted tests(approved): new 0, update 12, delete 0

[EmbeddingAPI] Move XWalkSettingTest to new v6 test

---

cordova/cordova-sampleapp-android-tests/sampleapp/GoogleMapsPlugin.html
cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/COPYING
cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/REAMDE.md
cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/google-maps-plugin.py
cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/index.html
cordova/cordova-sampleapp-android-tests/suite.json
cordova/cordova-sampleapp-android-tests/tests.4.x.xml
cordova/cordova-sampleapp-android-tests/tests.full.xml

- Set z order of web view with the preference xwalkZOrderOnTop
- Cordova GoogleMaps plugin for Android
- Fail Analyse: <br/>
XWALK-5869 xwalkZorderOnTop does not make webview in top level.<br/>
XWALK-5868 ANIMATABLE_XWALK_VIEW is not false by default
Unit test platform: cordova-plugin-crosswalk-webview
BUG=https://crosswalk-project.org/jira/browse/XWALK-5779

[cordova] Add tests for googlemaps plugin

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingSetInitialPageScaleAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingSetInitialPageScale.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase for XWalkView Setting API setInitialPageScale
https://crosswalk-project.org/jira/browse/XWALK-5423

[EmbeddingAPI] Add usecase for XWalkView Setting API setInitialPageScale

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_capture_bitmap_async.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/basic/XWalkViewWithCaptureBitmapAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_capture_bitmap_async.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/basic/XWalkViewWithCaptureBitmapAsync.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase for XWalkView API captureBitmapAsync
BUG=https://crosswalk-project.org/jira/browse/XWALK-5880

[EmbeddingAPI] Add usecase for XWalkView API captureBitmapAsync

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_on_touch_listener_async.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/misc/XWalkViewWithOnTouchListenerAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_on_touch_listener.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/misc/XWalkViewWithOnTouchListener.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase for XWalkView API setOnTouchListener
BUG=https://crosswalk-project.org/jira/browse/XWALK-5884

[EmbeddingAPI] Add usecase for XWalkView API setOnTouchListener

---

tools/build/pack_deb.py

Update the correct file path of .deb files when packing the test suites
of Crosswalk for Linux.
Related to: XWALK-5783

Update the correct .deb file path for deb packages

---

usecase/usecase-wrt-linux-tests/samples/IconDisplay/README.md
usecase/usecase-wrt-linux-tests/samples/IconDisplay/index.html
usecase/usecase-wrt-linux-tests/steps/IconDisplay/step.js
usecase/usecase-wrt-linux-tests/tests.full.xml
usecase/usecase-wrt-linux-tests/tests.xml

Unit test platform: Crosswalk for Linux 15.44.384
Icon specified in the command line is not shown in taskbar
BUG=https://crosswalk-project.org/jira/browse/XWALK-4764

[usecase-linux] Add usecase for Icon Display

---

cordova/cordova-sampleapp-android-tests/tests.4.x.xml
tools/build/README.md
tools/build/pack_cordova_sample.py

- It's fine to pack cordova 4.x privateNotes
Unit test platform: Crosswalk Project for android 17.46.447.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5866

[Cordova] Add Cordova4.x support for AppSecurityApi cases

---

cordova/cordova-sampleapp-android-tests/tests.4.x.xml
tools/build/README.md
tools/build/pack_cordova_sample.py

- It's fine to pack cordova 4.x privateNotes
Unit test platform: Crosswalk Project for android 17.46.447.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5866

[Crosswalk-16][Cordova] Add Cordova4.x support for AppSecurityApi cases

---

tools/build/pack_windows.py

- It's fine to pack usecase-wrt-windows-tests

[Windows][hotfix] Remove the msi file after copy it to opt directory to avoid to get a wrong msi

---

usecase/usecase-wrt-android-tests/suite.json

- The test ExtensionPermission has been removed in pr crosswalk-project#3128,
but it was not removed in pr crosswalk-project#3071.
Impacted TCs num(approved): New 0, Update 0, Delete 1

[usecase]Remove tests ExtensionPermission from suite.json

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/assets/favicon.html
usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_get_favicon_async.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/basic/XWalkViewWithGetFaviconAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/assets/favicon.html
usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_get_favicon.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/basic/XWalkViewWithGetFavicon.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase for XWalkView API getFavicon
BUG=https://crosswalk-project.org/jira/browse/XWALK-5420

[EmbeddingAPI] Add usecase for XWalkView API getFavicon

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTest.java
embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v6.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v6.xml

-Add autocase for XWalkView API getFavicon
https://crosswalk-project.org/jira/browse/XWALK-5420

[EmbeddingAPI-autocase] Add autocase for XWalkView API getFavicon

---

tools/build/build_android.py

Fix a bug when there is no "CROSSWALK_APP_TOOLS_CACHE_DIR" setted in os
environment.

[pack-script] Set default value for crosswalk-version

---

webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/ecmascript_simd_tests.js
webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/load_stroe_test.html
webapi/webapi-simd-nonw3c-tests/simd/float32x4.html
webapi/webapi-simd-nonw3c-tests/simd/float64x2.html
webapi/webapi-simd-nonw3c-tests/simd/int32x4.html

Crosswalk 16 has implemented extractLane, replaceLane in crosswalk-project/v8-crosswalk#122.
There are some changes:
- SIMD.XXXX.x/y/z/w -> SIMD.XXXX.extractLane(m, 0/1/2/3)
- SIMD.XXXX.withX/Y/Z/W(m, value) -> SIMD.XXXX.replaceLane(m, 0/1/2/3, value)
Impacted TCs num(approved): New 0, Update 1069, Delete 0
Unit test result summary: Pass 1459, Fail 44, Blocked 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5731

[Crosswalk-16][webapi] Update SIMD tests

---

usecase/usecase-wrt-android-tests/suite.json

Add app-name property for all the subapp to avoid packing errors.
Fix a JSON format error.
Related to: https://crosswalk-project.org/jira/browse/XWALK-6058

[usecase-wrt]Update suite.json for packing

---

misc/sampleapp-android-tests/testscripts/memorygame_appFunction.feature

https://github.com/crosswalk-project/crosswalk-demos/tree/master/MemoryGame has changed its title to "Memory Cards for Older Kids".
BUG=https://crosswalk-project.org/jira/browse/XWALK-5958

[misc] Update MemoryGame title in memorygame_appFunction.feature

---

usecase/usecase-webapi-xwalk-tests/manifest.json
usecase/usecase-webapi-xwalk-tests/suite.json
usecase/usecase-wrt-android-tests/samples/OpenFile/res/manifest.json
usecase/usecase-wrt-android-tests/samples/PermissionApiContacts/res/manifest.json

- Add permissions:</br>
CAMERA</br>
MODIFY_AUDIO_SETTINGS</br>
RECORD_AUDIO</br>
ACCESS_FINE_LOCATION</br>
VIBRATE</br>
CHANGE_WIFI_STATE</br>
CHANGE_NETWORK_STATE</br>
BILLING</br>
READ_EXTERNAL_STORAGE</br>
WRITE_EXTERNAL_STORAGE</br>
READ_CONTACTS</br>
WRITE_CONTACTS</br>
- Update xwalk_permissions to xwalk_android_permissions
- Update xwalk_version to xwalk_app_version
- Failure Analysis:
Not find permissions for Notifications and Midi SysEx.
Unit test result summary: pass 9, fail 1, block 0
https://crosswalk-project.org/jira/browse/XWALK-6092

[usecase] Add permissions in manifest.json

---

misc/sampleapp-android-tests/sampleapp/comm.py
misc/sampleapp-android-tests/sampleapp/extensionsandroid_pack.py

- Crosswalk-16 branch need to be tested with Sampleapp sourcecode for Crosswalk-16
- Support 64bit android testing
- XWALK-5742 sampleapp switch function fail in 64bit android
Impacted TCs num(approved): New 0, Update 83, Delete 0
Unit test Platform: Android Crosswalk Canary 16.45.421.19-64bit
Android test result summary: Pass 78, Fail 5, Block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5818

[Crosswalk-16][misc] Update sampleapp android to support 64bit

---

wrt/wrt-securitymanu-android-tests/testapp/permission_field_contacts_tests/manifest.json
wrt/wrt-securitymanu-android-tests/testapp/permission_field_geolocation_tests/manifest.json
wrt/wrt-securitymanu-android-tests/testapp/permission_field_messaging_tests/manifest.json

- permission definition changed by app tools:</br>
READ_CONTACTS</br>
WRITE_CONTACTS</br>
READ_SMS</br>
READ_PHONE_STATE</br>
RECEIVE_SMS</br>
SEND_SMS</br>
WRITE_SMS</br>
https://crosswalk-project.org/jira/browse/XWALK-6092

[wrt] Update permissions in manifest.json

---

wrt/wrt-security-android-tests/README.md
wrt/wrt-security-android-tests/security/comm.py
wrt/wrt-security-android-tests/security/permissiontest.py
wrt/wrt-security-android-tests/suite.json
wrt/wrt-security-android-tests/testapp/permission_field_chinese_tests/manifest.json
wrt/wrt-security-android-tests/testapp/permission_field_noapi_tests/manifest.json
wrt/wrt-security-android-tests/testapp/permission_field_null_tests/manifest.json
wrt/wrt-security-android-tests/testapp/permission_field_splite_tests/manifest.json

- Replace make_apk.py by app tools
- Support 64bit
- Failure analysis:
XWALK-6016 Build both x86 and arm apk using crosswalk-pkg with "--targets=x86"
Unit test platform: Crosswalk Project for Android 18.46.458.0
Unit test result summary: pass 2, fail 2, block 0
https://crosswalk-project.org/jira/browse/XWALK-5737

[wrt] Update tests using make_apk.py by app tools

---

usecase/usecase-webapi-xwalk-tests/samples/SetCookie/REAMDE.md
usecase/usecase-webapi-xwalk-tests/samples/SetCookie/index.html
usecase/usecase-webapi-xwalk-tests/samples/SetCookie/res/headers.cgi
usecase/usecase-webapi-xwalk-tests/samples/SetCookie/res/iframe.html
usecase/usecase-webapi-xwalk-tests/steps/SetCookie/step.js
usecase/usecase-webapi-xwalk-tests/suite.json
usecase/usecase-webapi-xwalk-tests/tests.android.xml
usecase/usecase-webapi-xwalk-tests/tests.full.xml

The XMLHttpRequest API need docroot for usecase in tinyweb, it is blocked by
https://crosswalk-project.org/jira/browse/XWALK-5905.
Unit test platform: Crosswalk Project for Android 18.46.455.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5985

[usecase] Add Set-Cookie test

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkResourceClientTest.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkResourceClientTestAsync.java

-Fix the testOnLoadStartedWithLocalUrl case bug
BUG=https://crosswalk-project.org/jira/browse/XWALK-3508

[EmbeddingAPI-autocase] Fix the testOnLoadStartedWithLocalUrl case bug

---

usecase/usecase-embedding-android-tests/embeddingapi-silentdownload-lzma/res/values/strings.xml
usecase/usecase-embedding-android-tests/inst.apk.py

-fix inst.py command bug
BUG=https://crosswalk-project.org/jira/browse/XWALK-6089

[EmbeddingAPI] fix inst.py command bug

---

apptools/apptools-android-tests/apptools/Ant_Path_With_Whitespace.html
apptools/apptools-android-tests/apptools/comm.py
apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml

BUG=https://crosswalk-project.org/jira/browse/XWALK-5894

[apptools-android] Add tests to test whitespace in path to apache ant for apptools android

---

tools/build/README.md
tools/build/build_cordova.py
tools/build/pack_cordova_sample.py

- It's fine to pack cordova app
- Fail Analyse:XWALK-6159/2648/2233/4415
Impacted tests(approved): new 0, update 140, delete 0
Unit test platform: Crosswalk Project for android 17.46.448.5
Unit test result summary: pass 54, fail 86, block 0
https://crosswalk-project.org/jira/browse/XWALK-5430

[Cordova] Add 64 bit support for cordova pack

---

apptools/apptools-android-tests/apptools/CI/crosswalk_pkg_basic.py

https://crosswalk-project.org/jira/browse/XWALK-6016
Unit test result summary: pass 9, fail 1, block 0

[apptools-android] Remove the duplicated module for apptools android

---

apptools/apptools-android-tests/apptools/Manifest_ContactExtension.html
apptools/apptools-android-tests/apptools/create_package.py
apptools/apptools-android-tests/testapp/extension_permission/manifest.json

https://crosswalk-project.org/jira/browse/XWALK-5825

[apptools-android] Add tests to test build external extensions without .js file for apptools android

---

usecase/usecase-webapi-xwalk-tests/tests.windows.xml

Impacted tests(approved): new 0, update 0, delete 2
Unit test platform: Crosswalk Project for Windows 18.46.468.0
Unit test result summary: pass 0, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-6194

[Windows] Drop WebCL, Vibration related tests from usecase

---

tools/atip/atip/web/steps.py
tools/atip/atip/web/web.py

Verified steps with bdd tests in usecase-webapi-xwalk-tests and web api test suites,  steps work properly except @step(u'I should see an alert with text "{text}"') and @step(u'I go to frame "{key}"')
BUG=https://crosswalk-project.org/jira/browse/XWALK-6105

[atip-windows] Update atip to support windows platform

---

usecase/usecase-webapi-xwalk-tests/samples/IAPXiaomiStore/REAME.md

Add an instruction of embedding "MiGameCenterSDKService.apk" before building
sub app IAPXiaomiStore to README

[usecase-webapi] Add an instruction to README

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkResourceClientTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTest.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkResourceClientTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTestAsync.java

-Modify related embeddingAPI autocase about bug 6252
BUG=https://crosswalk-project.org/jira/browse/XWALK-6252

[EmbeddingAPI] Modify related embeddingAPI autocase about bug 6252

---

usecase/usecase-cordova-android-tests/res/comm.py
usecase/usecase-cordova-android-tests/samples/CrosswalkVersion/res/test.py

- Download and install 64 bit crosswalk canary aar by itself
Unit test platform: Crosswalk Project for android 19.48.483.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6301

[Cordova] Support to download and install 64 bit crosswalk canary aar by itself

---

tools/atip/tests/environment.py
tools/atip/tools/set_env.py
tools/resources/bdd/data.conf

- Update environment set up script to python version in order to support variable
platforms
MEMO8 PAD:
webapi-devicecapabilities-w3c-tests:
Impacted TCs num(approved): New 0, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 18.46.471.0
In windows platform, process of bdd tests also works normally

[atip] Update environment set up script to support variable platforms

---

webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceAcceleration_attributes_readonly.html
webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceAcceleration_attributes_test.html
webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceMotionEvent_attributes_readonly.html
webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceMotionEvent_attributes_test.html
webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceOrientationEvent_attributes_readonly.html
webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceOrientationEvent_attributes_test.html
webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceRotationRate_attributes_basic.html
webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceRotationRate_attributes_test.html
webapi/tct-deviceorientation-w3c-tests/tests.full.xml
webapi/tct-deviceorientation-w3c-tests/tests.xml

- Update attribute init value according XWALK-2460 comment.
- Fix timeout still execute issue when tests finished in Windows
Impacted tests(approved): new 0, update 40, delete 0
Unit test platform: Crosswalk Project for Windows 17.45.426.0
Unit test result summary: pass 36, fail 4, block 0
Impacted tests(approved): new 0, update 40, delete 0
Unit test result summary: pass 40, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-5634

[Crosswalk-18][webapi] Fix timeout issue in DeviceOrientation for Windows

---

tools/resources/testharness/README.md
tools/resources/testharness/testharness.js
tools/resources/testharness/testharnessreport.js

https://github.com/w3c/testharness.js/commit/eaa4c5f793f07e2dc6edbeddb3d5bb6275ebd580
$ git log --no-merges --oneline cf0b67dff57c3140c882b1ffd2b5f4c7adc2ba44..head testharness.js
shows these changes since last sync:
5423ec7 Issue #179: Fix step_timeout
7e9a45d Reinstate InUseAttributeError.
e8f43ce Fix #59: stop cross-origin objects from throwing in harness when creating failed assertion messages.
f54f26e Allow using assert_inherits with function objects.
ed8c5a4 Add [test.]step_timeout function.
3cfb463 braces
4abfeec Fix handling of assertions in workers
e19ed06 Fix potential infinite loop in AssertionError.get_stack().
2ae2785 Add ability to subscribe to only certain events via postMessage.
84094aa Set correct this value in worker structured clone function.
57fb468 Tweak comments and …

[tools] Sync testharness.js framework to latest

---

misc/webmanu-system-android-tests/tests.full.xml
misc/webmanu-system-android-tests/tests.xml

cookie test need to load web page for long time, poor network
will increase this time.
Unit test platform: Crosswalk Project for Android 17.46.448.10
BUG=https://crosswalk-project.org/jira/browse/XWALK-6052

[Crosswalk-17][misc] Add timeout for cookie upgrade test

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_clear_ssl_preferences_async.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/misc/XWalkViewWithClearSslPreferencesAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_clear_ssl_preferences.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/misc/XWalkViewWithClearSslPreferences.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase for API clearSslPreferences()
BUG=https://crosswalk-project.org/jira/browse/XWALK-6438

[EmbeddingAPI] add usecase for API clearSslPreferences()

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/ClearSslPreferenceTest.java
embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v6.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/ClearSslPreferenceTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v6.xml

-Add autocase for API clearSslPreferences()
--Cover the XWalkActivity and XWalkInitializer two ways
BUG=https://crosswalk-project.org/jira/browse/XWALK-6438

[EmbeddingAPI] add autocase for API clearSslPreferences()

---

tools/build/build_msi.py

- Support "apk-common-opts" config to pack release app
- Support "apk-ext-opt" config to pack extension app
BUG=https://crosswalk-project.org/jira/browse/XWALK-6452

[Windows] Improve the pack script

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_clear_clientcert_preferences_async.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/basic/XWalkViewWithClearClientCertPreferencesAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_clear_clientcert_preferences.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/basic/XWalkViewWithClearClientCertPreferences.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase for API clearClientCertPreferences
BUG=https://crosswalk-project.org/jira/browse/XWALK-6439

[EmbeddingAPI] Add usecase for API clearClientCertPreferences

---

webapi/tct-webgl-nonw3c-tests/suite.json

WebGL test suite can't build if the command exists, when removed it doesn't effect pass rate.

[webapi] Remove apt-cmd-opt command on Windows

---

tools/build/released_suites/Android-Platform
tools/build/released_suites/Windows-Platform

- Since the windows wrt suites have been merged,  need to add the suites to this release list
- Since the webapi-appsecurityapi-external-tests suite is ready, need to add the suite to cordova and windows release list

[windows] Update the released_suites list

---

tools/build/released_suites/Windows-Platform
usecase/usecase-webapi-xwalk-tests/tests.windows.xml
webapi/tct-mediacapture-w3c-tests/suite.json

- Since media capture is not supported, remove the media capture related cases on windows test
BUG=https://crosswalk-project.org/jira/browse/XWALK-6511

[Windows] Drop the media capture related cases from windows test

---

webapi/webapi-appsecurity-external-tests/tests.full.xml
webapi/webapi-appsecurity-external-tests/tests.xml

- Use "WebAPI/EXTERNAL/App Security API" instead of "Cordova Features/AppSecurityApi" for the component because this suite is not only for cordova, but also for windows.

[Cordova][hotfix] Update the component for webapi-appsecurity-external-tests

---

webapi/tct-sse-w3c-tests/sse-py/w3c/COPYING
webapi/tct-sse-w3c-tests/sse-py/w3c/resources/message.py

Scanning for WTS turned up a Critical Cross Site Scripting issue:
http://wts.crosswalk-project.org/tests/sse/w3c/resources/message.py?message=data%3Atest%0A%20data%0Adata%0Afoobar%3Axxx%0Ajustsometext%0A%3Athisisacommentyay%0Adata%3Atest &lt;whscheck&gt; $1&lt;whscheck&gt;
BUG=OTCIS-6641

[webapi] Fix XSS scripting in message.py

---

usecase/usecase-webapi-xwalk-tests/manifest.json

- Camera, FileReader,FileSystem also need this permission for external storage.
This permission is added default in make_apk.py before.
- Failure reason: XWALK-6430 html5 capture api always use camcoder even for images
Unit test result summary: pass 2, fail 1, block 0
https://crosswalk-project.org/jira/browse/XWALK-6032

[Crosswalk-18][usecase] Add READ_EXTERNAL_STORAGE permission

---

usecase/usecase-webapi-xwalk-tests/manifest.json

- Camera, FileReader,FileSystem also need this permission for external storage.
This permission is added default in make_apk.py before.
- Failure reason: XWALK-6430 html5 capture api always use camcoder even for images
Unit test result summary: pass 2, fail 1, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6032

[usecase] Add READ_EXTERNAL_STORAGE permission

---

wrt/wrt-packagemgtmanu-tests/wrt-packagemgt-app/testscripts/Crosswalk_WebApp_Icon_Launcher.feature

The suite name has been renamed to wrt-packagemgtmanu-tests,
but not updated in Crosswalk_WebApp_Icon_Launcher.feature.
BUG=https://crosswalk-project.org/jira/browse/XWALK-6489

[wrt] Rename package name in .feature

---

tools/build/README.md
tools/build/build_cordova.py
tools/build/pack_cordova_sample.py

- It's fine to pack helloworld, mobilespec, cordova usecase pkgs for lite mode
- It's fine to pack helloworld, mobilespec, cordova usecase pkgs for embedded mode
- It's fine to pack helloworld, mobilespec, cordova usecase pkgs for shared mode
https://crosswalk-project.org/jira/browse/XWALK-6503

[Cordova] Enable lite mode for the pack script

---

usecase/usecase-webapi-xwalk-tests/manifest.json
webapi/tct-mediacapture-w3c-tests/manifest.json

Camera need save image to external storage, add this permission for it.

[usecase] Add WRITE_EXTERNAL_STORAGE permission for Camera

---

usecase/usecase-webapi-xwalk-tests/manifest.json
webapi/tct-mediacapture-w3c-tests/manifest.json

Camera need save image to external storage, add this permission for it.

[Crosswalk-18][usecase] Add WRITE_EXTERNAL_STORAGE permission for Camera

---

cordova/cordova-feature-android-tests/feature/app_multiple_apk_false.py
cordova/cordova-feature-android-tests/feature/app_multiple_apk_true.py
cordova/cordova-feature-android-tests/feature/comm.py
cordova/cordova-feature-android-tests/feature/remotedebugging_pack.py
cordova/cordova-lite-android-tests/lite/comm.py
cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
cordova/cordova-sampleapp-android-tests/sampleapp/privateNotes_build.py
cordova/cordova-sampleapp-android-tests/sampleapp/spacedodge_build.py
cordova/cordova-webapp-android-tests/webapp/comm.py
cordova/cordova-webapp-android-tests/webapp/webapp_build.py

- Use the same comm.py for cordova feature cases
Unit test platform: Crosswalk Project for android 18.48.477.8
BUG=https://crosswalk-project.org/jira/browse/XWALK-6487
BUG=https://crosswalk-project.org/jira/browse/XWALK-6601

[Cordova] Use XWALKMULTIPLEAPK instead of xwalkMultipleApk in config.xml

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_compute_scroll_async.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/extended/XWalkViewWithComputeScrollAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_compute_scroll.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/extended/XWalkViewWithComputeScroll.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

-Add usecase for computeHorizontalScrollRange related API
BUG=https://crosswalk-project.org/jira/browse/XWALK-5417

[EmbeddingAPI] Add usecase for computeHorizontalScrollRange related API

---

usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_on_received_httpauth_request_async.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/client/XWalkViewWithOnReceivedHttpAuthRequestAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_on_received_httpauth_request.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/client/XWalkViewWithOnReceivedHttpAuthRequest.java

-Update usecase for API isFirstAttempt as part of public XWalkHttpAuthHandler
BUG=https://crosswalk-project.org/jira/browse/XWALK-6609

[EmbeddingAPI] Update usecase for API isFirstAttempt

---

tools/build/released_suites/Windows-Platform

Since webapi/tct-mediacapture-w3c-tests already remove support for
Windows before last update the gap test suites, so remove this test suite
from the list of Windows.

Correct the Windows-Platform

---

usecase/usecase-wrt-android-tests/suite.json

Tester need copy jquery.js to ApplicationlocalStorage/res/res/js/
manually everytime, let's copy it to source code when packing.
Unit test platform: Crosswalk Project for Android 19.48.503.0

[usecase-wrt] Copy jquery.js to sub app for manual packing

---

usecase/usecase-wrt-android-tests/suite.json

Tester need copy jquery.js to ApplicationlocalStorage/res/res/js/
manually everytime, let's copy it to source code when packing.

[Crosswalk-18][usecase-wrt]Copy jquery.js to sub app for manual packing

---

usecase/usecase-wrt-android-tests/samples/ApplicationlocalStorage/res/upgradeapp/index.html
usecase/usecase-wrt-android-tests/suite.json

Tester need copy jquery.js to ApplicationlocalStorage/res/res/js/
manually everytime, let's copy it to source code when packing.
Unit test platform: Crosswalk Project for Android 17.46.448.10

[Crosswalk-17][usecase-wrt]Copy jquery.js to sub app for manual packing

---

apptools/apptools-windows-tests/apptools/check_d3dcompiler_47.py
apptools/apptools-windows-tests/tests.full.xml
apptools/apptools-windows-tests/tests.xml

https://crosswalk-project.org/jira/browse/XWALK-5661
BUG=https://crosswalk-project.org/jira/browse/XWALK-6646

[apptools-windows] Add tests to test d3dcompiler_47.dll exist for apptools windows

---

cordova/cordova-feature-android-tests/feature/app_multiple_apk_false.py
cordova/cordova-feature-android-tests/feature/app_multiple_apk_true.py
cordova/cordova-feature-android-tests/feature/comm.py
cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
cordova/cordova-webapp-android-tests/webapp/comm.py

- update app_multiple_apk_false/true to make the uninstall be executed after the app has been stoped
https://crosswalk-project.org/jira/browse/XWALK-6487

[Crosswalk-18][Cordova] Use XWALKMULTIPLEAPK instead of xwalkMultipleApk

---

usecase/usecase-cordova-android-tests/res/comm.py
usecase/usecase-cordova-android-tests/samples/CordovaPackage/res/test.py
usecase/usecase-cordova-android-tests/samples/CrosswalkVersion/res/test.py
usecase/usecase-cordova-android-tests/samples/Database/res/test.py
usecase/usecase-cordova-android-tests/samples/DefaultCrosswalkVersion/index.html
usecase/usecase-cordova-android-tests/samples/SharedModeLibraryDownload/res/test.py
usecase/usecase-cordova-android-tests/steps/DefaultCrosswalkVersion/step.js

- Update sub cases which not support to pack embedded/shared
- Add copyright for python script
Unit test platform: Crosswalk Project for Android 19.49.509.0

[usecase-cordova] Add shared mode support and copyright

---

wrt/wrt-uxmanu-tests/wrt-ux-app/testscripts/Crosswalk_Lock_And_Unlock_Screen.feature
wrt/wrt-uxmanu-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_BackKey_Back.feature
wrt/wrt-uxmanu-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_BackKey_Exit.feature
wrt/wrt-uxmanu-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_HTML5_Notification.feature
wrt/wrt-uxmanu-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature
wrt/wrt-uxmanu-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Touch_Gesture_Click.feature

After M49 rebase, the dump tree of uiautomator have changed, the steps
will fail to get element.
BUG=https://crosswalk-project.org/jira/browse/XWALK-6737

[wrt] Update bdd steps for M49

---

apptools/apptools-android-tests/apptools/CI/crosswalk_pkg_basic.py
apptools/apptools-android-tests/apptools/comm.py

Tests such as `test_keep_project` were needlessly relying on app-tools'
output format to determine the directory where the build tree was
created. app-tools has changed its output months ago and the test was
failing. On Windows, this also depends on app-tools pull request #129 to
work.
Other tests were failing in 64-bits mode, either because comm.py guessed
the wrong file name for the 64-bits zip files, and several tests failed
there because by default app-tools will only produce 32-bit APKs and the
test were not passing `--targets` to it.
`invokeCrosswalkPkg()` was also added to make invoking crosswalk-pkg and
checking its return code easier. `comm.getstatusoutput()` was left
intact because other tests depend on it, but it definitely should be
rewritten.

[apptools] Fix all failing crosswalk_pkg_basic tests.

---

apptools/apptools-android-tests/apptools/CI/crosswalk_pkg_basic.py
apptools/apptools-android-tests/apptools/create_package_target.py
apptools/apptools-android-tests/apptools/crosswalk_app_targets.py

This partially reverts commit 501e71ca ("[apptools] Add extension file
for apptools").
Setting variables such as `x86Length` in the global scope is wrong, as
they will not be available in the test methods unless one uses a
`global` statement. If that is not done, we end up with failures like
this:
======================================================================
ERROR: test_target_arch (__main__.TestCrosswalkApptoolsFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
File "crosswalk_pkg_basic.py", line 312, in test_target_arch
x86Length = x86Length + 1
UnboundLocalError: local variable 'x86Length' referenced before assignment

[apptools] Stop setting the Length variables in the global scope.

---

apptools/apptools-android-tests/apptools/CI/crosswalk_pkg_basic.py
apptools/apptools-android-tests/apptools/comm.py
apptools/apptools-android-tests/tests.full.xml
apptools/apptools-android-tests/tests.xml
apptools/apptools-windows-tests/apptools/CI/crosswalk_app_basic.py
apptools/apptools-windows-tests/apptools/CI/crosswalk_pkg_basic.py
apptools/apptools-windows-tests/apptools/CI/manifest_basic.py
apptools/apptools-windows-tests/apptools/build_path.py
apptools/apptools-windows-tests/apptools/create_package.py
apptools/apptools-windows-tests/tests.full.xml
apptools/apptools-windows-tests/tests.xml

- Due to https://crosswalk-project.org/jira/browse/XWALK-4042 hasn't been resolved, so remove running release apk checkpoints
- Due to https://crosswalk-project.org/jira/browse/XWALK-6012 and https://crosswalk-project.org/jira/browse/XWALK-6524 haven't been resolved, so remove these checkpoints from CI
Impacted tests(approved): new 1, update 8, delete 0
Unit test result summary: pass 7, fail 2, block 0

[apptools] Fix all failing CI tests for apptools

---

webapi/webapi-iap-xwalk-tests/README.md
webapi/webapi-iap-xwalk-tests/suite.json

Webapi-iap-xwalk-tests currently only supports apk type when packing
the test suite. Remove the cordova and cordova-aio packing type from
suite.json.
BUG=https://crosswalk-project.org/jira/browse/CTS-732

[webapi-iap]Remove the unsupported packing type

---

tools/testsync/testsync.py
webapi/webapi-webgl-khronos-tests/webgl/khronos/conformance/more/unit.js

BUG=https://crosswalk-project.org/jira/browse/CTS-905

[windows] Fix "FAIL" result when all subcases are "PASS"

---

usecase/usecase-wrt-android-tests/tests.android.xml
usecase/usecase-wrt-android-tests/tests.full.xml

execution_type should be auto if it's a bdd/ref test.

[Crosswalk-19][usecase-wrt]Fix incorrect execution_type in tests.xml

---

usecase/usecase-webapi-xwalk-tests/manifest.json

[usecase-webapi] Fix a FingerPrint extension directory typo.
FingerPrint example is copied from demo-express, so keep the
extension directory same as manifest.json in demo-express.

[usecase-webapi] Fix a FingerPrint extension directory typo

---

.travis.yml
tools/lint/COPYING
tools/lint/README.md
tools/lint/item.py
tools/lint/lint.py
tools/lint/lint.whitelist
tools/lint/sourcefile.py
tools/lint/utils.py
tools/lint/vcs.py

- The lint tool can catch common mistakes in test files. Now it can check html, htm, xhtml, xhtm, json and xml files.
https://crosswalk-project.org/jira/browse/CTS-258

[tools] Add lint tool for catching common mistakes in test files

---

wrt/wrt-uxmanu-tests/testapp/web_feature_notification_tests/index.html

Windows
Unit test platform: Crosswalk Project for Windows 20.49.527.0
Android
Unit test platform: Crosswalk Project for Windows 20.49.527.0
BUG=CTS-1548

[Webapi] Add requestPermission method before create a notification on

---

webapi/webapi-webcl-nonw3c-tests/tests.full.xml
webapi/webapi-webcl-nonw3c-tests/tests.xml
webapi/webapi-webcl-nonw3c-tests/webcl/khronos/resources/js-test-pre.js
webapi/webapi-webgl-khronos-tests/webgl/khronos/COPYING
webapi/webapi-webgl-khronos-tests/webgl/khronos/conformance/more/unit.js
webapi/webapi-webgl-khronos-tests/webgl/khronos/resources/js-test-pre.js

[WebAPI] Make the test results' numbers of webapi-webcl-nonw3c-tests &
webapi-webgl-khronos-tests on WTS be consistent with the ones by testkit-lite.
Format webapi/webapi-webgl-khronos-tests/webgl/khronos/conformance/more/unit.js
by unix mode.
Remove subcase attribute from testcase node in
webapi/webapi-webcl-nonw3c-tests/tests.xml
webapi/webapi-webcl-nonw3c-tests/tests.full.xml .
BUG=CTS-1716

[WebAPI] Make the test results' numbers on WTS be consistent with the ones by testkit-lite.

---

cordova/cordova-api-ios-tests/tests.full.xml
cordova/cordova-api-ios-tests/tests.xml
cordova/cordova-feature-android-tests/feature/CrossWalk_Cordova_Remote_Debug_Pack.html

Replace tab space with whitespace using:
grep "  " -rl * |grep ".html"|xargs -I% sed -i 's/    /    /g' %
grep "  " -rl * |grep ".xml"|xargs -I% sed -i 's/    /    /g' %
https://crosswalk-project.org/jira/browse/CTS-1438

[lint-tool] Fix lint error in cordova tests

---

usecase/usecase-wrt-android-tests/suite.json

Default is remote debugging mode by app tools.
Another is release mode, no debug port open.

[usecase-wrt] Change remote debugging test

---

apptools/apptools-android-tests/apptools/CI/crosswalk_pkg_basic.py
apptools/apptools-android-tests/apptools/create_package_abbreviated_command.py
apptools/apptools-android-tests/apptools/manifest_xwalk_target_platforms.py
apptools/apptools-ios-tests/apptools/manifest_xwalk_target_platforms.py
apptools/apptools-linux-tests/apptools/manifest_xwalk_target_platforms.py
apptools/apptools-windows-tests/apptools/CI/crosswalk_pkg_basic.py
apptools/apptools-windows-tests/apptools/create_package.py
apptools/apptools-windows-tests/apptools/manifest_xwalk_target_platforms.py

Host setup check is now disabled by default in app-tools when not running
in an interactive terminal (APPTOOLS-303). So the build output changed,
and the string search asserts looking for which platform is build also
have to be updated.
BUG=CTS-1732

Update assertions after app-tools change

---

webapi/webapi-iap-xwalk-tests/iap/Navigator_iap_queryProductsInfo_invalidaccess.html
webapi/webapi-iap-xwalk-tests/iap/Navigator_iap_queryProductsInfo_invalidstate.html
webapi/webapi-iap-xwalk-tests/iap/Navigator_iap_queryProductsInfo_opererror.html
webapi/webapi-iap-xwalk-tests/tests.full.xml
webapi/webapi-iap-xwalk-tests/tests.xml

Add 3 IAP query test cases and modify the tests.xml and tests.full.xml accordingly.
Unit test platform: Crosswalk Project for Android 20.50.528.0
Unit test result summary: Pass 1, Fail 2, Block 0
Coverity scan result: no issue related to the 3 html files.
Related bug: XWALK-6931, XWALK-6932
BUG=https://crosswalk-project.org/jira/browse/CTS-41

[WebAPI] Add 3 IAP query test cases

---

usecase/usecase-cordova-android-tests/samples/DefaultCrosswalkVersion/index.html
usecase/usecase-cordova-android-tests/steps/DefaultCrosswalkVersion/step.js

For default crosswalk version for webview plugin, no need shared
mode testing, it will use local runtime lib verison. default version
should be testing in embedded mode only.
XWALK 6879 Webview plugin default crosswalk version is not 19
even if crosswalk is 19 in maven2/org/xwalk/xwalk_core_library_beta.
Unit test platform: WebView Plugin 1.7.0

[Crosswalk-19][usecase-cordova] Remove shared mode in DefaultCrosswalkVersion

---

usecase/usecase-cordova-android-tests/samples/DefaultCrosswalkVersion/index.html
usecase/usecase-cordova-android-tests/steps/DefaultCrosswalkVersion/step.js

For default crosswalk version for webview plugin, no need shared
mode testing, it will use local runtime lib verison. default version
should be testing in embedded mode only.
XWALK 6879 Webview plugin default crosswalk version is not 19
even if crosswalk is 19 in maven2/org/xwalk/xwalk_core_library_beta.
Unit test platform: WebView Plugin 1.7.0

[usecase-cordova] Remove shared mode in DefaultCrosswalkVersion

---

tools/build/pack.py

--pkg-version options can be used to both specify a crosswalk version
number or the absolute path of a crosswalk binary.

Update the usage information for --pkg-version option

---

webapi/webapi-iap-xwalk-tests/iap/Navigator_iap_queryProductsInfo_opererror.html

Modify the Navigator_iap_queryProductsInfo_opererror.html
Unit test platform: Crosswalk Project for Android: 20.50.532.0
The case fail due to the Google Play doesn't follow the spec.
Coverity test no issue.
Related bug: XWALK-6932

[WebAPI] Modify the test case to avoid testharness Uncaught Error

---

apptools/apptools-windows-tests/apptools/create_package.py

Unit test platform: Crosswalk Project for Windows 20.50.533.1
BUG=CTS-1760

[app-tools] Update duplicated case id in apptools-windows-tests

---

embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkViewTestAsync.java

BUG=https://crosswalk-project.org/jira/browse/CTS-1768

[Embeddingapi] Fix the v7.XWalkViewTestAsync block issue

---

embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkViewTestAsync.java

BUG=https://crosswalk-project.org/jira/browse/CTS-1768

[Crosswalk-20][Embeddingapi] Fix the v7.XWalkViewTestAsync block issue

---

webapi/tct-webaudio-w3c-tests/tests.full.xml
webapi/tct-webaudio-w3c-tests/tests.xml
webapi/tct-webaudio-w3c-tests/webaudio/offlineaudiocontext_length.html
webapi/tct-webaudio-w3c-tests/webaudio/offlineaudiocontext_length_exists.html

Chromium 51 add the length attribute.
add test cases to check length attribute exist, is readonly and the value is same as the the value in the constructor
Imapcted tests(approved): new 3, update 0, delete 0
Unit test platform: Crosswalk Project for Android 21.51.541.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1777

[WebAPI] Add web audo test cases for chromium 51

---

webapi/webapi-webcl-nonw3c-tests/webcl/khronos/conformance/functionalityTesting/buildingAndRunning/setArg_basic.html

Unit test platform: Crosswalk Project for Android 20.50.533.0
Unit fail reason: sync the test case to latest. The test case fail because Crosswalk doesn't support WebCL completely.
BUG=https://crosswalk-project.org/jira/browse/CTS-1767

Resolve crash problem caused by WebCLKernel_setArg_basic

---

.travis.yml

Update Python setuptools so the Travis-CI will not fail to
install some recent Python packages.

[lint] Update setuptools for Travis-CI

---

tools/atip/atip/android/steps.py
wrt/wrt-uxmanu-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature

in clicking app from task manager between Xiaomi Pad2 and other devices
Unit test platform: [Xiaomi Pad2][Memo8]
BUG=https://crosswalk-project.org/jira/browse/CTS-150

[ATIP] Add new step to fix incompatibility issue

---

embeddingapi/embedding-asyncapi-android-tests/embeddingapi/AndroidManifest.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/asynctest/v6/ShouldInterceptLoadRequestTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestContentProvider.java
tools/build/pack.py

BUG=https://crosswalk-project.org/jira/browse/CTS-1784

[Embeddingapi] Fix the testNotCalledForExistingContentUrl fail issue

---

cordova/cordova-feature-android-tests/feature/comm.py
cordova/cordova-lite-android-tests/lite/comm.py
cordova/cordova-lite-android-tests/res/util.py
cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/google-maps-plugin.py
cordova/cordova-webapp-android-tests/webapp/comm.py
usecase/usecase-cordova-android-tests/res/comm.py
usecase/usecase-cordova-android-tests/samples/CordovaPackage/res/test.py
usecase/usecase-cordova-android-tests/samples/Database/res/test.py
usecase/usecase-cordova-android-tests/samples/DefaultCrosswalkVersion/index.html

BUG=https://crosswalk-project.org/jira/browse/CTS-1831

[Cordova] Upgrade the value of minSdkVersion parameter from 14(default) to 16 when building cordova tests.

---

cordova/cordova-lite-android-tests/lite/comm.py

Restore minSdkVersion changes for Cordova Lite tests in https://github.com/crosswalk-project/crosswalk-test-suite/pull/3702, keep using minSdkVersion=14, because Crosswalk lite still use Crosswalk 17 as default version, and minSdkVersion=16 is effective from Crosswalk 20.
https://crosswalk-project.org/jira/browse/CTS-1831

[Cordova] Restore minSdkVersion to 14 for Cordova Lite tests

---

tools/build/pack_cordova_sample.py

Fix the cca build that can't recoginzed --minSdkVersion=16.
The solution for cca build is to use option --android-minSdkVersion=16
BUG=https://crosswalk-project.org/jira/browse/XWALK-7101

[release] Fix cca build issue with --minSdkVersion=16

---

tools/build/pack_cordova_sample.py

Cca application build can't read the correct Crosswalk version in
the project config.xml. Before we made a workaround to hack the
xwalk.gradle of cordova-plugin-crosswalk-webview. Now we add a
command line option to fix this issue.
Relate to: https://crosswalk-project.org/jira/browse/CTS-1834

[cca-release] Make cca build can recognize correct Crosswalk version

---

tools/build/build_cordova.py
tools/build/pack_cordova_sample.py

Bug XWALK-7083 has been fixed in the cordova-plugin-crosswalk-webview.
So remove the workaround in the scripts.

[release] Remove the workaround of XWALK-7083

---

cordova/cordova-feature-android-tests/feature/comm.py
cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/google-maps-plugin.py
cordova/cordova-webapp-android-tests/webapp/comm.py
usecase/usecase-cordova-android-tests/res/comm.py
usecase/usecase-cordova-android-tests/samples/CordovaPackage/res/test.py
usecase/usecase-cordova-android-tests/samples/Database/res/test.py
usecase/usecase-cordova-android-tests/samples/DefaultCrosswalkVersion/index.html

Since bug CTS-1831 has been fixed by cordova-plugin-crosswalk-webview supporting minSdkVersion to be 16 as default,
no need workaround to add minSdkVersion parameter for cordova build/run commands.
@haoxli PTAL

[Cordova] Remove minSdkVersion parameter.

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkSettingTest.java
embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v7.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/asynctest/v7/XWalkSettingTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml

Test APIs:
set/getCacheMode
set/getBlockNetworkLoads
Unit test platform: Crosswalk for Android 21.51.548.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1822

[Embeddingapi] Add tests for setCacheMode API in XWalkSettings

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkSettingTest.java
embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v7.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/asynctest/v7/XWalkSettingTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml

Test APIs:
set/getCacheMode
set/getBlockNetworkLoads
Unit test platform: Crosswalk for Android 21.51.548.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1822

[Crosswalk-21][Embeddingapi]Add tests for setCacheMode API in XWalkSettings

---

webapi/tct-geoallow-w3c-tests/geoallow/Coordinates_attribute_timeout_60000.html

Unit test platform: Crosswalk Project for Windows 20.49.525.0
BUG=CTS-1848

Update test case to reset the scope value of latitude and longitude

---

embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v7.xml
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml

There should be 11 subcases in v7.XWalkSettingTest(7 new tests
added by commit fb02b606f52c242ea9a9c202205734935d5801b4)
https://crosswalk-project.org/jira/browse/CTS-1819

[Embeddingapi] Correct subcase number in v7.XWalkSettingTest

---

embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v7.xml
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml

There should be 11 subcases in v7.XWalkSettingTest(7 new tests
added by commit 47705205d4e814212d4ffa452305ea106a1eea00)
https://crosswalk-project.org/jira/browse/CTS-1819

[Crosswalk-21][Embeddingapi] Correct subcase number in v7.XWalkSettingTest

---

embeddingapi/embedding-api-android-tests/embeddingapi/assets/create_window_1.html
embeddingapi/embedding-api-android-tests/embeddingapi/assets/create_window_2.html
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnCreateWindowRequestedHelper.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/OnCreateWindowRequestedTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkSettingTest.java
embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/util/ImagePageGenerator.java
embeddingapi/embedding-api-android-tests/inst.apk.py
embeddingapi/embedding-api-android-tests/tests.full.xml
embeddingapi/embedding-api-android-tests/tests_v7.xml
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/assets/create_window_1.html
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/assets/create_window_2.html
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/asynctest/v7/OnCreateWindowRequestedTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/asynctest/v7/XWalkSettingTestAsync.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnCreateWindowRequestedHelper.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/util/ImagePageGenerator.java
embeddingapi/embedding-asyncapi-android-tests/inst.apk.py
embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml

Test APIs:
setLoadsImagesAutomatically/getLoadsImagesAutomatically
set/getBlockNetworkImage
set/getMediaPlaybackRequiresUserGesture
set/getSupportMultipleWindows
Impacted tests(approved): new 10, update 0, delete 0
Unit test platform: Crosswalk for Android 22.52.561.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1841

[Embeddingapi] Add tests for new exposed APIs

---

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/assets/database_enable.html
usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_setting_database_enable_async.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md
usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingDatabaseEnabledAsync.java
usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
usecase/usecase-embedding-android-tests/embeddingapi/assets/database_enable.html
usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_database_enable.xml
usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingDatabaseEnabled.java
usecase/usecase-embedding-android-tests/tests.android.xml
usecase/usecase-embedding-android-tests/tests.full.xml

Test APIs:
set/getDatabaseEnable
Unit test platform: Crosswalk for Android 22.52.561.0
https://crosswalk-project.org/jira/browse/CTS-1841

[Embeddingapi] Add tests for setDatabaseEnable API in XWalkSettings

---

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewInternalTestBase.java
embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewInternalTestBase.java

After Crosswalk 23.52.564.0, class XWalkWebChromeClient has been removed,
cannot use it anymore. Remove related code.
Unit test platform: Crosswalk for Android 23.52.564.0
Unit test result summary: pass 44, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/CTS-1884

[Embeddeding] Remove useless class for Crosswalk 23.52.564.0

---

misc/webapi-service-docroot-tests/inst.iot.py
misc/webapi-service-docroot-tests/pack.sh
tools/resources/inst/inst.iot.py

Update:
1. Use abspath when scp packages
2. Add a new inst.py for docroot on IoT

Improve inst.py for IoT platform

---

misc/webapi-service-docroot-tests/inst.iot.py
misc/webapi-service-docroot-tests/pack.sh
tools/resources/inst/inst.iot.py

Update:
1. Use abspath when scp packages
2. Add a new inst.py for docroot on IoT

Cherry-pick inst.py improvement from master to Crosswalk-20

---

tools/build/build_cordova.py
usecase/usecase-cordova-android-tests/suite.json

XWALK-7368 Not able to migrate the existing webview data (localstorage/websql) to crosswalk
Unit test platform: Crosswalk Project for Android 23.52.580.0
https://crosswalk-project.org/jira/browse/XWALK-6767

[Cordova] Update Cordova default version to 1.0.0

---

tools/build/build_cordova.py
usecase/usecase-cordova-android-tests/suite.json

XWALK-7368 Not able to migrate the existing webview data (localstorage/websql) to crosswalk
Unit test platform: Crosswalk Project for Android 21.51.546.7
https://crosswalk-project.org/jira/browse/XWALK-6767

[Crosswalk-21][Cordova]Update Cordova default version to 1.0.0

---

tools/build/build_cordova.py
usecase/usecase-cordova-android-tests/suite.json

XWALK-7368 Not able to migrate the existing webview data (localstorage/websql) to crosswalk
Unit test platform: Crosswalk Project for Android 22.52.561.0
https://crosswalk-project.org/jira/browse/XWALK-6767

[Crosswalk-22][Cordova] Update Cordova default version to 1.0.0

---

webapi/webapi-sensors-w3c-tests/sensors/resources/generic-sensor-tests.js

Unit test platform: Chrome Canary 57.0.2942.0/Google Nexus 9 for Android

Add onerror event to fix browing context timeout bug.

---

webapi/webapi-sensors-w3c-tests/sensors/Accelerometer.https.html
webapi/webapi-sensors-w3c-tests/sensors/Gyroscope.https.html
webapi/webapi-sensors-w3c-tests/sensors/Magnetometer.https.html
webapi/webapi-sensors-w3c-tests/sensors/resources/generic-sensor-tests.js

Impacted tests(approved): new 10, update 12, delete 4
Unit test platform: Chrome Canary 57.0.2943.3/Google Nexus 9
Unit test result summary: pass 22, fail 0, block 0
Unit test delete reason: merge it to the case "Test that sensor reading is correct."

Modify the sensors and add timeStamp/frequency cases.
