usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_over_scroll_by_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/OverScrollXWalkView.java, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithOverScrollByAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_over_scroll_by.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/OverScrollXWalkView.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithOverScrollBy.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
Bug is reported
https://crosswalk-project.org/jira/browse/XWALK-4894
=> [usecase-embedding] Add a usecase for checking overScrollBy method

webapi/tct-webgl-nonw3c-tests/tests.full.xml, webapi/tct-webgl-nonw3c-tests/tests.xml
Impacted tests(approved): new 2, update 6, delete 0
Unit test platform: Crosswalk Project for Android 15.44.394.0
Unit test result summary: pass 1583, fail 12, block 2
https://crosswalk-project.org/jira/browse/XWALK-4888
=> [webapi] Rollback WebGL subcase changes

webapi/tct-webgl-nonw3c-tests/tests.full.xml, webapi/tct-webgl-nonw3c-tests/tests.xml
Impacted tests(approved): new 2, update 6, delete 0
Unit test platform: Crosswalk Project for Android 15.44.394.0
Unit test result summary: pass 1583, fail 12, block 2
https://crosswalk-project.org/jira/browse/XWALK-4888
=> [Crosswalk-15][webapi] Rollback WebGL subcase changes

tools/atip/atip/common/common.py, tools/atip/atip/common/steps.py
BUG=https://crosswalk-project.org/jira/browse/XWALK-4844
=> [atip] Add steps for install and uninstall app on Android

tools/build/released_suites/PLATFORMS, tools/build/released_suites/WTS, webapi/webapi-deviceadaptation-css3-tests/README, webapi/webapi-deviceadaptation-css3-tests/deviceadaptation/spec.json
And update spec link and category.
https://crosswalk-project.org/jira/browse/XWALK-577
=> Add CSS Device Adaptation test suite to testing scope

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_size_changed_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/SizeChangedXWalkView.java, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithSizeChangedAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_size_changed.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/SizeChangedXWalkView.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithSizeChanged.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
=> [usecase-embedding] Add a usecase to check if onSizeChanged works

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_visibility_changed_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/VisibilityChangedXWalkView.java, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithVisibilityChangedAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_visibility_changed.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/VisibilityChangedXWalkView.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithVisibilityChanged.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
=> [usecase-embedding] Add a usecase to check if onVisibilityChanged works

misc/webapi-noneservice-tests/webrunner/testrunner.js
https://github.com/testkit/webrunner/commit/5ae225043ee9ed0b3e7be908a3ebf3a1494e4ba6
=> [tools] Sync web runner to latest to support W3C sub-tests for noneservice

tools/build/pack_windows.py
- It's successfull to pack in windows8
BUG=https://crosswalk-project.org/jira/browse/XWALK-4904
=> [windows] Add pack script for windows tests

apptools/apptools-windows-tests/manifest.json
Impacted tests(approved): new 85, update 0, delete 0
Unit test result summary: pass 80, fail 5, block 0
=> [apptools-windows] Add icons field to web manifest for apptools windows

tools/atip/atip/android/android.py
-Modify common steps logic
-Cover wifi, airplane mode, gps steps
-Back to previous state after operation
BUG=https://crosswalk-project.org/jira/browse/XWALK-4881
=> [ATIP-android] Modify common steps logic

webapi/tct-notification-w3c-tests/notification/w3c/tag-same-manual.html
https://crosswalk-project.org/jira/browse/XWALK-4841
=> [Crosswalk-15][webapi] Sync notification tag same test to latest W3C

tools/atip/atip/web/steps.py, tools/atip/atip/web/web.py, usecase/usecase-webapi-xwalk-tests/tests.android.xml, usecase/usecase-webapi-xwalk-tests/tests.auto.xml, usecase/usecase-webapi-xwalk-tests/tests.full.xml, usecase/usecase-webapi-xwalk-tests/testscripts/BrowserState.feature, usecase/usecase-webapi-xwalk-tests/testscripts/Notifications.feature
Unit test Platform: Crosswalk Project for Android 15.44.374
=> [usecase] Autoamtion BrowserState and Notifications sample app

VERSION, cordova/cordova-feature-android-tests/feature/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/comm.py, cordova/cordova-webapp-android-tests/webapp/comm.py, misc/webapi-noneservice-tests/pack.sh, misc/webapi-service-tests/pack.sh, tools/build/pack.py, tools/build/pack_cordova_sample.py
- Crosswalk beta configuration in Webview plugin need update in packaged scripts
- For canary crosswalk app, install crosswalk in script
- Build a variety of cordova app successfully 
BUG=https://crosswalk-project.org/jira/browse/XWALK-4903
=> [cordova] update pack scripts for beta configuration

webapi/tct-2dtransforms-css3-tests/2dtransforms/csswg/reference/transform-scale-test-ref.html, webapi/tct-2dtransforms-css3-tests/2dtransforms/csswg/scale-optional-second-001-manual.html, webapi/tct-2dtransforms-css3-tests/2dtransforms/csswg/transform-scale-test-manual.html
Unit test Platform: Crosswalk Project for Android 16.44.396.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4566
BUG=https://crosswalk-project.org/jira/browse/XWALK-4567
=> [webapi] Sync 2dtransforms tests to latest W3C

webapi/tct-2dtransforms-css3-tests/2dtransforms/csswg/reference/transform-scale-test-ref.html, webapi/tct-2dtransforms-css3-tests/2dtransforms/csswg/scale-optional-second-001-manual.html, webapi/tct-2dtransforms-css3-tests/2dtransforms/csswg/transform-scale-test-manual.html
https://crosswalk-project.org/jira/browse/XWALK-4566
https://crosswalk-project.org/jira/browse/XWALK-4567
=> [Crosswalk-15][webapi] Sync 2dtransforms tests to latest W3C

usecase/usecase-embedding-android-tests/suite.json, usecase/usecase-embedding-android-tests/tests.auto.xml, usecase/usecase-embedding-android-tests/tests.full.xml
add android tests full xml auto part
=> [EmbeddingUsecase] add android tests full xml auto part

webapi/tct-csp-w3c-tests/tests.full.xml, webapi/tct-csp-w3c-tests/tests.xml
Unit test Platform: Crosswalk Project for Android 16.44.399.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4928
=> [webapi] Fix match reference cases for csp tests

VERSION, cordova/cordova-feature-android-tests/feature/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/comm.py, cordova/cordova-webapp-android-tests/webapp/comm.py, misc/webapi-noneservice-tests/pack.sh, misc/webapi-service-tests/pack.sh, tools/build/pack.py, tools/build/pack_cordova_sample.py
- Crosswalk beta configuration in Webview plugin need update in packaged scripts
https://crosswalk-project.org/jira/browse/XWALK-4903
=> [Crosswalk-15]update pack scripts for beta configuration

usecase/usecase-cordova-android-tests/extra_plugins/cordova-plugin-crosswalk-webview-tests/README.md, usecase/usecase-cordova-android-tests/extra_plugins/cordova-plugin-crosswalk-webview-tests/package.json, usecase/usecase-cordova-android-tests/extra_plugins/cordova-plugin-crosswalk-webview-tests/platforms/android/src/WebViewTest.java, usecase/usecase-cordova-android-tests/extra_plugins/cordova-plugin-crosswalk-webview-tests/plugin.xml, usecase/usecase-cordova-android-tests/extra_plugins/cordova-plugin-crosswalk-webview-tests/www/WebViewTest.js, usecase/usecase-cordova-android-tests/samples/CanGoBack/index.html, usecase/usecase-cordova-android-tests/samples/CanGoBack/js/support.js, usecase/usecase-cordova-android-tests/steps/CanGoBack/step.js, usecase/usecase-cordova-android-tests/tests.full.xml, usecase/usecase-cordova-android-tests/tests.xml
Unit test platform: Crosswalk Project for Android 16.44.391.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4175
=> [usecase-cordova] add plugin and case for webview canGoBack test

webapi/tct-csp-w3c-tests/tests.full.xml, webapi/tct-csp-w3c-tests/tests.xml
Impacted TCs num(approved): New 0, Update 8, Delete 0
Unit test Platform: Crosswalk Project for Android 16.44.399.0
Unit test result summary: Pass 8, Fail 0, Blocked 0
https://crosswalk-project.org/jira/browse/XWALK-4924
=> [webapi] Fix frame-src tests for CSP

usecase/usecase-wrt-android-tests/samples/BackgroundColor/README.md, usecase/usecase-wrt-android-tests/samples/BackgroundColor/index.html, usecase/usecase-wrt-android-tests/samples/BackgroundColor/res/index.html, usecase/usecase-wrt-android-tests/samples/BackgroundColor/res/manifest.json, usecase/usecase-wrt-android-tests/steps/BackgroundColor/step.js, usecase/usecase-wrt-android-tests/suite.json, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml
Fail BugID: XWALK-4809
BUG=https://crosswalk-project.org/jira/browse/XWALK-4856
=> [usecase] Add test for background color

wrt/wrt-coreshellmanu-android-tests/wrt-coreshell-app/testscripts/Crosswalk_Multiple_Tab_DiffPages.feature
=> [wrt] Update test steps for coreshell

wrt/wrt-coreshellmanu-android-tests/coreshellmanu/bdd/Crosswalk_Multiple_Tab_DiffPages.html, wrt/wrt-coreshellmanu-android-tests/coreshellmanu/bdd/Crosswalk_Multiple_Tab_ErrorPages.html, wrt/wrt-coreshellmanu-android-tests/coreshellmanu/bdd/Crosswalk_Multiple_Tab_LocalPages.html, wrt/wrt-coreshellmanu-android-tests/coreshellmanu/bdd/Crosswalk_Multiple_Tab_OtherPages.html, wrt/wrt-coreshellmanu-android-tests/coreshellmanu/bdd/Crosswalk_Multiple_Tab_SamePages.html
Impacted TCs num(approved): New 0, Update 5, Delete 0
Android test result summary: Pass 5, Fail 0, Block 0
=> [wrt] Update manual test steps for coreshell

usecase/usecase-webapi-xwalk-tests/testscripts/steps/steps.py
=> [usecase-webapi] Update steps.py for usecase webapi

usecase/usecase-wrt-android-tests/samples/BackgroundColor1/README.md, usecase/usecase-wrt-android-tests/samples/BackgroundColor1/index.html, usecase/usecase-wrt-android-tests/samples/BackgroundColor1/res/index.html, usecase/usecase-wrt-android-tests/samples/BackgroundColor1/res/manifest.json, usecase/usecase-wrt-android-tests/samples/BackgroundColor2/README.md, usecase/usecase-wrt-android-tests/samples/BackgroundColor2/index.html, usecase/usecase-wrt-android-tests/samples/BackgroundColor2/res/index.html, usecase/usecase-wrt-android-tests/samples/BackgroundColor2/res/manifest.json, usecase/usecase-wrt-android-tests/steps/BackgroundColor1/step.js, usecase/usecase-wrt-android-tests/steps/BackgroundColor2/step.js, usecase/usecase-wrt-android-tests/suite.json, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml
The Fail BugId: XWALK-4809
Impacted TCs num(approved): New 1, Update 1, Delete 0
Android test result summary: Pass 0, Fail 2, Block 0
=> [usecase-wrt] Add new test for backgroundcolor

apptools/apptools-android-tests/apptools/check_host.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4956
https://crosswalk-project.org/jira/browse/XWALK-4754
=> [apptools-android] Add tests to test 'check' command for apptools android

apptools/apptools-windows-tests/apptools/check_host.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
Impacted tests(approved): new 2, update 1, delete 0
https://crosswalk-project.org/jira/browse/XWALK-4949
=> [apptools-windows] Add tests to test 'check' command for apptools windows

usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/client_layout.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/ResourceAndUIClientsActivityAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/client_layout.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/ResourceAndUIClientsActivity.java
-Add usecase for the api of doUpdateVisitedHistory
https://crosswalk-project.org/jira/browse/XWALK-4739
=> [Embeddingapi] Add usecase for the api of doUpdateVisitedHistory

misc/webapi-noneservice-tests/pack.sh, misc/webapi-service-tests/pack.sh, tools/build/README.md, tools/build/pack.py, tools/build/pack_cordova_sample.py
- Update follow ﻿https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/blob/master/README.md
- Add one way to install webview plugin from npm
- It's successfull to pack cordova pkgs and all in one script can run successfully
=> [Tools] Update shared mode package method in webview plugin

misc/webapi-noneservice-tests/pack.sh, misc/webapi-service-tests/pack.sh, tools/build/README.md, tools/build/pack.py, tools/build/pack_cordova_sample.py
- Follow ﻿https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/blob/master/README.md
- Add one way to install webview plugin from npm
- It's successfull to pack cordova pkgs and all in one script can run successfully
=> [Tools][Crosswalk-15] Update shared mode package method in webview plugin

usecase/usecase-cordova-android-tests/samples/SharedModeLibraryDownload4.x/res/test.py
Unit test platform: Crosswalk Project for Android 15.44.384.7
=> [Cordova][hotfix] Fix missed common setup for SharedModeLibraryDownload

wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature
BUG=https://crosswalk-project.org/jira/browse/XWALK-4976
=> [wrt] Update test steps for uxmanu

misc/sampleapp-android-tests/tests.full.xml, misc/sampleapp-android-tests/tests.xml
This test case should be removed together with pull request #2795.
BUG=https://crosswalk-project.org/jira/browse/XWALK-5020
=> [misc] Remove test case sysapps_appFunction from .xml files

usecase/usecase-embedding-android-tests/testscripts/Versions.feature, usecase/usecase-embedding-android-tests/testscripts/VersionsAsync.feature
-Modify usecase testscript Versions feature steps
BUG=https://crosswalk-project.org/jira/browse/XWALK-5010
=> [ATIP] Modify usecase testscript Versions feature steps

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnCreateInputConnectionXWalkView.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnDrawXWalkView.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewOverrideTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v5.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnCreateInputConnectionXWalkView.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnDrawXWalkView.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewOverrideTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml
-Add autocase for API onDraw & onCreateInputConnection
=> [EmbeddingApi] Add autocase for API onDraw & onCreateInputConnection

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/RequestFocusXWalkView.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewOverrideTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v5.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/RequestFocusXWalkView.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewOverrideTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml
-Add autocase for API requestFocus
=> [Embeddingapi] Add autocase for API requestFocus

tools/atip/atip/common/steps.py, tools/atip/atip/web/web.py, tools/atip/tools/set_env.sh
Enable deepin app launch/initial function in ATIP refer to the comments
in XWALK-4721
=> [atip-linux] Enable deepin app launch/initial function in ATIP

wrt/wrt-internetstdmanu-android-tests/tests.full.xml, wrt/wrt-internetstdmanu-android-tests/tests.xml, wrt/wrt-rt-linux-tests/tests.full.xml, wrt/wrt-rt-linux-tests/tests.xml, wrt/wrt-rtcoremanu-android-tests/tests.full.xml, wrt/wrt-rtcoremanu-android-tests/tests.xml, wrt/wrt-sharedmodemanu-android-tests/tests.full.xml, wrt/wrt-sharedmodemanu-android-tests/tests.xml
- Fix duplicated test purpose issue for internetstdmanu, rt
, rtcoremanu and sharedmodemanu
=> [wrt] Fix duplicated test purpose issue

tools/atip/atip/android/android.py
-Modify atip android gps operation step
-Verifid locally on related device
BUG=https://crosswalk-project.org/jira/browse/XWALK-5027
=> [ATIP] Modify atip android gps operation step

usecase/usecase-cordova-android-tests/res/comm.py, usecase/usecase-cordova-android-tests/samples/SharedModeLibraryDownload4.x/res/test.py
Unit test platform: Crosswalk Project for Android 15.44.384.7
BUG=https://crosswalk-project.org/jira/browse/XWALK-5023
=> [usecase-cordova] fix SharedModeLibrary download crosswalk failed issue

usecase/usecase-wrt-android-tests/steps/ManifestDemo7/step.js, usecase/usecase-wrt-android-tests/suite.json, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml
https://crosswalk-project.org/jira/browse/XWALK-4963
=> [usecase] Add test for xwalk_view member in manifest file

webapi/tct-csp-w3c-tests/csp-py/csp_referrer_always.html, webapi/tct-csp-w3c-tests/csp-py/csp_referrer_default.html, webapi/tct-csp-w3c-tests/csp-py/csp_referrer_never.html, webapi/tct-csp-w3c-tests/csp-py/csp_referrer_origin.html, webapi/tct-csp-w3c-tests/csp-py/support/referrer.html, webapi/tct-csp-w3c-tests/csp/csp_referrer_always.html, webapi/tct-csp-w3c-tests/csp/csp_referrer_default.html, webapi/tct-csp-w3c-tests/csp/csp_referrer_never.html, webapi/tct-csp-w3c-tests/csp/csp_referrer_origin.html, webapi/tct-csp-w3c-tests/csp/reference/csp_referrer_always-ref.html, webapi/tct-csp-w3c-tests/csp/reference/csp_referrer_never-ref.html, webapi/tct-csp-w3c-tests/csp/reference/csp_referrer_origin-ref.html, webapi/tct-csp-w3c-tests/csp/support/referrer.html, webapi/tct-csp-w3c-tests/tests.full.xml, webapi/tct-csp-w3c-tests/tests.xml
Impacted TCs num(approved): New 4, Update 13, Delete 4
Unit test result summary: Pass 17, Fail 0, Blocked 0
https://crosswalk-project.org/jira/browse/XWALK-4924
https://crosswalk-project.org/jira/browse/XWALK-4926
https://crosswalk-project.org/jira/browse/XWALK-4927
https://crosswalk-project.org/jira/browse/XWALK-4928
=> [Crosswalk-15][webapi] Fix match reference cases for CSP

usecase/usecase-cordova-android-tests/res/comm.py, usecase/usecase-cordova-android-tests/samples/SharedModeLibraryDownload4.x/res/test.py
Unit test platform: Crosswalk Project for Android 15.44.384.7
https://crosswalk-project.org/jira/browse/XWALK-5023
=> [Cordova][Crosswalk-15] Fix SharedModeLibrary download crosswalk failed issue

usecase/usecase-wrt-android-tests/samples/Widevine/README.md, usecase/usecase-wrt-android-tests/samples/Widevine/index.html, usecase/usecase-wrt-android-tests/samples/Widevine/res/manifest.json, usecase/usecase-wrt-android-tests/steps/Widevine/step.js, usecase/usecase-wrt-android-tests/suite.json, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml
- Fail bugid: XWALK-5066
https://crosswalk-project.org/jira/browse/XWALK-5030
=> [usecase] Add test for widevine

tools/xml/xml2csv.py
Improve xml2scv.py to convert tests.full.xml without spec node successfully
=> [tools] Improve xml2scv.py for other suites

misc/sampleapp-android-tests/sampleApp_pack.sh, misc/sampleapp-android-tests/sampleapp/helloworld_pack.py
hello-world is changed from hello_world in https://github.com/crosswalk-project/crosswalk-samples/pull/28
Unit test platform: Crosswalk Project for Android 16.45.408.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5015
=> [misc] Update hello-world name

doc/Chromium_Feature_Verification_Guide.md
These typos shall be found when edit the text; but my Notepad++
doesn't work well on spell check.
=> [doc] Fix more typos

wrt/wrt-internetstdmanu-android-tests/internetstdmanu/Crosswalk_WebApp_Scheme_App.html, wrt/wrt-manifest2-android-tests/README, wrt/wrt-packertool-android-tests/README, wrt/wrt-packertool-android-tests/tests.py, wrt/wrt-packertool2-android-tests/README, wrt/wrt-packertoolmanu-android-tests/packertoolmanu/Crosswalk_Packer_Tool_Disable_Xwalk_Extensions.html, wrt/wrt-security-android-tests/README, wrt/wrt-sharedmode-android-tests/sharedmode/Crosswalk_ShareMode_Uninstall_WithAppRunning_test.sh, wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_arm_embeded.html, wrt/wrt-uxmanu-android-tests/testapp/web_hwaccelerated_video_tests/index.html, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_Lock_And_Unlock_Screen.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_BackKey_Exit.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Terminated_TaskManager.feature
Clean up tail space in README, feature, html and scripts
=> [wrt] Clean up tail space in README, feature, html and scripts

apptools/apptools-android-tests/apptools/Check_WebApp_Name.html, apptools/apptools-android-tests/apptools/manifest_name.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5022
=> [apptools-android] Add cases to test app name is from web manifest for apptools android

apptools/apptools-android-tests/README, apptools/apptools-android-tests/apptools/Check_Apk_Size.html, apptools/apptools-android-tests/apptools/build_webp.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5049
Unit test result summary: pass 4, fail 8, block 0
https://crosswalk-project.org/jira/browse/XWALK-3829
=> [apptools-android] Add case to test automatic conversion of assets for apptools android

webapi/tct-webaudio-w3c-tests/tests.full.xml, webapi/tct-webaudio-w3c-tests/webaudio/oscillatornode_type_invalid_value.html
Latest W3C spec: http://webaudio.github.io/web-audio-api/#
Unit test Platform: Crosswalk Project for Android 16.45.410.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5084
=> [webapi] Update OscillatorNode custom test for Web Audio

usecase/usecase-wrt-android-tests/steps/ManifestDemo8/step.js, usecase/usecase-wrt-android-tests/suite.json, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml
- Fail bugid: XWALK-4809
https://crosswalk-project.org/jira/browse/XWALK-4963
=> [usecase] Add test for xwalk_view

misc/sampleapp-android-tests/sampleapp/spacedodgegame_base_appFunction.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_base_icon.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_base_orientation.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_manifestorientationresize_appFunction.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_manifestorientationresize_icon.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_manifestorientationresize_orientation.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_manifestorientationscale_appFunction.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_manifestorientationscale_icon.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_manifestorientationscale_orientation.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationresize_appFunction.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationresize_icon.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationresize_orientation.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationscale_appFunction.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationscale_icon.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationscale_orientation.html, misc/sampleapp-android-tests/tests.full.xml, misc/sampleapp-android-tests/tests.xml
Failure Analysis: screen-orientation-scale fail to scale to full screen
after rotate to portrait orientation.
Impacted tests(approved): new 12, update 3, delete 0
Unit test platform: Crosswalk Project for Android 16.45.410.0
Unit test result summary: pass 14, fail 1, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4968
=> [misc] Revise manual tests for space dodge game

apptools/apptools-linux-tests/manifest.json
Impacted tests(approved): new 0, update 79, delete 0
Unit test platform: [Deepin]
Unit test result summary: pass 77, fail 2, block 0
=> [apptools-linux] Update manifest.json for apptools linux

tools/build/pack.py
- It's fine to pack release and debug mode pkg for embeddingapi cases
BUG=https://crosswalk-project.org/jira/browse/XWALK-5114
=> [Embeddingapi] Add release mode pack

usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithDownloadListenerActivityAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithDownloadListenerActivity.java
-Update usecase to implement XWalkView.getUserAgentString
BUG=https://crosswalk-project.org/jira/browse/XWALK-4825
=> [EmbeddingApi] Update usecase to implement XWalkView.getUserAgentString

stability/stability-embeddingapi-android-tests/auto/Long_Time_Navigation_Website.py, stability/stability-embeddingapi-android-tests/auto/xwalk_utils.py, stability/stability-embeddingapi-android-tests/testapp/AndroidManifest.xml, stability/stability-embeddingapi-android-tests/testapp/res/layout/view_checkbox.xml, stability/stability-embeddingapi-android-tests/testapp/res/layout/view_navigation.xml, stability/stability-embeddingapi-android-tests/testapp/src/org/xwalkview/stability/app/NavigationWebViewsActivity.java, stability/stability-embeddingapi-android-tests/testapp/src/org/xwalkview/stability/app/NavigationXWalkViewsActivity.java, stability/stability-embeddingapi-android-tests/testapp/src/org/xwalkview/stability/base/XWalkBaseNavigationActivity.java
-Add long time navigation stability test of webview & xwalkview
-Add auto running py script
=> [Stability-EmbeddingApi] Add long time navigation stability test

usecase/usecase-wrt-windows-tests/samples/PackertoolIcon/README.md, usecase/usecase-wrt-windows-tests/samples/PackertoolIcon/index.html, usecase/usecase-wrt-windows-tests/samples/VideoPlay/index.html, usecase/usecase-wrt-windows-tests/steps/PackertoolIcon/step.js, usecase/usecase-wrt-windows-tests/steps/VideoPlay/step.js, usecase/usecase-wrt-windows-tests/tests.full.xml, usecase/usecase-wrt-windows-tests/tests.xml
- Add playing video from "http://" for VideoPlay
- Failed Analyse: XWALK-4998 XWALK-4960
Unit test platform: Crosswalk Project for Windows 15.44.374.0
=> [usecase-windows] Add icon case for usecase-wrt-windows-tests

stability/stability-embeddingapi-android-tests/suite.json, stability/stability-embeddingapi-android-tests/tests.xml
-update stability tests.xml & suite.json
=> [Stability-embeddingapi] update stability tests.xml

misc/sampleapp-android-tests/testscripts/simd_appFunction.feature
Unit test platform: Crosswalk Project for Android 16.45.410.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4685
=> [misc] Increase timeout to make ftp stable in SIMD

tools/atip/README.md, tools/atip/atip/android/android.py, tools/atip/atip/android/steps.py
-add step for getting device dumped xml content
=> [ATIP] add step for getting device dumped xml

tools/atip/README.md, tools/atip/atip/web/steps.py
Unit test Platform: Crosswalk Project for Android 16.45.409.0
=> [atip] Improve steps for ATIP

tools/atip/README.md, tools/atip/atip/common/common.py, tools/atip/atip/common/steps.py
- The step can run normally
Unit test Platform: Android crosswalk-16.45.419.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4844
=> [tools-atip] Add new steps for upgrade app on android

apptools/apptools-android-tests/apptools/Manifest_Command_Line_DisableWebGL.html, apptools/apptools-android-tests/apptools/Manifest_Command_Line_EnableRemoteDebugging.html, apptools/apptools-android-tests/apptools/Manifest_Command_Line_EnableWebGL.html, apptools/apptools-android-tests/testapp/webgl_disable_tests/index.html, apptools/apptools-android-tests/testapp/webgl_enable_tests/index.html, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-4028
=> [apptools-android] Add tests to test crosswalk command line args for apptools android

tools/atip/atip/android/steps.py
=> [ATIP] Fix android swipe step bug

apptools/apptools-android-tests/apptools/create_offline.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5180
=> [apptools-android] Add tests to test offline operation for apptools android

usecase/usecase-cordova-android-tests/res/comm.py, usecase/usecase-cordova-android-tests/samples/CrosswalkVersion/res/test.py
Unit test platform: Crosswalk Project for Android 14.43.343.24
=> [Cordova][hotfix] Improve comm.py  to get lastest version according the main_version

misc/sampleapp-android-tests/sampleApp_pack.sh, misc/sampleapp-android-tests/sampleapp/comm.py, misc/sampleapp-android-tests/tests.full.xml, misc/sampleapp-android-tests/tests.xml
- Update to reference from crosswalk-samples
- Add all version of space-dodge-game
- Remove tizen-apis
=> [misc] Update sampleapp pack for corsswalk samples

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnScaleChangedHelper.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestXWalkUIClientBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkUIClientTest.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v5.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnScaleChangedHelper.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestXWalkUIClientBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkUIClientTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml
-Add autocase for embedding api setInitialScale
https://crosswalk-project.org/jira/browse/XWALK-4365
=> [EmbeddingApi] Add autocase for embedding api setInitialScale

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml
-Update androidmanifest xml to reorganize usecase ui level
task https://crosswalk-project.org/jira/browse/XWALK-5056
Impacted tests(approved): new 0, update 56, delete 0
Unit test platform: Crosswalk for Android 16.45.409.0
Unit test result summary: pass 56, fail 0, block 0
=> [EmbeddingApi] Update androidmanifest xml to reorganize usecase level

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkViewWithSetInitialScaleAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkViewWithSetInitialScale.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
-Add usecase for embedding api setInitialScale
https://crosswalk-project.org/jira/browse/XWALK-4365
=> [EmbeddingApi] Add usecase for embedding api setInitialScale

apptools/apptools-android-tests/apptools/check_target_version.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-3833
https://crosswalk-project.org/jira/browse/XWALK-5181
=> [apptools-android] Add tests to check required minimum API target version for apptools android

tools/build/build_android.py, tools/build/build_cordova.py, tools/build/build_embeddingapi.py, tools/build/build_tizen.py, tools/build/pack.py, tools/build/utils.py, tools/build/varshop.py
1. Separate the utils functions from pack.py to utils.py
2. Separate the backends in pack.py to build_*.py
BUGS=XWALK-5037 XWALK-5038 XWALK-5039
=> [pack-script] Re-construct of pack scirpts

apptools/apptools-android-tests/apptools/Manifest_Orientation_Any.html, apptools/apptools-android-tests/apptools/Manifest_Orientation_Landscape.html, apptools/apptools-android-tests/apptools/Manifest_Orientation_LandscapePrimary.html, apptools/apptools-android-tests/apptools/Manifest_Orientation_LandscapeSecondary.html, apptools/apptools-android-tests/apptools/Manifest_Orientation_Natural.html, apptools/apptools-android-tests/apptools/Manifest_Orientation_Portrait.html, apptools/apptools-android-tests/apptools/Manifest_Orientation_PortraitPrimary.html, apptools/apptools-android-tests/apptools/Manifest_Orientation_PortraitSecondary.html, apptools/apptools-android-tests/apptools/manifest_orientation.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5199
Impacted tests(approved): new 9, update 0, delete 0
Unit test result summary: pass 1, fail 8, block 0
https://crosswalk-project.org/jira/browse/XWALK-4689
=> [apptools-android] Add tests to test manifest orientation field for apptools android

cordova/cordova-feature-android-tests/feature/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/privateNotes_build.py, cordova/cordova-webapp-android-tests/webapp/comm.py, tools/build/pack_cordova_sample.py
Impacted tests(approved): new 0, update 22, delete 0
Unit test platform: Crosswalk Project for Android 16.44.406.0
Unit test result summary: pass 22, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-5098
=> [Cordova] make priveteNotes install AppSecurityApi plugin online

usecase/usecase-wrt-linux-tests/inst.deb.py, usecase/usecase-wrt-linux-tests/suite.json, usecase/usecase-wrt-linux-tests/tests.auto.xml, usecase/usecase-wrt-linux-tests/testscripts/StartURL.feature, usecase/usecase-wrt-linux-tests/testscripts/steps/steps.py
Unit test Platform: Crosswalk Project for Linux 16.45.413.0
=> [usecase-linux] Automation StartURL tests

apptools/apptools-android-tests/apptools/Manifest_Display_Fullscreen.html, apptools/apptools-android-tests/apptools/Manifest_Display_Standalone.html, apptools/apptools-android-tests/apptools/manifest_display.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml, apptools/apptools-ios-tests/apptools/Manifest_Display_Browser.html, apptools/apptools-ios-tests/apptools/Manifest_Display_Fullscreen.html, apptools/apptools-ios-tests/apptools/Manifest_Display_MinimalUi.html, apptools/apptools-ios-tests/apptools/Manifest_Display_Standalone.html, apptools/apptools-ios-tests/apptools/manifest_display.py, apptools/apptools-ios-tests/tests.full.xml, apptools/apptools-ios-tests/tests.xml, apptools/apptools-linux-tests/apptools/Manifest_Display_Browser.html, apptools/apptools-linux-tests/apptools/Manifest_Display_Fullscreen.html, apptools/apptools-linux-tests/apptools/Manifest_Display_MinimalUi.html, apptools/apptools-linux-tests/apptools/Manifest_Display_Standalone.html, apptools/apptools-linux-tests/apptools/manifest_display.py, apptools/apptools-linux-tests/tests.full.xml, apptools/apptools-linux-tests/tests.xml, apptools/apptools-windows-tests/apptools/Manifest_Display_Fullscreen.html, apptools/apptools-windows-tests/apptools/Manifest_Display_Standalone.html, apptools/apptools-windows-tests/apptools/manifest_display.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5224
Impacted tests(approved): new 27, update 1, delete 0
Unit test result summary: pass 23, fail 5, block 0
https://crosswalk-project.org/jira/browse/XWALK-5028
BUG=https://crosswalk-project.org/jira/browse/XWALK-5165
=> [apptools] Add tests to test display field value for apptools

usecase/usecase-wrt-android-tests/tests.auto.xml, usecase/usecase-wrt-android-tests/testscripts/ApplicationlocalStorage.feature
BUG=https://crosswalk-project.org/jira/browse/XWALK-4901
=> [usecase-wrt] Update test steps for ApplicationlocalStorage

apptools/apptools-sampleapp-tests/sampleapp-android/Crosswalk_Apptools_SampleApp_Spacedodgegame_Build.html, apptools/apptools-sampleapp-tests/sampleapp-deb/Crosswalk_Apptools_SampleApp_Spacedodgegame_Build_Deb.html, apptools/apptools-sampleapp-tests/sampleapp-ios/Crosswalk_Apptools_SampleApp_Spacedodgegame_Build_iOS.html, apptools/apptools-sampleapp-tests/sampleapp-windows/Crosswalk_Apptools_SampleApp_Spacedodgegame_Build_Windows.html, apptools/apptools-sampleapp-tests/tests.android.xml, apptools/apptools-sampleapp-tests/tests.deb.xml, apptools/apptools-sampleapp-tests/tests.full.xml, apptools/apptools-sampleapp-tests/tests.ios.xml, apptools/apptools-sampleapp-tests/tests.windows.xml
=> [apptools-sampleapp] Update test steps for apptools sampleapp

webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest/xhr2_XMLHttpRequestEventTarget_ontimeout_event.html
Unit test Platform: Crosswalk Project for Android 16.45.418.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5190
=> [webapi] Update XMLHttpRequst ontimeout test

misc/sampleapp-android-tests/testscripts/helloworld_switch.feature
hello-world sample had been updated in
https://github.com/crosswalk-project/crosswalk-samples/pull/28,
renamed to 'Hello World'
BUG=https://crosswalk-project.org/jira/browse/XWALK-5202
=> [misc] Update hellow-world name to 'Hello World'

misc/sampleapp-android-tests/testscripts/helloworld_switch.feature
hello-world sample had been updated in
https://github.com/crosswalk-project/crosswalk-samples/pull/28,
renamed to 'Hello World'
Unit test platform: Crosswalk Project for Android 15.44.383.0
https://crosswalk-project.org/jira/browse/XWALK-5202
=> [Crosswalk-15][misc]Update hellow-world name to 'Hello World'

apptools/apptools-linux-tests/apptools/create.py, apptools/apptools-linux-tests/apptools/create_with_target_platform.py
=> [apptools-linux] Clear project before creating for apptools linux

apptools/apptools-ios-tests/apptools/create.py, apptools/apptools-ios-tests/apptools/create_with_target_platform.py
=> [apptools-iOS] Remove project before creating project for apptools iOS

tools/atip/README.md, tools/atip/atip/android/steps.py
Unit test Platform: Crosswalk Project for Linux 16.45.421.0
=> [atip-android] Add steps for notification automation

usecase/usecase-litewrt-android-tests/steps/VideoWebSite/step.js, usecase/usecase-litewrt-android-tests/suite.json, usecase/usecase-litewrt-android-tests/tests.android.xml, usecase/usecase-litewrt-android-tests/tests.full.xml, usecase/usecase-litewrt-android-tests/tests/VideoWebSite/README.md, usecase/usecase-litewrt-android-tests/tests/VideoWebSite/index.html, usecase/usecase-litewrt-android-tests/tests/VideoWebSite/res/manifest.json
Unit test Platform: Crosswalk Project for Android 15.44.391.7
BUG=https://crosswalk-project.org/jira/browse/XWALK-5232
=> [usecase-lite] Add VideoWebSite test for lite wrt usecase

webapi/tct-notification-w3c-tests/notification/w3c/bdd/body-basic-manual.html, webapi/tct-notification-w3c-tests/notification/w3c/bdd/event-onclick-manual.html, webapi/tct-notification-w3c-tests/notification/w3c/bdd/tag-different-manual.html, webapi/tct-notification-w3c-tests/notification/w3c/bdd/tag-same-manual.html, webapi/tct-notification-w3c-tests/suite.json, webapi/tct-notification-w3c-tests/tests.full.xml, webapi/tct-notification-w3c-tests/tests.xml, webapi/tct-notification-w3c-tests/w3c-notification-app/testscripts/body-basic-manual.feature, webapi/tct-notification-w3c-tests/w3c-notification-app/testscripts/event-onclick-manual.feature, webapi/tct-notification-w3c-tests/w3c-notification-app/testscripts/notification_body.feature, webapi/tct-notification-w3c-tests/w3c-notification-app/testscripts/notification_tag.feature, webapi/tct-notification-w3c-tests/w3c-notification-app/testscripts/tag-different-manual.feature, webapi/tct-notification-w3c-tests/w3c-notification-app/testscripts/tag-same-manual.feature
Unit test Platform: Crosswalk Project for Linux 16.45.421.0
=> [webapi] Automation tests for Notification API

misc/sampleapp-android-tests/sampleapp/TestApp.py
Impacted TCs num(approved): New 0, Update 5, Delete 0
Android test result summary: Pass 5, Fail 0, Block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5239
=> [misc-sample]Update test step for Spacedodgegame

tools/xml/README, tools/xml/result2csv.py
Add result2csv.py for convert result xml to csv offline.
=> [tools] Add result2csv for report convert

usecase/usecase-apptools-tests/tests.android.xml, usecase/usecase-apptools-tests/tests.deb.xml, usecase/usecase-apptools-tests/tests.full.xml, usecase/usecase-apptools-tests/tests.ios.xml, usecase/usecase-apptools-tests/tests.windows.xml, usecase/usecase-cordova-android-tests/tests.full.xml, usecase/usecase-cordova-android-tests/tests.xml, usecase/usecase-ios-tests/tests.full.xml, usecase/usecase-ios-tests/tests.xml, usecase/usecase-litewrt-android-tests/tests.android.xml, usecase/usecase-litewrt-android-tests/tests.full.xml, usecase/usecase-webapi-xwalk-tests/tests.android.xml, usecase/usecase-webapi-xwalk-tests/tests.auto.xml, usecase/usecase-webapi-xwalk-tests/tests.full.xml, usecase/usecase-webapi-xwalk-tests/tests.windows.xml, usecase/usecase-webapi-xwalk-tests/tests.wts.xml, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.auto.xml, usecase/usecase-wrt-android-tests/tests.full.xml, usecase/usecase-wrt-android-tests/tests.shared.xml, usecase/usecase-wrt-auto-tests/tests.full.xml, usecase/usecase-wrt-auto-tests/tests.xml, usecase/usecase-wrt-linux-tests/tests.auto.xml, usecase/usecase-wrt-windows-tests/tests.full.xml, usecase/usecase-wrt-windows-tests/tests.xml
-Unify component to "Crosswalk Use Cases/*"
-Update suite name
=> [usecase] Unify component for usecase test suite

usecase/usecase-apptools-tests/tests.android.xml, usecase/usecase-apptools-tests/tests.deb.xml, usecase/usecase-apptools-tests/tests.full.xml, usecase/usecase-apptools-tests/tests.ios.xml, usecase/usecase-cordova-android-tests/tests.full.xml, usecase/usecase-cordova-android-tests/tests.xml, usecase/usecase-ios-tests/tests.full.xml, usecase/usecase-ios-tests/tests.xml, usecase/usecase-litewrt-android-tests/tests.android.xml, usecase/usecase-webapi-xwalk-tests/tests.android.xml, usecase/usecase-webapi-xwalk-tests/tests.auto.xml, usecase/usecase-webapi-xwalk-tests/tests.full.xml, usecase/usecase-webapi-xwalk-tests/tests.tizen.xml, usecase/usecase-webapi-xwalk-tests/tests.wts.xml, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.auto.xml, usecase/usecase-wrt-android-tests/tests.full.xml, usecase/usecase-wrt-android-tests/tests.shared.xml, usecase/usecase-wrt-tizen-tests/subtestresult.xml, usecase/usecase-wrt-tizen-tests/tests.full.xml, usecase/usecase-wrt-tizen-tests/tests.tizen.xml
-Unify component to "Crosswalk Use Cases/*"
-Update suite name
=> [Crosswalk-15][usecase] Unify component for usecase test suite

usecase/usecase-webapi-xwalk-tests/samples/MediaSource/res/html5demos/media-source.html, usecase/usecase-webapi-xwalk-tests/samples/PermissionsAPI/index.html, usecase/usecase-webapi-xwalk-tests/samples/WebNotification/index.html
Remove MediaSource, PermissionsAPI and WebNotification test
BUG=https://crosswalk-project.org/jira/browse/XWALK-4231
=> [usecase] Remove Google Analytics code

tools/atip/atip/web/steps.py
=> [atip] Improve steps for switch app

usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md
-Update embeddingapi usecase & async usecase README
https://crosswalk-project.org/jira/browse/XWALK-5056
=> [EmbeddingApi] Update embeddingapi usecase & async usecase README

tools/atip/README.md, tools/atip/atip/android/android.py, tools/atip/atip/android/steps.py
=> [atip-android] Add steps for switch language

webapi/tct-extra-html5-tests/html5-extra-app/testscripts/get-navigatorlanguage.feature, webapi/tct-extra-html5-tests/html5-extra-app/testscripts/steps/steps.py, webapi/tct-extra-html5-tests/suite.json, webapi/tct-extra-html5-tests/tests.full.xml, webapi/tct-extra-html5-tests/tests.xml, webapi/tct-extra-html5-tests/w3c/system-state-and-capabilities/the-navigator-object/bdd/get-navigatorlanguage-manual.html
=> [webapi] Automation tests for get-navigatorlanguage

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_scrollview_parent.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/XWalkEmbeddedAPISample.java, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/basic/XWalkViewWithScrollViewParentAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_scrollview_parent.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/XWalkEmbeddedAPISample.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/basic/XWalkViewWithScrollViewParent.java
-Add a usecase to create a xwalkview as a scrollview child
-Modify README source code file path
BUG=https://crosswalk-project.org/jira/browse/XWALK-4987
=> [EmbeddingAPI] Add a usecase to create a xwalkview as a scrollview child

apptools/apptools-windows-tests/README, apptools/apptools-windows-tests/apptools/comm.py, apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/suite.json, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5563
https://crosswalk-project.org/jira/browse/XWALK-5288
BUG=https://crosswalk-project.org/jira/browse/XWALK-5556
=> [apptools-windows] Add tests to test enable crosswalk download on windows

apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml, apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5564
https://crosswalk-project.org/jira/browse/XWALK-5258
BUG=https://crosswalk-project.org/jira/browse/XWALK-5446
=> [apptools] Add tests to test build project with crosswalk zip for apptools

apptools/apptools-ios-tests/apptools/build_arguments.py, apptools/apptools-ios-tests/tests.full.xml, apptools/apptools-ios-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5280
Unit test result summary: pass 0, fail 3, block 0
https://crosswalk-project.org/jira/browse/XWALK-4245
=> [apptools-ios] Add cases to test build arguments for apptools ios

apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-android-tests/apptools/init_manifest.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml, apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/apptools/init_manifest.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-5447
=> [apptools] Add tests to test init manifest for apptools

apptools/apptools-android-tests/apptools/comm.py, apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-android-tests/testapp/start_url/index.html, apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/testapp/start_url/index.html
https://crosswalk-project.org/jira/browse/XWALK-5564
Impacted tests(approved): new 0, update 12, delete 0
Unit test result summary: pass 10, fail 2, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5445
=> [apptools-android] Add checkpoints to test shared mode in crosswalk-pkg for apptools android

apptools/apptools-android-tests/testapp/start_url/index.html, apptools/apptools-windows-tests/testapp/start_url/index.html
=> [apptools] Add copyright in files for apptools

apptools/apptools-android-tests/apptools/Manifest_Command_Line_DisableWebGL.html, apptools/apptools-android-tests/apptools/Manifest_Command_Line_EnableWebGL.html, apptools/apptools-android-tests/apptools/Manifest_ContactExtension.html
https://crosswalk-project.org/jira/browse/XWALK-5590
Unit test result summary: pass 2, fail 1, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5265
=> [apptools-android] Update the path of project index.html for apptools android

usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml, usecase/usecase-embedding-android-tests/testscripts/AcceptFileSchemeCookies.feature, usecase/usecase-embedding-android-tests/testscripts/AcceptFileSchemeCookiesAsync.feature, usecase/usecase-embedding-android-tests/testscripts/ContactExtension.feature, usecase/usecase-embedding-android-tests/testscripts/ContactExtensionAsync.feature, usecase/usecase-embedding-android-tests/testscripts/Extension.feature, usecase/usecase-embedding-android-tests/testscripts/ExtensionAsync.feature, usecase/usecase-embedding-android-tests/testscripts/LoadAppFromManifest.feature, usecase/usecase-embedding-android-tests/testscripts/LoadAppFromManifestAsync.feature, usecase/usecase-embedding-android-tests/testscripts/OnCreateWindowRequested.feature, usecase/usecase-embedding-android-tests/testscripts/OnCreateWindowRequestedAsync.feature, usecase/usecase-embedding-android-tests/testscripts/PauseJsTimers.feature, usecase/usecase-embedding-android-tests/testscripts/PauseJsTimersAsync.feature, usecase/usecase-embedding-android-tests/testscripts/Versions.feature, usecase/usecase-embedding-android-tests/testscripts/VersionsAsync.feature, usecase/usecase-embedding-android-tests/testscripts/XWalkViewWithWindowsVisibilityChanged.feature, usecase/usecase-embedding-android-tests/testscripts/XWalkViewWithWindowsVisibilityChangedAsync.feature, usecase/usecase-embedding-android-tests/testscripts/onIconAvailableOnReceivedIcon.feature, usecase/usecase-embedding-android-tests/testscripts/onIconAvailableOnReceivedIconAsync.feature
-Modify automation usecase tests xml ID & feature ID
Impacted tests(approved): new 0, update 18, delete 0
Unit test result summary: pass 18, fail 0, block 0
=> [EmbeddingApi] Modify automation usecase tests xml ID & feature ID

stability/stability-embeddingapi-android-tests/suite.json, stability/stability-embeddingapi-android-tests/testapp/AndroidManifest.xml, stability/stability-embeddingapi-android-tests/tests.full.xml, stability/stability-embeddingapi-android-tests/tests.webview.xml, stability/stability-embeddingapi-android-tests/tests.xml, stability/stability-embeddingapi-android-tests/testscripts/LongTimeWebViewSwipe.feature, stability/stability-embeddingapi-android-tests/testscripts/LongTimeXWalkViewSwipe.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiTabWebViewImage.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiTabWebViewVideo.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiTabWebViewWebsite.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiTabXWalkViewImage.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiTabXWalkViewVideo.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiTabXWalkViewWebsite.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiWebViewImage.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiWebViewVideo.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiWebViewWebsite.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiXWalkViewImage.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiXWalkViewVideo.feature, stability/stability-embeddingapi-android-tests/testscripts/MultiXWalkViewWebsite.feature, stability/stability-embeddingapi-android-tests/testscripts/steps/steps.py, tools/atip/README.md, tools/atip/atip/android/android.py, tools/atip/atip/android/steps.py
-Add automation tests of stability embedding API
=> [EmbeddingApi-Stability] Add automation tests of stability embedding API

apptools/apptools-android-tests/apptools/Manifest_Disable_AnimatableView.html, apptools/apptools-android-tests/apptools/Manifest_Enable_AnimatableView.html, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5598
BUG=https://crosswalk-project.org/jira/browse/XWALK-5560
=> [apptools-android] Add tests to test animatable view for apptools android

webapi/tct-extra-html5-tests/suite.json
BUG=https://crosswalk-project.org/jira/browse/XWALK-5597
=> [webapi] Update suite.json for Extra HTML5

tools/atip/atip/web/web.py
Impacted TCs num(approved): New 0, Update , Delete 0
Unit test result summary: Pass 16, Fail 0, Blocked 0
Automation tests in tct-backgrounds-css3-tests both got pass with binary
webdriver or python version if crosswalk webdriver.
=> [atip] Update atip to support Python version of Crosswalk WebDriver

cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_open_all_optional.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_open_bad_url.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_open_no_optional.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setHeaderValue_all_optional.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setHeaderValue_invalid_instance.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setHeaderValue_no_optional.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setMethod_correct_parameters.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setMethod_invalid_instance.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setMethod_invalid_method.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setURL_bad_url.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setURL_correct_parameters.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setURL_invalid_instance.html, cordova/cordova-appsecurityapi-android-tests/tests.full.xml, cordova/cordova-appsecurityapi-android-tests/tests.xml
Unit test platform: Crosswalk Project for Android 16.45.421.1
https://crosswalk-project.org/jira/browse/XWALK-5098
=> [cordova] Add security cases for 'Secure Transport'

wrt/wrt-manifest-android-tests/README.md, wrt/wrt-manifest-android-tests/ge_unitcase.py, wrt/wrt-manifest-android-tests/run_app.py, wrt/wrt-manifest2-android-tests/manifest2/comm.py, wrt/wrt-packertool2-android-tests/packertool2/comm.py, wrt/wrt-security-android-tests/security/comm.py
Impacted TCs num(approved): New 0, Update 322, Delete 0
Unit test Platform: Android Crosswalk Canary 17.45.429.0-64bit
Android test result summary: Pass 322, Fail 0, Block 0
=> [wrt] Update test scripts to support arm64 and x86_64 bit

usecase/usecase-wrt-auto-tests/samples/ApkBuildAnyLocation/comm.py, usecase/usecase-wrt-auto-tests/samples/ApkBuildTemporary/comm.py, usecase/usecase-wrt-auto-tests/samples/PackertoolCompressor/common.py, usecase/usecase-wrt-auto-tests/samples/PackertoolCompressorCss/common.py, usecase/usecase-wrt-auto-tests/samples/WebAppVersionUpdate/versionupdate.py
Impacted TCs num(approved): New 0, Update 15, Delete 0
Unit test Platform: Android Crosswalk Canary 17.45.429.0-64bit
Android test result summary: Pass 15, Fail 0, Block 0
=> [usecase] Update test scripts to support arm64 and x86_64

webapi/webapi-webspeech-w3c-tests/webspeech/speechrecognitionresult_length-manual.html, webapi/webapi-webspeech-w3c-tests/webspeech/speechrecognitionresultlist_length-manual.html
Unit test Platform: Crosswalk Project for Android 14.43.347.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5163
=> [Crosswalk-14][webapi] Update SpeechRecognitionResult length tests

misc/sampleapp-android-tests/sampleapp/comm.py
Unit test platform: Crosswalk Project for Android 17.45.424.0
Unit test result summary: pass 83, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-5557
=> [misc] Update arch type for 64bits support

wrt/wrt-securitymanu-android-tests/suite.json
Impacted TCs num(approved): New 0, Update 22, Delete 0
Unit test Platform: Android Crosswalk Canary 17.45.429.0
Android test result summary: Pass 22, Fail 0, Block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5609
BUG=https://crosswalk-project.org/jira/browse/XWALK-5610
BUG=https://crosswalk-project.org/jira/browse/XWALK-5613
=> [wrt] Update suite.json for securitymanu

apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml, apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
Impacted tests(approved): new 2, update 2, delete 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5642
=> [apptools] Add tests to test reading manifest data for apptools

apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-windows-tests/apptools/create_package.py
BUG=https://crosswalk-project.org/jira/browse/XWALK-5624
=> [apptools] Update tests to test only check setup for target platforms on apptools

cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_destroySecureTransport_correct_instance.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_destroySecureTransport_invalid_instance.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_destroy_correct_instance.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_destroy_invalid_instance.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_open_DELETE.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_open_GET.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_open_HEAD.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_open_OPTIONS.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_open_POST.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_open_PUT.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_open_invalid_method.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_sendRequest_GENERIC.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_sendRequest_JSON.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_sendRequest_invalid_id.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_sendRequest_no_optional.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setMethod_DELETE.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setMethod_GET.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setMethod_HEAD.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setMethod_OPTIONS.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setMethod_POST.html, cordova/cordova-appsecurityapi-android-tests/appsecurityapi/AppSecurityApi_setMethod_PUT.html, cordova/cordova-appsecurityapi-android-tests/tests.full.xml, cordova/cordova-appsecurityapi-android-tests/tests.xml
- Fail analyse: XWALK-5638
Impacted tests(approved): new 17, update 5, delete 0
Unit test platform: Crosswalk Project for Android 16.45.421.1
Unit test result summary: pass 21, fail 1, block 0
https://crosswalk-project.org/jira/browse/XWALK-5098
=> [cordova] Add secure cases for 'Secure Transport'

usecase/usecase-embedding-android-tests/webviewtest/AndroidManifest.xml, usecase/usecase-embedding-android-tests/webviewtest/res/layout/activity_with_webview_clients.xml, usecase/usecase-embedding-android-tests/webviewtest/res/layout/activity_with_webview_multi_instance_overlay.xml, usecase/usecase-embedding-android-tests/webviewtest/res/layout/activity_with_webview_navigation.xml, usecase/usecase-embedding-android-tests/webviewtest/res/layout/activity_with_webview_scrollview_parent.xml, usecase/usecase-embedding-android-tests/webviewtest/res/values/strings.xml, usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/README.md, usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/WebViewAPISample.java, usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/basic/WebViewWithMultiInstanceOverlay.java, usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/basic/WebViewWithScrollViewParent.java, usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/client/WebViewWithClients.java, usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/misc/WebViewWithNavigation.java
-add webview usecase WebViewWithScrollViewParent
-add webview usecase WebViewWithMultiInstanceOverlay
-add webview usecase WebViewWithClients
-add webview usecase WebViewWithNavigation
https://crosswalk-project.org/jira/browse/XWALK-5057
=> [EmbeddingAPI] Add usecase of WebView for xwalkview reference

apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml, apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5661
Unit test result summary: pass 2, fail 2, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5612
=> [apptools] Add tests to test keep files for apptools

apptools/apptools-android-tests/apptools/activity_name.py, apptools/apptools-android-tests/apptools/comm.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
Impacted tests(approved): new 1, update 44, delete 0
Unit test result summary: pass 45, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5660
=> [apptools_android] Add tests to test activity name for apptools android

apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5592
=> [apptools_android] Add tests to test -r without argument for apptools android

webapi/tct-csp-w3c-tests/csp/csp_frame-ancestors_none-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_asterisk_allowed_ext-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_allowed-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_blocked-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_blocked_int-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_multi_allowed_one-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_multi_allowed_two-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_multi_blocked-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_multi_blocked_int-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_none_blocked_ext-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_none_blocked_int-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_self_allowed-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_self_blocked-manual.cgi, webapi/tct-csp-w3c-tests/csp/reference/csp_object-src_allowed-ref.html, webapi/tct-csp-w3c-tests/csp/support/object-src-allow.html, webapi/tct-csp-w3c-tests/csp/support/object-src-block.html, webapi/tct-csp-w3c-tests/tests.full.xml, webapi/tct-csp-w3c-tests/tests.xml
Impacted TCs num(approved): New 0, Update 14, Delete 0
Unit test Platform: Crosswalk Project for Android 17.45.429.0
Unit test result summary: Pass 14, Fail 0, Blocked 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4924
=> [webapi] Fix object-src tests for CSP

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_on_javascript_modal_dialog_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/client/XWalkViewWithOnJavascriptModalDialogAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_on_javascript_modal_dialog.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/client/XWalkViewWithOnJavascriptModalDialog.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
-Add usecase for XWalkUIClient onJavascriptModalDialog API
BUG=https://crosswalk-project.org/jira/browse/XWALK-5102
=> [EmbeddingAPI] Add usecase for XWalkUIClient onJavascriptModalDialog API

webapi/tct-csp-w3c-tests/csp/csp_object-src_asterisk_allowed_ext-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_asterisk_allowed_int-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_allowed-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_blocked-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_blocked_int-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_multi_allowed_one-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_multi_allowed_two-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_multi_blocked-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_cross-origin_multi_blocked_int-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_none_blocked_ext-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_none_blocked_int-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_self_allowed-manual.cgi, webapi/tct-csp-w3c-tests/csp/csp_object-src_self_blocked-manual.cgi, webapi/tct-csp-w3c-tests/csp/reference/csp_object-src_allowed-ref.html, webapi/tct-csp-w3c-tests/csp/support/object-src-allow.html, webapi/tct-csp-w3c-tests/csp/support/object-src-block.html, webapi/tct-csp-w3c-tests/tests.full.xml, webapi/tct-csp-w3c-tests/tests.xml
Impacted TCs num(approved): New 0, Update 14, Delete 0
Unit test result summary: Pass 14, Fail 0, Blocked 0
https://crosswalk-project.org/jira/browse/XWALK-4924
=> [Crosswalk-15][webapi] Fix object-src tests for CSP

tools/atip/atip/android/android.py
Unit test platform: Crosswalk Project for Android 17.45.424.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5571
=> [atip] Update airplane for Android 5.0

tools/atip/atip/android/android.py
Unit test Platform: Crosswalk Project for Android 17.45.430.0
https://crosswalk-project.org/jira/browse/XWALK-5725
=> [atip-android] Update switch language steps for Android 5.0

usecase/usecase-extension-windows-tests/README.md, usecase/usecase-extension-windows-tests/extension/extension_echo.html, usecase/usecase-extension-windows-tests/suite.json, usecase/usecase-extension-windows-tests/tests.full.xml, usecase/usecase-extension-windows-tests/tests.xml, usecase/usecase-extension-windows-tests/xwalk-echo-app/index.html, usecase/usecase-extension-windows-tests/xwalk-echo-extension/XWalkExtension.cs, usecase/usecase-extension-windows-tests/xwalk-echo-extension/XWalkExtensionInstance.cs
Unit test platform: Crosswalk Project for windows 17.45.426.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5663
=> [windows] Add .Net extension usecase

apptools/apptools-android-tests/apptools/create_package_target.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-5614
=> [apptools_android] Add tests to test target CPU ABI for apptools android

apptools/apptools-android-tests/apptools/AppTools_Crosswalk_Pkg_Help.html, apptools/apptools-android-tests/apptools/comm.py, apptools/apptools-android-tests/apptools/create_offline.py, apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-android-tests/apptools/create_package_abbreviated_command.py, apptools/apptools-android-tests/apptools/crosswalk_pkg_version.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml, apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-3782
Impacted tests(approved): new 7, update 17, delete 0
Unit test result summary: pass 21, fail 3, block 0
=> [apptools] Add tests to test crosswalk-pkg with abbreviated command for apptools

usecase/usecase-cordova-android-tests/samples/DefaultCrosswalkVersion/REAMDE.md, usecase/usecase-cordova-android-tests/samples/DefaultCrosswalkVersion/index.html, usecase/usecase-cordova-android-tests/samples/DefaultCrosswalkVersion/testapp/index.html, usecase/usecase-cordova-android-tests/steps/DefaultCrosswalkVersion/step.js, usecase/usecase-cordova-android-tests/suite.json
Unit test platform: cordova-plugin-crosswalk-webview-tests
BUG=https://crosswalk-project.org/jira/browse/XWALK-5715
=> [usecase-cordova] Add test for default crosswalk version

tools/apkanalyser/main.py, tools/apkanalyser/result/apk-analyser-result.xsl
[Unit Test] Pass for arm64 and x86_64 apps test
=> [tool][apk analyser] Add arm64 and x86_64 apps detection support

tools/resources/inst/inst.msi.py
It will be copyed in suite.json
- inst.py -i
- inst.py -u
- inst.py -d \<device ip\> -i
- inst.py -d \<device ip\> -u
https://crosswalk-project.org/jira/browse/XWALK-5632
=> [webapi] Add inst.msi.py for windows

apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-android-tests/apptools/create_package_target.py
Impacted tests(approved): new 0, update 13, delete 0
Unit test result summary: pass 13, fail 0, block 0
=> [apptools-android] Update tests to test target CPU ABI for apptools android

usecase/usecase-cordova-android-tests/tests.full.xml, usecase/usecase-cordova-android-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5715
=> [usecase-cordova] Add DefaultCrosswalkVersion in tests.xml

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkSettingTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v5.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkSettingTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml
Impacted tests: new 12, update 0, delete 0
=> [Embedding-API] Add 12 auto test cases for XWalkSetting

tools/apkanalyser/main.py
=> [tools][ApkAnalyser] Fix path issue of ApkAnalyser

usecase/usecase-wrt-android-tests/samples/ThemeColor/index.html, usecase/usecase-wrt-android-tests/steps/ThemeColor/step.js
Unit test Platform: Android Crosswalk Canary 17.46.447.0
https://crosswalk-project.org/jira/browse/XWALK-4305
=> [usecase] Update test steps for theme-color

usecase/usecase-wrt-android-tests/samples/ThemeColor/index.html, usecase/usecase-wrt-android-tests/steps/ThemeColor/step.js
Unit test Platform: Android Crosswalk Canary 17.46.447.0
https://crosswalk-project.org/jira/browse/XWALK-4305
=> [Crosswalk16][usecase] Update test steps for theme-color

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v5.xml, embeddingapi/embedding-api-android-tests/tests_v6.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v6.xml
-Move 6 cases to v6 & update related files
=> [EmbeddingAPI] Move some cases to v6

tools/resources/inst/inst.msi.py
https://crosswalk-project.org/jira/browse/XWALK-5632
=> [windows] Update inst.py to support "-m"

cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/google-maps-plugin.py
Unit test platform: Crosswalk Project for Android 17.45.439.0
https://crosswalk-project.org/jira/browse/XWALK-5869
=> [cordova] Enable zOrderOnTop in GoogleMaps by workaround

cordova/cordova-sampleapp-android-tests/sampleapp/Crosswalk_Cordova_SampleApp_Spacedodge_arm_embedded_on_ia.html, cordova/cordova-sampleapp-android-tests/sampleapp/Crosswalk_Cordova_SampleApp_Spacedodge_arm_shared_on_ia.html, cordova/cordova-sampleapp-android-tests/sampleapp/Crosswalk_Cordova_SampleApp_Spacedodge_ia_embedded_on_arm.html, cordova/cordova-sampleapp-android-tests/sampleapp/Crosswalk_Cordova_SampleApp_Spacedodge_ia_shared_on_arm.html, cordova/cordova-sampleapp-android-tests/tests.3.6.xml, cordova/cordova-sampleapp-android-tests/tests.4.x.xml, cordova/cordova-sampleapp-android-tests/tests.full.xml, misc/cordova-compatibility-android-tests/README.md
Unit test platform: Crosswalk Project for android 16.45.421.18
BUG=https://crosswalk-project.org/jira/browse/XWALK-5852
=> [Cordova] Add tests for Across Platforms Compatibility testing

misc/sampleapp-android-tests/tests.full.xml
- pack, install, uninstall -> P1
- icon -> P2
- uninstall when running -> P3
=> [misc] Adjust test priority for Sample App

usecase/usecase-wrt-windows-tests/samples/Picker/README.md, usecase/usecase-wrt-windows-tests/samples/Picker/index.html, usecase/usecase-wrt-windows-tests/samples/Picker/res/index.html, usecase/usecase-wrt-windows-tests/steps/Picker/step.js, usecase/usecase-wrt-windows-tests/suite.json, usecase/usecase-wrt-windows-tests/tests.full.xml, usecase/usecase-wrt-windows-tests/tests.xml
Unit test platform: Crosswalk Project for windows 17.45.426.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5435
=> [windows] Add picker usecase for usecase-wrt-windows-tests

tools/build/pack_windows.py
- It's fine to pack msi package with the template manifest.json file
https://crosswalk-project.org/jira/browse/XWALK-5632
=> [windows] Modify pack script to enable webapi test suite msi package

apptools/apptools-android-tests/apptools/manifest_display.py, apptools/apptools-android-tests/apptools/manifest_orientation.py, apptools/apptools-ios-tests/apptools/manifest_display.py, apptools/apptools-linux-tests/apptools/manifest_display.py, apptools/apptools-windows-tests/apptools/manifest_display.py
https://crosswalk-project.org/jira/browse/XWALK-5262
=> [apptools] Update the build result of invalid display/orientation for apptools

apptools/apptools-windows-tests/apptools/Manifest_Command_Line_DisableWebGL.html, apptools/apptools-windows-tests/apptools/Manifest_Command_Line_EnableWebGL.html, apptools/apptools-windows-tests/testapp/webgl_disable_tests/index.html, apptools/apptools-windows-tests/testapp/webgl_enable_tests/index.html, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-5439
=> [apptools-windows] Add tests to test command-line for apptools windows

tools/atip/atip/web/web.py
tct-backgrounds-css3-tests:
Impacted TCs num(approved): New 0, Update 16, Delete 0
Unit test Platform: Crosswalk Project for Android 17.45.430.0
Unit test result summary: Pass 16, Fail 0, Blocked 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5717
=> [atip] Update activity for app tools support

usecase/usecase-litewrt-android-tests/suite.json, usecase/usecase-litewrt-android-tests/tests/VideoWebSite/res/manifest.json, usecase/usecase-webapi-xwalk-tests/samples/Advertising/res/manifest.json, usecase/usecase-webapi-xwalk-tests/samples/InAppPayment/iap/manifest.json, usecase/usecase-webapi-xwalk-tests/suite.json, usecase/usecase-wrt-windows-tests/suite.json
Fail Analyse:
XWALK-5646 Support xwalk permissions does not resolved
usecase-webapi-xwalk-tests:
Unit test platform: Crosswalk Project for Android 17.45.439.0
Unit test result summary: pass 52, fail 15, block 2
usecase-litewrt-android-tests
Unit test platform: Crosswalk Project for Android 17.45.439.0
https://crosswalk-project.org/jira/browse/XWALK-5716
https://crosswalk-project.org/jira/browse/XWALK-5726
https://crosswalk-project.org/jira/browse/XWALK-5760
https://crosswalk-project.org/jira/browse/XWALK-5778
=> [usecase] Update manifest and suite.json for app tools support

misc/web-abat-xwalk-tests/manifest.json, misc/web-abat-xwalk-tests/suite.json, misc/webmanu-system-android-tests/suite.json, misc/webmanu-system-android-tests/testapp/audio/manifest.json, misc/webmanu-system-android-tests/testapp/canvas/manifest.json, misc/webmanu-system-android-tests/testapp/cookie/manifest.json, misc/webmanu-system-android-tests/testapp/cookie_upgrade/manifest.json, misc/webmanu-system-android-tests/testapp/filepicker/manifest.json, misc/webmanu-system-android-tests/testapp/filereader/manifest.json, misc/webmanu-system-android-tests/testapp/filereader_upgrade/manifest.json, misc/webmanu-system-android-tests/testapp/fullscreen/manifest.json, misc/webmanu-system-android-tests/testapp/indexdb/manifest.json, misc/webmanu-system-android-tests/testapp/indexdb_upgrade/manifest.json, misc/webmanu-system-android-tests/testapp/localstorage/manifest.json, misc/webmanu-system-android-tests/testapp/localstorage_upgrade/manifest.json, misc/webmanu-system-android-tests/testapp/video/manifest.json, misc/webmanu-system-android-tests/testapp/webaudio/manifest.json, misc/webmanu-system-android-tests/testapp/webgl/manifest.json, misc/webmanu-system-android-tests/testapp/webrtc/manifest.json
- Add "xwalk_package_id" in manifest.json of sub apps
- Update xwalk_version to xwalk_app_version
- Remove "apk-pkg-opt", "apk-version-opt"
Impacted TCs num(approved): New 0, Update 17, Delete 0
Unit test platform: Crosswalk Project for Android 17.45.439.0
Android test result summary: Pass 17, Fail 0, Block 0
https://crosswalk-project.org/jira/browse/XWALK-5716
https://crosswalk-project.org/jira/browse/XWALK-5759
https://crosswalk-project.org/jira/browse/XWALK-5732
=> [misc] Update suite.json and manifest.json for app tools

stability/stability-lowresource-android-tests/README.md, stability/stability-lowresource-android-tests/lowresource/Webapp_Operations_UnderLowDisk.py, stability/stability-overload-android-tests/README.md, stability/stability-overload-android-tests/overload/Launch_MultiApps_WithSystemForceTerminate.sh, stability/stability-overload-android-tests/suite.json
Unit test platform: Crosswalk Project for Android 17.45.439.0
Android test result summary: Pass 2, Fail 0, Block 0
https://crosswalk-project.org/jira/browse/XWALK-5737
=> [stability] Update tests using make_apk.py by app tools

tools/build/README.md, tools/build/pack_cordova_sample.py, usecase/usecase-cordova-android-tests/samples/SetUserAgent/REAMDE.md, usecase/usecase-cordova-android-tests/samples/SetUserAgent/index.html, usecase/usecase-cordova-android-tests/samples/SetUserAgent/res/index.html, usecase/usecase-cordova-android-tests/steps/SetUserAgent/step.js, usecase/usecase-cordova-android-tests/tests.full.xml, usecase/usecase-cordova-android-tests/tests.xml
Unit test platform: Crosswalk Project for android 18.46.453.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5191
=> [Cordova] Add setUserAgent usecase

tools/atip/atip/android/android.py
- Refactor atip for android
- Update atip android for Android 5+ (wifi, gps, airplane mode)
- Update atip android to support device ecs2-8a
Impacted TCs num(approved): New 0, Update 40, Delete 0
Unit test result summary: Pass 21, Fail 19, Blocked 0
Failed tests tracked by XWALK-5595 and XWALK-5001, atip steps for android
(wifi, gps, airplane mode) work normally.
https://crosswalk-project.org/jira/browse/XWALK-5725
=> [atip-android] Refactor atip android and update atip for Android 5+

tools/atip/atip/android/android.py
- Refactor atip for android
- Update atip android for Android 5+ (wifi, gps, airplane mode)
- Update atip android to support device ecs2-8a
Impacted TCs num(approved): New 0, Update 40, Delete 0
Unit test result summary: Pass 21, Fail 19, Blocked 0
Failed tests tracked by XWALK-5595 and XWALK-5001, atip steps for android
(wifi, gps, airplane mode) work normally.
https://crosswalk-project.org/jira/browse/XWALK-5725
https://crosswalk-project.org/jira/browse/XWALK-5571
=> [crosswalk-17][atip-android] Refactor atip android and update atip for Android 5+ 

tools/atip/atip/android/android.py
- Refactor atip for android
- Update atip android for Android 5+ (wifi, gps, airplane mode)
- Update atip android to support device ecs2-8a
Impacted TCs num(approved): New 0, Update 40, Delete 0
Unit test result summary: Pass 21, Fail 19, Blocked 0
Failed tests tracked by XWALK-5595 and XWALK-5001, atip steps for android
(wifi, gps, airplane mode) work normally.
https://crosswalk-project.org/jira/browse/XWALK-5725
https://crosswalk-project.org/jira/browse/XWALK-5571
=> [crosswalk-16][atip-android] Refactor atip android and update atip for Android 5+

cordova/cordova-feature-android-tests/feature/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/comm.py, cordova/cordova-webapp-android-tests/webapp/comm.py
Impacted tests(approved): new 0, update 28, delete 0
Unit test platform: Crosswalk Project for android 18.46.453.0
Unit test result summary: pass 28, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-5867
=> [Cordova] Cordova build separate arch apks for feature

usecase/usecase-cordova-android-tests/res/comm.py, usecase/usecase-cordova-android-tests/samples/CrosswalkVersion/res/test.py
Unit test platform: Crosswalk Project for android 18.46.453.0
https://crosswalk-project.org/jira/browse/XWALK-5867
=> [Cordova] Cordova build separate arch apks for usecases

cordova/cordova-sampleapp-android-tests/sampleapp/GoogleMapsPlugin.html
https://crosswalk-project.org/jira/browse/XWALK-5779
=> [cordova] Update guide to get Google Maps API key

cordova/cordova-sampleapp-android-tests/sampleapp/GoogleMapsPlugin.html
https://crosswalk-project.org/jira/browse/XWALK-5779
=> [Crosswalk-17][cordova] Update guide to get Google Maps API key

apptools/apptools-windows-tests/apptools/Windows_Compatible.html, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
=> [apptools-windows] Add tests to test win10's app run on win8.1 for apptools windows

apptools/apptools-ios-tests/apptools/create_package.py, apptools/apptools-ios-tests/tests.full.xml, apptools/apptools-ios-tests/tests.xml, apptools/apptools-linux-tests/apptools/create_package.py, apptools/apptools-linux-tests/tests.full.xml, apptools/apptools-linux-tests/tests.xml, apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-6018
Unit test result summary: pass 2, fail 1, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5437
=> [apptools] Add tests to test multiple backends for apptools

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v6.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v6.xml
-Add autocase for XWalkView API loadExtension
BUG=https://crosswalk-project.org/jira/browse/XWALK-6017
=> [EmbeddingAPI-autocase] Add autocase for XWalkView API loadExtension

usecase/usecase-wrt-android-tests/samples/WebPassword/README.md, usecase/usecase-wrt-android-tests/samples/WebPassword/index.html, usecase/usecase-wrt-android-tests/steps/WebPassword/step.js, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-5675
=> [wrt] Test for auth dialog password

usecase/usecase-wrt-android-tests/samples/InputPassword/README.md, usecase/usecase-wrt-android-tests/samples/InputPassword/index.html, usecase/usecase-wrt-android-tests/steps/InputPassword/step.js, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-4306
=> [wrt] Test for input password echoing

misc/webapi-noneservice-tests/pack.sh, misc/webapi-service-tests/pack.sh, tools/build/build_cordova.py, tools/build/pack_cordova_sample.py
- It's fine to pack cordova apps
https://crosswalk-project.org/jira/browse/XWALK-5867
=> [Cordova] Cordova build separate arch apks

misc/sampleapp-android-tests/testscripts/memorygame_appFunction.feature
https://github.com/crosswalk-project/crosswalk-demos/tree/master/MemoryGame has changed its title to "Memory Cards for Older Kids".
Unit test platform: Crosswalk Project for Android 17.46.448.1
https://crosswalk-project.org/jira/browse/XWALK-5958
=> [Crosswalk-17][misc]Update MemoryGame title in memorygame_appFunction.feature

misc/sampleapp-ios-tests/sampleapp/InAppPurchaseDemo_Build.html, misc/sampleapp-ios-tests/sampleapp/InAppPurchaseDemo_Function.html, misc/sampleapp-ios-tests/tests.full.xml, misc/sampleapp-ios-tests/tests.xml
Add 2 manual test cases for Crosswalk Sample App for iOS.
The test cases will test if the In-App Purchase API works well.
BUG=https://crosswalk-project.org/jira/browse/XWALK-5883
=> [sampleapp-ios]Add 2 manual In-App purchase test cases

apptools/apptools-windows-tests/apptools/Manifest_Command_Line_RemoteDebugging.html, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml, usecase/usecase-apptools-tests/samples-windows/Remote_Debugging/index.html, usecase/usecase-apptools-tests/tests.full.xml, usecase/usecase-apptools-tests/tests.windows.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-5809
=> [apptools-windows] Add tests to test remote debugging for apptools windows

tools/build/pack_cordova_sample.py, usecase/usecase-cordova-android-tests/samples/SetBackgroundColor/res/anotherPage.html, usecase/usecase-cordova-android-tests/samples/SetBackgroundColor/res/index.html
- It's fine to pack cordova sample app pkg
https://crosswalk-project.org/jira/browse/XWALK-5785
https://crosswalk-project.org/jira/browse/XWALK-6075
=> [Crosswalk-17][Cordova] Improve setBackGround usecase and pack script

tools/build/build_cordova.py, tools/build/pack_cordova_sample.py, usecase/usecase-cordova-android-tests/samples/SetBackgroundColor/res/anotherPage.html, usecase/usecase-cordova-android-tests/samples/SetBackgroundColor/res/index.html
- It's fine to pack cordova sample app pkg
BUG=https://crosswalk-project.org/jira/browse/XWALK-5785
BUG=https://crosswalk-project.org/jira/browse/XWALK-6075
=> [Cordova] Improve setBackGround usecase and pack script

misc/webapi-service-tests/pack.sh, tools/build/pack.py
1. Add x86_64 and arm64 options
2. Change service all-in-one packing path
=> [pack-script] Add pack support for 64bits

usecase/usecase-cordova-android-tests/samples/SharedModeLibraryDownload4.x/res/test.py
Unit test platform: Crosswalk Project for android 18.46.458.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6078
=> [Cordova] Add permission for SharedModeLibraryDownload usecase

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_FullScreen_reopen.feature
ECS2-8A:
https://crosswalk-project.org/jira/browse/XWALK-5559
=> [crosswalk-16][misc] Update steps for Crosswalk FullScreen Reopen

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_FullScreen_reopen.feature
ECS2-8A:
https://crosswalk-project.org/jira/browse/XWALK-5559
=> [crosswalk-17][misc] Update steps for Crosswalk FullScreen Reopen

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_FullScreen_reopen.feature
ECS2-8A:
Unit test Platform: Crosswalk Project for Android 18.46.457.0
https://crosswalk-project.org/jira/browse/XWALK-5559
=> [misc] Update steps for Crosswalk FullScreen Reopen

webapi/tct-geoallow-w3c-tests/manifest.json, webapi/tct-geoallow-w3c-tests/suite.json, webapi/tct-gumallow-w3c-tests/manifest.json, webapi/tct-gumallow-w3c-tests/suite.json, webapi/tct-mediacapture-w3c-tests/manifest.json, webapi/tct-mediacapture-w3c-tests/suite.json, webapi/tct-vibration-w3c-tests/manifest.json, webapi/tct-vibration-w3c-tests/suite.json, webapi/webapi-iap-xwalk-tests/manifest.json, webapi/webapi-iap-xwalk-tests/suite.json, webapi/webapi-nativefilesystem-xwalk-tests/manifest.json, webapi/webapi-nativefilesystem-xwalk-tests/suite.json, webapi/webapi-nfc-w3c-tests/manifest.json, webapi/webapi-nfc-w3c-tests/suite.json, webapi/webapi-webspeech-w3c-tests/manifest.json, webapi/webapi-webspeech-w3c-tests/suite.json
- Add permissions:</br>
tct-geoallow-w3c-tests: ACCESS_FINE_LOCATION</br>
tct-gumallow-w3c-tests: CAMERA</br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;MODIFY_AUDIO_SETTINGS</br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;RECORD_AUDIO</br>
tct-mediacapture-w3c-tests: CAMERA</br>
webapi-webspeech-w3c-tests: MODIFY_AUDIO_SETTINGS</br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;RECORD_AUDIO</br>
webapi-nativefilesystem-xwalk-tests: WRITE_EXTERNAL_STORAGE</br> …
=> [webapi] Add permissions in manifest.json

webapi/tct-flexiblebox-css3-tests/flexiblebox/CSS3FlexBox_initial_value.html
BUG=https://crosswalk-project.org/jira/browse/XWALK-3227
=> [Crosswalk-16][webapi] Update flexiblebox test

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_Canvas_reopen.feature, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_Cookie_reopen.feature, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_restart.feature
ECS2-8A:
Unit test Platform: Crosswalk Project for Android 18.46.462.0
https://crosswalk-project.org/jira/browse/XWALK-5583
=> [misc] Update automation steps for webmanu-system-android-tests

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_Canvas_reopen.feature, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_Cookie_reopen.feature, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_restart.feature
ECS2-8A:
https://crosswalk-project.org/jira/browse/XWALK-5583
=> [crosswalk-17][misc] Update automation steps for webmanu-system-android-tests

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_Canvas_reopen.feature, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_Cookie_reopen.feature, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_restart.feature
ECS2-8A:
https://crosswalk-project.org/jira/browse/XWALK-5583
=> [crosswalk-16][misc] Update automation steps for webmanu-system-android-tests

webapi/tct-webgl-nonw3c-tests/tests.xml
- Add timeout option to tests.xml for uniform-samplers-test
Unit test Platform: Android Crosswalk Beta 15.44.384.9
BUG=https://crosswalk-project.org/jira/browse/XWALK-5248
=> [webapi] Update tests.xml for test uniform-samplers-test

misc/sampleapp-android-tests/sampleapp/comm.py, misc/sampleapp-android-tests/sampleapp/extensionsandroid_pack.py
XWALK-5746 Move external extensions management framework  down into Crosswalk Webview
extensions-android is updated by https://github.com/crosswalk-project/crosswalk-samples/pull/38
BUG=https://crosswalk-project.org/jira/browse/XWALK-5987
=> [misc] Update extensions layout in extensions-android

webapi/tct-indexeddb-w3c-tests/indexeddb/IDBRequest_error_default_value.html, webapi/tct-indexeddb-w3c-tests/indexeddb/IDBRequest_error_exception_InvalidStateError.html, webapi/tct-indexeddb-w3c-tests/indexeddb/IDBRequest_error_exist.html, webapi/tct-indexeddb-w3c-tests/indexeddb/IDBRequest_error_readonly.html, webapi/tct-indexeddb-w3c-tests/indexeddb/IDBRequest_error_type.html, webapi/tct-indexeddb-w3c-tests/indexeddb/IDBTransaction_onabort_base.html
BUG=https://crosswalk-project.org/jira/browse/XWALK-5933
=> [webapi] Update indexedDB tests to replace DOMError with DOMException

apptools/apptools-android-tests/testapp/manifest_name_chinese/manifest.json, apptools/apptools-ios-tests/testapp/manifest_name_chinese/manifest.json, apptools/apptools-linux-tests/testapp/manifest_name_chinese/manifest.json, apptools/apptools-sampleapp-tests/sampleapp-android/Crosswalk_Apptools_SampleApp_Spacedodgegame_Build.html, apptools/apptools-sampleapp-tests/sampleapp-deb/Crosswalk_Apptools_SampleApp_Spacedodgegame_Build_Deb.html, apptools/apptools-sampleapp-tests/sampleapp-ios/Crosswalk_Apptools_SampleApp_Spacedodgegame_Build_iOS.html, apptools/apptools-sampleapp-tests/sampleapp-windows/Crosswalk_Apptools_SampleApp_Spacedodgegame_Build_Windows.html, apptools/apptools-sampleapp-tests/tests.android.xml, apptools/apptools-sampleapp-tests/tests.deb.xml, apptools/apptools-sampleapp-tests/tests.full.xml, apptools/apptools-sampleapp-tests/tests.ios.xml, apptools/apptools-sampleapp-tests/tests.windows.xml, apptools/apptools-windows-tests/testapp/manifest_name_chinese/manifest.json
Impacted tests(approved): new 0, update 8, delete 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6124
=> [apptools] Update 'xwalk_target_platforms' for apptools

apptools/apptools-android-tests/apptools/crosswalk_app_targets.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
Impacted tests(approved): new 14, update 0, delete 0
Unit test result summary: pass 14, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6123
=> [apptools-android] Add tests to test crosswalk-app --android-targets for apptools android

webapi/tct-indexeddb-w3c-tests/indexeddb/IDBObjectStore_createIndex_exception_NotSupportedError.html, webapi/tct-indexeddb-w3c-tests/indexeddb/IDBTransaction_onabort_base.html
https://crosswalk-project.org/jira/browse/XWALK-5933
=> [webapi] Update indexedDB test

usecase/usecase-webapi-xwalk-tests/suite.json
https://crosswalk-project.org/jira/browse/XWALK-5905
=> [usecase] Add all-in-one config for usecase docroot

wrt/wrt-internetstdmanu-android-tests/testapp/web_scheme_content/manifest.json, wrt/wrt-packagemgtmanu-android-tests/testapp/web_openfile_thirdpart_tests/manifest.json
Unit test platform: Crosswalk Project for Android 18.46.462.0
https://crosswalk-project.org/jira/browse/XWALK-6097
=> [wrt] Add EXTERNAL_STORAGE permissions

apptools/apptools-android-tests/apptools/comm.py
https://crosswalk-project.org/jira/browse/XWALK-6126
Impacted tests(approved): new 0, update 150, delete 0
Unit test result summary: pass 84, fail 66, block 0
=> [apptools-android] Skip emulator checkpoints on Travis-CI for apptools android

cordova/cordova-feature-android-tests/feature/app_multiple_apk_false.py, cordova/cordova-feature-android-tests/feature/app_multiple_apk_true.py, cordova/cordova-feature-android-tests/feature/comm.py, cordova/cordova-feature-android-tests/tests.full.xml, cordova/cordova-feature-android-tests/tests.xml, cordova/cordova-sampleapp-android-tests/sampleapp/comm.py, cordova/cordova-webapp-android-tests/webapp/comm.py
Impacted tests(approved): new 2, update 34, delete 0
Unit test result summary: pass 36, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5862
=> [Cordova] Add cases for xwalkMultipleApk

usecase/usecase-cordova-android-tests/samples/Camera/js/main.js
https://crosswalk-project.org/jira/browse/XWALK-4704
=> [Cordova] enable the camera uscase selection

usecase/usecase-cordova-android-tests/samples/Camera/js/main.js
https://crosswalk-project.org/jira/browse/XWALK-4704
=> [Crosswalk-16][Cordova] enable the camera uscase selection

usecase/usecase-cordova-android-tests/samples/Camera/js/main.js
https://crosswalk-project.org/jira/browse/XWALK-4704
=> [Crosswalk-17][Cordova] enable the camera uscase selection

cordova/cordova-appsecurityapi-android-tests/tests.full.xml
- the num of tests.full.xml is less than tests.xml, so need to update the  tests.full.xml  to make it be consistent with the tests.xml.
=> [Cordova][hotfix] Update the tests.full.xml

usecase/usecase-wrt-android-tests/samples/WebAppXwalkHost/res/manifest.json
MEMO PAD8:
https://crosswalk-project.org/jira/browse/XWALK-5747
=> [crosswalk-17][usecase] Update manifest for WebAppTaskManager

usecase/usecase-wrt-android-tests/samples/WebAppXwalkHost/res/manifest.json
MEMO PAD8:
https://crosswalk-project.org/jira/browse/XWALK-5747
=> [crosswalk-16][usecase] Update manifest for WebAppTaskManager

usecase/usecase-wrt-android-tests/samples/WebAppXwalkHost/res/manifest.json
MEMO PAD8:
Unit test Platform: Crosswalk Project for Android 18.46.465.0
https://crosswalk-project.org/jira/browse/XWALK-5747
=> [usecase] Update manifest for WebAppTaskManager

tools/atip/atip/android/android.py
=> [crosswalk-16][atip-android] Update atip for geolocation operation

usecase/usecase-webapi-xwalk-tests/testscripts/Geolocation.feature
=> [crosswalk-16][usecase] Update steps for Geolocation automation

tools/atip/atip/android/android.py
=> [crosswalk-17][atip-android] Update atip for geolocation operation

usecase/usecase-webapi-xwalk-tests/testscripts/Geolocation.feature
=> [crosswalk-17][usecase] Update steps for Geolocation automation

usecase/usecase-webapi-xwalk-tests/testscripts/Geolocation.feature
ECS2-8A:
Unit test Platform: Crosswalk Project for Android 18.46.469.0
=> [usecase] Update steps for Geolocation automation

tools/atip/atip/android/android.py
ECS2-8A:
Unit test Platform: Crosswalk Project for Android 18.46.469.0
=> [atip-android] Update atip for geolocation operation

misc/webapi-noneservice-tests/pack.sh, misc/webapi-service-tests/pack.sh
- It's fine to pack all in one packages
https://crosswalk-project.org/jira/browse/XWALK-5430
=> [Cordova] Add 64 bit support for all in one pack script

usecase/usecase-cordova-android-tests/samples/CrosswalkVersion/res/test.py
Unit test platform: Crosswalk Project for android 17.46.448.5
https://crosswalk-project.org/jira/browse/XWALK-5430
=> [Cordova] Add 64 bit support for usecase

cordova/cordova-feature-android-tests/feature/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/comm.py, cordova/cordova-webapp-android-tests/webapp/comm.py
Impacted tests(approved): new 0, update 36, delete 0
Unit test platform: Crosswalk Project for android 17.46.448.5
Unit test result summary: pass 36, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-5430
=> [Cordova] Add 64 bit support for cordova feature cases

wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_arm_shared.html, wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_arm_x86_shared.html, wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_arm_embeded.html, wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_arm_shared_x86_2.html, wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_arm_shared_x86_crosswalk.html, wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_x86_embeded.html, wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_x86_shared_arm_2.html, wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_mismatch_x86_shared_arm_crosswalk.html, wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_arch_x86_shared.html, wrt/wrt-sharedmodemanu-android-tests/sharedmodemanu/Crosswalk_shared_download_break.html
https://crosswalk-project.org/jira/browse/XWALK-6148
=> [wrt] Clean up residuary make_apk.py dependent tests

usecase/usecase-webapi-xwalk-tests/samples/SetCookie/index.html, usecase/usecase-webapi-xwalk-tests/samples/SetCookie/res/iframe.html, usecase/usecase-webapi-xwalk-tests/suite.json
- Update setcookie resources to aio copylist
- Remove not found style path
=> [usecase] Update setcookie test

webapi/webapi-webrtc-w3c-tests/tests.full.xml, webapi/webapi-webrtc-w3c-tests/tests.xml, webapi/webapi-webrtc-w3c-tests/webrtc/RTCDataChannel_onbufferedamountlow.html
Unit test Platform: Crosswalk Project for Android 18.46.465.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5667
=> [webapi] Add bufferedamountlow event test for WebRTC

webapi/webapi-resourcetiming-w3c-tests/resourcetiming/resource-timing-workerstart.html, webapi/webapi-resourcetiming-w3c-tests/resourcetiming/resource-timing.worker.html, webapi/webapi-resourcetiming-w3c-tests/resourcetiming/resource-timing.worker.js, webapi/webapi-resourcetiming-w3c-tests/resourcetiming/resources/COPYING, webapi/webapi-resourcetiming-w3c-tests/resourcetiming/resources/blank-iframe.html, webapi/webapi-resourcetiming-w3c-tests/resourcetiming/resources/service-worker.js, webapi/webapi-resourcetiming-w3c-tests/resourcetiming/resources/test-helpers.js, webapi/webapi-resourcetiming-w3c-tests/tests.full.xml, webapi/webapi-resourcetiming-w3c-tests/tests.xml
- Add tests to check Performance timeline for workers
- Add tests to check PerformanceResourceTiming.workStart attribute
Impacted TCs num(approved): New 4, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 18.46.469.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5672
BUG=https://crosswalk-project.org/jira/browse/XWALK-5673
=> [webapi] Add Resource Timing tests

wrt/wrt-sharedmode-android-tests/Crosswalk_sharedmode.conf
=> [wrt] Remove useless config in sharedmode

apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-5829
=> [apptools-android] Update subcase num for apptools android

apptools/apptools-windows-tests/apptools/Manifest_Extension.html, apptools/apptools-windows-tests/testapp/xwalk_echo_extension/extension/README.md, apptools/apptools-windows-tests/testapp/xwalk_echo_extension/index.html, apptools/apptools-windows-tests/testapp/xwalk_echo_extension/manifest.json, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-5438
=> [apptools-windows] Add tests to test packaging of extensions for apptools windows

misc/crosswalk-compatibility-android-tests/compatibility/upgrade_embedded2embedded_aVn-1Vn_aVnVn.html, misc/crosswalk-compatibility-android-tests/compatibility/upgrade_embedded2embedded_aVn-1Vn_bVnVn.html, misc/crosswalk-compatibility-android-tests/compatibility/upgrade_shared2embedded_aVn-1Vn_aVnVn.html, misc/crosswalk-compatibility-android-tests/compatibility/upgrade_shared2embedded_aVn-1Vn_bVnVn.html, misc/crosswalk-compatibility-android-tests/compatibility/upgrade_shared2shared_aVn-1Vn-1_bVnVn.html, misc/crosswalk-compatibility-android-tests/compatibility/upgrade_shared2shared_aVn-1Vn_aVnVn.html, misc/crosswalk-compatibility-android-tests/compatibility/upgrade_shared2shared_aVn-1Vn_bVnVn.html, misc/crosswalk-compatibility-android-tests/compatibility/upgrade_shared2shared_aVnVn-1_aVnVn.html, misc/crosswalk-compatibility-android-tests/compatibility/upgrade_shared2shared_aVnVn-1_bVnVn.html, misc/crosswalk-compatibility-android-tests/suite.json, misc/crosswalk-compatibility-android-tests/testapps/demo/index.html, misc/crosswalk-compatibility-android-tests/testapps/demo/manifest.json, misc/crosswalk-compatibility-android-tests/testapps/demo_upgrade/index.html, misc/crosswalk-compatibility-android-tests/testapps/demo_upgrade/manifest.json, misc/crosswalk-compatibility-android-tests/tests.full.xml, misc/crosswalk-compatibility-android-tests/tests.xml
Impacted tests(approved): new 9, update 0, delete 0
Unit test result summary: pass 9, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5774
=> [misc] Add app upgrade tests in compatibility

wrt/wrt-upgrademanu-android-tests/upgrademanu/Crosswalk_Embedded_Embedded_Version_other.html
https://crosswalk-project.org/jira/browse/XWALK-5774
=> [wrt] Fix description typo in upgrademanual

webapi/tct-vibration-w3c-tests/suite.json, webapi/webapi-webcl-nonw3c-tests/suite.json
https://crosswalk-project.org/jira/browse/XWALK-6194
=> [Windows] Drop WebCL, Vibration related tests from webapi

wrt/wrt-packagemgtmanu-android-tests/packagemgtmanu/Crosswalk_WebApp_openfile_docx_windows.html, wrt/wrt-packagemgtmanu-android-tests/packagemgtmanu/Crosswalk_WebApp_openfile_html.html, wrt/wrt-packagemgtmanu-android-tests/suite.json, wrt/wrt-packagemgtmanu-android-tests/testapp/web_openfile_thirdpart_tests/index.windows.html, wrt/wrt-packagemgtmanu-android-tests/tests.windows.full.xml, wrt/wrt-packagemgtmanu-android-tests/tests.windows.xml
Impacted tests(approved): new 6, update 0, delete 0
Unit test platform: Crosswalk Project for Windows 18.46.457.0
Unit test result summary: pass 4, fail 2, block 0
https://crosswalk-project.org/jira/browse/XWALK-5983
=> [Windows] Add manual package mgt cases

misc/webapi-service-docroot-tests/pack.sh, tools/build/released_suites/PLATFORMS
=> [pack] Add usecase tinyweb related resources to docroot package

webapi/tct-geodeny-w3c-tests/w3c-geodeny-app/testscripts/Geolocation_getCurrentPosition_operation_failed.feature, webapi/tct-geodeny-w3c-tests/w3c-geodeny-app/testscripts/Geolocation_watchPosition_operation_failed.feature, webapi/tct-geodeny-w3c-tests/w3c-geodeny-app/testscripts/t.feature
MEMO8 PAD:
Unit test Platform: Crosswalk Project for Android 18.46.471.0
https://crosswalk-project.org/jira/browse/XWALK-5595
=> [webapi] Improve steps for tct-geodeny-w3c-tests automation tests

webapi/tct-geodeny-w3c-tests/w3c-geodeny-app/testscripts/Geolocation_getCurrentPosition_operation_failed.feature, webapi/tct-geodeny-w3c-tests/w3c-geodeny-app/testscripts/Geolocation_watchPosition_operation_failed.feature, webapi/tct-geodeny-w3c-tests/w3c-geodeny-app/testscripts/t.feature
MEMO8 PAD:
Unit test result summary: Pass 0, Fail 3, Blocked 0
Issue tracked by https://crosswalk-project.org/jira/browse/XWALK-5595
=> [crosswalk-16][webapi] Improve steps for tct-geodeny-w3c-tests automation tests

webapi/tct-geodeny-w3c-tests/w3c-geodeny-app/testscripts/Geolocation_getCurrentPosition_operation_failed.feature, webapi/tct-geodeny-w3c-tests/w3c-geodeny-app/testscripts/Geolocation_watchPosition_operation_failed.feature, webapi/tct-geodeny-w3c-tests/w3c-geodeny-app/testscripts/t.feature
MEMO8 PAD:
Unit test result summary: Pass 0, Fail 3, Blocked 0
Issue tracked by https://crosswalk-project.org/jira/browse/XWALK-5595
=> [crosswalk-17][webapi] Improve steps for tct-geodeny-w3c-tests automation tests

apptools/apptools-android-tests/apptools/Manifest_Permissions_DisableCamera.html, apptools/apptools-android-tests/apptools/Manifest_Permissions_EnableCamera.html, apptools/apptools-android-tests/apptools/manifest_xwalk_permissions.py, apptools/apptools-android-tests/testapp/camera_permissions_disable/index.html, apptools/apptools-android-tests/testapp/camera_permissions_disable/manifest.json, apptools/apptools-android-tests/testapp/camera_permissions_enable/index.html, apptools/apptools-android-tests/testapp/camera_permissions_enable/manifest.json, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-5026
=> [apptools-android] Add tests to test permissions for apptools android

apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-6206
=> [apptools-android] Add tests to test the way of packing external extensions for apptools android

usecase/usecase-extension-android-tests/README.md, usecase/usecase-extension-android-tests/samples/ExtensionManager/index.html
https://crosswalk-project.org/jira/browse/XWALK-6148
=> [usecase-extension] Clean up residuary make_apk.py dependent tests

misc/webmanu-system-android-tests/tests.full.xml, misc/webmanu-system-android-tests/tests.xml, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_upgrade.feature, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_LocalStorage_upgrade.feature
Unit test platform: Crosswalk Project for Android 16.45.421.19
BUG=https://crosswalk-project.org/jira/browse/XWALK-6037
BUG=https://crosswalk-project.org/jira/browse/XWALK-6052
=> [Crosswalk-16][misc] Update upgrade method in feature files

usecase/usecase-wrt-android-tests/suite.json
https://crosswalk-project.org/jira/browse/XWALK-4425
=> [usecase-wrt] Fix video copylist

tools/atip/atip/common/steps.py
https://crosswalk-project.org/jira/browse/XWALK-6105
=> [atip] Improve atip to support windows platform

tools/atip/atip/web/steps.py
MEMO PAD8:
webapi-devicecapabilities-w3c-tests:
Impacted TCs num(approved): New 0, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 18.46.465.0
tct-webstorage-w3c-tests:
webapi-devicecapabilities-w3c-tests:
Impacted TCs num(approved): New 0, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 18.46.465.0
Unit test result summary: Pass 1, Fail 1, Blocked 0
https://crosswalk-project.org/jira/browse/XWALK-6251
=> [atip] Improve atip for crosswalk webdriver of python

misc/sampleapp-android-tests/testscripts/hexgl_appFunction.feature
HexGL upstream code update to https://github.com/BKcore/HexGL
BUG=https://crosswalk-project.org/jira/browse/XWALK-6164
=> [misc] Update hexgl_appFunction due to HexGL changed

webapi/tct-webgl-nonw3c-tests/webgl/khronos/buffer-data-array-buffer.html
Unit test Platform: Crosswalk Project for Android 18.48.475.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6259
=> [webapi] Update bufferSubData test for WebGL

wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Icon_NoFile.html, wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Icon_ThreeIcon.html, wrt/wrt-rtcoremanu-android-tests/rtcoremanu/Crosswalk_Manifest_Icon_TwoIcon.html, wrt/wrt-rtcoremanu-android-tests/testapp/manifest_icon_twoicon_tests/manifest.json
BUG=https://crosswalk-project.org/jira/browse/XWALK-6247
=> [wrt] Update test description due to app tools output changed

webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/ecmascript_simd_tests.js, webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/load_stroe_test.html, webapi/webapi-simd-nonw3c-tests/tests.full.xml, webapi/webapi-simd-nonw3c-tests/tests.xml
Impacted TCs num(approved): New 0, Update 37, Delete 1
Unit test Platform: Crosswalk Project for Android 18.48.477.0
Unit test result summary: Pass 34, Fail 3, Blocked 0
https://crosswalk-project.org/jira/browse/XWALK-6244
=> [webapi] Update SIMD tests with M48 rebase

webapi/tct-jsenhance-html5-tests/jsenhance/window_hashchange_HashChangeEventInit.html, webapi/tct-jsenhance-html5-tests/tests.full.xml, webapi/tct-jsenhance-html5-tests/tests.xml
Unit test Platform: Crosswalk Project for Android 18.48.475.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6217
=> [webapi] Update jsenhance test

webapi/tct-geoallow-w3c-tests/w3c-geoallow-app/testscripts/t00002.feature, webapi/tct-geoallow-w3c-tests/w3c-geoallow-app/testscripts/t00031.feature, webapi/tct-geoallow-w3c-tests/w3c-geoallow-app/testscripts/t00062.feature
MEMO8 PAD:
https://crosswalk-project.org/jira/browse/XWALK-5595
=> [crosswalk-17][webapi] Update steps for tct-geoallow-w3c-tests automation tests

webapi/webapi-serviceworkers-w3c-tests/serviceworkers/requestinit-referrer.html, webapi/webapi-serviceworkers-w3c-tests/tests.full.xml, webapi/webapi-serviceworkers-w3c-tests/tests.xml
Impacted TCs num(approved): New 5, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 18.46.474.0
Unit test result summary: Pass 5, Fail 0, Blocked 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5687
=> [webapi] Add RequestInit.referrer test

cordova/cordova-feature-android-tests/feature/app_multiple_apk_false.py, cordova/cordova-feature-android-tests/feature/app_multiple_apk_true.py, cordova/cordova-feature-android-tests/feature/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/comm.py, cordova/cordova-webapp-android-tests/webapp/comm.py, tools/build/pack_cordova_sample.py
- Fail bug: XWALK-6260
Impacted tests(approved): new 0, update 36, delete 0
Unit test platform: Crosswalk Project for android 19.48.483.0
Unit test result summary: pass 35, fail 1, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6311
=> [Cordova] Use cca to build 64-bit cordova app

webapi/tct-csp-w3c-tests/csp/csp_base-uri_cross-origin_block.cgi, webapi/tct-csp-w3c-tests/csp/csp_plugin-types_blocked-manual.cgi, webapi/tct-csp-w3c-tests/csp/reference/csp_base-uri_cross-origin_block-ref.html, webapi/tct-csp-w3c-tests/tests.full.xml, webapi/tct-csp-w3c-tests/tests.xml
Unit test Platform: Crosswalk Project for Android 18.46.474.0
https://crosswalk-project.org/jira/browse/XWALK-4925
=> [webapi] Update CSP test

wrt/wrt-packagemgtmanu-android-tests/wrt-packagemgt-app/testscripts/Crosswalk_WebApp_Icon_Launcher.feature
https://crosswalk-project.org/jira/browse/XWALK-5941
=> [crosswalk-16][wrt] Improve bdd steps for wrt-packagemgtmanu-android-tests

wrt/wrt-packagemgtmanu-android-tests/wrt-packagemgt-app/testscripts/Crosswalk_WebApp_Icon_Launcher.feature
Unit test Platform: Crosswalk Project for Android 18.48.477.0
https://crosswalk-project.org/jira/browse/XWALK-5941
=> [wrt] Improve bdd steps for wrt-packagemgtmanu-android-tests

wrt/wrt-packagemgtmanu-android-tests/wrt-packagemgt-app/testscripts/Crosswalk_WebApp_Icon_Launcher.feature
https://crosswalk-project.org/jira/browse/XWALK-5941
=> [crosswalk-17][wrt] Improve bdd steps for wrt-packagemgtmanu-android-tests

tools/codescan/separate.sh
Many thanks to @pjckcs for creating this script.
=> [tools] Upload script to separate files per license

tools/build/released_suites/Android-Platform, usecase/usecase-wrt-android-tests/suite.json
Unit test platform: Crosswalk Project for Android 18.48.484.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-4425
=> [usecase-wrt] Update video resource for ManifestCSP

misc/webapi-service-docroot-tests/pack.sh, tools/build/released_suites/PLATFORMS, usecase/usecase-wrt-android-tests/suite.json
Unit test platform: Crosswalk Project for Android 17.46.448.6
https://crosswalk-project.org/jira/browse/XWALK-4425
=> [Crosswalk-17][usecase-wrt] Update video resource for ManifestCSP

doc/Apptools_Test_Suite_Developer_Guide.md, doc/Apptools_Test_Suite_User_Guide.md
- Add developer guide for apptools testsuit
- Add user guide for apptools testsuit
=> [doc-apptools] Add developer guide and user guide for apptools

misc/webapi-noneservice-tests/pack.sh, misc/webapi-service-tests/pack.sh, tools/build/README.md, tools/build/build_cordova.py, tools/build/pack.py, tools/build/pack_cordova_sample.py
- Fail bug: XWALK-6260/6325
Impacted tests(approved): new 0, update 119, delete 0
Unit test platform: Crosswalk Project for android 19.48.483.0
Unit test result summary: pass 92, fail 25, block 2
https://crosswalk-project.org/jira/browse/XWALK-6202
=> [Cordova]Remove build scripts for Cordova Android 3.6

webapi/tct-geoallow-w3c-tests/w3c-geoallow-app/testscripts/t00002.feature, webapi/tct-geoallow-w3c-tests/w3c-geoallow-app/testscripts/t00031.feature, webapi/tct-geoallow-w3c-tests/w3c-geoallow-app/testscripts/t00062.feature
MEMO8 PAD:
Unit test Platform: Crosswalk Project for Android 18.46.465.0
https://crosswalk-project.org/jira/browse/XWALK-5595
=> [webapi] Update steps for tct-geoallow-w3c-tests automation tests

webapi/tct-geoallow-w3c-tests/w3c-geoallow-app/testscripts/t00002.feature, webapi/tct-geoallow-w3c-tests/w3c-geoallow-app/testscripts/t00031.feature, webapi/tct-geoallow-w3c-tests/w3c-geoallow-app/testscripts/t00062.feature
MEMO8 PAD:
https://crosswalk-project.org/jira/browse/XWALK-5595
=> [crosswalk-16][webapi] Update steps for tct-geoallow-w3c-tests automation tests

webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceAcceleration_attributes_readonly.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceAcceleration_attributes_test.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceMotionEvent_attributes_readonly.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceMotionEvent_attributes_test.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceOrientationEvent_attributes_readonly.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceOrientationEvent_attributes_test.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceRotationRate_attributes_basic.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceRotationRate_attributes_test.html, webapi/tct-deviceorientation-w3c-tests/tests.full.xml, webapi/tct-deviceorientation-w3c-tests/tests.xml
- Update attribute init value according XWALK-2460 comment.
- Fix timeout still execute issue when test finished in Windows
Impacted tests(approved): new 0, update 40, delete 0
Unit test platform: Crosswalk Project for Windows 17.45.426.0
Unit test result summary: pass 36, fail 4, block 0
Impacted tests(approved): new 0, update 40, delete 0
Unit test platform: Crosswalk Project for Windows 17.45.426.0
Unit test result summary: pass 36, fail 4, block 0
Impacted tests(approved): new 0, update 40, delete 0
Unit test result summary: pass 40, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5634
=> [webapi] Fix timeout issue in DeviceOrientation for Windows

webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceAcceleration_attributes_readonly.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceAcceleration_attributes_test.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceMotionEvent_attributes_readonly.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceMotionEvent_attributes_test.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceOrientationEvent_attributes_readonly.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceOrientationEvent_attributes_test.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceRotationRate_attributes_basic.html, webapi/tct-deviceorientation-w3c-tests/deviceorientation/DeviceRotationRate_attributes_test.html, webapi/tct-deviceorientation-w3c-tests/tests.full.xml, webapi/tct-deviceorientation-w3c-tests/tests.xml
- Update attribute init value according XWALK-2460 comment.
- Fix timeout still execute issue when tests finished in Windows
Impacted tests(approved): new 0, update 40, delete 0
Unit test platform: Crosswalk Project for Windows 17.45.426.0
Unit test result summary: pass 36, fail 4, block 0
Impacted tests(approved): new 0, update 40, delete 0
Unit test result summary: pass 40, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-5634
=> [Crosswalk-17][webapi] Fix timeout issue in DeviceOrientation for Windows

tools/build/build_cordova.py
Unit test platform: Crosswalk Project for android 19.48.483.0
https://crosswalk-project.org/jira/browse/XWALK-6220
=> [Cordova] Implement app_version cmd for Cordova build

webapi/tct-gumallow-w3c-tests/gumallow/mediastreamtrack-remote.html, webapi/tct-gumallow-w3c-tests/tests.full.xml, webapi/tct-gumallow-w3c-tests/tests.xml
Impacted TCs num(approved): New 2, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 19.48.485.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5934
=> [webapi] Add MediaStreamTrack.remote test

tools/build/build_android.py
=> Fix building issue on app-tools, do not set arch option when building

misc/webmanu-system-android-tests/suite.json, misc/webmanu-system-android-tests/systemmanu/Crosswalk_Geolocation_watchPosition_background.html, misc/webmanu-system-android-tests/testapp/geolocation/index.html, misc/webmanu-system-android-tests/testapp/geolocation/manifest.json, misc/webmanu-system-android-tests/tests.full.xml, misc/webmanu-system-android-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-4637
=> [misc] Add tests for Geolocation.watchPosition in background

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_restart.feature
Memo Pad8:
https://crosswalk-project.org/jira/browse/XWALK-6386
=> [crosswalk-17][misc] Improve bdd steps for webmanu-system-android-tests

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_restart.feature
Memo Pad8:
Unit test Platform: Crosswalk Project for Android 18.48.477.0
https://crosswalk-project.org/jira/browse/XWALK-6386
=> [crosswalk-18][misc] Improve bdd steps for webmanu-system-android-tests

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_restart.feature
Memo Pad8:
Unit test Platform: Crosswalk Project for Android 19.48.487.0
https://crosswalk-project.org/jira/browse/XWALK-6386
=> [misc] Improve bdd steps for webmanu-system-android-tests

wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_Lock_And_Unlock_Screen.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_BackKey_Back.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_BackKey_Exit.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Touch_Gesture_Click.feature
Unit test platform: Crosswalk Project for Android 17.46.447.0
https://crosswalk-project.org/jira/browse/XWALK-6143
=> [Crosswalk-17][wrt] Update uiautomator steps due to test website changed

wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_Lock_And_Unlock_Screen.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_BackKey_Back.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_BackKey_Exit.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Touch_Gesture_Click.feature
https://crosswalk-project.org/jira/browse/XWALK-6143
=> [Crosswalk-18][wrt] Update uiautomator steps due to test website changed

wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_Lock_And_Unlock_Screen.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_BackKey_Back.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_BackKey_Exit.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Touch_Gesture_Click.feature
BUG=https://crosswalk-project.org/jira/browse/XWALK-6143
=> [wrt] Update uiautomator steps due to test website changed

usecase/usecase-webapi-xwalk-tests/samples/Fingerprint/README.md, usecase/usecase-webapi-xwalk-tests/samples/Fingerprint/fingerprint/manifest.json, usecase/usecase-webapi-xwalk-tests/samples/Fingerprint/index.html, usecase/usecase-webapi-xwalk-tests/steps/Fingerprint/step.js, usecase/usecase-webapi-xwalk-tests/suite.json, usecase/usecase-webapi-xwalk-tests/tests.android.xml, usecase/usecase-webapi-xwalk-tests/tests.full.xml
Integrate crosswalk android extension fingerprint feature example
for usecase webapi test suite.
Unit test platform: Crosswalk for Android 19.48.489.0
Unit test result summary: pass 1, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6233
=> [usecase-webapi] Integrate the fingerprint feature test case

misc/sampleapp-ios-tests/README.md, misc/sampleapp-ios-tests/sampleapp/FingerprintDemo_Build.html, misc/sampleapp-ios-tests/sampleapp/FingerprintDemo_Function.html, misc/sampleapp-ios-tests/tests.full.xml, misc/sampleapp-ios-tests/tests.xml
Add 2 manual fingerprint test cases to test if the Crosswalk
fingerprint extension feature works well.
BUG=https://crosswalk-project.org/jira/browse/XWALK-6234
=> [sample-ios] Add 2 manual fingerprint test cases for iOS

tools/build/pack.py
=> Update pack.py to support build package for GBK encoding on Windows

tools/workstat/git_stat.py
./git_stat.py -r /path/to/crosswalk-test-suite --since 2016-1-1
BUG=https://crosswalk-project.org/jira/browse/XWALK-6119
=> [tools] Add git statistics script

usecase/usecase-webapi-xwalk-tests/samples/SetCookie/res/headers.cgi, usecase/usecase-webapi-xwalk-tests/samples/SetCookie/res/iframe.html
Unit test platform: Crosswalk Project for Android 19.48.491.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6315
=> [usecase] Update SetCookie sample

usecase/usecase-webapi-xwalk-tests/samples/SetCookie/res/headers.cgi, usecase/usecase-webapi-xwalk-tests/samples/SetCookie/res/iframe.html
Unit test platform: Crosswalk Project for Android 18.48.477.0
https://crosswalk-project.org/jira/browse/XWALK-6315
=> [Crosswalk-18][usecase] Update SetCookie sample

apptools/apptools-android-tests/apptools/manifest_xwalk_target_platforms.py, apptools/apptools-android-tests/testapp/manifest_xwalk_target_platforms/manifest.json, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml, apptools/apptools-ios-tests/apptools/manifest_xwalk_target_platforms.py, apptools/apptools-ios-tests/testapp/manifest_xwalk_target_platforms/android_platform/manifest.json, apptools/apptools-ios-tests/testapp/manifest_xwalk_target_platforms/iOS_platform/manifest.json, apptools/apptools-ios-tests/tests.full.xml, apptools/apptools-ios-tests/tests.xml, apptools/apptools-linux-tests/apptools/manifest_xwalk_target_platforms.py, apptools/apptools-linux-tests/testapp/manifest_xwalk_target_platforms/android_platform/manifest.json, apptools/apptools-linux-tests/testapp/manifest_xwalk_target_platforms/deb_platform/manifest.json, apptools/apptools-linux-tests/tests.full.xml, apptools/apptools-linux-tests/tests.xml, apptools/apptools-windows-tests/apptools/manifest_xwalk_target_platforms.py, apptools/apptools-windows-tests/testapp/manifest_xwalk_target_platforms/android_platform/manifest.json, apptools/apptools-windows-tests/testapp/manifest_xwalk_target_platforms/windows_platform/manifest.json, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-6020
Impacted tests(approved): new 7, update 0, delete 0
Unit test result summary: pass 5, fail 2, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6407
=> [apptools] Add tests to test setting 'xwalk_target_platforms' for apptools

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_restart.feature, usecase/usecase-wrt-android-tests/testscripts/WebAppTaskManager.feature, wrt/wrt-securitymanu-android-tests/wrt-security-app/testscripts/Crosswalk_WebApp_Certificate_Trusted_ReOpen.feature, wrt/wrt-securitymanu-android-tests/wrt-security-app/testscripts/Crosswalk_WebApp_Certificate_Untrusted_ReOpen.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Terminated_TaskManager.feature
=> [crosswalk-17][wrt] Improve steps for bdd tests

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_restart.feature, usecase/usecase-wrt-android-tests/testscripts/WebAppTaskManager.feature, wrt/wrt-securitymanu-tests/wrt-security-app/testscripts/Crosswalk_WebApp_Certificate_Trusted_ReOpen.feature, wrt/wrt-securitymanu-tests/wrt-security-app/testscripts/Crosswalk_WebApp_Certificate_Untrusted_ReOpen.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature, wrt/wrt-uxmanu-android-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Terminated_TaskManager.feature
Memo Pad8:
Unit test Platform: Crosswalk Project for Android 18.48.477.0
=> [crosswalk-18][wrt] Improve steps for bdd tests

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_restart.feature, usecase/usecase-wrt-android-tests/testscripts/WebAppTaskManager.feature, wrt/wrt-securitymanu-tests/wrt-security-app/testscripts/Crosswalk_WebApp_Certificate_Trusted_ReOpen.feature, wrt/wrt-securitymanu-tests/wrt-security-app/testscripts/Crosswalk_WebApp_Certificate_Untrusted_ReOpen.feature, wrt/wrt-uxmanu-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Integration_Switch.feature, wrt/wrt-uxmanu-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Terminated_TaskManager.feature
Memo Pad8:
Unit test Platform: Crosswalk Project for Android 19.48.493.0
=> [wrt] Improve steps for bdd tests

apptools/apptools-linux-tests/tests.full.xml, apptools/apptools-linux-tests/tests.xml, usecase/usecase-apptools-tests/inst.deb.py, usecase/usecase-apptools-tests/samples-deb/AppToolsHelpUsage/README.md, usecase/usecase-apptools-tests/samples-deb/AppToolsHelpUsage/index.html, usecase/usecase-apptools-tests/samples-deb/AppToolsOptions/README.md, usecase/usecase-apptools-tests/samples-deb/AppToolsOptions/index.html, usecase/usecase-apptools-tests/samples-deb/ManifestDisplay/README.md, usecase/usecase-apptools-tests/samples-deb/ManifestDisplay/index.html, usecase/usecase-apptools-tests/samples-deb/ManifestDisplay/res/browser/index.html, usecase/usecase-apptools-tests/samples-deb/ManifestDisplay/res/fullscreen/index.html, usecase/usecase-apptools-tests/samples-deb/ManifestDisplay/res/minimal_ui/index.html, usecase/usecase-apptools-tests/samples-deb/ManifestDisplay/res/standalone/index.html, usecase/usecase-apptools-tests/samples-deb/ManifestDisplay/subcase.json, usecase/usecase-apptools-tests/samples-deb/ManifestStartUrl/README.md, usecase/usecase-apptools-tests/samples-deb/ManifestStartUrl/index.html, usecase/usecase-apptools-tests/suite.json, usecase/usecase-apptools-tests/tests.deb.xml, usecase/usecase-apptools-tests/tests.full.xml
Impacted tests(approved): new 6, update 1, delete 6
https://crosswalk-project.org/jira/browse/XWALK-6242
https://crosswalk-project.org/jira/browse/XWALK-5797
=> [usecase-apptools] Move deb manual tests to apptools usecase

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v6.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v6.xml
-Add autocase for API clearClientCertPreferences
BUG=https://crosswalk-project.org/jira/browse/XWALK-6439
=> [EmbeddingAPI] Add autocase for API clearClientCertPreferences

usecase/usecase-apptools-tests/inst.deb.py, usecase/usecase-apptools-tests/suite.json
=> [usecase-apptools] Update suite.json for deb apptools usecase

usecase/usecase-wrt-windows-tests/tests.full.xml, usecase/usecase-wrt-windows-tests/tests.xml
- Remove Widevine usecase since the feature(6102) is Reopened
=> [Windows] Remove Widevine usecase from the case main page

usecase/usecase-apptools-tests/samples-android/SigningRelease/README.md, usecase/usecase-apptools-tests/samples-android/SigningRelease/index.html, usecase/usecase-apptools-tests/steps/SigningRelease/step.js, usecase/usecase-apptools-tests/tests.android.xml, usecase/usecase-apptools-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-5436
=> [usecase-apptools] Add tests to test signing release for android apptools usecase

apptools/apptools-android-tests/apptools/manifest_xwalk_permissions.py, apptools/apptools-android-tests/testapp/third_app_permission/manifest.json, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-6502
=> [apptools-android] Add tests to test the third app permission in AndroidManifest.xml for apptools android

webapi/tct-backgrounds-css3-tests/backgrounds/CSS3BG_border_0point5px_dashed_000.html, webapi/tct-backgrounds-css3-tests/backgrounds/support/background_border_test.js
Unit test Platform: Crosswalk Project for Android 19.48.491.0
Unit test result summary: Pass 3, Fail 0, Blocke 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6329
BUG=https://crosswalk-project.org/jira/browse/XWALK-6330
=> [webapi] Update backgrounds tests

webapi/tct-backgrounds-css3-tests/backgrounds/CSS3BG_border_0point5px_dashed_000.html, webapi/tct-backgrounds-css3-tests/backgrounds/support/background_border_test.js
Unit test Platform: Crosswalk Project for Android 18.48.477.3
Unit test result summary: Pass 3, Fail 0, Blocke 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6329
BUG=https://crosswalk-project.org/jira/browse/XWALK-6330
=> [Crosswalk-18][webapi] Update background tests

usecase/usecase-apptools-tests/samples-android/AntPathWithWhitespace/index.html, usecase/usecase-apptools-tests/samples-android/SigningRelease/index.html, usecase/usecase-apptools-tests/samples-ios/AppToolsOptions/index.html, usecase/usecase-apptools-tests/samples-ios/AppTools_install_using_npm/index.html, usecase/usecase-apptools-tests/samples-ios/BuildNoSDK/index.html, usecase/usecase-apptools-tests/samples-ios/BuildRelease/index.html, usecase/usecase-apptools-tests/samples-windows/Windows_Compatible/index.html
=> [usecase-apptools] Copy index.html to test app for apptools usecase

webapi/tct-gumallow-w3c-tests/gumallow/w3c/stream-api/mediastream/mediastream-finished-add-manual.html, webapi/tct-gumallow-w3c-tests/gumallow/w3c/stream-api/mediastream/mediastream-idl-manual.html, webapi/tct-gumallow-w3c-tests/gumallow/w3c/stream-api/mediastreamtrack/mediastreamtrack-end-manual.html
Unit test Platform: Crosswalk Project for Android 19.48.491.0
Unit test result summary: Pass 2, Fail 0, Blocke 1
=> [webapi] Sync MediaCapture upstream tests

webapi/webapi-realsense-xwalk-tests/realsense/enhanced_photography.html, webapi/webapi-realsense-xwalk-tests/realsense/enhancedphotography.js, webapi/webapi-realsense-xwalk-tests/realsense/face.html, webapi/webapi-realsense-xwalk-tests/realsense/face.js, webapi/webapi-realsense-xwalk-tests/realsense/sceneperception.js, webapi/webapi-realsense-xwalk-tests/realsense/support/support.js, webapi/webapi-realsense-xwalk-tests/tests.full.xml, webapi/webapi-realsense-xwalk-tests/tests.xml
Impacted TCs num(approved): New 12, Update 12, Delete 2
Unit test Platform: Crosswalk Project for Windows 18.48.475.0
Unit test result summary: Pass 148, Fail 7, Blocked 0
=> [webapi] Add PhotoCapture tests for RealSense

apptools/apptools-windows-tests/apptools/CI/crosswalk_pkg_basic.py, apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/apptools/manifest_hooks.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-6524
https://crosswalk-project.org/jira/browse/XWALK-6527
Impacted tests(approved): new 4, update 3, delete 0
Unit test result summary: pass 2, fail 5, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-5437
=> [apptools-windows] Add tests to test multiple backends for apptools windows

usecase/usecase-apptools-tests/README.md, usecase/usecase-apptools-tests/samples-windows/API_Keys/README.md, usecase/usecase-apptools-tests/samples-windows/API_Keys/index.html, usecase/usecase-apptools-tests/steps/API_Keys/step.js, usecase/usecase-apptools-tests/testapp/apikeys/.crosswalk-app-tools-keys.json, usecase/usecase-apptools-tests/tests.full.xml, usecase/usecase-apptools-tests/tests.windows.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-6497
=> [usecase-apptools] Add tests to test API keys for windows apptools usecase

usecase/usecase-apptools-tests/tests.android.xml, usecase/usecase-apptools-tests/tests.ios.xml
- Update tests.android.xml according to tests.full.xml
- Update tests.ios.xml according to tests.full.xml
Unit test result summary: pass 29, fail 0, block 0
=> [usecase-apptools] Update tests.android.xml for apptools usecase

usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/README.md, usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/index.html, usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/res/any/index.html, usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/res/landscape/index.html, usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/res/landscape_primary/index.html, usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/res/landscape_secondary/index.html, usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/res/natural/index.html, usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/res/portrait/index.html, usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/res/portrait_primary/index.html, usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/res/portrait_secondary/index.html, usecase/usecase-apptools-tests/samples-windows/ManifestOrientation/subcase.json, usecase/usecase-apptools-tests/suite.json, usecase/usecase-apptools-tests/tests.full.xml, usecase/usecase-apptools-tests/tests.windows.xml
Impacted tests(approved): new 8, update 0, delete 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6500
=> [usecase-apptools] Add tests to test manifest orientation field for windows apptools usecase

tools/gitstat/README.md, tools/gitstat/git_stat.py, tools/gitstat/git_stat_pr.py
- Rename workstat to gitstat
- Add git statistics for merged pull request
https://crosswalk-project.org/jira/browse/XWALK-6119
=> [tools] Add git statistics for merged pull request

tools/build/README.md, tools/build/build_cordova.py, tools/build/pack_cordova_sample.py
- It's fine to build "sampleRelease" app
=> [Cordova] Add sampleRelease app package

misc/sampleapp-android-tests/sampleapp/comm.py, misc/sampleapp-android-tests/sampleapp/extensionsandroid.py, misc/sampleapp-android-tests/sampleapp/hangonman.py, misc/sampleapp-android-tests/sampleapp/helloworld.py, misc/sampleapp-android-tests/sampleapp/hexgl.py, misc/sampleapp-android-tests/sampleapp/memorygame.py, misc/sampleapp-android-tests/sampleapp/simd.py, misc/sampleapp-android-tests/sampleapp/spacedodgegame_base.py, misc/sampleapp-android-tests/sampleapp/spacedodgegame_manifestorientationresize.py, misc/sampleapp-android-tests/sampleapp/spacedodgegame_manifestorientationscale.py, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationresize.py, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationscale.py, misc/sampleapp-android-tests/sampleapp/webgl.py, misc/sampleapp-android-tests/sampleapp/webrtc.py
crosswalk-pkg have fixed -t bug, no need the workaround anymore.
Impacted tests(approved): new 0, update 13, delete 0
Unit test result summary: pass 13, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6328
=> [misc] Fix shared mode tests in sampleapp-android-tests

misc/sampleapp-android-tests/sampleapp/comm.py, misc/sampleapp-android-tests/sampleapp/extensionsandroid.py, misc/sampleapp-android-tests/sampleapp/hangonman.py, misc/sampleapp-android-tests/sampleapp/helloworld.py, misc/sampleapp-android-tests/sampleapp/hexgl.py, misc/sampleapp-android-tests/sampleapp/memorygame.py, misc/sampleapp-android-tests/sampleapp/simd.py, misc/sampleapp-android-tests/sampleapp/spacedodgegame_base.py, misc/sampleapp-android-tests/sampleapp/spacedodgegame_manifestorientationresize.py, misc/sampleapp-android-tests/sampleapp/spacedodgegame_manifestorientationscale.py, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationresize.py, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationscale.py, misc/sampleapp-android-tests/sampleapp/webgl.py, misc/sampleapp-android-tests/sampleapp/webrtc.py
crosswalk-pkg have fixed -t bug, no need the workaround anymore.
Impacted tests(approved): new 0, update 13, delete 0
Unit test result summary: pass 13, fail 0, block 0
https://crosswalk-project.org/jira/browse/XWALK-6328
=> [Crosswalk-18][misc] Fix shared mode tests in sampleapp-android-tests

webapi/tct-touchevent-w3c-tests/w3c-touchevent-app/testscripts/TouchEvent_altKey_exist.feature, webapi/tct-touchevent-w3c-tests/w3c-touchevent-app/testscripts/TouchEvent_ctrlKey_exist.feature, webapi/tct-touchevent-w3c-tests/w3c-touchevent-app/testscripts/TouchEvent_metaKey_exist.feature, webapi/tct-touchevent-w3c-tests/w3c-touchevent-app/testscripts/TouchEvent_shiftKey_exist.feature
MEMO PAD8:
Unit test Platform: Crosswalk Project for Android 19.48.493.0
=> [webapi] Improve bdd steps for tct-touchevent-w3c-tests

cordova/cordova-lite-android-tests/lite/app_multiple_apk_false.py, cordova/cordova-lite-android-tests/lite/app_multiple_apk_true.py, cordova/cordova-lite-android-tests/lite/comm.py, cordova/cordova-lite-android-tests/tests.full.xml, cordova/cordova-lite-android-tests/tests.xml
- Remove releaseSample from tests.xml file
Unit test platform: Crosswalk Project for android 17.46.455.1
https://crosswalk-project.org/jira/browse/XWALK-6503
=> [Cordova] Add file size check point for cordova lite

tools/build/pack_cordova_sample.py, usecase/usecase-cordova-android-tests/samples/SetUserAgent/REAMDE.md, usecase/usecase-cordova-android-tests/samples/SetUserAgent/index.html
Unit test platform: Crosswalk Project for android 18.48.477.8
BUG=https://crosswalk-project.org/jira/browse/XWALK-6526
=> [Cordova] Add AppendUserAgent checkpoint for SetUserAgent usecase

misc/webmanu-system-android-tests/testapp/filepicker/manifest.json, misc/webmanu-system-android-tests/testapp/filereader/manifest.json, misc/webmanu-system-android-tests/testapp/filereader_upgrade/manifest.json
https://crosswalk-project.org/jira/browse/XWALK-6032
=> [misc] Add external storage permission

misc/webmanu-system-android-tests/testapp/filepicker/manifest.json, misc/webmanu-system-android-tests/testapp/filereader/manifest.json, misc/webmanu-system-android-tests/testapp/filereader_upgrade/manifest.json
https://crosswalk-project.org/jira/browse/XWALK-6032
=> [Crosswalk-18][misc] Add external storage permission

apptools/apptools-windows-tests/apptools/CI/crosswalk_pkg_basic.py, apptools/apptools-windows-tests/apptools/comm.py, apptools/apptools-windows-tests/apptools/create_package.py
BUG=https://crosswalk-project.org/jira/browse/XWALK-6618
=> [apptools-windows] Update crosswalk name for apptools windows

usecase/usecase-cordova-android-tests/samples/SigningRelease/README.md, usecase/usecase-cordova-android-tests/samples/SigningRelease/index.html, usecase/usecase-cordova-android-tests/steps/SigningRelease/step.js, usecase/usecase-cordova-android-tests/tests.full.xml, usecase/usecase-cordova-android-tests/tests.xml
Unit test platform: Crosswalk Project for android 18.48.477.8
BUG=https://crosswalk-project.org/jira/browse/XWALK-6614
=> [Cordova] Add case to sign release apk

webapi/webapi-appsecurity-external-tests/tests.full.xml, webapi/webapi-appsecurity-external-tests/tests.xml
Unit test platform: Crosswalk Project for android 18.48.477.8
Unit test result summary: pass 82, fail 0, block 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6616
=> [Cordova] Add onload_delay property in tests.xml

webapi/webapi-appsecurity-external-tests/appsecurityapi/spec.json, webapi/webapi-appsecurity-external-tests/tests.full.xml, webapi/webapi-appsecurity-external-tests/tests.xml
- Remove the spec.json as it won't be used
- Update the category to "WebAPI/EXTERNAL"
- Remove the duplicated 'status="approved" type="compliance"' in test.full.xml
=> [Cordova][hotfix] Fix the count issue

wrt/wrt-security-android-tests/security/comm.py
BUG=https://crosswalk-project.org/jira/browse/XWALK-6588
=> [wrt] Import missing glob lib

wrt/wrt-security-android-tests/security/comm.py
https://crosswalk-project.org/jira/browse/XWALK-6588
=> [Crosswalk-18][wrt] Import missing glob lib

wrt/wrt-rtcoremanu-tests/suite.json, wrt/wrt-rtcoremanu-tests/tests.windows.xml, wrt/wrt-securitymanu-tests/suite.json, wrt/wrt-securitymanu-tests/tests.windows.xml
- Use the separate tests.windows.xml for wrt-securitymanu-tests and wrt-rtcoremanu-tests
BUG=https://crosswalk-project.org/jira/browse/XWALK-6558
=> [windows] Remove the unreasonable cases

apptools/apptools-windows-tests/apptools/check_wxsfile.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
https://crosswalk-project.org/jira/browse/XWALK-5661
BUG=https://crosswalk-project.org/jira/browse/XWALK-6608
=> [apptools-windows] Add tests to test wxs file is created for apptools windows

tools/atip/atip/web/web.py
Nexus4:
webmanu-system-android-tests:
Impacted TCs num(approved): New 0, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 19.49.507.0
Unit test result summary: Pass 9, Fail 0, Blocked 0
Update atip to make sure baseline data can be generated normally with several comparsion in one feature file.
=> [atip] Improve atip for baseline data generation

usecase/usecase-wrt-windows-tests/samples/Fullscreen/index.html
=> [Windows][wrt] Update fullscreen usecase testcase

misc/sampleapp-windows-tests/sampleapp/Kingsoft_Fast_Docs_Launch.html
Unit test platform: Crosswalk Project for Windows 19.48.495.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6579
=> [Windows]Update web URL for Kingsoft_Fast_Docs

usecase/usecase-apptools-tests/samples-windows/CheckMSISize/README.md, usecase/usecase-apptools-tests/samples-windows/CheckMSISize/index.html, usecase/usecase-apptools-tests/steps/CheckMSISize/step.js, usecase/usecase-apptools-tests/tests.full.xml, usecase/usecase-apptools-tests/tests.windows.xml
=> [usecase-apptools] Update tests to check apk size for usecase apptools windows

webapi/webapi-realsense-xwalk-tests/README.md, webapi/webapi-realsense-xwalk-tests/manifest.json, webapi/webapi-realsense-xwalk-tests/tests.full.xml, webapi/webapi-realsense-xwalk-tests/tests.xml
- Update latest realsense_extensions link
- Add "extension" parameter for Teskitlite
https://crosswalk-project.org/jira/browse/XWALK-6595
=> [webapi] Add "extension" parameter for Teskitlite in realsense test suite

webapi/tct-webaudio-w3c-tests/tests.full.xml, webapi/tct-webaudio-w3c-tests/tests.xml, webapi/tct-webaudio-w3c-tests/webaudio/audiocontext_createIIRFilter.html, webapi/tct-webaudio-w3c-tests/webaudio/audiocontext_decodeAudioData.html, webapi/tct-webaudio-w3c-tests/webaudio/offlineaudiocontext_suspend_and_resume.html
Impacted tests(approved): new 8, update 0, delete 0
Unit test platform: Crosswalk Project for android 19.49.506.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6545
=> [webapi] Add WebAudio test with rebase M49

webapi/webapi-realsense-xwalk-tests/realsense/face.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_checksignature.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_clone-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_querycameraperspectivemodel-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_querycamerapose-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_querycameravendorinfo-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_querycontainerimage-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_querydevicevendorinfo-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_queryimage-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_querynumberofcameras.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_queryrawdepth-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_queryxdmrevision.html, webapi/webapi-realsense-xwalk-tests/realsense/photo_resetcontainerimage.html, webapi/webapi-realsense-xwalk-tests/realsense/photoutils_colorresize-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photoutils_commonfov-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photoutils_depthresize-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photoutils_enhancedepth-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/photoutils_getdepthquality.html, webapi/webapi-realsense-xwalk-tests/realsense/photoutils_photorotate-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/sceneperception.js, webapi/webapi-realsense-xwalk-tests/realsense/support/adapter.js, webapi/webapi-realsense-xwalk-tests/realsense/support/common.js, webapi/webapi-realsense-xwalk-tests/realsense/support/support.js, webapi/webapi-realsense-xwalk-tests/tests.full.xml, webapi/webapi-realsense-xwalk-tests/tests.xml
- Add tests for Photo, PhotoCapture API
- Add tests for new API: getInternalCameraIntrinsics,
getVolumePreview
Impacted TCs num(approved): New 20, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Windows 19.48.498.0
Unit test result summary: Pass 20, Fail 0, Blocked 0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6345
BUG=https://crosswalk-project.org/jira/browse/XWALK-6545
=> [webapi] Add RealSense tests

webapi/webapi-serviceworkers-w3c-tests/serviceworkers/resources/fetchevent-constructor-worker.js
BUG=https://crosswalk-project.org/jira/browse/XWALK-6546
Test Result is blocked by
https://crosswalk-project.org/jira/browse/XWALK-6015
=> [webapi] Add FetchEvent.clientId attribute

usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/basic/XWalkViewWithOnHideOnShowAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/basic/XWalkViewWithOnHideOnShow.java, usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/basic/WebViewWithPlayVideoActivity.java
BUG=https://crosswalk-project.org/jira/browse/XWALK-6633
=> [EmbeddingApi] Fix the issue that can't paly video

usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_with_redirection_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/client/XWalkViewWithRedirectionAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_redirection.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/client/XWalkViewWithRedirection.java
-Modify usecase of XWalkViewWithRedirection to better test
BUG=https://crosswalk-project.org/jira/browse/XWALK-6654
=> [EmbeddingAPI] Modify usecase of XWalkViewWithRedirection to better test

usecase/usecase-webapi-xwalk-tests/data/x86-ecs2/default-src_self_baseline.md5
ecs2-8a:
Unit test Platform: Crosswalk Project for Android 19.49.509.0
Unit test result summary: Pass 0, Fail 0, Blocked 0
https://crosswalk-project.org/jira/browse/XWALK-6666
=> [usecase] Update baseline data to sync with m49 for ecs2-8a

usecase/usecase-webapi-xwalk-tests/steps/FullScreen/step.js
- This case will fail on nexus 5
BUG=https://crosswalk-project.org/jira/browse/XWALK-6691
=> [usecase-webapi] Add clicking drop down list for fullscreen usecase

cordova/cordova-feature-android-tests/feature/app_multiple_apk_false.py, cordova/cordova-feature-android-tests/feature/app_multiple_apk_true.py, cordova/cordova-feature-android-tests/feature/comm.py, cordova/cordova-lite-android-tests/lite/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/comm.py, cordova/cordova-webapp-android-tests/webapp/comm.py, usecase/usecase-cordova-android-tests/samples/CrosswalkVersion/res/test.py
- Use the separate size range to check shared mode app size
https://crosswalk-project.org/jira/browse/XWALK-6433
=> [Cordova] Use the correct app name for shared mode

cordova/cordova-sampleapp-android-tests/sampleapp/GoogleMapsPlugin.html, cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/google-maps-plugin.py, cordova/cordova-sampleapp-android-tests/suite.json
Unit test platform: Crosswalk Project for Android 19.49.506.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6122
=> [cordova] Update GoogleMapsPlugin for crosswalk version packing

cordova/cordova-sampleapp-android-tests/sampleapp/GoogleMapsPlugin.html, cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/google-maps-plugin.py, cordova/cordova-sampleapp-android-tests/suite.json
https://crosswalk-project.org/jira/browse/XWALK-6122
=> [Crosswalk-18][cordova]Update GoogleMapsPlugin for crosswalk version packing

cordova/cordova-feature-android-tests/feature/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/comm.py, cordova/cordova-webapp-android-tests/webapp/comm.py, usecase/usecase-cordova-android-tests/samples/CrosswalkVersion/res/test.py
https://crosswalk-project.org/jira/browse/XWALK-6433
=> [Crosswalk-18][Cordova] Use the correct app name for shared mode

cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/google-maps-plugin.py
Unit test platform: Crosswalk Project for Android 19.49.509.0
https://crosswalk-project.org/jira/browse/XWALK-6122
=> [cordova] Fix GoogleMapsPlugin shared mode

stability/stability-manual-android-tests/manifest.json, stability/stability-manual-android-tests/suite.json, stability/stability-manual-android-tests/testapp/downloadtest/manifest.json
Unit test platform: Crosswalk Project for Android 19.49.509.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6032
=> [stability]  Add external storage permission

cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/google-maps-plugin.py
https://crosswalk-project.org/jira/browse/XWALK-6122
=> [Crosswalk-18][cordova]Fix GoogleMapsPlugin shared mode

stability/stability-manual-android-tests/manifest.json, stability/stability-manual-android-tests/suite.json, stability/stability-manual-android-tests/testapp/downloadtest/manifest.json
https://crosswalk-project.org/jira/browse/XWALK-6032
=> [Crosswalk-18][stability] Add external storage permission

webapi/webapi-realsense-xwalk-tests/realsense/measurement_measuredistance-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/motioneffect_apply-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/support/common.js, webapi/webapi-realsense-xwalk-tests/realsense/xdmutils_loadxdm-manual.html, webapi/webapi-realsense-xwalk-tests/realsense/xdmutils_savexdm-manual.html, webapi/webapi-realsense-xwalk-tests/tests.full.xml, webapi/webapi-realsense-xwalk-tests/tests.xml
- Cases for Measurement, MotionEffect, and XDMUtils interfaces
Impacted TCs num(approved): New 4, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Windows 19.49.509.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6695
=> [webapi] Add new cases for RealSense

webapi/webapi-realsense-xwalk-tests/realsense/realsense.js, webapi/webapi-realsense-xwalk-tests/tests.full.xml, webapi/webapi-realsense-xwalk-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/XWALK-6645
=> [webapi] Remove realsense readonly checking test

tools/build/build_msi.py, tools/build/pack.py, webapi/tct-csp-w3c-tests/suite.json
=> [build-script] Update build script to fix not run issue on csp test.

embeddingapi/embedding-build-android-tests/build.gradle, embeddingapi/embedding-build-android-tests/comm.py, embeddingapi/embedding-build-android-tests/gradle/crosswalk_libphonenumber_gradle_build_all_app.py, embeddingapi/embedding-build-android-tests/gradle/crosswalk_libphonenumber_gradle_build_app.py, embeddingapi/embedding-build-android-tests/tests.full.xml, embeddingapi/embedding-build-android-tests/tests.xml
Impacted tests(approved): new 2, update 4, delete 0
Unit test platform: Crosswalk Project for Android 18.48.477.13
BUG=https://crosswalk-project.org/jira/browse/XWALK-6772
=> [Embeddingapi] TC add for building crosswalk with LibPhoneNumber

webapi/tct-canvas-html5-tests/suite.json, webapi/tct-cors-w3c-tests/suite.json, webapi/tct-navigationtiming-w3c-tests/suite.json, webapi/tct-sandbox-html5-tests/suite.json, webapi/tct-sessionhistory-html5-tests/suite.json, webapi/tct-sse-w3c-tests/suite.json, webapi/tct-webmessaging-w3c-tests/suite.json, webapi/tct-websocket-w3c-tests/suite.json, webapi/tct-webstorage-w3c-tests/suite.json, webapi/tct-xmlhttprequest-w3c-tests/suite.json, webapi/webapi-resourcetiming-w3c-tests/suite.json, webapi/webapi-serviceworkers-w3c-tests/suite.json
Add host-app parameter in suite.json.
Impacted tests(approved): new 0, update 11, delete 0
Unit test platform: Crosswalk Project for Windows 19.49.514.0
Unit test result summary: pass 11, fail 0, block 0
BUG=XWALK-6598
=> [build-script][windows]Update all suite.json for host app in windows

webapi/tct-fileapi-w3c-tests/fileapi/w3c/Blob-slice.html
Impacted tests(approved): new 0, update 19, delete 0
Unit test result summary: pass 19, fail 0, block 0
=> [webapi] Sync Blob-slice test for File API

misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_FileWriter_FileReader_restart.feature, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_FileWriter_FileReader_upgrade.feature, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_IndexDB_restart.feature, misc/webmanu-system-android-tests/web-system-app/testscripts/Crosswalk_LocalStorage_restart.feature, tools/atip/README.md, tools/atip/atip/android/android.py, tools/atip/atip/android/steps.py, usecase/usecase-wrt-android-tests/testscripts/ApplicationlocalStorage.feature, usecase/usecase-wrt-android-tests/testscripts/WebAppTaskManager.feature, wrt/wrt-securitymanu-tests/wrt-security-app/testscripts/Crosswalk_WebApp_Certificate_Trusted_ReOpen.feature, wrt/wrt-securitymanu-tests/wrt-security-app/testscripts/Crosswalk_WebApp_Certificate_Untrusted_ReOpen.feature, wrt/wrt-uxmanu-tests/wrt-ux-app/testscripts/Crosswalk_WebApp_Terminated_TaskManager.feature
* Add new step for app close from task manager via swiping action
* To be compatible with "File Explorer" on xiaomi
* Update 9 related bdd tests
Impact tests(approved): new 0, update 9, delete 0
Unit test platform: [Android][Xiaomi Pad2][memo pad 8]
Unit test result summary: pass 9, fail 0, block 0
Bug=https://crosswalk-project.org/jira/browse/XWALK-6757
Bug=https://crosswalk-project.org/jira/browse/XWALK-6791
=> [GUI-Auto] Fix compatibility issue between Xiaomi and other devices

tools/atip/atip/android/android.py
The step "close app from task manager" works well
=> [ATIP] Remove invalid assertion

usecase/usecase-realsense-xwalk-tests/README.md, usecase/usecase-realsense-xwalk-tests/samples/AlertEvent/js/main.js
- use realsense_extension_v19.6.1
- update "_" to "-" from spec
Unit test Platform: Crosswalk Project for Windows 20.49.516.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6749
=> [usecase][realsense] Update AlertEvent test

webapi/webapi-realsense-xwalk-tests/realsense/enhancedphotography.js, webapi/webapi-realsense-xwalk-tests/realsense/face.js, webapi/webapi-realsense-xwalk-tests/realsense/sceneperception.js
There are some changes with realsense v19.6.1:
- FaceError, SPError, DEPError are replaced with DOMException
- enumeration values be all lowercase, and that multiple words be separated using dashes
Impacted TCs num(approved): New 0, Update 33, Delete 0
Unit test Platform: Crosswalk Project for Windows 20.49.516.0
Unit test result summary: Pass 19, Fail 14, Blocked 0
BUG=https://crosswalk-project.org/jira/browse/CTS-603
BUG=https://crosswalk-project.org/jira/browse/CTS-602
=> [webapi][realsense] Update realsense tests

webapi/webapi-webrtc-w3c-tests/webrtc/RTCDTMFSender_canInsertDTMF.html, webapi/webapi-webrtc-w3c-tests/webrtc/RTCDTMFToneChangeEvent_tone_basic.html, webapi/webapi-webrtc-w3c-tests/webrtc/RTCPeerConnectionIceEvent_candidate.html, webapi/webapi-webrtc-w3c-tests/webrtc/RTCPeerConnectionIceEvent_candidate_basic.html
BUG= https://crosswalk-project.org/jira/browse/CTS-645
=> [webapi] Update webrtc tests

apptools/apptools-android-tests/apptools/CI/crosswalk_pkg_basic.py, apptools/apptools-android-tests/apptools/create_package_target.py, apptools/apptools-android-tests/apptools/crosswalk_app_targets.py
For fixing CI failure on appVeyor.
=> [apptools] Add missing "apkLength" variable initialization in funtion

webapi/webapi-realsense-xwalk-tests/README.md, webapi/webapi-realsense-xwalk-tests/realsense/handtracking.html, webapi/webapi-realsense-xwalk-tests/realsense/handtracking.js, webapi/webapi-realsense-xwalk-tests/tests.full.xml, webapi/webapi-realsense-xwalk-tests/tests.xml
Hand Tracking needs a device with builtin camera, such as Lenovo Yoga 15,
SR300 camera or F200 camera.
Impacted TCs num(approved): New 11, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Windows 20.49.516.0
Unit test result summary: Pass 11, Fail 10, Blocked 0
BUG=https://crosswalk-project.org/jira/browse/CTS-729
=> [webapi][realsense] Add hand tracking tests

tools/atip/atip/android/android.py
* Open Settings via command line does not work on Xiaomi Pad2
* Open/Close GPS/WiFi/Airplane mode on Xiaomi Pad2 are different from others
Unit test platform: Xiaomi Pad2, Memo Pad8
Unit test result summary: pass 7, fail 1, block 0
Fail reason: XWALK-1693
BUG=https://crosswalk-project.org/jira/browse/CTS-246
=> [ATIP] Fix incompatibility issues in Settings for Xiaomi Pad2

apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
Due to these cases have been moved to apptools-manifest-tests, so remove these cases xml
=> [apptools-windows] Update xml for apptools windows

usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/basic/XWalkViewWithOnHideOnShowAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/basic/XWalkViewWithOnHideOnShow.java
Unit test platform: Crosswalk Project for Android 20.49.517.0
BUG=https://crosswalk-project.org/jira/browse/XWALK-6120
=> [Embeddingapi] Need to check the video playing in android TV

usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/basic/XWalkViewWithOnHideOnShowAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/basic/XWalkViewWithOnHideOnShow.java, usecase/usecase-embedding-android-tests/webviewtest/src/org/android/webview/api/sample/basic/WebViewWithPlayVideoActivity.java
- Need to check the video playing in android TV
BUG=https://crosswalk-project.org/jira/browse/XWALK-6633
BUG=https://crosswalk-project.org/jira/browse/XWALK-6120
=> [Crosswalk-18][Embeddingapi] Fix the issue that can't paly video

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/text_zoom_css3.html, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/zoom_css3columns_layout.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/menu/main.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingTextZoomForCss3Async.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/assets/text_zoom_css3.html, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/zoom_css3columns_layout.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/menu/main.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingTextZoomForCss3.java
BUG=https://crosswalk-project.org/jira/browse/CTS-712
=> [Embeddingapi] TC add for setTextZoom with CSS3 columns

usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml
execution_type should be auto if it's a bdd/ref test.
=> [usecase-wrt] Fix incorrect execution_type in tests.xml

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v6.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v6.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_get_certificate.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/basic/XWalkViewGetCertificateAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_get_certificate.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/basic/XWalkViewGetCertificate.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
Impacted tests(approved): new 8, update 0, delete 0
Unit test platform: Crosswalk Project for Android 20.49.522.0
BUG=https://crosswalk-project.org/jira/browse/CTS-736
=> [Embeddingapi] Add TC for getCertificate method

webapi/webapi-webgl-khronos-tests/webgl/khronos/resources/js-test-pre.js
BUG=https://crosswalk-project.org/jira/browse/CTS-788
=> [WebAPI] Update js-test-pre.js to support webgl test cases for wts.

.travis.yml, apptools/apptools-android-tests/testapp/extension_permission/index.html, apptools/apptools-windows-tests/testapp/xwalk_echo_extension/index.html, tools/lint/lint.whitelist
=> Fix lint error for test cases in apptools

tools/lint/README.md, tools/lint/lint.py
Support to specify repo with `-r` for other repos lint check
https://crosswalk-project.org/jira/browse/CTS-258
=> [tools] Support to specify test repo for lint tool

usecase/usecase-wrt-android-tests/samples/CustomURLScheme/README.md, usecase/usecase-wrt-android-tests/samples/CustomURLScheme/index.html, usecase/usecase-wrt-android-tests/steps/CustomURLScheme/step.js, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml, usecase/usecase-wrt-android-tests/tests.shared.xml
Unit test platform: Crosswalk for Android 20.49.527.0
BUG=https://crosswalk-project.org/jira/browse/CTS-609
=> [usecase-wrt] Add test for Custom URL Scheme

apptools/apptools-windows-tests/apptools/comm.py, apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
Unit test platform: Crosswalk Project for Windows 20.49.527.0
BUG=CTS-1693
=> [app-tools] Add auto test case for APPTOOLS-339 to check "locale" folder in package.

apptools/apptools-windows-tests/apptools/comm.py
=> [apptools-windows-test] Fix indentation error in comm.py

embeddingapi/embedding-api-android-tests/embeddingapi/assets/js_modal_dialog.html, embeddingapi/embedding-api-android-tests/embeddingapi/assets/navigator.online.html, embeddingapi/embedding-api-android-tests/embeddingapi/assets/pause_timers.html, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnReceivedClientCertRequestHelper.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v2/XWalkExtensionTest.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/CookieManagerTest.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/SetNetworkAvailableTest.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkUIClientTest.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTest.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/assets/js_modal_dialog.html, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/assets/navigator.online.html, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/assets/pause_timers.html, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnReceivedClientCertRequestHelper.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestXWalkResourceClientBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkViewTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v2/XWalkExtensionTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/CookieManagerTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/SetNetworkAvailableTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkUIClientTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v5/XWalkViewTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTestAsync.java, embeddingapi/embedding-build-android-tests/demo/AndroidManifest.xml
- Fix TRAILING WHITESPACE
sed -i 's/[ \t]*$//' /path/to/file
- Fix INDENT TABS
sed -i 's/	/    /g' /path/to/file
https://crosswalk-project.org/jira/browse/CTS-1438
=> [lint-tool] Fix lint error in embeddingapi tests

tools/lint/lint.py
No need to split repo root in dir identify
=> [lint-tool] Fix issue in file itera

webapi/webapi-realsense-xwalk-tests/README.md, webapi/webapi-realsense-xwalk-tests/manifest.json, webapi/webapi-realsense-xwalk-tests/realsense/face.js, webapi/webapi-realsense-xwalk-tests/realsense/sceneperception.js
BUG=https://crosswalk-project.org/jira/browse/CTS-1729
=> [webapi][realsense] Add hand tracking extension

misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationresize_orientation.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationscale_orientation.html
Unit test platform: Crosswalk for Android 20.50.529.0
=> [misc] Update orientation steps in Sampleapp/Space Dodge Game

misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationresize_orientation.html, misc/sampleapp-android-tests/sampleapp/spacedodgegame_screenorientationscale_orientation.html
Unit test platform: Crosswalk for Android 19.49.514.2
=> [Crosswalk-19][misc] Update orientation steps in Sampleapp/Space Dodge Game

misc/webapi-noneservice-tests/pack.sh, tools/build/build_android.py, webapi/tct-fileapi-w3c-tests/suite.json
Add WRITE_EXTERNAL_STORAGE explicitly for tct-fileapi-w3c-tests
and AIO packing, fix issue CTS-1755.
BUG=https://crosswalk-project.org/jira/browse/CTS-1755
=> [webapi-fileapi]Add WRITE_EXTERNAL_STORAGE permission

embeddingapi/embedding-api-android-tests/embeddingapi/assets/find.html, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnFindResultReceivedHelper.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/suite.json, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v7.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/assets/find.html, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/OnFindResultReceivedHelper.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkViewTestAsnyc.java, embeddingapi/embedding-asyncapi-android-tests/suite.json, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/client/XWalkViewWithFindTextAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/client/XWalkViewWithFindText.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
Impacted tests(approved): new 8, update 0, delete 0
Unit test platform: Crosswalk Project for Android 20.50.533.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1568
=> [Embeddingapi] TC dev for finding text in the web page

usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_with_session_storage.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/misc/XWalkViewWithSessionStorage.java
Unit test platform: Crosswalk Project for Android 20.49.522.0
BUG=https://crosswalk-project.org/jira/browse/CTS-702
=> [Embeddingapi] Restore seesionstorage value after the page is loaded

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v7.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkViewTestAsnyc.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/basic/XWalkViewWithGetContentHeightAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/basic/XWalkViewWithGetContentHeight.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
Impacted tests(approved): new 6, update 0, delete 0
Unit test platform: Crosswalk Project for Android 21.50.534.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1756
=> [Embeddingapi] TC dev for getContentHeight method

embeddingapi/embedding-api-android-tests/embeddingapi/res/layout/xwview_layout.xml, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkSettingTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v7.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/res/layout/xwview_layout.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkSettingTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml
Unit test platform: Crosswalk Project for Android 20.50.534.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1565
=> [Embeddingapi] TC dev for setLoadWithOverviewMode API

embeddingapi/embedding-api-android-tests/embeddingapi/assets/add_js_interface.html, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v7.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/assets/add_js_interface.html, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v1/XWalkViewTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkViewTestAsnyc.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1564
=> [Embeddingapi] TC dev for XWalkView.removeJavascriptInterface

embeddingapi/embedding-api-android-tests/embeddingapi/res/layout/xwview_layout.xml, embeddingapi/embedding-api-android-tests/embeddingapi/res/values/attrs.xml, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkViewTest.java, embeddingapi/embedding-api-android-tests/suite.json, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v7.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/res/layout/xwview_layout.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/res/values/attrs.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/MainActivity.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/XWalkViewTestAsnyc.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-656
=> [embeddingapi] TC dev for XWalkView.getCompositingSurfaceType

apptools/apptools-android-tests/apptools/create_package.py, apptools/apptools-android-tests/tests.full.xml, apptools/apptools-android-tests/tests.xml
Unit test platform: Crosswalk Project for Windows 19.49.514.0
BUG=CTS-1750
=> [app-tools] Add test cases for skip option

apptools/apptools-windows-tests/apptools/create_package.py, apptools/apptools-windows-tests/tests.full.xml, apptools/apptools-windows-tests/tests.xml
Unit test platform: Crosswalk Project for Windows 20.49.527.0
BUG=CTS-1750
=> [app-tools][windows] Add test cases for skip option

usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1720
BUG=https://crosswalk-project.org/jira/browse/CTS-1711
=> [Embeddingapi] update non-standard tests.xml

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/ClearSslPreferenceTest.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/ClearSslPreferenceTestAsync.java
BUG=https://crosswalk-project.org/jira/browse/CTS-1713
=> [Embeddingapi] Update ClearSslPreferenceTest usecase

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTest.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTestAsync.java
BUG=https://crosswalk-project.org/jira/browse/CTS-1715
=> [Embeddingapi] Update the website to get null certificate

embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1773
=> [Embeddingapi] Improve tests.full.xml to support launch auto cases

embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1773
=> [Crosswalk-20][Embeddingapi] Improve tests.full.xml to support launch auto cases

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/ClearSslPreferenceTest.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewTestBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/ClearSslPreferenceTestAsync.java
BUG=https://crosswalk-project.org/jira/browse/CTS-1713
=> [Crosswalk-20][Embeddingapi] Update ClearSslPreferenceTest usecase

embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTest.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/test/v6/XWalkViewTestAsync.java
BUG=https://crosswalk-project.org/jira/browse/CTS-1715
=> [Crosswalk-20][Embeddingapi]Update the website to get null certificate

usecase/usecase-embedding-android-tests/embeddingapi-async/assets/sharedDialog.html, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/extended/XWalkViewWithSharedDialogAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/assets/sharedDialog.html, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/extended/XWalkViewWithSharedDialog.java
BUG=https://crosswalk-project.org/jira/browse/CTS-1766
=> [Embeddingapi] Improve XWalkViewWithSharedDialog usecase

webapi/tct-canvas-html5-tests/canvas/WebKit/COPYING, webapi/tct-canvas-html5-tests/canvas/WebKit/canvas-createImageBitmap-blob-in-workers.html, webapi/tct-canvas-html5-tests/canvas/WebKit/canvas-createImageBitmap-from-canvas-toBlob.html, webapi/tct-canvas-html5-tests/canvas/WebKit/canvas-createImageBitmap-recursive.html, webapi/tct-canvas-html5-tests/canvas/WebKit/resources/canvas-createImageBitmap-blob-in-workers.js, webapi/tct-canvas-html5-tests/canvas/WebKit/resources/js-test.js, webapi/tct-canvas-html5-tests/tests.full.xml, webapi/tct-canvas-html5-tests/tests.xml
Unit test platform: Crosswalk Project for Android 20.50.533.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1746
=> [WebAPI] TC dev for ImageBitmap

usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/client/XWalkViewWithOpenFileChooserAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/client/XWalkViewWithOpenFileChooser.java
BUG=https://crosswalk-project.org/jira/browse/CTS-1763
=> [Embeddingapi] Refine the XWalkVeiwWithOpenFileChooser usecase

usecase/usecase-cordova-android-tests/steps/DefaultCrosswalkVersion/step.js
Unit test platform: Crosswalk for Android 19.49.514.4
https://crosswalk-project.org/jira/browse/CTS-1798
=> [Crosswalk-20][usecase-cordova] Update DefaultCrosswalkVersion to latest stable version

usecase/usecase-cordova-android-tests/steps/DefaultCrosswalkVersion/step.js
Unit test platform: Crosswalk for Android 19.49.514.4
BUG=https://crosswalk-project.org/jira/browse/CTS-1798
=> [usecase-cordova] Update DefaultCrosswalkVersion to latest stable version

webapi/webapi-webgl-khronos-tests/webgl/tools/COPYING, webapi/webapi-webgl-khronos-tests/webgl/tools/README.md, webapi/webapi-webgl-khronos-tests/webgl/tools/import-conformance-tests.py, webapi/webapi-webgl-khronos-tests/webgl/tools/js-test-pre.patch, webapi/webapi-webgl-khronos-tests/webgl/tools/unit_css.patch, webapi/webapi-webgl-khronos-tests/webgl/tools/unit_js.patch
BUG=https://crosswalk-project.org/jira/browse/CTS-1792
=> Add an automated tool to sync WebGL conformance tests

webapi/webapi-webrtc-w3c-tests/tests.full.xml, webapi/webapi-webrtc-w3c-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1806
Remove subcase='1' in tests.xml and tests.full.xml.
=> Remove subcase='1'

webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/COPYING, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/clients-get.https.html, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/resources/clients-get-frame.html, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/resources/clients-get-worker.js, webapi/webapi-serviceworkers-w3c-tests/tests.full.xml, webapi/webapi-serviceworkers-w3c-tests/tests.xml
https://crosswalk-project.org/jira/browse/CTS-1808
=> Fixed bug CTS-1808 [WebAPI] TC dev for Clients.get(id) for Chromium 51

embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v1.xml, embeddingapi/embedding-api-android-tests/tests_v2.xml, embeddingapi/embedding-api-android-tests/tests_v3.xml, embeddingapi/embedding-api-android-tests/tests_v4.xml, embeddingapi/embedding-api-android-tests/tests_v5.xml, embeddingapi/embedding-api-android-tests/tests_v6.xml, embeddingapi/embedding-api-android-tests/tests_v7.xml, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_sd.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v1.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v2.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v3.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v4.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v5.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v6.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1181
=> [Embeddingapi] Alter suite name in tests.xml and tests.full.xml

misc/webmanu-system-android-tests/suite.json
Remove cordova package support for misc/webmanu-system-android-tests
=> [webmanu] Remove cordova package support

webapi/webapi-webgl-khronos-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1823
=> Fix the same case id in webapi-webgl-khronos-tests

webapi/tct-xmlhttprequest-w3c-tests/tests.full.xml, webapi/tct-xmlhttprequest-w3c-tests/tests.xml, webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest-py/w3c/formdata-delete.htm, webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest-py/w3c/formdata-get.htm, webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest-py/w3c/formdata-has.htm, webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest/w3c/formdata-delete.htm, webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest/w3c/formdata-get.htm, webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest/w3c/formdata-has.htm
https://crosswalk-project.org/jira/browse/CTS-1743
Impacted tests(approved): new 25, update 0, delete 0
Unit test platform: Crosswalk for Android 21.50.540.0
Unit test result summary: pass 25, fail 0, block 0
=> Fixed bug CTS-1743 [WebAPI] TC dev for FormData methods

misc/sampleapp-android-tests/sampleApp_pack_64bit.sh
- Add 64bit pack script
- Update HexGL code
- Reconstruct code
=> [misc] Update sampleapp pack script

tools/atip/atip/android/android.py
https://crosswalk-project.org/jira/browse/CTS-1712
=> Fix ugly False return

tools/atip/atip/android/android.py
BUG=https://crosswalk-project.org/jira/browse/CTS-1712
=> [ATIP] Fix ugly False return

usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/zoom_css3columns_layout.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingTextZoomForCss3Async.java, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/zoom_css3columns_layout.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingTextZoomForCss3.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1764
=> [Embeddingapi] Improve XWalkViewSettingTextZoomForCss3 usecase

webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-auto-manual.html, webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-balance-001-manual.html, webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-balance-002-manual.html, webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-balance-manual.html, webapi/tct-multicolumn-css3-tests/tests.full.xml, webapi/tct-multicolumn-css3-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1735
=> [master][WebAPI]Fixed the bug CTS-1735 [WebAPI] TC dev for CSS column-fill property

webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-auto-manual.html, webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-balance-001-manual.html, webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-balance-002-manual.html, webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-balance-manual.html, webapi/tct-multicolumn-css3-tests/tests.full.xml, webapi/tct-multicolumn-css3-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1735
=> [Crosswalk-21][WebAPI]Fixed the bug CTS-1735 [WebAPI] TC dev for CSS column-fill property

webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-auto-manual.html, webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-balance-001-manual.html, webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-balance-002-manual.html, webapi/tct-multicolumn-css3-tests/multicolumn/CSS3Multicolumn_column-fill-balance-manual.html, webapi/tct-multicolumn-css3-tests/tests.full.xml, webapi/tct-multicolumn-css3-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1735
Unit test platform: Crosswalk for Android 21.50.540.0
=> [Crosswalk-20][WebAPI]Fixed the bug CTS-1735 [WebAPI] TC dev for CSS column-fill property

cordova/cordova-sampleapp-android-tests/sampleapp/comm.py
to specific crosswalk version.
BUG=https://crosswalk-project.org/jira/browse/CTS-1834
=> [Cordova] Add webview parameter into 'cca build' command line

usecase/usecase-wrt-android-tests/samples/SSLCertificate/README.md, usecase/usecase-wrt-android-tests/samples/SSLCertificate/index.html, usecase/usecase-wrt-android-tests/samples/SSLCertificate/res/index.html, usecase/usecase-wrt-android-tests/samples/SSLCertificate/res/manifest.json, usecase/usecase-wrt-android-tests/steps/SSLCertificate/step.js, usecase/usecase-wrt-android-tests/suite.json, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml, usecase/usecase-wrt-android-tests/tests.shared.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1799
=> [usecase-wrt] Add test for handling SSL certificates

usecase/usecase-wrt-android-tests/samples/SSLCertificate/README.md, usecase/usecase-wrt-android-tests/samples/SSLCertificate/index.html, usecase/usecase-wrt-android-tests/samples/SSLCertificate/res/index.html, usecase/usecase-wrt-android-tests/samples/SSLCertificate/res/manifest.json, usecase/usecase-wrt-android-tests/steps/SSLCertificate/step.js, usecase/usecase-wrt-android-tests/suite.json, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml, usecase/usecase-wrt-android-tests/tests.shared.xml
Unit test platform: Crosswalk for Android 20.50.533.11
https://crosswalk-project.org/jira/browse/CTS-1799
=> [Crosswalk-20][usecase-wrt]Add test for handling SSL certificates

usecase/usecase-wrt-android-tests/samples/SSLCertificate/README.md, usecase/usecase-wrt-android-tests/samples/SSLCertificate/index.html, usecase/usecase-wrt-android-tests/samples/SSLCertificate/res/index.html, usecase/usecase-wrt-android-tests/samples/SSLCertificate/res/manifest.json, usecase/usecase-wrt-android-tests/steps/SSLCertificate/step.js, usecase/usecase-wrt-android-tests/suite.json, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml, usecase/usecase-wrt-android-tests/tests.shared.xml
https://crosswalk-project.org/jira/browse/CTS-1799
=> [Crosswalk-21][usecase-wrt]Add test for handling SSL certificates

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/dom_storage_enable.html, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_setting_dom_storage_enable_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingDomStorageEnabledAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/assets/dom_storage_enable.html, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_dom_storage_enable.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingDomStorageEnabled.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1820
=> [usecase-embeddingapi] Add test for set/getDomStorageEnabled methods

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/dom_storage_enable.html, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_setting_dom_storage_enable_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingDomStorageEnabledAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/assets/dom_storage_enable.html, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_dom_storage_enable.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingDomStorageEnabled.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
https://crosswalk-project.org/jira/browse/CTS-1820
=> [Crosswalk-21][usecase-embeddingapi]Add test for set/getDomStorageEnabled methods

webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/extendable-event-async-waituntil.https.html, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/extendable-event-waituntil.https.html, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/resources/extendable-event-async-waituntil.js, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/resources/extendable-event-waituntil.js, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/resources/test-helpers.sub.js, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/resources/testharness-helpers.js, webapi/webapi-serviceworkers-w3c-tests/tests.full.xml, webapi/webapi-serviceworkers-w3c-tests/tests.xml
https://crosswalk-project.org/jira/browse/CTS-1812
=> [WebAPI] TC dev for ExtendableMessageEvent.waitUntil()

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/save_form_data.html, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_setting_save_form_data_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingSaveFormDataAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/assets/save_form_data.html, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_save_form_data.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingSaveFormData.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
https://crosswalk-project.org/jira/browse/CTS-1821
=> [Crosswalk-21][usecase-embeddingapi]Add test for set/getSaveFormData methods

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/save_form_data.html, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_setting_save_form_data_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingSaveFormDataAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/assets/save_form_data.html, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_save_form_data.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingSaveFormData.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1821
=> [usecase-embeddingapi]Add test for set/getSaveFormData methods

webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/extendable-event-async-waituntil.https.html, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/extendable-event-waituntil.https.html, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/resources/extendable-event-async-waituntil.js, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/resources/extendable-event-waituntil.js, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/resources/test-helpers.sub.js, webapi/webapi-serviceworkers-w3c-tests/serviceworkers/w3c/service-workers/resources/testharness-helpers.js, webapi/webapi-serviceworkers-w3c-tests/tests.full.xml, webapi/webapi-serviceworkers-w3c-tests/tests.xml
https://crosswalk-project.org/jira/browse/CTS-1812
=> [WebAPI] TC dev for ExtendableMessageEvent.waitUntil() (#3714)

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/javascript_enabled.html, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/window_open_automatically.html, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/window_open_automatically_enabled.html, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_setting_javascript_enabled_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_setting_javascript_open_windows_automatically_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingJavaScriptCanOpenWindowsAutomaticallyAsync.java, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingJavaScriptEnabledAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/assets/javascript_enabled.html, usecase/usecase-embedding-android-tests/embeddingapi/assets/window_open_automatically.html, usecase/usecase-embedding-android-tests/embeddingapi/assets/window_open_automatically_enabled.html, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_dom_storage_enable.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_javascript_enabled.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_javascript_open_windows_automatically.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingJavaScriptCanOpenWindowsAutomatically.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingJavaScriptEnabled.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
https://crosswalk-project.org/jira/browse/CTS-1818
=> [Crosswalk-21][usecase-embeddingapi]Add tests for setJavaScript related APIs

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/javascript_enabled.html, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/window_open_automatically.html, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/window_open_automatically_enabled.html, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_setting_javascript_enabled_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_view_setting_javascript_open_windows_automatically_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/README.md, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingJavaScriptCanOpenWindowsAutomaticallyAsync.java, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/setting/XWalkViewSettingJavaScriptEnabledAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/assets/javascript_enabled.html, usecase/usecase-embedding-android-tests/embeddingapi/assets/window_open_automatically.html, usecase/usecase-embedding-android-tests/embeddingapi/assets/window_open_automatically_enabled.html, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_dom_storage_enable.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_javascript_enabled.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_view_setting_javascript_open_windows_automatically.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/README.md, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingJavaScriptCanOpenWindowsAutomatically.java, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/setting/XWalkViewSettingJavaScriptEnabled.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1818
=> [usecase-embeddingapi] Add tests for setJavaScript related APIs

usecase/usecase-cordova-android-tests/samples/SharedModeLibraryDownload/res/test.py
set its' value be 600000 (10 minutes).
BUG=https://crosswalk-project.org/jira/browse/CTS-1855
=> [usecase] Add the preference element with LoadUrlTimeoutValue attribute to config.xml

cordova/cordova-feature-android-tests/feature/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/comm.py, cordova/cordova-sampleapp-android-tests/sampleapp/res/GoogleMapsPlugin/google-maps-plugin.py, cordova/cordova-webapp-android-tests/webapp/comm.py, usecase/usecase-cordova-android-tests/res/comm.py, usecase/usecase-cordova-android-tests/samples/CordovaPackage/res/test.py, usecase/usecase-cordova-android-tests/samples/Database/res/test.py, usecase/usecase-cordova-android-tests/samples/DefaultCrosswalkVersion/index.html, usecase/usecase-cordova-android-tests/samples/SharedModeLibraryDownload/res/test.py
=> [usecase] Add the preference element with LoadUrlTimeoutValue attribute to config.xml [Cordova] Remove minSdkVersion parameter.

webapi/tct-fileapi-w3c-tests/fileapi/FileReader_DONE_exist.html, webapi/tct-fileapi-w3c-tests/fileapi/FileReader_EMPTY_exist.html, webapi/tct-fileapi-w3c-tests/fileapi/FileReader_LOADING_exist.html, webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest-py/w3c/open-url-multi-window.htm, webapi/tct-xmlhttprequest-w3c-tests/xmlhttprequest/w3c/open-url-multi-window.htm, webapi/webapi-simd-nonw3c-tests/simd/ecmascript_simd/src/external/qunit.js
- CONSTANT_EXPRESSION_RESULT
- NESTING_INDENT_MISMATCH 
https://crosswalk-project.org/jira/browse/CTS-1737
=> [coverity] Fix 2 coverity errors

webapi/tct-webaudio-w3c-tests/tests.full.xml, webapi/tct-webaudio-w3c-tests/tests.xml, webapi/tct-webaudio-w3c-tests/webaudio/dynamicscompressornode_reduction_default_value.html
Unit test platform: Crosswalk for Android 22.52.557.0
https://crosswalk-project.org/jira/browse/CTS-1851
=> [WebAPI] TC for DynamicsCompressor.reduction for Chromium 52

webapi/tct-webaudio-w3c-tests/tests.full.xml, webapi/tct-webaudio-w3c-tests/tests.xml, webapi/tct-webaudio-w3c-tests/webaudio/automation-support.html
Unit test platform: Crosswalk for Android 22.52.557.0
https://crosswalk-project.org/jira/browse/CTS-1852
=> [WebAPI] TC dev for Automation Support for Chromium 52

webapi/tct-webaudio-w3c-tests/tests.full.xml, webapi/tct-webaudio-w3c-tests/tests.xml, webapi/tct-webaudio-w3c-tests/webaudio/WebKit/COPYING, webapi/tct-webaudio-w3c-tests/webaudio/WebKit/audioparam-nominal-range.html, webapi/tct-webaudio-w3c-tests/webaudio/WebKit/resources/audio-testing.js, webapi/tct-webaudio-w3c-tests/webaudio/WebKit/resources/compatibility.js, webapi/tct-webaudio-w3c-tests/webaudio/WebKit/resources/js-test.js
Unit test platform: Crosswalk for Android 22.52.557.0
https://crosswalk-project.org/jira/browse/CTS-1862
=> [WebAPI] TC dev for AudioParams nominal range for Chromium 52

embeddingapi/embedding-api-android-tests/embeddingapi/AndroidManifest.xml, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewInternalTestBase.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewInternalTestRunnerActivity.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/test/v7/HitTestTest.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/util/CommonResources.java, embeddingapi/embedding-api-android-tests/embeddingapi/src/org/xwalk/embedding/util/XWalkViewInternalTestTouchUtils.java, embeddingapi/embedding-api-android-tests/tests.full.xml, embeddingapi/embedding-api-android-tests/tests_v7.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/AndroidManifest.xml, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/asynctest/v7/HitTestTestAsync.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/TestHelperBridge.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewInternalTestBase.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/base/XWalkViewInternalTestRunnerActivity.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/util/CommonResources.java, embeddingapi/embedding-asyncapi-android-tests/embeddingapi/src/org/xwalk/embedding/util/XWalkViewInternalTestTouchUtils.java, embeddingapi/embedding-asyncapi-android-tests/tests.full.xml, embeddingapi/embedding-asyncapi-android-tests/tests_v7.xml
Impacted tests(approved): new 44, update 0, delete 0
Unit test platform: Crosswalk for Android 22.51.556.0
Unit test result summary: pass 44, fail 0, block 0
https://crosswalk-project.org/jira/browse/CTS-1566
=> [Embeddingapi] Add tests for getHitTestResult()

usecase/usecase-webapi-xwalk-tests/samples/WebAssembly/index.html, usecase/usecase-webapi-xwalk-tests/samples/WebAssembly/webassembly/manifest.json, usecase/usecase-webapi-xwalk-tests/steps/WebAssembly/step.js, usecase/usecase-webapi-xwalk-tests/suite.json, usecase/usecase-webapi-xwalk-tests/tests.android.xml, usecase/usecase-webapi-xwalk-tests/tests.full.xml, usecase/usecase-webapi-xwalk-tests/tests.windows.xml, usecase/usecase-wrt-linux-tests/samples/WebAssembly/index.html, usecase/usecase-wrt-linux-tests/steps/WebAssembly/step.js, usecase/usecase-wrt-linux-tests/tests.full.xml, usecase/usecase-wrt-linux-tests/tests.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1859
Unit test platform: Crosswalk for Android 22.52.557.0
Unit test platform: Crosswalk for Windows 22.52.557.0
Unit test platform: Crosswalk for Linux 22.52.557.0
Unit test result of each platform summary: pass 3, fail 0, block 0
=> Add the usecase of the  WebAssembly.

webapi/webapi-twoinone-xwalk-tests/README.md
=> Update the README title of webapi-twoinone-xwalk-tests

usecase/usecase-webapi-xwalk-tests/steps/Viewport/step.js, usecase/usecase-webapi-xwalk-tests/tests.android.xml, usecase/usecase-webapi-xwalk-tests/tests.full.xml, usecase/usecase-webapi-xwalk-tests/tests.wts.xml
Viewport sample in https://github.com/kaixinjxq/demo-express/tree/master/samples/Viewport
New pull request on demo-express is https://github.com/crosswalk-project/demo-express/pull/147
BUG=https://crosswalk-project.org/jira/browse/XWALK-7312
=> Add Viewport in usecase.

misc/webapi-service-docroot-tests/pack.sh, tools/build/build_iot.py, tools/build/pack.py, tools/resources/inst/inst.iot.py, webapi/tct-2dtransforms-css3-tests/suite.json, webapi/tct-canvas-html5-tests/suite.json
Make the webapi test suites support Ostro IoT platform.
BUG=https://crosswalk-project.org/jira/browse/CTS-1886
=> [WebAPI] Make the test suites support Ostro IoT platform

tools/resources/inst/inst.iot.py
Make the inst.py for IoT easier to use.
No need to input the test suite name.
Support the uninstall feature.
=> Optimize the inst.py for IoT platform

misc/webapi-service-docroot-tests/pack.sh, tools/build/build_iot.py, tools/build/pack.py, tools/resources/inst/inst.iot.py, webapi/tct-2dtransforms-css3-tests/suite.json, webapi/tct-canvas-html5-tests/suite.json
[WebAPI] Make the test suites support Ostro IoT platform
Cherry-pick from the master branch.
=> [WebAPI] Make the test suites support Ostro IoT platform on Crosswalk 20 branch

misc/webapi-service-docroot-tests/pack.sh, tools/build/build_iot.py, tools/build/pack.py, tools/resources/inst/inst.iot.py, webapi/tct-2dtransforms-css3-tests/suite.json, webapi/tct-canvas-html5-tests/suite.json
Make the test suites support Ostro IoT platform
Cherry-pick from the master branch.
=> [WebAPI] Make the test suites support Ostro IoT platform on Crosswalk 22 branch

misc/webapi-service-docroot-tests/pack.sh, tools/build/build_iot.py, tools/build/pack.py, tools/resources/inst/inst.iot.py, webapi/tct-2dtransforms-css3-tests/suite.json, webapi/tct-canvas-html5-tests/suite.json
Make the test suites support Ostro IoT platform
Cherry-pick from the master branch.
=> [WebAPI] Make the test suites support Ostro IoT platform on Crosswalk 21 branch

usecase/usecase-webapi-xwalk-tests/manifest.iot.json, usecase/usecase-webapi-xwalk-tests/suite.json, usecase/usecase-webapi-xwalk-tests/tests.full.xml, usecase/usecase-webapi-xwalk-tests/tests.iot.xml
https://crosswalk-project.org/jira/browse/CTS-1901
Impacted tests(approved): new 64, update 0, delete 0
Unit test result summary: pass 42, fail 17, block 5
The result is normal.
=> Add the usecase support for iot.

usecase/usecase-cordova-android-tests/samples/CordovaPackage/index.html, usecase/usecase-cordova-android-tests/samples/CordovaPackage/res/test.py, usecase/usecase-cordova-android-tests/samples/CrosswalkVersion/index.html, usecase/usecase-cordova-android-tests/samples/CrosswalkVersion/res/test.py
Unit test platform: Crosswalk Project for Android 23.52.580.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1888
=> [Cordova] Update CordovaPackage/Crosswalkversion to support crosswalk-lite

usecase/usecase-wrt-android-tests/samples/InputColor/README.md, usecase/usecase-wrt-android-tests/samples/InputColor/index.html, usecase/usecase-wrt-android-tests/steps/InputColor/step.js, usecase/usecase-wrt-android-tests/tests.android.xml, usecase/usecase-wrt-android-tests/tests.full.xml
BUG=https://crosswalk-project.org/jira/browse/CTS-1905
Add the checkpoint about the input color.
It is fail in Crosswalk 21.51.546.7.
There is a feature bug XWALK-7367 to track it.
=> Add the input color checkpoint.

usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/REAMDE.md, usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/index.html, usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/res/index.html, usecase/usecase-cordova-android-tests/steps/XwalkCommandLine/step.js
Unit test platform: Crosswalk Project for Android 23.53.586.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1908
=> [usecase-cordova] Remove --disable-webrtc test

usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/REAMDE.md, usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/index.html, usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/res/index.html, usecase/usecase-cordova-android-tests/steps/XwalkCommandLine/step.js
Unit test platform: Crosswalk Project for Android 21.51.546.4
https://crosswalk-project.org/jira/browse/CTS-1908
=> [Crosswalk-21][usecase-cordova] Remove --disable-webrtc test

usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/REAMDE.md, usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/index.html, usecase/usecase-cordova-android-tests/samples/XwalkCommandLine/res/index.html, usecase/usecase-cordova-android-tests/steps/XwalkCommandLine/step.js
Unit test platform: Crosswalk Project for Android 22.52.561.0
https://crosswalk-project.org/jira/browse/CTS-1908
=> [Crosswalk-22][usecase-cordova]Remove --disable-webrtc test

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/form_database.html, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_formdatabase_clearformdata_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/database/XWalkViewDatabaseWithClearFormDataAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/assets/form_database.html, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_formdatabase_clearformdata.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/database/XWalkViewDatabaseWithClearFormData.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
Unit test platform: Crosswalk Project for Android 24.53.593.0
BUG=https://crosswalk-project.org/jira/browse/CTS-1919
=> [Embeddingapi] Add tests for WebViewDatabase.clearFormData()

usecase/usecase-embedding-android-tests/embeddingapi-async/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/assets/form_database.html, usecase/usecase-embedding-android-tests/embeddingapi-async/res/layout/activity_xwalk_formdatabase_clearformdata_async.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi-async/src/org/xwalk/embedded/api/asyncsample/database/XWalkViewDatabaseWithClearFormDataAsync.java, usecase/usecase-embedding-android-tests/embeddingapi/AndroidManifest.xml, usecase/usecase-embedding-android-tests/embeddingapi/assets/form_database.html, usecase/usecase-embedding-android-tests/embeddingapi/res/layout/activity_xwalk_formdatabase_clearformdata.xml, usecase/usecase-embedding-android-tests/embeddingapi/res/values/strings.xml, usecase/usecase-embedding-android-tests/embeddingapi/src/org/xwalk/embedded/api/sample/database/XWalkViewDatabaseWithClearFormData.java, usecase/usecase-embedding-android-tests/tests.android.xml, usecase/usecase-embedding-android-tests/tests.full.xml
Unit test platform: Crosswalk Project for Android 23.53.589.3
https://crosswalk-project.org/jira/browse/CTS-1919
=> [Crosswalk-23][Embeddingapi]Add tests for WebViewDatabase.clearFormData()

webapi/webapi-sensors-w3c-tests/sensors/Accelerometer.https.html, webapi/webapi-sensors-w3c-tests/sensors/resources/generic-sensor-tests.js
Unit test platform: Chrome Canary 57.0.2943.3/Google Nexus 9
=> Add onerror catch to sensor

webapi/webapi-sensors-w3c-tests/sensors/Accelerometer.https.html, webapi/webapi-sensors-w3c-tests/sensors/resources/generic-sensor-tests.js
Impacted tests(approved): new 0, update 31, delete 0
Unit test platform: Chrome Canary 57.0.2943.3/Google Nexus 9
Unit test result summary: pass 31, fail 0, block 0
=> Change the sensor.start() step on sensor

webapi/webapi-sensors-w3c-tests/sensors/resources/generic-sensor-tests.js
update 8 cases, and all tests pass.
=> Remove the useless parameters in sensor.

tools/build/build_iot.py, tools/build/pack.py
Update the pack.py and build_iot.py for NW.js test suites packing.
Signed-off-by: Zhong Qiu <zhongx.qiu@intel.com>
=> [release-scripts]Update the packing scripts for NW.js

tools/build/build_iot.py, tools/build/pack.py, tools/build/released_suites/IoT-Platform, webapi/webapi-deviceadaptation-css3-tests/suite.json
Add webapi-deviceadaptation-css3-tests to NW.js test scope.
=> Add webapi deviceadaptation to nwjs
